### ISSUE TITLE
Add falcon-agent addon

### ISSUE THREAD

**Issue by csantanapr** [aws-ia/terraform-aws-eks-blueprints#1005]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Customer requested falcon-agent addon https://github.com/CrowdStrike/falcon-helm

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Falcon you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
