### ISSUE TITLE
modlue source location incorrect in location - terraform-aws-eks-blueprints/examples/ingress-controllers/nginx/main.tf

### ISSUE THREAD

**Issue by Nadeem93** [aws-ia/terraform-aws-eks-blueprints#1017]
## Description
In file location terraform-aws-eks-blueprints/tree/main/examples/ingress-controllers/nginx/main.tf line number **64** the source path of the module is incorrect.
It should be "**../../modules/kubernetes-addons**".

<img width="906" alt="Screenshot 2022-10-03 at 3 24 32 PM" src="https://user-images.githubusercontent.com/62740409/193549873-fe1de852-1c51-4ceb-a7f7-0d94a259cca4.png">

**Comment by bryantbiggs** [comment]
I am unable to reproduce this error and the relative path is correct based on the current structure
