### ISSUE TITLE
helm addon create_namespace != null or > 0 in new relase

### ISSUE THREAD

**Issue by mondrias** [aws-ia/terraform-aws-eks-blueprints#1020]
## Description

I have to habiltate addon without irsa config i have error in create namespace in local default_helm_config = true. Is i set  irsa_config  = null when call helm addon to create namespace i get error in type in count, 
I propose in file modules\kubernetes-addons\helm-addon\main.tf, line 9 change 

create_namespace           = var.irsa_config != null 
to 
create_namespace           = length(var.irsa_config) > 0 ? 

Thanks.

**Comment by bryantbiggs** [comment]
closed in #1019
