### ISSUE TITLE
Unable to set `enable_gatekeeper` in 4.12 (also shown in CI)

### ISSUE THREAD

**Issue by wjam** [aws-ia/terraform-aws-eks-blueprints#1022]
## Description

I've just upgraded to 4.12 and previously working Terraform, which had `enable_gatekeeper` set to true, is now broken with this error:
```
│ Error: create: failed to create: namespaces "gatekeeper-system" not found
│ 
│   with module.eks_blueprints_kubernetes_addons.module.gatekeeper[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
```

[This is the same error that is appear in the failing CI test](https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/3178775713/jobs/5180608951#step:7:3558)

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Module version [Required]: 4.8.1
- Terraform version: v1.2.8
- Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.29.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/time v0.8.0

## Reproduction Code [Required]

See CI test

## Expected behaviour

CI test should pass

**Comment by bryantbiggs** [comment]
this is fixed in #1019 and available in v4.12.1
