### ISSUE TITLE
Increased node capacity with Bottlerocket

### ISSUE THREAD

**Issue by pescador691** [aws-ia/terraform-aws-eks-blueprints#1023]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Hey! 

I am trying to launch the k8s cluster with a node group with increased pod capacity.

Saw that the `userdata-bottlerocket.tpl` has the following format as stated in [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/aws-eks-managed-node-groups/templates/userdata-bottlerocket.tpl):

```
${pre_userdata}
[settings.kubernetes]
api-server = "${cluster_endpoint}"
cluster-certificate = "${cluster_ca_base64}"
cluster-name = "${eks_cluster_id}"
${post_userdata}
```

Also saw in bottlerocket docs that to increase the number of pods per node, I should add `settings.kubernetes.max-pods`.

To increase the pod capacity per node, I defined the following managed node group:
```
custom_ami = {
      node_group_name = "custom-ami" # Max 40 characters for node group name
      instance_types = ["m5.xlarge"]
      force_update_version = true
      ami_type             = "BOTTLEROCKET_x86_64"
      min_size     = 1
      max_size     = 1
      desired_size = 1
      launch_template_os     = "bottlerocket"
      post_userdata = <<-EOT
        "max-pods" = "110"
      EOT
    }
```

Since I am using a m5.xlarge instance, I was expecting to see that the node had a max capacity of 110 but it still has a capacity of 58 pods.

What am I missing?

Thanks!

**Comment by bryantbiggs** [comment]
```hcl
custom_ami = {
  node_group_name      = "custom-ami"
  instance_types       = ["m5.xlarge"]
  force_update_version = true
  ami_type             = "BOTTLEROCKET_x86_64"
  min_size             = 1
  max_size             = 1
  desired_size         = 1

  create_launch_template = true # ensure custom launch template is used
  launch_template_os     = "bottlerocket"
  post_userdata          = <<-EOT
    "max-pods" = "110"
  EOT
}
```

**Comment by pescador691** [comment]
When using the `create_launch_template = true`, terraform throws the following error:

```
error waiting for EKS Node Group (...) to create: context deadline exceeded
```

I can see that the ec2 instance is created and working. When inspecting the nodegroup, it shows that even though the instance was created, it failled to join the kubernetes cluster. 

It looks that the even though the instance was created, the variables that allow it to connect to the cluster are missing.

When setting `create_launch_template = true` will it change the usedata file and I need to define it?

Or do I need to set extra variables to point to the k8s cluster?

I am using the [ipv4-prefix-delegation](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ipv4-prefix-delegation) example. I commented the section  **Modify VPC CNI deployment** and only changed the **managed_node_groups**.

**Comment by bryantbiggs** [comment]
ah, my apologies - you also have to provide a "custom AMI ID" to enable the user data as well https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/ipv4-prefix-delegation/main.tf#L66 You can use the data source to pull the EKS provided Bottlerocket AMI
