### ISSUE TITLE
enable_aws_node_termination_handler not producing any effect

### ISSUE THREAD

**Issue by mballoni** [aws-ia/terraform-aws-eks-blueprints#1025]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

 I have recently created a new EKS cluster and would like to install the node termination handler.
 The motivation is both the near future Spot instance usage and a smooth node transition.
 
  When I set the termination handler addon:
  
```
  module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.12.1"

  enable_aws_node_termination_handler = true

  eks_cluster_id = module.runners_cluster.eks_cluster_id
}
```
Nothing gets changed on terraform plan.

I was looking into all issues and found this: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/464#issuecomment-1107485356

But I don't understand why it should be enabled only when I also have auto-scaling enable.

Is it mandatory or something that we can handle differently ?

Thank you folks, this is an amazing project pushing EKS setup quality and terraform knowledge as well.

**Comment by askulkarni2** [comment]
@florentio thanks for the suggestion.

@mballoni does @florentio's suggestion work? Also are you using MNG or self-managed? For managed node groups, you do not need to run NTH (ref: [blog](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-provisioning-and-managing-ec2-spot-instances-in-managed-node-groups/))

**Comment by bryantbiggs** [comment]
Correct, even with spot

>To handle Spot interruptions, you do not need to install any extra automation tools on the cluster, for example: AWS Node Termination Handler. The managed node group handles Spot interruptions for you in the following way: the underlying EC2 Auto Scaling group is opted-in to Capacity Rebalancing, which means that when one of the Spot Instances in your node group is at elevated risk of interruption and gets an [EC2 instance rebalance recommendation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/rebalance-recommendations.html), it will attempt to launch a replacement instance. The more instance types you configure in the managed node group, the more chances EC2 Auto Scaling has of launching a replacement Spot Instance. [Click here](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html#managed-node-group-capacity-types) for more details in the user guide.
