### ISSUE TITLE
Nginx-Ingress should depend on AWS Loadbalancer

### ISSUE THREAD

**Issue by torvitas** [aws-ia/terraform-aws-eks-blueprints#1030]
## Description

When setting `enable_aws_load_balancer_controller = true` and `enable_aws_load_balancer_controller = true` it is necessary to use targeted destroys to make sure the ingress is being teared down before the loadbalancer as otherwise there will be finalizers left over that cannot be resolved anymore. (see: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ingress-controllers/nginx)

This could be resolved by letting the ingress-nginx module explicitly depend on the load balancer module.

## Versions

- Module version: 4.12.1

- Terraform version: 1.2.9

## Reproduction Code

See: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ingress-controllers/nginx

## Expected behaviour

`terraform destroy` just works

## Actual behaviour

`terraform destroy` needs to be run multiple times with defined targets

**Comment by tanvp112** [comment]
Functionally, external LB like AWS ELB works with/without ingress controller on the cluster like ingress-nginx. And the opposite is true as well. Also, it is possible to use in in-tree NLB support with ingress-nginx without the AWS LB controller. 

There shouldn't be any dependency among ingress controller and AWS LB controller, especially there are other ingress controllers like traefik, haproxy... such "dependency" will become a maintenance nightmare.

**Comment by torvitas** [comment]
I am not sure if I fully understand your concerns. This would not be a hard dependency. As long as you do not enable the AWS LB controller the count for the LB will be 0 and the dependency will still be fulfilled.

We are working around that issue by loading the ingress-nginx addon directly and adding the dependency there.

**Comment by tanvp112** [comment]
My apology, the title may sounds like one but after seeing your changed this is indeed not a "hard" dependency.
