### ISSUE TITLE
KMS key clean up

### ISSUE THREAD

**Issue by xincanva** [aws-ia/terraform-aws-eks-blueprints#1040]
## Description

KMS key created as part of this module cannot be deleted by other admins.

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/6f571f2dbe3e5243681562f4ac9964af9e391c3c/data.tf#L89

This has cause a lot of issues with clean up in our use case, where the original creator role may not be available.

can we add root to the principal list?

```
        "arn:${local.context.aws_partition_id}:iam::${local.context.aws_caller_identity_account_id}:root"
```

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by askulkarni2** [comment]
@xincanva you should be able to provide additional arns using `cluster_kms_key_additional_admin_arns`. See https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/6f571f2dbe3e5243681562f4ac9964af9e391c3c/variables.tf#L129

**Comment by bryantbiggs** [comment]
Closing for now - please see the guidance provided above by Apoorva as well as https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1319 where the v19 of the `terraform-aws-eks` module handles this for users today
