### ISSUE TITLE
Fail to destroy resources while enable aws load balancer controller

### ISSUE THREAD

**Issue by mingshun** [aws-ia/terraform-aws-eks-blueprints#1050]
## Versions

- Module version [Required]: v4.12.2

- Terraform version:
Terraform v1.3.0
on linux_amd64
- Provider version(s):
  - provider registry.terraform.io/gavinbunney/kubectl v1.14.0
  - provider registry.terraform.io/hashicorp/aws v4.34.0
  - provider registry.terraform.io/hashicorp/cloudinit v2.2.0
  - provider registry.terraform.io/hashicorp/helm v2.7.0
  - provider registry.terraform.io/hashicorp/kubernetes v2.14.0
  - provider registry.terraform.io/hashicorp/null v3.1.1
  - provider registry.terraform.io/hashicorp/random v3.4.3
  - provider registry.terraform.io/hashicorp/time v0.8.0
  - provider registry.terraform.io/hashicorp/tls v4.0.

## Reproduction Code [Required]

```
module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons"

  eks_cluster_id = module.eks.cluster_id

  enable_amazon_eks_aws_ebs_csi_driver = true
  enable_aws_load_balancer_controller  = true
}
```

```
terraform init
terraform apply
terraform destroy
```

## Expected behaviour

Delete all resources.

## Actual behaviour

Reported following error while refreshing state:

```
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/locals.tf line 13, in locals:
│   13:     awsLoadBalancerController = var.enable_aws_load_balancer_controller ? module.aws_load_balancer_controller[0].argocd_gitops_config : null
│     ├────────────────
│     │ module.aws_load_balancer_controller[0] is object with 2 attributes
│ 
│ This object does not have an attribute named "argocd_gitops_config".

```

**Comment by bryantbiggs** [comment]
Please see https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/FAQ.md#timeouts-on-destroy

The recommended cleanup steps are
```sh
terraform destroy -target="module.eks_blueprints_kubernetes_addons" -auto-approve
terraform destroy -target="module.eks_blueprints" -auto-approve
terraform destroy -auto-approve
```

**Comment by mingshun** [comment]
> ```shell
> terraform destroy -target="module.eks_blueprints_kubernetes_addons" -auto-approve
> terraform destroy -target="module.eks_blueprints" -auto-approve
> terraform destroy -auto-approve
> ```

I tried to run the above commands in order. It still reports the same errors while running the last command.
