### ISSUE TITLE
Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by YuvarajuR** [aws-ia/terraform-aws-eks-blueprints#1053]
- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have provisioned the EKS cluster through the EKS-Blueprints and while destroying the EKS cluster getting below error every and the cluster is not deleted.

**Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.**

Not sure what is the root cause of it.

Could someone help me on this.

**Comment by bryantbiggs** [comment]
Have you removed the resources in the prescribed order?
1. `terraform destroy -target=module.eks_blueprints_kubernetes_addons`
2. `terraform destroy -target=module.eks_blueprints`
3. `terraform destroy`

**Comment by YuvarajuR** [comment]
@bryantbiggs Thank you for your response. No, i have directly executed the terraform destroy...

**Comment by bryantbiggs** [comment]
That is the prescribed order to ensure that addons that create AWS resources are cleaned up first since they are outside of Terraform's control. This avoids this situation that you are experiencing

**Comment by YuvarajuR** [comment]
Got it. Thank you for the info on this sequence of command executions @bryantbiggs.
