### ISSUE TITLE
Worker node security check plz.

### ISSUE THREAD

**Issue by kichigai** [aws-ia/terraform-aws-eks-blueprints#1054]
Hello, I use this blueprint module to create eks clusters and worker node groups.

And the output parameter 'worker_node_security_group_id' seems to be an invalid value.

Worker node ec2 instance is not assigned to a security group with ID `worker_node_security_group_id`.

Only security groups with ID `cluster_primary_security_group_id` value were assigned on worker node EC2 instance.

Is that ok?

**Comment by bryantbiggs** [comment]
When the default launch template is used for EKS managed node groups, only the cluster primary security group is attached to nodes. To have the custom security group be attached to the nodes, you need to specify the use of a custom launch template

**Comment by kichigai** [comment]
> When the default launch template is used for EKS managed node groups, only the cluster primary security group is attached to nodes. To have the custom security group be attached to the nodes, you need to specify the use of a custom launch template

So what is the output of [`worker_node_security_group_id`](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1054#output_worker_node_security_group_id)?
Why does worker node sharing security group exist?
The security group is not attached with any other AWS resource except other security groups.

**Comment by bryantbiggs** [comment]
please see my comment posted above
