### ISSUE TITLE
[FEATURE] Create a dedicated GitHub repository

### ISSUE THREAD

**Issue by GaRiY** [aws-ia/terraform-aws-eks-blueprints#1058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

- If a CD tool is deployed on the kubernetes cluster (e.g. ArgoCD), a dedicated GitHub repository will be created, where the desired infrastructure code (e.g. helm charts) will be stored (In case of ArgoCD: application manifests)
- The CD operator deployment will be connected to that repository, and deploy everything that's in there.

#### Describe the solution you would like

- A sub-module that will be used to create the repository using a template
- If the repository was created, CD modules should automatically connect to that repository
- Repository's name arguably should be the name of the cluster, so it will be easier to find the repository

**Comment by edikmkoyan** [comment]
@bryantbiggs @GaRiY has the solution. How does he create a PR? Can he do that?

**Comment by bryantbiggs** [comment]
Thanks for raising this @GaRiY - however, I don't think this quite fits into the project. Users may use GitHub, GitLab, BitBucket, CodeCommit, etc. and there isn't anything specific around the GitHub repository being proposed here - its just vanilla Terraform creating an empty GitHub repository. So at this time we won't be looking to add this functionality to the project
