### ISSUE TITLE
Enabling vault add-on causes terraform to fail

### ISSUE THREAD

**Issue by camba1** [aws-ia/terraform-aws-eks-blueprints#1060]
## Description

Enabling Hashicorp Vault add-on  causes terraform to throw the following error:

```

│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/eks-blueprints-kubernetes-addons.vault/main.tf line 11, in resource "helm_release" "vault":
│   11:   values           = try(var.helm_config.values, file("${path.module}/vault-config.yml"))
│     ├────────────────
│     │ path.module is ".terraform/modules/eks-blueprints-kubernetes-addons.vault"
│     │ var.helm_config is null
│ 
│ Inappropriate value for attribute "values": list of string required.

```

I tried with and without config. They both fail:

`  enable_vault = true`

or
```
  enable_vault = true
  vault_helm_config = {
    namespace = var.vaultNameSpace
  }
```

This was working fine in version 4.12.0 and it seems to have broken when upgraded to 4.12.2 
If vault is disabled (`enable_vault = false`), everything works

- [ X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
 4.12.2
- Terraform version:
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.34.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.9.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]
(not showing all add-ons for brevity)

```
module "eks-blueprints-kubernetes-addons" {
  source         = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.12.2/modules/kubernetes-addons"
  eks_cluster_id = module.eks-blueprints.eks_cluster_id


  enable_amazon_eks_vpc_cni              = true
  enable_amazon_eks_coredns              = true
  enable_amazon_eks_kube_proxy           = true
  enable_amazon_eks_aws_ebs_csi_driver   = true

  enable_argocd                       = true

  argocd_manage_add_ons               = false
  argocd_applications = {
    workloads = var.workload_repo
  }

  # HashiCorp Vault
  enable_vault = true
#  vault_helm_config = {
#    namespace = var.vaultNameSpace
#  }

  depends_on = [module.eks-blueprints.managed_node_groups]
}

```

No

Yes

Upgraded from 4.12.0 to 4.12.2 to fix an issue with the namespaces not getting created for Kiverno and Calico (which was fixed by upgrade). But now Vault throws an error when doing `Terraform Plan`

## Expected behaviour

Terraform plan succeeds without errors

## Actual behaviour

The error listed above is thrown

**Comment by bryantbiggs** [comment]
PR opened to fix https://github.com/hashicorp/terraform-aws-hashicorp-vault-eks-addon/pull/10
