### ISSUE TITLE
Error: Could not download chart `cluster_proportional_autoscaler` with module CoreDNS

### ISSUE THREAD

**Issue by AErmie** [aws-ia/terraform-aws-eks-blueprints#1061]
## Description

I believe this issue is related to all the helm chart issues that are occurring. 

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v4.13.0

- Terraform version: 1.2.9 (because of the breaking changes with `experimental` code in v1.3.x)

- Provider version(s): 

  - Installed terraform-aws-modules/http v2.4.1 (self-signed, key ID B2C1C0641B6B0EB7)
  - Installed hashicorp/helm v2.7.1 (signed by HashiCorp)
  - Installed hashicorp/tls v3.4.0 (signed by HashiCorp)
  - Installed hashicorp/aws v4.34.0 (signed by HashiCorp)
  - Installed hashicorp/random v3.4.3 (signed by HashiCorp)
  - Installed hashicorp/cloudinit v2.2.0 (signed by HashiCorp)
  - Installed hashicorp/kubernetes v2.14.0 (signed by HashiCorp)
  - Installed hashicorp/local v2.2.3 (signed by HashiCorp)
  - Installed gavinbunney/kubectl v1.14.0 (self-signed, key ID AD64217B5ADD572F)
  - Installed hashicorp/null v3.1.1 (signed by HashiCorp)
  - Installed hashicorp/time v0.9.0 (signed by HashiCorp)

## Reproduction Code [Required]

```YAML
locals {
  cluster_version= "1.23"
}

module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.13.0"

  eks_cluster_id = module.eks_blueprints.eks_cluster_id

  # EKS Addons
  enable_amazon_eks_coredns = true
  amazon_eks_coredns_config = {
    most_recent        = true
    kubernetes_version = local.cluster_version
    resolve_conflicts  = "OVERWRITE"
  }
}
```

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

## Expected behaviour

I expect the CoreDNS EKS add-on to be fully deployed.

## Actual behaviour

Even though the CoreDNS add-on is actually installed correctly into the cluster, the output from `terraform apply` indicates that the `cluster_proportional_autoscaler` component (which I guess is auto-included in the deployment of CoreDNS), fails to install, and therefore causes Terraform to report a failed `apply` operation.

### Terminal Output Screenshot(s)

![TerraformApplyResults](https://user-images.githubusercontent.com/10376796/196062819-c6ab8a11-6d61-460d-a500-fdc7c7edeca9.png)

## Additional context

This is being run in an Azure Pipeline, using Azure DevOps (online, not server).

**Comment by bryantbiggs** [comment]
The chart repository is valid https://github.com/hashicorp/terraform-aws-hashicorp-vault-eks-addon/pull/10

Can you try running 
```sh
helm repo add cluster-proportional-autoscaler https://kubernetes-sigs.github.io/cluster-proportional-autoscaler
helm repo update
```

And then re-run terraform
