### ISSUE TITLE
Managed Auto Scaling Group resources do not receive all specified tags

### ISSUE THREAD

**Issue by constantinevitt** [aws-ia/terraform-aws-eks-blueprints#1063]
## Description

Using the example provided for [EKS Managed Node Groups](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/node-groups/managed-node-groups) the actual Auto Scaling Groups which are created do not receive all tags which are defined in either the `local.tags` block on [line 45](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/node-groups/managed-node-groups/main.tf#L45) or the `additional_tags` block(s), for example on [line 173](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/node-groups/managed-node-groups/main.tf#L173)

Other resources, such as instances and security groups do receive the relevant tags.

## Versions

- Module version [Required]:

- Terraform version:
```
Terraform v1.3.2
on linux_amd64
```
- Provider version(s):
```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.34.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.9.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```
## Reproduction Code [Required]

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/node-groups/managed-node-groups/main.tf

Run the above example
Check ASG tags via AWS console or cli

## Expected behaviour

AWS autoscaling groups receive tags as defined by
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/node-groups/managed-node-groups/main.tf#L45

## Actual behaviour

Auto Scaling Groups receive only standard EKS tags
![image](https://user-images.githubusercontent.com/20411992/196235898-b66d9207-2584-48a8-b567-93d4f568dd16.png)

**Comment by bryantbiggs** [comment]
Tags are only propagated when a custom launch template is used https://github.com/aws/containers-roadmap/issues/1541
