### ISSUE TITLE
[ADDON] Tekton

### ISSUE THREAD

**Issue by askulkarni2** [aws-ia/terraform-aws-eks-blueprints#1071]
Create add-on for [Tekton](https://tekton.dev/docs/installation/) to demonstrate CI/CD pattern.

**Comment by savipavan** [comment]
Hi AWS Team,
We too having the same requirement to have Tekton add-on in our aws eks blueprints templates

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Tekton you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
