### ISSUE TITLE
How to configure prometheus when add ons are managed via ArgoCd?

### ISSUE THREAD

**Issue by DylanWarnock** [aws-ia/terraform-aws-eks-blueprints#1082]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I'm managing add on through argo by setting `argocd_manage_add_ons = true`. I'm attempting to install prometheus on our cluster using the instructions described [here](https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.5.0/add-ons/prometheus/#gitops-configuration), but `enable_amazon_prometheus = true` does create a AMP workspace.  My assumption was a AMP workspace should get created and the prometheus server install on our cluster would forward metrics to the workspace. Then using the workspace we could configuring various monitoring alerts for our applications. Is the assumption correct? With out a AMP workspace what value does setting `enable_prometheus = true` and `enable_amazon_prometheus = true` provide?

**Comment by netzon-eladio** [comment]
I'm facing the same issue

**Comment by bryantbiggs** [comment]
I would follow along here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114
