### ISSUE TITLE
Create Route53 zones for external-dns.

### ISSUE THREAD

**Issue by Sahakanush** [aws-ia/terraform-aws-eks-blueprints#1106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

- I would like to have a way to pass **domain names** to external-dns module, so that it will create route53 zones for it, and use them.

#### Describe the solution you would like

- Just a variable that will get domain name.
- And a resource that will use that variable, to create route53 zones.

#### Additional context

I already have the solution. I'll create a pull request if this issue gets approved.

**Comment by bryantbiggs** [comment]
thank you for filing the issue. Route53 zones tend to be used by more than just K8s ingress and the amount of support that would be required to support creating zones and all the configurations provided, and exporting their values used elsewhere, etc. At this time we don't foresee this as something that will be created within the project and instead should be created externally and passed into the relevant inputs

**Comment by edikmkoyan** [comment]
@bryantbiggs I believe GitOps flow implies cluster naming conventions and each EKS cluster should have a separate DNS zone based on cluster name to be used by the services deployed on the cluster. Therefor it would be convenient to have an option of specifying a DNS zone to be created or reusing an existing zone based on user's preference.

**Comment by bryantbiggs** [comment]
GitOps does not make any such assumptions about DNS or cluster names https://opengitops.dev/

**Comment by edikmkoyan** [comment]
@bryantbiggs I want to be able to **declare** that I want a cluster with all the "batteries included". That implies having a DNS zone for the cluster. In various development environments it is convenient to have the cluster name in the service URL, that helps to troubleshoot faster as the need of interpersonal communication decreases.
