### ISSUE TITLE
Add Istio module add-on

### ISSUE THREAD

**Issue by ovaleanu** [aws-ia/terraform-aws-eks-blueprints#1107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Terraform module for deploying [Istio](https://istio.io/) via Helm.

#### Describe the solution you would like

Include the istio addon in the `kubernetes-addons` section of this blueprint.

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Istio you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
