### ISSUE TITLE
[ FEATURE ] Change installation method for argocd-application

### ISSUE THREAD

**Issue by armenmelkonyan90** [aws-ia/terraform-aws-eks-blueprints#1109]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

To have the opportunity to install argocd-apps from the chart repository

#### Describe the solution you would like

The argocd submodule uses a custom helm-chart to install argocd-apps, this approach does not allow using the features of the official chart. I propose to change the submodule and give the opportunity to install the argocd-apps from the official or any other repository.

#### Additional context
I already have the solution. I'll create a pull request if this issue gets approved.

**Comment by askulkarni2** [comment]
Which official helm chart are you referring to and what features are you trying to use?

**Comment by hakmkoyan** [comment]
@askulkarni2 What investigations you advice?

**Comment by hakmkoyan** [comment]
is this still open?
