### ISSUE TITLE
Use a source URL instead of relative path for source section of module code

### ISSUE THREAD

**Issue by danvau7** [aws-ia/terraform-aws-eks-blueprints#1112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

1. Could we add a url to source these Terraform modules instead of a relative path? For where I think it would be helpful to have a source URL instead of a source relative path, [see here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/main.tf#L50).

2. Currently to leverage this very very helpful Terraform module I have to clone the entire repo and manage all of those files. I personally don't mind, but my team at work is a bit skeptical about this, since we are more used to url paths to the Git repo or a relative path that leverages the Terraform Registry.

3. Examples added to the documentation that show using URLs to the Github repo instead of relative paths. I was able to figure this out partially, but could not determine a URL when it came time to source the `kubernetes-addons` module/folder.

4. I've tried to figure this out myself, as I hate filing issues and feel very self-conscious :):)
But I was unable to come up with any URL I could point to in the source section of modules and instead simply downloaded the whole repo.

**Comment by bryantbiggs** [comment]
hi @danvau7 - you don't need to clone or fork the repository, you can use the repository + tag/hash for the source. this is the recommended manner to consume Terraform modules - through a pinned version (whether it be a git tag/hash or a version from the registry)

```hcl
module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.12.0"
  
 ...
}

module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.12.0"

  ...
}
```

**Comment by danvau7** [comment]
Thanks @bryantbiggs. The configuration you provided worked very well and was exactly what I was looking for. Again thanks and closing this issue!
