### ISSUE TITLE
[FEATURE] Wiz Add-On

### ISSUE THREAD

**Issue by yebolenko** [aws-ia/terraform-aws-eks-blueprints#1122]

**Comment by yebolenko** [comment]
These are instructions how to add wiz add-on:
https://docs.wiz.io/wiz-docs/docs/auto-connect-clusters
https://docs.wiz.io/wiz-docs/docs/deploy-wiz-ac

**Comment by bryantbiggs** [comment]
hi @yebolenko please fill in the provided template so we can properly evaluate the request
