### ISSUE TITLE
Example - Karpenter on Fargate

### ISSUE THREAD

**Issue by micbegin** [aws-ia/terraform-aws-eks-blueprints#1159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

- An example/blueprint that demonstrates how to create a cluster using a Fargate profile in which to run Karpenter.

Reference documentation:

- [Getting Started with eksctl - Create a Cluster - Example 2: Create basic cluster with Karpenter on Fargate](https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/#create-a-cluster)
- [Karpenter Best Practices - Run the Karpenter controller on EKS Fargate or on a worker node that belongs to a node group](https://aws.github.io/aws-eks-best-practices/karpenter/#run-the-karpenter-controller-on-eks-fargate-or-on-a-worker-node-that-belongs-to-a-node-group)

#### Describe the solution you would like

- An example that documents and provides the steps necessary to create an EKS cluster with a Fargate Profile where to run Karpenter using EKS blueprints
- A default Karpenter provisioner using Bottlerocket AMI and a mix of spot and on-demand instances
- A demo application to demonstrates how Karpenter scales nodes based on workload constraints like `nodeSelector`, `topologySpreadConstraints`, and `podAntiAffinity`
- Other add-ons like [aws-load-balancer-controller](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/aws-load-balancer-controller) and [external-dns](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/external-dns) running on fargate or nodes provisionned by Karpenter to demonstrate how a cluster can operate without any managed node groups

#### Additional context

I have tested this approach already and I have code that could be used to create this example.

**Comment by bryantbiggs** [comment]
the current example for Karpenter is already configured for running on Fargate. If there are additional features/questions related to this pattern, please feel free to open a new issue describing the solution you would like to see or have answered 

Ref: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/karpenter

**Comment by micbegin** [comment]
I'm not sure why you are closing this issue since https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/karpenter does not provide the following items:

- A default Karpenter provisioner using Bottlerocket AMI and a mix of spot and on-demand instances
- A demo application to demonstrates how Karpenter scales nodes based on workload constraints like nodeSelector, topologySpreadConstraints, and podAntiAffinity
- Other add-ons like [aws-load-balancer-controller](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/aws-load-balancer-controller) and [external-dns](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/external-dns) running on fargate or nodes provisionned by Karpenter to demonstrate how a cluster can operate without any managed node groups

Why are you asking me to open a new issue when this one already contains the proposed solution?

**Comment by bryantbiggs** [comment]
Because I don't think a separate example is warranted just for those items, no?

> A default Karpenter provisioner using Bottlerocket AMI and a mix of spot and on-demand instances

What are we trying to demonstrate with this, what should users take away from the example? Is this just showing that you can do this with Karpenter, or is there something specific we are trying to highlight. Lastly - why are these important enough to highlight to users

> A demo application to demonstrates how Karpenter scales nodes based on workload constraints like nodeSelector, topologySpreadConstraints, and podAntiAffinity

What makes this unique from a Karpenter perspective since these are Kubernetes constructs? What should users take away from demonstrating these?

> Other add-ons like [aws-load-balancer-controller](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/aws-load-balancer-controller) and [external-dns](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/external-dns) running on fargate or nodes provisionned by Karpenter to demonstrate how a cluster can operate without any managed node groups

I'm not following this one. We have an example that shows a fully serverless cluster running on Fargate profiles with a [sample app and AWS LBC](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/6a5ec3397b3880a2d1c7ce0639b18e5b1c6212aa/examples/fargate-serverless/main.tf#L128-L148). If we want to add those addons here just to show resources running on compute provided by Karpenter, I think thats fine to add

**Comment by micbegin** [comment]
I think it would have been better to clarify these points before working on the PR. The description of this issue is the same since Nov 10, 2022. I was assigned to it and no questions where asked at that time so I assumed it was OK.

I also tried to answer all the questions (similar to the ones you are asking here) that were asked in https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1187 but did not get any feedback that could have help improving the PR.
