### ISSUE TITLE
git fetch error upon connecting to AWS CodeCommit repo using SSH

### ISSUE THREAD

**Issue by saratlin** [aws-ia/terraform-aws-eks-blueprints#1166]
## Description

I successfully connected to AWS CodeCommit using SSH. However, my argoCD application shows an error in argo UI:

`rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed exit status 128: Load key "/dev/shm/3417040879": error in libcrypto APKAZINASJ5QQT52GVZ2@git-codecommit.us-east-1.amazonaws.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.`

I am using AWS EKS to deploy argoCD. I generated an SSH key pair and stored the public key in an IAM user's credentials that has AWSCodeCommitFullAccess. The private key is stored in AWS secrets manager and referenced from terraform. Here's my argo config in terraform:

## Versions
ArgoCD - tried both 5.6.1 and 5.8.3 

- Module version [Required]:

- Terraform version:

- Provider version(s):

## Reproduction Code [Required]

````terraform
#enable argoCD
  enable_argocd = true

   argocd_helm_config = {
    name             = "argo-cd"
    chart            = "argo-cd"
    repository       = "https://argoproj.github.io/argo-helm"
    version          = "5.6.1"
    namespace        = "argocd"
    timeout          = "1200"
    create_namespace = true
    # Set default ArgoCD Admin Password using SecretsManager with Helm Chart set_sensitive values.
    set_sensitive = [
      {
        name  = "configs.secret.argocdServerAdminPassword"
        value = jsondecode(data.aws_secretsmanager_secret_version.admin_password_version.secret_string)["argocd"]
      }
    ]
   }

   argocd_manage_add_ons = false # Indicates that ArgoCD is responsible for managing/deploying add-ons

   argocd_applications = {
     workloads = {
       path                = "charts" #"env/${var.env_name}/${var.cell_name}"  
       repo_url            = "ssh://APKAZINASJ5QQT52GVZ2@git-codecommit.us-east-1.amazonaws.com/v1/repos/datahubHelmRepo"
       ssh_key_secret_name = var.code_commit_secret
       add_on_application = false
     }
   }

   enable_argo_rollouts = true

````

1. setup a code commit repo
2. generate a ssh keypair
3. create an IAM user
4. set public key in IAM user credentials
5. set private key in AWS secrets manager
6. name the secret code_commit_secret
7. use the same name for the secret's variable name in terraform
8. make the following changes to this example: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/gitops/argocd/main.tf
9. run terraform init, plan and apply

## Expected behaviour

ArgoCD connects to code commit repo and the application syncs correctly.

## Actual behaviour

Application shows the error above.

**Comment by bryantbiggs** [comment]
I'm afraid this is outside the scope of the project. It appears that the SSH key that is being used/provided is either incorrect, not available, or does not have the appropriate permissions
