### ISSUE TITLE
Improved IAM permissions with more resource restrictions

### ISSUE THREAD

**Issue by danvau7** [aws-ia/terraform-aws-eks-blueprints#1169]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

At [this link](https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.16.0/iam/minimum-iam-policy/) I noticed the following line: 

```
Note: The policy resource is set as * to allow all resources, this is not a recommended practice.
```

Is there any way to restrict this policy or improve upon this policy? At the minimum, I think restricting to something like a region, say `us-east-1` (or wherever the cluster is created), would be sufficient. Or perhaps there is a way to update the roles that appear in IAM (I think the blueprint creates about 5 of them) with code to restrict by region? An AWS permissions boundary should take care of this.

Anyway thank you for your suggestions if you have any!

**Comment by bryantbiggs** [comment]
the policy that is provided is automatically generated by a tool https://github.com/iann0036/iamlive which shows what permission APIs are required. In terms of further scoping down that policy to something more specific, this can only be done by users based on the conditions they are looking to enforce
