### ISSUE TITLE
csi_secrets_store_provider_aws error when providing existing namespace into csi_secrets_store_provider_aws_helm_config like kube-system

### ISSUE THREAD

**Issue by mldevpants** [aws-ia/terraform-aws-eks-blueprints#1172]
## Description

The creation of namespace does not have a condition either the namespace parameter was provided or the namespace is kube-system.
I've tried to use kube-system to fix permissions in the cluster and hence found the problem,
Also missing handling the create_namespace parameter if provided as opposed to other addons.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

- [x] 1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
- [x] 2. Re-initialize the project root to pull down modules: `terraform init`
- [x] 3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
  - 4.14.0
  - 4.15.0
  - 4.16.0

- Terraform version:
- Provider version(s):
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.39.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
❯ tg -version
terragrunt version v0.40.0

## Reproduction Code [Required]

add this part to the addons:
```hcl
module "kubernets_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons/?ref=v4.16.0"
  .
  .
  .
  enable_secrets_store_csi_driver_provider_aws = true

  csi_secrets_store_provider_aws_helm_config = {
    namespace = "kube-system"
    values = [
      <<-EOT
        rbac:
          install: true
          pspEnabled: false

        secrets-store-csi-driver:
          syncSecret.enabled: true
      EOT
    ]
  }
}
```

 - Both, different projects, one with terragrunt with default workspace and other with workspaces

- Yes, cleared the local cache

Perform the steps 
1. init
2. plan
3. apply

## Expected behaviour
Installs the chart without trying to create the namespace provided since "namespace" was provided and the namespace is "kube-system".
Also missing the create_namespace parameter to handle the the namespace creation.

install the chart in the given namespace without trying to create "kube-system" namespace

## Actual behaviour
The addon tries to create alrady existing namespace and throughs an error

### Terminal Output Screenshot(s)
```
╷
│ Error: namespaces "kube-system" already exists
│ 
│   with module.kubernetes_addons.module.csi_secrets_store_provider_aws[0].kubernetes_namespace_v1.csi_secrets_store_provider_aws,
│   on .terraform/modules/kubernetes_addons/modules/kubernetes-addons/csi-secrets-store-provider-aws/main.tf line 6, in resource "kubernetes_namespace_v1" "csi_secrets_store_provider_aws":
│    6: resource "kubernetes_namespace_v1" "csi_secrets_store_provider_aws" {
│ 
```

**Comment by MaiCabrera** [comment]
Thank you for this!!! I was just refactoring my iaac and got this error. 
![image](https://user-images.githubusercontent.com/61064938/201958497-2a4f0f97-4453-400e-ab41-4b172ad3e058.png)
please lets get this in today 🙏🏼

**Comment by MaiCabrera** [comment]
@mldevpants any chance for your PR to get merged? 🙏🏼
