### ISSUE TITLE
Upgrades for karpenter v0.19.1

### ISSUE THREAD

**Issue by askulkarni2** [aws-ia/terraform-aws-eks-blueprints#1175]
Things that need upgrade:
1. Helm chart version upgrade
2. Native Spot Termination Handling IRSA policy update ([#2546](https://github.com/aws/karpenter/pull/2546))
3. Update [values.yaml](https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L129-L161) for `karpenter-global-settings`

**Comment by armujahid** [comment]
Perhaps we also need to maintain backward compatibility so that karpenter < v0.19 can also be installed.

**Comment by FernandoMiguel** [comment]
> Perhaps we also need to maintain backward compatibility so that karpenter < v0.19 can also be installed.

what do you propose @armujahid ?

**Comment by FernandoMiguel** [comment]
@armujahid but we dont have go here... only terraform
not sure how the maintainers of this project would want to handle this

**Comment by FernandoMiguel** [comment]
we can keep HEAD using latest karpenter, and anyone that needs the older config can use a previous release tag

**Comment by FernandoMiguel** [comment]
@armujahid i wouldnt know how that is best handled on this project since I dont handle release notes

**Comment by bryantbiggs** [comment]
users are able to provide both the version of Karpenter as well as its associated values so we don't  need to worry about anything dynamic
