### ISSUE TITLE
NodeLocal DNSCache

### ISSUE THREAD

**Issue by askulkarni2** [aws-ia/terraform-aws-eks-blueprints#1182]
Add-on for https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use NodeLocal DNSCache you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
