### ISSUE TITLE
Cannot upgrade argocd 

### ISSUE THREAD

**Issue by ZeroDeth** [aws-ia/terraform-aws-eks-blueprints#1190]
## Description

The issue with upgrading argocd for missing the following:
`app.kubernetes.io/managed-by: Helm`
& `app.kubernetes.io/instance: <RELEASE_NAME>`

<img width="1043" alt="CleanShot 2022-11-17 at 21 33 03@2x" src="https://user-images.githubusercontent.com/10928577/202564360-c1c6324e-1639-4e2e-8b25-6bb72fac43e1.png">

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

As described in this PR: https://github.com/helm/helm/pull/7649

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v4.16.0

- Terraform version: v1.1.9

- Provider version(s):

### Terminal Output Screenshot(s)

The same issue after annotating & label all applications & namespace under argocd  
<img width="1006" alt="CleanShot 2022-11-17 at 22 40 29@2x" src="https://user-images.githubusercontent.com/10928577/202575586-09d8c023-89b5-47ce-9ac6-c8b6b87bb888.png">

**Comment by domeales-paloit** [comment]
I have just hit this issue too.

Any workarounds or fixes for this?

**Comment by domeales-paloit** [comment]
I have a workaround. I manually added the labels and annotations that Helm was complaining about, using `kubectl` and a bit of shell:

```bash
kubectl get crds \
  | awk '/argoproj/{print $1}' \
  | xargs -n1 sh -c 'kubectl label crd $0 app.kubernetes.io/managed-by=Helm && kubectl annotate crd $0 meta.helm.sh/release-name=argo-cd meta.helm.sh/release-namespace=argocd'
```

After doing this the upgrade worked correctly via Terraform.

**Comment by bryantbiggs** [comment]
this looks to be an upstream issue that should be handled by ArgoCD, closing for now
