### ISSUE TITLE
AWS Node Termination Handler - Support for ArgoCD Gitops

### ISSUE THREAD

**Issue by mikeinton** [aws-ia/terraform-aws-eks-blueprints#1194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
We’d like to install NTH via ArgoCD.

#### Describe the solution you would like
There is an open feature request to add NTH to the eks-blueprints-add-ons example repo here - https://github.com/aws-samples/eks-blueprints-add-ons/issues/32.

In addition to adding the argo application manifests to the add-ons repo above, it seems that the kubernetes-addons module in this repo will need an enablement of manage_via_gitops for aws-node-termination-handler.

#### Additional context
If there are no concerns with deploying NTH via ArgoCD I'd like to work on a PR to get this added. Thanks.

**Comment by bryantbiggs** [comment]
> If there are no concerns with deploying NTH via ArgoCD I'd like to work on a PR to get this added. Thanks.

Yes, please do if you can
