### ISSUE TITLE
EKS IPv6 with Cilium Chain Mode + DualStack

### ISSUE THREAD

**Issue by sabinayakc** [aws-ia/terraform-aws-eks-blueprints#1201]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have setup a new EKS with IPV6 Enabled. Now I want to implement Cilium CNI. Has anyone implemented Cilium with EKS IPV6?

I know AWS VPC CNI doesn't support dual stack and that's why I am trying to use Cilium in chaining mode. 

Any suggestion or advice would be greatly appreciated?

#### Provide a link to the example/module related to the question

Similar Issue: https://github.com/cilium/cilium/issues/18405 

#### Additional context

I am trying to use Helm and pass the necessary helm values to make this work.

**Comment by triadcode** [comment]
Same here. Any news about this?
