### ISSUE TITLE
Support for Juniper CN2 CNI as add-on

### ISSUE THREAD

**Issue by prtkdave** [aws-ia/terraform-aws-eks-blueprints#1203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

We will be able to deploy EKS cluster with Juniper CN2 CNI.

Currently, We do not have support for Juniper CN2 , we will be able to deploy CN2 using helm chart by adding this add-on.
#### Describe the solution you would like
EKS Cluster with Juniper CN2 as CNI

For more details checkout [CN2](https://www.juniper.net/us/en/products/sdn-and-orchestration/contrail/cloud-native-contrail-networking.html) docs

**Comment by bryantbiggs** [comment]
Thank you for the issue @prtkdave   - this looks like its just simply wrapping the Juniper CN2 CNI helm chart using `helm_release` resource directly. I would recommend that route if you wish to deploy the Juniper CN2 CNI in your cluster

**Comment by prtkdave** [comment]
The requirement is to install CN2 CNI as part of terraform blueprint which requires this to be added as a kubernetes add-on in blueprint repo.
