### ISSUE TITLE
Set the variable TF_APPEND_USER_AGENT to improve troubleshooting experience

### ISSUE THREAD

**Issue by csantanapr** [aws-ia/terraform-aws-eks-blueprints#1205]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Improve observability when troubleshooting a problem with the blueprint addons

#### Describe the solution you would like

To be able to easily detect which version of the blueprint is being used when helping an end user with a blueprint

#### Describe alternatives you have considered

Customize the User-Agent for terraform providers by using the `TF_APPEND_USER_AGENT` described here https://registry.terraform.io/providers/hashicorp/aws/latest/docs#custom-user-agent-information

The string could contain the version or if using git HEAD then the commit hash 7

For example: `EKSBlueprints BuildId/v4.17.0` or `EKSBlueprints BuildID/bb52577`

**Comment by bryantbiggs** [comment]
this would have to take place on the users end - closing this for now
