### ISSUE TITLE
Consolidate and enrich destroy instructions

### ISSUE THREAD

**Issue by timblaktu** [aws-ia/terraform-aws-eks-blueprints#1229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I would like to see the various instructions for how to destroy eks_blueprints consolidated, and in a single place, or at least properly inter-linked so that it is easy and obvious to users what _superset_ of problems exist that necessitate a controlled destroy sequence at all. 

At first glance, we have:

1. https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.18.0/getting-started/#cleanup
2. https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/FAQ.md#timeouts-on-destroy
3. specific recommendations embedded within each example project - https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples

This is a follow up on the issue I raised which was apparently caused by the well-known "leaky vpc eni" issue, and closed from inactivity. As I now have time to return to the issue (bc I'm still seeing "can't delete X bc Y has dependencies issues presumably caused by leaky eni), I made a [comment](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/968#issuecomment-1337542991), then realized it's best to create a new issue, so here we are.

#### Describe the solution you would like

1. Decide on what is the single-source-of-truth for this information (probably 1 above)
2. Create a list of all known bugs, race conditions, and as-design-terraform-isms that require workarounds
3. Embellish the official destroy sequence list with references to ALL of these workarounds inserted in the relevant stage of the destroy sequence.

4. Improve the instructions by showing the user _how_ to do all the steps. For the most part, this is already well done, but an example of where this is not is in the case of [the "Timeouts on Destroy" FAQ](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/FAQ.md#timeouts-on-destroy), it's not specified how long to wait, nor how to destroy the VPC ENI.

#### Describe alternatives you have considered

Spend days diving deep into relevant modules and answering these questions myself, not benefiting other users.

**Comment by timblaktu** [comment]
Re: how to "Delete VPC ENI", searching eks_blueprints for vpc and/or cni, I found references to it from the amazon_vpc_cni configmap and eni_config manifest, so I implemented:

  time terraform destroy -refresh=false \
      -target="module.eks_blueprints.kubernetes_config_map.amazon_vpc_cni" \
      -target="kubectl_manifest.eni_config"

Also found `eni_delete` input to the node groups. Can someone enlighten me on what is to be done in step 3 in [the FAQ](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/FAQ.md#timeouts-on-destroy)?

**Comment by dfroberg** [comment]
Might want to add 
`kubectl delete  Mutatingwebhookconfigurations --all  --all-namespaces`
