### ISSUE TITLE
Assign EIP to Pod - EKS

### ISSUE THREAD

**Issue by ZeroDeth** [aws-ia/terraform-aws-eks-blueprints#1230]
- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Trying to assign EIP to multiple pods to Whitelist by customer
Cluster & App config:
- Istio: 1.13.5 (istio-ingressgateway is NodePort) 
- VPC (Nat Gateway & reuse EIP)
- Ingress-Controller (ingress-nginx-controller is LoadBalancer)
- Applications URLs is ALB
- CoreDNS 

As I understand from my quick research;  
- switching from ALB to NLB, could annotate service with `service.beta.kubernetes.io/aws-load-balancer-eip-allocations`
- Replacing CoreDNS to Calico (maybe can help)
- Difficult to replace Istio because it required lots of time to refactor and choosing a right product
- Applying SNAT ??

Appreciate if quick solution or guide to resolve to give a static IP to some services for whitelisting. 

Thank you!

**Comment by bryantbiggs** [comment]
thank you but this is outside the scope of the project
