### ISSUE TITLE
[bug]: ALB throwing error while creating security group

### ISSUE THREAD

**Issue by deepakjeena** [aws-ia/terraform-aws-eks-blueprints#1248]
## Description
ALB is throwing error while it is creating sg for ingress gateway

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

### Terminal Output Screenshot(s)

{"level":"info","ts":1670748375.893224,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"istio-system/alb-istio-ingress\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-istiosys-albistio-46cb354422\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":80,\"toPort\":80,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]},{\"ipProtocol\":\"tcp\",\"fromPort\":443,\"toPort\":443,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"443\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":443,\"protocol\":\"HTTPS\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}],\"certificates\":[{\"certificateARN\":\"arn:aws:acm:me-central-1:365834278172:certificate/5678458f-e54d-407e-b986-441434b6dfd3\"}],\"sslPolicy\":\"ELBSecurityPolicy-2016-08\"}},\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"443:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/443/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/istio-system/alb-istio-ingress-istio-ingressgateway:15021/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"host-header\",\"hostHeaderConfig\":{\"values\":[\"*.shared.huru.co\"]}},{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/healthz/ready\",\"/healthz/ready/*\"]}}]}},\"443:2\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/443/status/listenerARN\"},\"priority\":2,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/istio-system/alb-istio-ingress-istio-ingressgateway:443/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"host-header\",\"hostHeaderConfig\":{\"values\":[\"*.shared.huru.co\"]}},{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}},\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/istio-system/alb-istio-ingress-istio-ingressgateway:15021/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"host-header\",\"hostHeaderConfig\":{\"values\":[\"*.shared.huru.co\"]}},{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/healthz/ready\",\"/healthz/ready/*\"]}}]}},\"80:2\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":2,\"actions\":[{\"type\":\"redirect\",\"redirectConfig\":{\"port\":\"443\",\"protocol\":\"HTTPS\",\"statusCode\":\"HTTP_301\"}}],\"conditions\":[{\"field\":\"host-header\",\"hostHeaderConfig\":{\"values\":[\"*.shared.huru.co\"]}},{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-istiosys-albistio-f32a9febc1\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-0546f443e496470c0\"},{\"subnetID\":\"subnet-0797121fd5f65131f\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"},\"sg-0b98e96b18f95f677\"]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"istio-system/alb-istio-ingress-istio-ingressgateway:15021\":{\"spec\":{\"name\":\"k8s-istiosys-istioing-4a64c0dcef\",\"targetType\":\"instance\",\"port\":32459,\"protocol\":\"HTTPS\",\"protocolVersion\":\"HTTP1\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":32459,\"protocol\":\"HTTPS\",\"path\":\"/healthz/ready\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}},\"istio-system/alb-istio-ingress-istio-ingressgateway:443\":{\"spec\":{\"name\":\"k8s-istiosys-istioing-c110344d76\",\"targetType\":\"instance\",\"port\":30699,\"protocol\":\"HTTPS\",\"protocolVersion\":\"HTTP1\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":32459,\"protocol\":\"HTTPS\",\"path\":\"/healthz/ready\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"istio-system/alb-istio-ingress-istio-ingressgateway:15021\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-istiosys-istioing-4a64c0dcef\",\"namespace\":\"istio-system\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/istio-system/alb-istio-ingress-istio-ingressgateway:15021/status/targetGroupARN\"},\"targetType\":\"instance\",\"serviceRef\":{\"name\":\"istio-ingressgateway\",\"port\":15021},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":\"sg-0b98e96b18f95f677\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":32459}]},{\"from\":[{\"securityGroup\":{\"groupID\":\"sg-0b98e96b18f95f677\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":32459}]}]},\"ipAddressType\":\"ipv4\"}}}},\"istio-system/alb-istio-ingress-istio-ingressgateway:443\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-istiosys-istioing-c110344d76\",\"namespace\":\"istio-system\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/istio-system/alb-istio-ingress-istio-ingressgateway:443/status/targetGroupARN\"},\"targetType\":\"instance\",\"serviceRef\":{\"name\":\"istio-ingressgateway\",\"port\":443},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":\"sg-0b98e96b18f95f677\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":30699}]},{\"from\":[{\"securityGroup\":{\"groupID\":\"sg-0b98e96b18f95f677\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":32459}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}
{"level":"error","ts":1670748376.498004,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"alb-istio-ingress","namespace":"istio-system","error":"AccessDeniedException: \n\tstatus code: 400, request id: 8c4cb483-e6cd-4639-be33-0c92d8d4800a"}

**Comment by Zvikan** [comment]
@deepakjeena we'll need a reproduction code in order to reproduce this issue first and troubleshoot from there.
if you used existing example, feel free to share a link of it. Thanks

**Comment by bryantbiggs** [comment]
closing for now - please feel free to provide more information here and we can revisit
