### ISSUE TITLE
EKS addons data lookup causing re-creation of resources

### ISSUE THREAD

**Issue by Pacobart** [aws-ia/terraform-aws-eks-blueprints#1253]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

The following change from `var.eks_cluster_id` to `data.aws_eks_cluster.eks_cluster.id` is causing resources to be re-created. This causes issues with all addons. Most noteably the vpc-cni plugin needs the iam role provisioned in order for the plugin to come to a ready state. Since this doesn't happen until after a managed node group is deployed, the managed node group fails to provision.

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/0875b78e09074b8fc48f757567bdd7e17ae9e574/modules/kubernetes-addons/locals.tf#L58

Here's an example of the forced re-creation. No changes were made to this module so it shouldn't be replaced.
```
  # module.eks.module.eks_addons[0].module.aws_for_fluent_bit[0].aws_iam_policy.aws_for_fluent_bit must be replaced
-/+ resource "aws_iam_policy" "aws_for_fluent_bit" {
      ~ arn         = "arn:aws:iam::XXXXX:policy/toolchain-dev-fluentbit" -> (known after apply)
      ~ id          = "arn:aws:iam::XXXXX:policy/toolchain-dev-fluentbit" -> (known after apply)
      ~ name        = "toolchain-dev-fluentbit" -> (known after apply) # forces replacement
    }
```
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 4.17.0

- Terraform version:
1.2.x
- Provider version(s):
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.72"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.10"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.4.1"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14"
    }
  }

## Reproduction Code [Required]

 Yes
 Yes

Run terraform plan/apply
Run terraform plan/apply again with no changes (may need to run 2 times to see the resource marked for recreation)

## Expected behaviour

If no changes are made for the resources, we shouldn't be re-creating them.

## Additional context

Issue introduced in previous PR: https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1200/files#diff-b3cde19b7e5167911ebfa8fd07ec22d9797f2e5414146035d129b2c2668ee28a

This issue started over the last few weeks, consistent with the release of the above PR.

**Comment by bryantbiggs** [comment]
do you have an explicit `depends_on` in your addons module definition?

**Comment by Pacobart** [comment]
> do you have an explicit `depends_on` in your addons module definition?
Yes, it does.

**Comment by bryantbiggs** [comment]
That should be removed and the problem will be resolved

**Comment by bryantbiggs** [comment]
you should not use `depends_on` across modules since it is very disruptive https://github.com/hashicorp/terraform/issues/26383

**Comment by tsndqst** [comment]
ah.  I'll find a different solution then.  I'm thinking a data object like https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/8fa9a62d/data.tf#L10-L16 that watches for nodes to be available.

**Comment by bryantbiggs** [comment]
you can use the `data_plane_wait_arn` to force the addons to wait for any values passed in to resolve before proceeding https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/90346b8545072ac032f64c232cbcaa6950348034/examples/fargate-serverless/main.tf#L98

**Comment by tsndqst** [comment]
Thanks!  I'll give it a try.

**Comment by bryantbiggs** [comment]
closing for now with guidance provided above
