### ISSUE TITLE
Broken link on "Amazon EKS Blueprint for Terraform"

### ISSUE THREAD

**Issue by John1Q84** [aws-ia/terraform-aws-eks-blueprints#1258]
## Description

ADoT introduction MD file seemed broken
"https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/aws-open-telemetry.md"
Above MD file shows broken page like attached png file

![image](https://user-images.githubusercontent.com/2988285/208020297-6404d59c-85b5-4bfd-b3ce-5843d44f2981.png)

**Comment by Zvikan** [comment]
@John1Q84 can you please provide details how you got to this page? was it from a different website/google search etc?
I did a search for `aws-open-telemetry.md` across the project and couldn't find anything like it.
Also looking at the URL itself, after `terraform-aws-eks-blueprints` and before `add-ons` there should be the version of the docs (i.e. `latest` / `v4.19.0` etc.).

**Comment by mattjshannon** [comment]
Hey, I came across this issue too. I came across it by first searching for `aws eks terraform` on Google. One of the first page results goes to: https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.25.0/

From that page, if you click on `Node Groups` (shows as https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.25.0/node-groups.md) it takes you to that broken page.
