### ISSUE TITLE
Add Windows Managed nodegroup support

### ISSUE THREAD

**Issue by marciogmorales** [aws-ia/terraform-aws-eks-blueprints#1259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Customers have the option to deploy a Windows-managed node group using EKS Blueprints.

#### Describe the solution you would like

Adding support for Windows Server 2019/2022 for managed node groups. Set Windows Server 2019 as default. In order to do so, we need to add **eks:kube-proxy-windows** to AWS IAM Authenticator configuration map when using Custom AMIs.

#### Describe alternatives you have considered

N/A

#### Additional context

https://github.com/aws/containers-roadmap/issues/584
https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html 

[]

**Comment by bryantbiggs** [comment]
Requires the Terraform aws-sdk version to be updated https://github.com/hashicorp/terraform-provider-aws/issues/28438

**Comment by mijndert** [comment]
@bryantbiggs can we get an update on this? Seems like the mentioned issue has been closed. Thanks!

**Comment by mijndert** [comment]
@bryantbiggs any word on this yet? thanks!

**Comment by Chabane** [comment]
any update to share?

**Comment by askulkarni2** [comment]
Given the direction of EKS Blueprints v5 this belongs in https://github.com/terraform-aws-modules/terraform-aws-eks. Closing it here. Please reopen in the upstream module.
