### ISSUE TITLE
Creating private EKS cluter with blueprints fails because of readiness

### ISSUE THREAD

**Issue by majstorki88** [aws-ia/terraform-aws-eks-blueprints#1264]
I want to create EKS cluster with a private endpoint (not to be able to access to API from the internet), and I have used following variables:

```console
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access = false
```
for `eks_blueprints` module.

When I run terraform apply, I got error with readiness (which is expected because endpoint is internal) because of this condition in data: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/696af3c8a399945c19ac1000981d70df107db7d1/data.tf#L11

As readiness is needed because further installation of k8s plugins (crossplane, argocd etc), do you maybe have some idea how to make workaround for this and make cluster private?

I want to be able to access EKS API only from jump (bastion) machine on AWS which have VPN Site to Site connection to my machine.

Thanks in advance

As addition, when I want to change EKS now to public by changing those values:

```console
  cluster_endpoint_private_access = false
  cluster_endpoint_public_access = true
```
Terraform plan command also fails because of readiness again...

**Comment by FernandoMiguel** [comment]
> I want to be able to access EKS API only from jump (bastion) machine on AWS which have VPN Site to Site connection to my machine.

vpc endpoints, vpc peer, transit gateways, are better options for you to look for

**Comment by majstorki88** [comment]
> > I want to be able to access EKS API only from jump (bastion) machine on AWS which have VPN Site to Site connection to my machine.
> 
> vpc endpoints, vpc peer, transit gateways, are better options for you to look for

but in that case, as I understand, will EKS have a publicly available endpoint or not?

**Comment by FernandoMiguel** [comment]
Any of those will be the VPC CIDRs that will reach your cluster

**Comment by majstorki88** [comment]
Well, I already planed transit GW in my scenario - but I also want private EKS endpoint.

I have written down some components that I want to deploy:

![image](https://user-images.githubusercontent.com/29049188/208444797-ab8abf77-9fb5-4a84-810f-fb014092b738.png)
 
And not sure what I will get with the publicly available EKS endpoint and VPC endpoint or transit GW...because I want to forbid any traffic from outside AWS to EKS API directly.

**Comment by FernandoMiguel** [comment]
All of ours are private, and we access them cross transit gw without any issues.
Even from Argo in other aws accounts.

**Comment by majstorki88** [comment]
Ah, than I understand. You have actually divided terraform scripts for transit GW and for EKS, and I have tried to deploy all components with one terraform. Thanks for help, and I will divide network objects and EKS into separate terraform plans.
