### ISSUE TITLE
K8ssandra Operator for Cassandra DB

### ISSUE THREAD

**Issue by AlyIbrahim** [aws-ia/terraform-aws-eks-blueprints#1277]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Create K8ssandra Operator as a Kubernetes add-on

#### Describe the solution you would like

As part of DoEKS to create Cassandra blueprints, we need K8ssandra operator. In this solution I will be installing k8ssandra operator using helm chart.

#### Describe alternatives you have considered

K8ssandra-operator comes in two versions for single and multi cluster installation. I am recommend using the single cluster/region.

#### Additional context

This is a pre-requisistes as part of DoEKS.

**Comment by AlyIbrahim** [comment]
I am working on this fix, you can assign it to me.

**Comment by vara-bonthu** [comment]
Thanks Aly 👍 Go for it!

**Comment by bryantbiggs** [comment]
Thank you for the issue @AlyIbrahim   - this looks like its just simply wrapping the K8ssandra helm chart, any reason to not just use the `helm_release` resource directly to deploy?

**Comment by AlyIbrahim** [comment]
@bryantbiggs That could be an option to use helm_release directly in DataOnEKS solution. I was thinking to add the operator here as part of the addons we offer for EKS blueprints as well.

**Comment by vara-bonthu** [comment]
@AlyIbrahim Lets add the helm release and the operator in Data on EKS blueprints. Closing this issue now
