### ISSUE TITLE
Add Virtual Gpu Device plugin support

### ISSUE THREAD

**Issue by leonidkhelemes** [aws-ia/terraform-aws-eks-blueprints#1278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
I want to be able use [aws-virtual-gpu-device-plugin](https://github.com/awslabs/aws-virtual-gpu-device-plugin)  with EKS Blueprints.
Share physical gpu with different pods on the same node. 
Ability to simply enable this plugin like other k8s plugins like **enable_amazon_eks_vgpu = true**

#### Describe the solution you would like

from their official documantation
kubectl create -f https://raw.githubusercontent.com/awslabs/aws-virtual-gpu-device-plugin/v0.1.1/manifests/device-plugin.yml

**Comment by bryantbiggs** [comment]
Thank you for the issue @leonidkhelemes   - this looks like its just simply wrapping the Daemonset, any reason to not just use the `kubernetes_daemon_set_v1` resource directly to deploy?

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Virtual GPU device plugin you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
