### ISSUE TITLE
Error with istio csr | seems this feature is not tested

### ISSUE THREAD

**Issue by deepakjeena** [aws-ia/terraform-aws-eks-blueprints#1280]
## Description
I am trying to install istio csr but this module is returing error I have tried different configuration but i am failed to deploy istio-csr.

module "eks_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.18.0"

  enable_cert_manager = true
  enable_cert_manager_istio_csr = true
  cert_manager_helm_config = {
    version = "v1.10.1"
  }
}

### Terminal Output Screenshot(s)

│ Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "istiod" namespace: "istio-system" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
│ ensure CRDs are installed first
│ 
│   with module.eks_addons.module.cert_manager_istio_csr[0].module.helm_addon.helm_release.addon[0],
│   on /home/ec2-user/git/infra/terraform/workspace/data/shared/eks/modules/eks_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│

**Comment by Pacobart** [comment]
@deepakjeena You will need to ensure the cert-manager CRD's are successfully installed before istio-csr will deploy properly. Will you validate with this command `kubectl get customresourcedefinitions | grep cert-manager.io`?

**Comment by deepakjeena** [comment]
@Pacobart : here is the output:

 kubectl get customresourcedefinitions | grep cert-manager.io
certificaterequests.cert-manager.io          2023-02-05T20:46:37Z
certificates.cert-manager.io                 2023-02-05T20:46:37Z
challenges.acme.cert-manager.io              2023-02-05T20:46:37Z
clusterissuers.cert-manager.io               2023-02-05T20:46:37Z
issuers.cert-manager.io                      2023-02-05T20:46:37Z
orders.acme.cert-manager.io                  2023-02-05T20:46:37Z

**Comment by bryantbiggs** [comment]
thank you for the issue - as we move forward with the project, we will not be continuing to support this addon within the project. if you wish to use Istio you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
