### ISSUE TITLE
Cert Manager Error

### ISSUE THREAD

**Issue by YuvarajuR** [aws-ia/terraform-aws-eks-blueprints#1282]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have provisioned the private endpoint eks cluster through the blueprints and enabled the cert-manager addon and it's failing.

#### Provide a link to the example/module related to the question
For your reference i've copied the tf code below
# -----------------------------------------------------------
# EKS Blueprints Kubernetes Addons
# -----------------------------------------------------------
module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints/modules/kubernetes-addons"

  eks_cluster_id       = module.eks_blueprints.eks_cluster_id
  eks_cluster_endpoint = module.eks_blueprints.eks_cluster_endpoint
  eks_oidc_provider    = module.eks_blueprints.oidc_provider
  eks_cluster_version  = module.eks_blueprints.eks_cluster_version

  # EKS Managed Add-ons
  enable_amazon_eks_vpc_cni            = false
  enable_amazon_eks_coredns            = true
  enable_amazon_eks_kube_proxy         = true
  enable_amazon_eks_aws_ebs_csi_driver = true

 # Disable coredns_cluster_proportional_autoscaler, it is enabled by default
  enable_coredns_cluster_proportional_autoscaler = false

  # Add-ons  
  enable_aws_load_balancer_controller = true
  enable_metrics_server               = true
  enable_aws_cloudwatch_metrics       = true
  enable_kubecost                     = false
  enable_gatekeeper                   = false
  enable_kubernetes_dashboard         = true
  enable_cluster_autoscaler           = true

  enable_cilium = true
  cilium_helm_config = {
    #default_cni = true  
    set = [
        {
          name = "cni.chainingMode"
          value = "none"
        },
        {
          name  = "tunnel"
          value = "vxlan"
        },
        {
          name  = "enableIPv4Masquerade"
          value = true
        },
        {
          name  = "endpointRoutes.enabled"
          value = false
        },
        {
         name  = "ipam.mode"
         value = "cluster-pool"
        },
        {
         name  = "ipam.operator.clusterPoolIPv4PodCIDRList"
         value =  "10.100.0.0/16"
        },
        {
         name  = "egressMasqueradeInterfaces"
         value = "eth0"
        },
        {
         name  = "hubble.ui.enabled"
         value = true
        },
        {
         name  = "hubble.relay.enabled"
         value = true
        }
    ]
  }
  
  cluster_autoscaler_helm_config = {
    set = [
      {
        name  = "podLabels.prometheus\\.io/scrape",
        value = "true",
        type  = "string",
      }
    ]
  }

  enable_cert_manager = true
  cert_manager_helm_config = {
    set_values = [
      {
        name  = "extraArgs[0]"
        value = "--enable-certificate-owner-ref=true"
      },
      # {
      #   name  = "serviceAccount.name"
      #   value = "var.serviceAccount"
      # },
      {
        name  = "installCRDs"
        value = "true"
      }
    ]
  }
  enable_cert_manager_csi_driver = true
  tags = local.tags

  depends_on = [module.eks_blueprints,module.eks_blueprints.managed_node_groups]
}

#### Additional context
Terraform apply output below

<html>
<body>

module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0]: Still creating... [5m0s elapsed]
--
863 | module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0]: Still creating... [5m10s elapsed]
864 | module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0]: Still creating... [5m20s elapsed]
865 | module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0]: Still creating... [5m30s elapsed]
866 | ╷
867 | │ Warning: Helm release "cert-manager" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
868 | │
869 | │   with module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0],
870 | │   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
871 | │    1: resource "helm_release" "addon" {

<html>
<body>

Error: failed post-install: job failed: BackoffLimitExceeded
--
888 | │
889 | │   with module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0],
890 | │   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
891 | │    1: resource "helm_release" "addon" {

</body>
</html>

Can any help me on this issue or any suggestions will be appreciated.

**Comment by YuvarajuRudraraju** [comment]
Can anyone help me on this ....

**Comment by Zvikan** [comment]
Hey @YuvarajuR , the only error message I can see here is that the helm deployment for cert manager failed because a job called "post-install" failed, that usually means a hook job after deployment is running and failing.

try to run `kubectl get all -n cert-manager` then you should see a job that's probably in status 0/1 , run `kubectl describe job -n cert-manager <job_name>` and see if you can track down the issue there, feel free to share your findings here.

Also, I highly recommend you'll use GitHub markdown when sharing code snippets, you can learn how to do it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), you can also select "Add code" (<>) which is an option on the top right of the comment box.

**Comment by bryantbiggs** [comment]
closing for now - please feel free to provide more information here and we can revisit
