### ISSUE TITLE
Dynamic managed nodegroups

### ISSUE THREAD

**Issue by tomerleib** [aws-ia/terraform-aws-eks-blueprints#1286]
- [x] ✋ I have searched the open/closed issues, and my issue is not listed.

#### Please describe your question here

According to the examples of using managed node groups, users need to provide a static value per nodegroup.
Can the node groups be created dynamically, i.e., the user will provide a list, and for each item in the list, a new nodegroup will be created?

**Comment by bryantbiggs** [comment]
The node groups are "dynamic" in that you can pass a map of definitions and for each entry in that map, a node group will be created
