### ISSUE TITLE
Request a Rancher Add-on 

### ISSUE THREAD

**Issue by peishuli** [aws-ia/terraform-aws-eks-blueprints#1287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Currently installing a SUSE Rancher on Kubernetes clusters including EKS is manual process (https://ranchermanager.docs.rancher.com/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster). A new add-on for Rancher will enable EKS customers to install Rancher on EKS as simple as using any existing Terraform EKS blueprints add-ons.

#### Describe the solution you would like

Terraform EKS blueprints users will be able to leverage the add-on framework to install SUSE Rancher on the EKS cluster:
```
  enable_rancher       = true
  rancher_helm_config       = {
    hostname                  = "rancher.${var.eks_cluster_domain}"
    bootstrapPassword         = "admin"
    ingress_tls_source        = "letsEncrypt"
    ingress_ingressClassName  = "nginx"
    version                   = "2.7.0"
  }
```
#### Describe alternatives you have considered

N/A

#### Additional context

We have successfully used new add-on in our real world EKS/Rancher deployments.

**Comment by bryantbiggs** [comment]
Thank you for the issue @peishuli   - this looks like its just simply wrapping the Rancher helm chart, any reason to not just use the `helm_release` resource directly to deploy?

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Rancher you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
