### ISSUE TITLE
[ADDON] - Add Addons for CloudNative PG operator

### ISSUE THREAD

**Issue by jihed** [aws-ia/terraform-aws-eks-blueprints#1288]
Kubernetes Add-on for [CloudNative PG operator](https://cloudnative-pg.io/) deployment in EKS
Example pattern for deploying production grade CloudNative PG deployment in EKS with best practices
Documentation for CloudNative PG usage with few examples

**Comment by bryantbiggs** [comment]
Thank you for the issue @jihed   - this looks like its just simply wrapping the CloudNative PG operator helm chart, any reason to not just use the `helm_release` resource directly to deploy?

**Comment by jihed** [comment]
Thanks Bryan for feedback. 

The goal is to use CloudNative PG operator as a terraform  helm-addon  and deployed with `terraform-aws-eks-blueprints`. This is will be used later on [data on eks project](https://awslabs.github.io/data-on-eks/) to share best practices on how to run postresql db via cloudnative-pg operator.

Tell me that makes sense.

**Comment by bryantbiggs** [comment]
please see https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/docs/v5-direction/DIRECTION_v5.md which is still under discussion https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1319

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use CloudNative PG operator you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
