### ISSUE TITLE
Upgrade/blue-green-route53 example ASG uses private and public subnets

### ISSUE THREAD

**Issue by brenwhyte** [aws-ia/terraform-aws-eks-blueprints#1293]
## Description

The [Upgrade/blue-green-route53](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/upgrade/blue-green-route53) example ASG uses private and public subnets when only private subnets are default.
This results in some instances spawning in either private or public subnets.

See: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/upgrade/blue-green-route53/modules/eks_cluster/main.tf#L228

I expect this has gone unnoticed as the nodes also get public ips assigned by default so have internet access.
I came across the issue when setting `public_ip  = false` in the `managed_node_groups` 

## Versions

- Module version [Required]: v4.18.1
Same for most recent 4.20 too

- Terraform version:
1.36

## Reproduction Code [Required]

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/upgrade/blue-green-route53

Spin up example blue-green-route53

## Expected behaviour

ASG nodes to spin up in private subnets

## Actual behaviour

ASG nodes spin up in both private and pubic subnets

### Terminal Output Screenshot(s)

n/a

## Additional context

I did try setting `subnet_type = "private"` in the managed_node_groups but this has no effect.

**Comment by bryantbiggs** [comment]
@allamand

**Comment by allamand** [comment]
Hi @brenwhyte, in the link you point, we can see that it uses the private subnet for the Managed node group: 

```
  managed_node_groups = {
    mg_5 = {
      node_group_name = local.node_group_name
      instance_types  = ["m5.xlarge"]
      min_size        = 3
      subnet_ids      = data.aws_subnets.private.ids
    }
  }
```

So all the nodes should be in the private subnet already
