### ISSUE TITLE
strimzi-kafka-operator: Namespace not created when `argocd_manage_add_ons=true`

### ISSUE THREAD

**Issue by Sebelino** [aws-ia/terraform-aws-eks-blueprints#1309]
## Description

I am trying to use [strimzi-kafka-operator](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/strimzi-kafka-operator) by setting `enable_strimzi_kafka_operator = true` in a module call to `kubernetes-addons`. However, when ArgoCD is managing the add-ons, ArgoCD fails to sync because a Kubernetes namespace for Strimzi is not being created.

![image](https://user-images.githubusercontent.com/837775/211336887-b2880d9e-e98f-4f86-a2fb-9b8501b5f2ba.png)

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v4.20.0

- Terraform version: Terraform v1.3.7 on linux_amd64

- Provider version(s):

```
Terraform v1.3.7              
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.49.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

## Reproduction Code [Required]

Add `enable_strimzi_kafka_operator = true` to the `examples/gitops/argocd/` example:

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a91b8409eac7442323de800584e762a525cde268/examples/gitops/argocd/main.tf#L126

1. `cd examples/gitops/argocd`
2. Add `enable_strimzi_kafka_operator = true` to the `eks_blueprints_kubernetes_addons` module call
3. `terraform init`
4. `terraform apply`

## Expected behaviour

A Kubernetes namespace named `strimzi` is created.

## Actual behaviour

A Kubernetes namespace named `strimzi` is not created.

**Comment by bryantbiggs** [comment]
this should be solved on the chart for the operator instead, like this https://github.com/aws-samples/eks-blueprints-add-ons/blob/1b131cafc5a331cf32d7d269fc8aa3ded69a803c/chart/templates/vault.yaml#L24-L25
