### ISSUE TITLE
nodes should not use secondary CIDR in example vpc custom cni

### ISSUE THREAD

**Issue by csantanapr** [aws-ia/terraform-aws-eks-blueprints#1313]
## Description

In example vpc-cni-custom-networking we create secondary CIDR `10.99.0.0/16` intended to be use only for Pods, while leaving primary ENI of the nodes on the primary CIDR `10.0.0.0/16` of the VPC

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking

I noticed that some nodes where getting assign to the secondary CIDR `10.99.0.0/16`

```
k get nodes                                                                                                           
NAME                                                                  STATUS   ROLES    AGE    VERSION
ip-10-0-47-171.us-west-2.compute.internal   Ready    <none>   144m   v1.24.7-eks-fb459a0
ip-10-99-6-194.us-west-2.compute.internal   Ready    <none>   144m   v1.24.7-eks-fb459a0
```

## Versions

- Module version [Required]:

- Terraform version:
1.3.7

- Provider version(s):

## Reproduction Code [Required]

```
git clone https://github.com/aws-ia/terraform-aws-eks-blueprints
cd examples/vpc-cni-custom-networking
terraform init
terraform apply -auto-approve
```

## Expected behaviour

All nodes using CIDR `10.0.0.0/16`

## Actual behaviour

All nodes using a mix of CIDRs

## Additional context

I think the fix is to only provide the private subnets of CIDR `10.0.0.0/16` to eks module instead of all 6 private subnets

**Comment by bryantbiggs** [comment]
custom networking means the pods use a different IP range than the nodes. So nodes will use the 10.0.0.0/16 range and pods will use the 10.99.0.0/16 range

```
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE   IP            NODE                                       NOMINATED NODE   READINESS GATES
kube-system   coredns-657694c6f4-8s5k6   1/1     Running   0          2m    10.99.135.1   ip-10-0-34-74.us-west-2.compute.internal   <none>           <none>
kube-system   coredns-657694c6f4-ntzcp   1/1     Running   0          2m    10.99.135.0   ip-10-0-34-74.us-west-2.compute.internal   <none>           <none>
```

**Comment by bryantbiggs** [comment]
ah, nvm - I see the issue - we are passing all of the private subnets and not just the specific subnets we intend for nodes to use. I'll open a PR
