### ISSUE TITLE
Deploy an ingress controller to expose the ArgoCD UI public

### ISSUE THREAD

**Issue by krishanshamod** [aws-ia/terraform-aws-eks-blueprints#1320]
I'm using the EKS Blusprints module to deploy the cluster. Currently, I'm struggling with deploying an ingress controller to expose ArgoCD UI to the public. How to archive this?

Here's the Terraform config I use currently for deploying add-ons but in there It uses a load balancer for exposing ArgoCD UI.

```
module "kubernetes_addons" {
  source = "github.com/krishanshamod/terraform-aws-eks-blueprints/modules/kubernetes-addons"

  eks_cluster_id = module.eks_blueprints.eks_cluster_id

  # ArgoCD addon
  enable_argocd         = true
  argocd_manage_add_ons = true

  argocd_applications = {
    addons = local.addon_application
    workloads = local.workload_application 
  }

  argocd_helm_config = {
    set = [
      {
        name  = "server.service.type"
        value = "LoadBalancer"
      }
    ]
  }

  enable_aws_load_balancer_controller  = true
  enable_karpenter                     = false
  enable_amazon_eks_aws_ebs_csi_driver = true
  enable_aws_for_fluentbit             = true
  enable_metrics_server                = true
}
```

**Comment by bullkloud** [comment]
Hello @krishanshamod , I recommend that you do not display the ingress from the helm chart, but rather create a separate service and ingress resource to be able to configure public access.

In the argocd documentation, you can find what you need.

https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode

Now if you need to expose argocd by a path other than root, you must pass these parameters in the argocd addon installation.

`
const argoCDAddOn = new blueprints.addons.ArgoCDAddOn({
                values: {
                    "server": {
                        "extraArgs": [
                            "--rootpath",
                            "/argo-cd"
                        ]
                    }
                }
            });
`
That example is in CDK, but you can easily transcribe it to TF.

Regards.
