### ISSUE TITLE
vpc-cni-custom-networking example node is not using secondary CIDR

### ISSUE THREAD

**Issue by csantanapr** [aws-ia/terraform-aws-eks-blueprints#1323]
## Description

The [vpc-cni-custom-networking](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking) example, one node is not using secondary CIDR `10.99.0.0/16`

Since the example is using ipv4 prefix delegation, the miss-configured node eats up 110 pods from the primary CIDR not the intended secondary CIDR

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions
- Terraform version: `1.3.7`

## Reproduction Code [Required]

```
git clone https://github.com/aws-ia/terraform-aws-eks-blueprints
cd examples/vpc-cni-custom-networking/
terraform init
terraform apply -auto-approve
```

## Expected behaviour

All nodes from the managed groups (ie 2) to be configured with secondary CIDR `10.99.0.0/16` for (secondary ENIs/Pod)

## Actual behaviour

Not all nodes using secondary CIDR, in one run one node using primary CIDR `10.0.0.0/16`

## Additional context

I think the problem is that the ENIConfig manifest files are deployed after the node gets created, and the node is not configured correctly.

**Comment by FernandoMiguel** [comment]
i believe coredns is set to use host network, so it sees the IPs of the node, not from extended subnets

**Comment by csantanapr** [comment]
>i believe coredns is set to use host network, so it sees the IPs of the node, not from extended subnets

coredns is not configured to use host network.

**Comment by csantanapr** [comment]
I'm looking for a way to force the creation the ENIConfig resource before the nodes are created.

**Comment by FernandoMiguel** [comment]
Both awsnode and kubeproxy bind to the host subnet cidr in our clusters and every other pod is in the extended cgnat CIDRs subnets.
I know from experience I can toggle that for karpenter for example
