### ISSUE TITLE
Add a `path` variable option for the Karpenter aws_iam_policy

### ISSUE THREAD

**Issue by nadaj** [aws-ia/terraform-aws-eks-blueprints#1326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I would like to be able to provide a custom path for the resource aws_iam_policy.karpenter. This would enable more secure policies, since the roles being used to deploy the resources might have strict permissions on certain policy paths.

#### Describe the solution you would like

Adding a var.path that would default to "/" if not provided.

#### Describe alternatives you have considered

There are no alternatives.

#### Additional context

n/a

**Comment by nadaj** [comment]
I would be interested in providing a fix for this issue - should be straightforward.

**Comment by bryantbiggs** [comment]
@nadaj  please feel free to open a PR if you have the time, thank you!
