### ISSUE TITLE
The example application in the fargate-serverless example cannot be scheduled because it does not tolerate Fargate taints

### ISSUE THREAD

**Issue by philmcdo** [aws-ia/terraform-aws-eks-blueprints#1328]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v4.20.0

- Terraform version: v1.3.6

- Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.49.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

```
cd terraform-aws-eks-blueprints/examples/fargate-serverless/
terraform init
terraform plan
terraform apply
```

## Expected behaviour
Describing the pods after launching this example fargate cluster should show 3 'app-2048' pods in the Running state with 1/1 ready status.

## Actual behaviour

The 'app-2048' pods are in a Pending state because the pods do not tolerate the 'compute-type: fargate'  taint in the Fargate compute environment:

```

kubectl describe pod app-2048-5fdfb6b559-9cqmn -n app-2048

...
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  37s (x95 over 97m)  default-scheduler  0/5 nodes are available: 5 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate.
```

## Additional context
Adding the toleration for 'compute-type: fargate' would allow the example application to be scheduled

**Comment by bryantbiggs** [comment]
I'm not seeing the same behavior:
```
k get pods -A
NAMESPACE     NAME                                            READY   STATUS    RESTARTS   AGE
app-2048      app-2048-6c759579fc-m7qfw                       1/1     Running   0          78s
app-2048      app-2048-6c759579fc-sbr4n                       1/1     Running   0          78s
app-2048      app-2048-6c759579fc-t9pkh                       1/1     Running   0          78s
kube-system   aws-load-balancer-controller-5bc4478bcd-d7nln   1/1     Running   0          63s
kube-system   aws-load-balancer-controller-5bc4478bcd-nvfvl   1/1     Running   0          63s
kube-system   coredns-555b66958f-8f97r                        1/1     Running   0          3m49s
kube-system   coredns-555b66958f-v7fqn                        1/1     Running   0          3m49s
```

**Comment by bryantbiggs** [comment]
going to close this for now, but please feel free to provide any additional details if you'd like me to troubleshoot further
