### ISSUE TITLE
Error when kubernetes-addons create karpenter and node_handler charts

### ISSUE THREAD

**Issue by dcristobalhMad** [aws-ia/terraform-aws-eks-blueprints#1336]
## Description

Terraform crashes when aws-blueprints creates karpenter and node_handler addons.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
v4.19.0, v4.20.0, v4.21.0
- Terraform version:
1.1.3
- Provider version(s):
├── provider[registry.terraform.io/hashicorp/null]
├── provider[registry.terraform.io/hashicorp/helm] ~> 2.6.0
├── provider[registry.terraform.io/integrations/github] ~> 5.0.0
├── provider[registry.terraform.io/hashicorp/tls]
├── provider[registry.terraform.io/hashicorp/kubernetes] ~> 2.13.0
├── provider[registry.terraform.io/hashicorp/time]
├── provider[registry.terraform.io/gavinbunney/kubectl] ~> 1.14.0
├── provider[registry.terraform.io/fluxcd/flux] ~> 0.19.0
├── provider[registry.terraform.io/hashicorp/aws] ~> 4.30.0

## Reproduction Code [Required]

`
 module "eks-blueprints-kubernetes-addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.21.0"

  eks_cluster_id                      = module.eks-blueprints.eks_cluster_id
  eks_worker_security_group_id        = module.eks-blueprints.worker_node_security_group_id
    # EKS Addons
  enable_amazon_eks_vpc_cni = true
  amazon_eks_vpc_cni_config = {
    most_recent = true
  }
  enable_amazon_eks_coredns = true
  amazon_eks_coredns_config = {
    most_recent = true
  }
  enable_amazon_eks_kube_proxy        = true
  enable_aws_node_termination_handler = true
  enable_karpenter                    = true

  depends_on = [module.eks-blueprints.managed_node_groups]
} 
`

 NO
 YES

Add karpenter and node handler addon to the blueprints addons section, after the terraform breaks it could repeat again terraform apply and it works

## Expected behaviour

All infra should be created

## Actual behaviour

Terraform apply breaks when it is creating node hander and karpenter resources

### Terminal Output Screenshot(s)
`module.eks-blueprints-kubernetes-addons.module.aws_vpc_cni[0].aws_eks_addon.vpc_cni: Creation complete after 1m7s [id=prod-t-rox:vpc-cni]
╷
│ Error: Unauthorized
│ 
│   with module.eks-blueprints-kubernetes-addons.module.karpenter[0].module.helm_addon.module.irsa[0].kubernetes_namespace_v1.irsa[0],
│   on .terraform/modules/eks-blueprints-kubernetes-addons/modules/irsa/main.tf line 5, in resource "kubernetes_namespace_v1" "irsa":
│    5: resource "kubernetes_namespace_v1" "irsa" {
│ 
╵
╷
│ Error: Unauthorized
│ 
│   with module.eks-blueprints-kubernetes-addons.module.aws_node_termination_handler[0].module.helm_addon.module.irsa[0].kubernetes_service_account_v1.irsa[0],
│   on .terraform/modules/eks-blueprints-kubernetes-addons/modules/irsa/main.tf line 30, in resource "kubernetes_service_account_v1" "irsa":
│   30: resource "kubernetes_service_account_v1" "irsa" {
│ 
╵
╷
│ Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
│ 
│   with module.eks-blueprints-kubernetes-addons.module.aws_coredns[0].module.cluster_proportional_autoscaler[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks-blueprints-kubernetes-addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {`

**Comment by bryantbiggs** [comment]
do not use a `depends_on` across modules as this is known to cause issues and Terraform advises against this practice
