### ISSUE TITLE
trying to set argocd ingress

### ISSUE THREAD

**Issue by nahum-landa** [aws-ia/terraform-aws-eks-blueprints#1337]
settings 
argocd_helm_config
```
{
name  = "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/target-type"
value = "ip"
type  = "string"
},
{
name  = "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/scheme"
value = "alb"
type  = "string"
},
```
translates to:
```

 annotations:
      alb: map[ingress:map[kubernetes:map[io/scheme:alb io/target-type:ip]]]

```

instead of 
```

 annotations:
     alb.ingress.kubernetes.io/target-type: ip
     alb.ingress.kubernetes.io/scheme: alb
```

what to do?

**Comment by pedrodparkes** [comment]
the problem is still here:
`set = [
      {
        name = "server.ingress.annotations.external-dns.alpha.kubernetes.io/hostname"
        value = "argocd.hello.net"
        type  = "string"
      },`
      
results in a map, instead of string value.

**Comment by asanka-x** [comment]
I am facing the same issue. Did anyone found any workaround or fix for this?
