### ISSUE TITLE
kuberhealthy add on module

### ISSUE THREAD

**Issue by karpra** [aws-ia/terraform-aws-eks-blueprints#1338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Installing/Configuring Kuberhealthy on EKS Cluster via Terraform AWS Blueprints.

#### Describe the solution you would like

Creating an add on module for kuberhealthy

#### Describe alternatives you have considered

Searches for addon modules for kuberhealthy does not exist & there is no mention of it in Issues.

**Comment by bryantbiggs** [comment]
Thank you for the issue @karpra  - this looks like its just simply wrapping the kuberhealthy helm chart, any reason to not just use the `helm_release` resource directly to deploy?
