### ISSUE TITLE
feat: Add Trino kubernetes-addon module

### ISSUE THREAD

**Issue by danpilch** [aws-ia/terraform-aws-eks-blueprints#1344]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Create an addon module for [Trino The Distributed SQL query engine for big data](https://trino.io/)

#### Describe the solution you would like

Trino has a community helm chart, seen [here](https://github.com/trinodb/charts). I'd like to implement a wrapper module to
install with EKS blueprints.

#### Describe alternatives you have considered

None.

**Comment by bryantbiggs** [comment]
Thank you for the issue @danpilch - this looks like its just simply wrapping the Trino helm chart, any reason to not just use the `helm_release` resource directly to deploy?
