### ISSUE TITLE
Changes on managed node groups forces vpc-cni addon replacement, causing new node creation failure (aws-node role missing)

### ISSUE THREAD

**Issue by caimez** [aws-ia/terraform-aws-eks-blueprints#1345]
Hello,

I have an issue where each time I want to upgrade my managed node groups (instance type for example), it creates changes on my eks module, which in turn forces the replacement of my addons.

Since the addons are destroyed before the new managed nodes are created, my new managed nodes are unable to initialize IPAMD, because the iam role for the vpc cni module is missing, which makes the new nodes unable to initialize the network layer correctly.

```  # module.eks_blueprints_kubernetes_addons.module.aws_vpc_cni[0].aws_eks_addon.vpc_cni must be replaced
-/+ resource "aws_eks_addon" "vpc_cni" {
      ~ addon_version            = "v1.11.4-eksbuild.1" -> (known after apply)
      ~ arn                      = "XXXXX" -> (known after apply)
      ~ cluster_name             = "XXXXX" -> (known after apply) **# forces replacement**
      + configuration_values     = (known after apply)
      ~ created_at               = "2023-01-19T14:53:09Z" -> (known after apply)
      ~ id                       = "XXXXX" -> (known after apply)
      ~ modified_at              = "2023-01-20T10:36:36Z" -> (known after apply)
      ~ service_account_role_arn = "XXXXX" -> (known after apply)
        tags                     = {
            "environment" = "dev"
            "provider"    = "terraform"
        }
        # (4 unchanged attributes hidden)
    }
```

```  # module.eks_blueprints_kubernetes_addons.module.aws_vpc_cni[0].module.irsa_addon[0].aws_iam_role.irsa[0] must be replaced
-/+ resource "aws_iam_role" "irsa" {
      ~ arn                   = "XXXXX" -> (known after apply)
      ...
      ~ name                  = "dev-eks-aws-node-irsa" -> (known after apply) **# forces replacement**
      ...
        }
    }
```

Therefore, I get the following logs in the /var/log/aws-routed-eni/ipamd.log file on the new nodes:

```{"level":"error","ts":"2023-01-20T10:54:46.494Z","caller":"ipamd/ipamd.go:462","msg":"Failed to call ec2:DescribeNetworkInterfaces for [eni-XXXXX]: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: c1bc8a83-1ba6-486e-8bfa-db6d2145369a"}
{"level":"error","ts":"2023-01-20T10:54:46.598Z","caller":"ipamd/ipamd.go:462","msg":"Failed to call ec2:DescribeNetworkInterfaces for [eni-XXXXX]: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: dd2c61e7-1ddc-4eb4-9434-72c12030c252"}
{"level":"error","ts":"2023-01-20T10:54:46.708Z","caller":"aws-k8s-agent/main.go:28","msg":"Initialization failure: ipamd init: failed to retrieve attached ENIs info: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: dd2c61e7-1ddc-4eb4-9434-72c12030c252"}
```

Am I missing something ? Should the eks module and addon modules be updated seperately ?

For now the only solution I have found is to destroy and recreate my eks cluster completeley which is ok for now cause I am in dev, but when I get to prod cluster, this will be unacceptable.

Please help me figure this out, I followed the examples and my terraform code is no different from the examples.

Thanks!

**Comment by bryantbiggs** [comment]
Please look at what Terraform is telling you in terms of what is prompting the changes:

```
~ cluster_name             = "XXXXX" -> (known after apply) **# forces replacement**
```

It appears your cluster name has changed which is going to be a replacement

**Comment by caimez** [comment]
@bryantbiggs except that I don't change my cluster name, the cluster name I think is calculated from the cluster id that is the input of the kubernetes addon module. Hereafter is the code for how I supply the cluster id (which I supply as cluster name instead of an output from the eks blueprint module to the addon module):

````
locals {
  cluster_name      = join("-", [var.project_name, var.environment, "eks"])
}

module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.20.0"

  eks_cluster_id       = local.cluster_name
  ...
}
```

**Comment by bryantbiggs** [comment]
you will need to provide a full reproduction in order to help troubleshoot

**Comment by caimez** [comment]
sure how can I do that ?

just to show what I see, the cluster_name in the kubernetes_addon module is equal to:

![image](https://user-images.githubusercontent.com/8994956/213780643-d2eb0388-2765-4bc6-91ef-124dc6ace1d7.png)

the var addon_context is equal to:

![image](https://user-images.githubusercontent.com/8994956/213780791-62a1704d-f742-4e75-bad0-5589cfe92fe4.png)

so the cluster_name for the addon is taken from the cluster_id from the aws_eks_cluster data source eks_cluster which depends on the downstream data plane (the nodes):

![image](https://user-images.githubusercontent.com/8994956/213781533-33b8d61e-036b-4b64-ab19-e7f614797007.png)

![image](https://user-images.githubusercontent.com/8994956/213781576-9153e5ad-3415-466c-bd01-4aa8b5559ceb.png)

so my understanding is that the addons are dependent on the worker nodes, so an update on the nodes forces the replacement of the addons am I correct ?

**Comment by bryantbiggs** [comment]
A reproduction would be the code YOU have defined to create the cluster/addons. Here is an example https://github.com/bryantbiggs/how-to-create-reproduction

Note - it does not need to be in its own repository, you can simply past it into a code block here in the thread

**Comment by caimez** [comment]
well that's embarassing, I just found this at the bottom of my addons module declaration:

```
module "eks_blueprints_kubernetes_addons" {
  ...
  depends_on = [module.eks.managed_node_groups]
}
```

found it when pasting the code, I have no idea why I put that at the bottom... my mistake

well thanks for the help @bryantbiggs !
