### ISSUE TITLE
Add Kube State Metrics addon

### ISSUE THREAD

**Issue by normalfaults** [aws-ia/terraform-aws-eks-blueprints#1375]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Observability examples require kube state metrics addon for base level k8s metrics

#### Describe the solution you would like

adding the addon for helm and argocd deployment

#### Describe alternatives you have considered

Kube State Metrics is the defacto open source addon which generates k8s metadata metrics

**Comment by todd-dsm** [comment]
This looks completed but I can find the docs. What's the current status of this request?
