### ISSUE TITLE
External-DNS with cross account access to domain hosted in root account

### ISSUE THREAD

**Issue by ghost** [aws-ia/terraform-aws-eks-blueprints#1382]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I want to run my cluster in a member account, and use external-DNS. My domain is hosted in a root account. I think I saw in a PR that you enabled to provide a custom service account with cross account access? I have created this SA, but where in your gitops/argocd example would I put this variable/value?

#### Provide a link to the example/module related to the question

(https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/gitops/argocd)

**Comment by FernandoMiguel** [comment]
yu create a provider alias, and use that in the module for external-dns

**Comment by FernandoMiguel** [comment]
We do cross account.. Or rather we assume roles for the accounts we need, from a central role.
It's the easiest.
You deploy a controller per role/account you need..

I don't really see an easy way to do it from a single account, cause you will never have privileges to change another account, at least not without assuming a role there.

**Comment by allamand** [comment]
Hi @upmyjob, you can show in this example https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/upgrade/blue-green-route53/modules/eks_cluster/main.tf#L450-L455 how to provide specivif values for the external-dns addon deploy with ArgoCD. You canthen specify your own ServiceAccountName cf https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/values.yaml#L79 that will be forwarded to the external-dns helm chart values : https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/templates/external-dns.yaml#L22-L23. 

It this what you were looking at ?

**Comment by upmyjob** [comment]
@allamand yes it is. After looking through the manifests yesterday afternoon, I arrived at the helm chart values as the probably solution. Thank you for confirming!

**Comment by upmyjob** [comment]
Before this issue gets closed, I have one other question. I have been assuming that since my primary domain is in the root account, I have to use a sub-domain if running hosts in a member account, because ACM won't create a cert in the member account for a domain that belongs to the root account. Is this a true limitation? If not I will pursue that also.
