### ISSUE TITLE
Make the creation of an IAM Policy in external-dns addon optional

### ISSUE THREAD

**Issue by Azrael808** [aws-ia/terraform-aws-eks-blueprints#1385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

A similar issue to the one I describe in #1379, however this time it's with the external-dns addon module. The Terraform module assumes that an IAM Policy should be created, but this isn't possible in the environment I'm attempting to deploy into.

Ideally, it should be possible to disable the creation of the IAM policy and simply pass through one created by another stack/team/etc.

#### Describe the solution you would like

I see that the external DNS module already allows for additional IAM policies, so I think the solution would look be as follows:

1. Add a boolean that disables the creation of the IAM Policy by the module
2. Change the logic that constructs the `irsa_config.irsa_iam_policies` attribute that's passed to the `helm_addon` module.

I will be making the changes in my forked repo to progress my own work, so I'll happily raise a PR once that's complete.

**Comment by FernandoMiguel** [comment]
I found the best way is to use a provider alias
```hcl
provider "aws" {
  alias = "route53_ANOTHER_ACCOUNT_NAME_HERE_assume_role"

  region = var.aws_region
  assume_role {
    ## if no role provided, use the account running
    role_arn = var.route53_ANOTHER_ACCOUNT_NAME_HERE_assume_role_arn != null ? var.route53_ANOTHER_ACCOUNT_NAME_HERE_assume_role_arn : var.assume_role_arn
  }
  default_tags {
    tags = local.tags
  }
}

module "eks_blueprints_kubernetes_addons_external_dns_ANOTHER_ACCOUNT_NAME_HERE" {
  count = local.external-dns["enabled"] && var.ANOTHER_ACCOUNT_NAME_HERE != null && var.route53_ANOTHER_ACCOUNT_NAME_HERE_assume_role_arn != null ? 1 : 0

  providers = {
    aws = aws.route53_ANOTHER_ACCOUNT_NAME_HERE_assume_role ## should be pre-existing `ANOTHER_ACCOUNT_NAME_HERE` AWS Account Route53 Zone
  }

  source = "git::ssh://git@github.com/aws-ia/terraform-aws-eks-blueprints.git//modules/kubernetes-addons/external-dns?ref=v4.21.0"
[...]
}

this way the module will create the IRSA role in the target account and should have all the privs it needs

**Comment by Azrael808** [comment]
@FernandoMiguel thanks, but I'm unsure whether this will help in my use case. The issue is that the module tries to create an IAM Policy in the same account I'm deploying the EKS cluster into - however, I do not have the necessary privileges for this to occur.

This is by design as the organisation requires any new Policies/Permissions go through an approval process before they can be implemented (by the team responsible for managing them). So, currently, I have to raise a ticket requesting a new IAM Policy, explaining the requirement and attaching a JSON document for the Security team to approve and create for me. I just get an ARN I can then use with my Terraform.

The external-dns module actually allows you to pass ARNs of _additional_ policies to attach to the IRSA role, so I can use that, but I need a way to disable the module from trying to create it's own.

I hope that all makes sense!

**Comment by FernandoMiguel** [comment]
even if you have an ARN from another account, your current role wont be able to use that , right?
you would need to allow the service account to jump accounts to assume that role, and that role to trust your SA role, either via iAM or OIDC.

**Comment by Azrael808** [comment]
@FernandoMiguel the Policy ARN wouldn't be from another AWS account.

I'm attempting to provision EKS into an AWS account for which I don't have privileges to create IAM Policies - so the execution of the external-dns module throws an exception (as did the aws-load-balancer-controller module, see #1379).

Once I have the Policy created by the security team (in the same AWS account), I should be able to pass that to the module (see PR #1381 for how I achieved this with the load balancer controller).

**Comment by dbaltor** [comment]
I recommend the folks facing the same constraint to have a look at [lablabs terraform-aws-eks-external-dns ](https://github.com/lablabs/terraform-aws-eks-external-dns/blob/master/variables.tf#L100)
