### ISSUE TITLE
Trouble getting the External-DNS example working: Skipping record because no host zone matching record DNS Name was detected.

### ISSUE THREAD

**Issue by beamsies** [aws-ia/terraform-aws-eks-blueprints#1386]
- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Okay so I'm experimenting with the ```terraform-aws-eks-blueprints``` for the first time. I was successful in deploying the example ```eks-cluster-with-external-dns``` found [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-external-dns). However, I cannot seem to get my domain networking to hit the ingress. 

I followed the instructions outlined in the example linked above by setting up an ```eks_cluster_domain``` and an ```acm_certificate_domain``` as stated [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-external-dns#step-3-replace-placeholder-values-in-terraformtfvars). 

What I did was add the fully qualified domain name to the route53 hosted zone, then I used the wildcard domain for subdomains in the certificate manager. I'm not sure if this is the correct way to do this for this example. 

I then added the domain to the ```variables.tf``` file. 

Next, I ran terraform apply in the following order and manner:
- ```terraform apply -target="module.vpc"```
- ```terraform apply -target="module.eks_blueprints"```
- ```terraform apply```

The above terraform scripts succeeded then I followed the rest of the instructions to get the host name from the `guestbook-ui.<eks_cluster_domain>` and navigate to it. It does not load the page and it also seems that it is not making its way into the application load balancer or even the network load balancer. I checked the logs for the network load balancer and didn't see any errors or logs for my own attempts at loading the guest book ui page.

One thing I did notice is when I ran ```k logs <external-dns-pod-name> -n external-dns``` I saw some interesting logs there that told me that the external-dns records were not being created: 
`
time="2023-01-30T04:36:29Z" level=debug msg="Skipping record {\n  Action: \"CREATE\",\n  ResourceRecordSet: {\n    Name: \"cname-2048.<eks_cluster_domain>\",\n    ResourceRecords: [{\n        Value: \"\\\"heritage=external-dns,external-dns/owner=external-dns,external-dns/resource=ingress/team-riker/ingress-2048\\\"\"\n      }],\n    SetIdentifier: \"external-dns\",\n    TTL: 300,\n    Type: \"TXT\",\n    Weight: 100\n  }\n} because no hosted zone matching record DNS Name was detected"
`

So now I'm confused as to what I did wrong to produce these results. If I passed in the correct `eks_cluster_domain` and set it up in route53 and created the certificate (in the correct region) I assumed it would all work. I must have missed a step or did something incorrect with the domain/route53. The domain is on google domains and I double-checked the correct name server values were applied there to send the network request to AWS nameservers. 

Any help would be greatly appreciated. 

#### Provide a link to the example/module related to the question

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-external-dns

#### Additional context

view of route53 with cert CNAME entry:
![image](https://user-images.githubusercontent.com/6827052/215400272-5bd1cb1d-f75b-46cd-aaf2-064e5ef50a1e.png)

view of ACM as valid:
![image](https://user-images.githubusercontent.com/6827052/215400696-82f84d36-d08d-4948-8a8f-b335532b938d.png)

**Comment by JoeNorth** [comment]
Thank you for pointing this out, @beamsies. I've tested this in my environment and confirmed the issue was introduced with #1035. The root cause being that `external_dns_helm_config` references `var.eks_cluster_domain` for `zoneIdFilter`. The `zoneIdFilter` value does not take the domain name but instead takes the zone ID of the public hosted zone. The easiest change to get this working is to add an `aws_route53_zone` data resource as follows:

```
data "aws_route53_zone" "external_dns_domain" {
  name = var.eks_cluster_domain
}
```

From here you can then edit the `external_dns_helm_config` to the following:

```
external_dns_helm_config = {
  values = [templatefile("${path.module}/external_dns-values.yaml", {
    txtOwnerId   = local.name
    zoneIdFilter = data.aws_route53_zone.external_dns_domain.zone_id
  })]
}
```

I'll be bringing this to the attention of the EKS Blueprints team to get this fix into a PR, tested, and merged.

**Comment by JoeNorth** [comment]
As a side note, you can alternatively edit the file `external_dns-values.yaml` to use the domainFilters parameter instead of zoneIdFilter as seen below:

```yaml
txtOwnerId: ${txtOwnerId}
zoneIdFilters:
  - ${zoneIdFilter}
policy: 'sync'
aws:
  zoneType: 'public'
  zonesCacheDuration: '1h'
logLevel: 'debug'
```

The `external_dns_helm_config` can then be edited to also use this parameter:

```tf
external_dns_helm_config = {
  values = [templatefile("${path.module}/external_dns-values.yaml", {
    txtOwnerId   = local.name
    domainFilter = var.eks_cluster_domain
  })]
}
```

Either solution will get to the same end result.

**Comment by beamsies** [comment]
@JoeNorth Thanks a ton for digging into this and figuring out the problem! I'll try the workaround.
