### ISSUE TITLE
AwsLoadBalancerController: expect exactly one securityGroup tagged with kubernetes.io/cluster/<my-cluster>

### ISSUE THREAD

**Issue by denniskniep** [aws-ia/terraform-aws-eks-blueprints#1390]
## Description
There is a automatically created Security Group by EKS: `eks-cluster-sg-<my-cluster>-<uniqueID>`
see https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

This Security Group is automatically tagged with
``
kubernetes.io/cluster/<my-cluster>:  owned
``

Furthermore there is a Security Group created ``my-cluster>-node-<uniqueId>``
which is also tagged with
 ``
kubernetes.io/cluster/<my-cluster>:  owned
``

Both are added to the VPC-CNI ENIConfig in the Custom Networking example:
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/8421a3b9600b734e600039ec2e8cddf6d03afe83/examples/vpc-cni-custom-networking/main.tf#L121-L142

That lead to errors if one is installing the Addon AwsLoadBalancerController

Error in pod ``aws-load-balancer-controller``
```
expect exactly one securityGroup tagged with kubernetes.io/cluster/<my-cluster>
```

Does it make sense to remove the securitygroup ``module.eks.node_security_group_id`` ?
Aws docs are also adding only the cluster security group to the ENIConfig:
https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html#custom-networking-configure-kubernetes

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 4.22.0

## Reproduction Code [Required]
Execute https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking

plus

`````
module "eks_blueprints_kubernetes_addons" {
  source = "../../modules/kubernetes-addons"
  enable_aws_load_balancer_controller = true
}
`````

I am happy to provide that PR if it will be accepted

**Comment by denniskniep** [comment]
not stale

**Comment by bryantbiggs** [comment]
you can see more about this error here and how to resolve it https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#i-received-an-error-expect-exactly-one-securitygroup-tagged-with-kubernetesioclustername-
