### ISSUE TITLE
aws_caller_identity returns inconsistent value when using assumed-role credentials

### ISSUE THREAD

**Issue by devopsrick** [aws-ia/terraform-aws-eks-blueprints#1393]
## Description

The aws_caller_identiy used in locals.context is returning a temporary assumed-role arn which changes every time a workspace runs in Terraform when using assumed-role credentials.  The aws_iam_session_context resource is designed to be able to return the actual role in this situation.  It would be great if the module allowed for this.

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/locals.tf#L8

This is resulting in the KMS key policy being updated every run with a new assumed-role arn, essentially this old provider bug which the aws_iam_session_context resource addresses:

https://github.com/hashicorp/terraform-provider-aws/issues/28381#issuecomment-1355593411

**Comment by devopsrick** [comment]
I am pretty sure this is all that is needed and it should work for workspaces with and without assumed-role auth.

```
diff --git a/data.tf b/data.tf
index ef7a17bc..e6b7fa33 100644
--- a/data.tf
+++ b/data.tf
@@ -2,6 +2,10 @@ data "aws_partition" "current" {}
 data "aws_caller_identity" "current" {}
 data "aws_region" "current" {}
 
+data "aws_iam_session_context" "current" {
+  arn = data.aws_caller_identity.current.arn
+}
+
 data "aws_eks_cluster" "cluster" {
   count = var.create_eks ? 1 : 0
   name  = module.aws_eks.cluster_id
diff --git a/locals.tf b/locals.tf
index 33326472..2a6745a4 100644
--- a/locals.tf
+++ b/locals.tf
@@ -5,7 +5,7 @@ locals {
     aws_region_name = data.aws_region.current.name
     # aws_caller_identity
     aws_caller_identity_account_id = data.aws_caller_identity.current.account_id
-    aws_caller_identity_arn        = data.aws_caller_identity.current.arn
+    aws_caller_identity_arn        = data.aws_iam_session_context.current.issuer_arn
     # aws_partition
     aws_partition_id         = data.aws_partition.current.id
     aws_partition_dns_suffix = data.aws_partition.current.dns_suffix
```

**Comment by bryantbiggs** [comment]
that is correct
