### ISSUE TITLE
Publish modules to terraform registry

### ISSUE THREAD

**Issue by rothgar** [aws-ia/terraform-aws-eks-blueprints#1394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I would like to use blueprints using traditional module import syntax like

```
module "eks-blueprints" {
  source  = "terraform-aws-modules/eks/blueprints"
  version = "19.6.0"
}
```

Today, I have to use git path source which is not as intuitive and harder to version. This option also has multiple options which are confusing to use and hard to get right.

```
module "eks-blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules//kubernetes-addons?ref=v4.19.0"
}
```
Alternatively, I could use `git::https://`, `git@github`, or `ssh://` syntax for the source which have different options and configuration (e.g. authentication) that add confusion. Because modules are in subfolders I also have to make sure I have `//` for folders and `?ref=` needs to come at the end of the string. These strings become difficult to parse and update.

All of the examples are not portable because they use path based source and require me to locally clone the repo to use.
```
module "eks-blueprints" {
  source = "../.."
}
```

#### Describe the solution you would like

The modules should be published to a terraform module registry so they can be more easily discovered, consumed, and versioned.

#### Describe alternatives you have considered

All of the alternative options are described above

#### Additional context

Please

**Comment by FernandoMiguel** [comment]
my understanding is that is going to happen with v5
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/9a440774a7b95d98a5e351af31486b0dd5038a79/DIRECTION_v5.md

**Comment by atheiman** [comment]
thanks for linking that @FernandoMiguel - @bryantbiggs it would be great to see an upgrade path from terraform-aws-eks-blueprints to terraform-aws-eks. Some instructions for `terraform import` commands to migrate a cluster created w/ this blueprints project over to terraform-aws-eks would be nice.
