### ISSUE TITLE
Teams: Why application team role dont have write permission in their own namespace

### ISSUE THREAD

**Issue by mk2134226** [aws-ia/terraform-aws-eks-blueprints#1397]
I am creating teams and when i use the team role
That role only has read only permissions. I was under the impression that team should be bale to do anything within their own namespace

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/aws-eks-teams/main.tf#L92

Now i have to use platform team which is cluster admin

**Comment by allamand** [comment]
Hi @mk2134226, the idea with the blueprint is that we should have the platform team, with write access to the cluster, and application teams, that have readonly access to the cluster, but are able to have write access to their namespaces through GitOps.

The Idea there is that the source of truth for the cluster should be store in several git repository (as we can imagine every teams synchronize their git to their namespace).

You can find a step/by/step guide in the following workshop : https://catalog.workshops.aws/eks-blueprints-terraform/en-US/030-provision-eks-cluster/6-bootstrap-argocd
