### ISSUE TITLE
How do you deal with dependencies between add-ons

### ISSUE THREAD

**Issue by Tommyf** [aws-ia/terraform-aws-eks-blueprints#1412]
- [Y] ✋ I have searched the open/closed issues and my issue is not listed.

I'm having some trouble working out how to manage dependencies between add-ons created by `terraform-aws-eks-blueprints//modules/kubernetes-addons`.

### Example Scenario
Starting out with the Karpenter example [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/karpenter), I built a cluster and added a few more add-ons using the module.

The Fargate profiles are set up such that only Karpenter and coredns run on Fargate nodes. All other workloads are to start on nodes that are provisioned by Karpenter.
When I initially built this test cluster, I was adding components one at a time and all was well.

### Problem
After tearing the cluster down (will get into problems with that further down) to rebuild from scratch, I re-provisioned everything in a fresh environment. In doing this, I ran into dependency problems.

All of the Kubernetes Addons would appear to be created in parrallel. By default, Terraform will only use 10 concurrent processes. The effect of this being that some dependency add-ons may not be created before some dependant add-ons.

In my case, this presented as Karpenter not being provisioned before AWS Load Balancer Controller and a few others. This resulted in no nodes becoming available for these other add-ons, which made the installation of them time-out.

On a re-run of `terraform apply`, Karpenter got provisioned by one of those threads and then every add-on that now had `pending` pods burst into life.

This is not a problem unique to Karpenter, although it's one of the bigger global dependencies on the cluster as there are no worker nodes until it comes up.

### Deprovisioning
Although the provisioning problem can be fixed when deploying by running multiple `terraform apply` until everything is reconciled, (As was mentioned in the 'ordering of dependencies' paragraph [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/docs/v5-direction/DIRECTION_v5.md#what-has-not)) it's not so pretty when running `terraform destroy`.

In this case, even running a targeted destroy with `terraform destroy --target module.eks_blueprints_kubernetes_addons` you still get dependency problems such as:

- Load Balancers for Nginx Ingress do not get deleted (as the AWS Load Balancer Controller gets removed in parallel so there is nothing there to delete the LB). This blocks deletion of the add-on. No amount of retrying can unblock this. You need to either redeploy the AWS Load Balancer Controller or just manually delete the AWS resources.
- Karpenter managed nodes don't get destroyed, as the karpenter controller pods get removed straight away.
- ArgoCD applications do not get deleted as the Argo CD pods get removed straight away

These were just some easy to identify dependencies, but I am sure there are more.

### Solutions
There are a few solutions I have come up with so far, but none are what I would consider elegant or robust.

#### Creating
- Target individual add-ons within the module itself. e.g.:
  - `terraform apply --target module.eks_blueprints_kubernetes_addons.module.karpenter`
  - `terraform apply --target module.eks_blueprints_kubernetes_addons.module.aws_load_balancer_controller`
  - `terraform apply` (To apply all remaining add-ons)
- Re-run `terraform apply` until it completes.
#### Deleteing
- Target individual add-ons within the module itself. You need to do this explicitly for all modules when destroying as you cannot say 'destroy all but karpenter' for example.
  - `terraform destroy --target module.eks_blueprints_kubernetes_addons.module.x`
  - `terraform destroy --target module.eks_blueprints_kubernetes_addons.module.y`
  - `terraform destroy --target module.eks_blueprints_kubernetes_addons.module.z`
  - `terraform destroy --target module.eks_blueprints_kubernetes_addons.module.argocd`
    - Even this does not work well if there are apps installed. They do not get deleted as the argocd pods are killed
  - `terraform destroy --target module.eks_blueprints_kubernetes_addons.module.ingress-nginx`
  - `terraform destroy --target module.eks_blueprints_kubernetes_addons.module.aws_load_balancer_controller`
  - `terraform destroy --target module.eks_blueprints_kubernetes_addons.module.karpenter`
  - `terraform destroy`
- Update code, disabling individual components in order and applying changes between

Neither of the above messages seem ideal:

 - According to the Terraform docs, "Targeting individual resources can be useful for troubleshooting errors, but should not be part of your normal workflow."
 - Manually updating code in multiple stages to deploy is not maintainable or easily automatable.

### Alternative Solutions
I did try creating multiple `terraform-aws-eks-blueprints//modules/kubernetes-addons` modules for the different dependency stages. This fell flat on its face when I tried using `depends_on` between the modules. Adding one dependent module made the plan take over 30s to complete. Two dependent modules resulted in the plan timing out somewhere in the region of 2000 seconds.

I have started trying to implement individual addons from the module (i.e. using `terraform-aws-eks-blueprints//modules/kubernetes-addons/karpenter`) so that I can declare dependencies between them. I am finding that I need to re-implement some of the `terraform-aws-eks-blueprints` code to get that working, such as the `local.addon_context`, so I am not sure if this is a good direction to go or not.

If I do go down some path of declaring each module separately, with explicitly defined dependencies, then I start wondering what EKS Blueprint code I am actually still using :) I am thinking that the upcoming [terraform-aws-eks-addon](https://github.com/aws-ia/terraform-aws-eks-addon) may be what I am looking for based on what I saw in the comments on [this commit](https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/4467d8e182255bbc5cbf2a9dfd4e456c94e25bdb).

Am I doing something fundamentally wrong here or have I landed on one of the "What does not work" items from the [V5 Directions Document](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/docs/v5-direction/DIRECTION_v5.md)

**Comment by Tommyf** [comment]
With my nice fresh 'morning head', I just found issue https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1198 that details the first of my '**Alternative Solutions**' above...

So from this, I see that it's an accepted approach for splitting up add-ons into related groupings. This can help with using `--target` as I can target core(e.g. Karpenter), then infra(e.g. AWS Load Balancer Controller), then apps(everything else).

Doing this would really simplify the destroy process as you would target these groupings instead of individual add-ons as mentioned above.

However, it would be nice if there was a way to have these groupings depend on each other, as it's still not ideal to need to use `--target` to provision and de-provision.

I tried this with using `depends_on` as I mentioned above, but this seems to have severe performance impact. I have not yet done a deep dive on how this functionality works, but I guess the DAG gets unfeasibly large with more than 1 level of dependencies. I have seen a fair bit of commentary suggesting that `depends_on` is a last resort and should generally not be used unless you are very careful.

Alternatively, I could define each module separately as @FernandoMiguel mentioned he does in https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1198#issuecomment-1321922940. This is the idea I was working towards in my second of my '**Alternative Solutions**' above.

It seems like I may be stumbling on the accepted way to do manage this...

**Comment by bryantbiggs** [comment]
Thank you for the issue! Dependency between addons when deployed with Terraform is going to be challenging. While we recognize that a lot of customers use Terraform and use it to deploy applications onto their clusters, the recommended approach would be to use a GitOps based implementation instead. With a gitops controller on the cluster, each tick of the reconciliation loop would keep trying to advance the deployment of resources, allowing dependencies to resolve themselves. You could achieve a similar cycle by re-applying Terraform several times until all applications are deployed but this is less than ideal. If you are facing dependency conflicts amongst addons when deploying/updating, I would encourage you to look into the GitOps based approach instead
