### ISSUE TITLE
kyverno-policies helm requires kyverno to be installed

### ISSUE THREAD

**Issue by andrewhibbert** [aws-ia/terraform-aws-eks-blueprints#1418]
## Description

Get the following error when installing these together:

```
│ ensure CRDs are installed first, resource mapping not found for name: "disallow-host-namespaces" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "disallow-host-path" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "disallow-host-ports" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "disallow-host-process" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "disallow-privileged-containers" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "disallow-proc-mount" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "disallow-selinux" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "restrict-apparmor-profiles" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "restrict-seccomp" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first, resource mapping not found for name: "restrict-sysctls" namespace: "" from "": no matches for kind "ClusterPolicy" in version "kyverno.io/v1"
│ ensure CRDs are installed first]
│
│   with module.kyverno.module.kyverno_addon.module.kyverno_policies_helm_addon[0].helm_release.addon[0],
│   on .terraform/modules/kyverno.kyverno_addon/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v4.21.0

- Terraform version: v1.1.9

- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v4.13.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0

## Reproduction Code [Required]

Set both `enable_kyverno_policies` and `enable_kyverno` to true

## Expected behaviour

Installs main kyverno helm chart first

## Actual behaviour

Receive error

**Comment by bryantbiggs** [comment]
thank you for the issue - as we move forward with the project, we will not be continuing to support this addon within the project. if you wish to use Kyverno you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
