### ISSUE TITLE
Error thrown when using wildcards in iam role trust policy with service account creation

### ISSUE THREAD

**Issue by nitrocode** [aws-ia/terraform-aws-eks-blueprints#1419]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 4.23.0

- Terraform version: 1.3.7

- Provider version(s): aws

## Reproduction Code [Required]

```hcl
module "datadog" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/irsa?ref=v4.23.0"

  create_kubernetes_namespace         = true
  create_kubernetes_service_account   = true
  create_service_account_secret_token = true
  kubernetes_namespace                = "datadog"
  kubernetes_service_account          = "datadog*"
  eks_cluster_id                      = module.eks.cluster_id
  eks_oidc_provider_arn               = module.eks.oidc_provider_arn
}
```

## Expected behaviour

Create datadog service account called `datadog` and an IAM role with `datadog*` trusted policy permissions without throwing an error.

## Problem

Here is the full problem. I want to manage my kubernetes namespace and IAM role in terraform. I want the datadog chart to reuse my service account for both the cluster-agent and the dd agent but it cannot do this without also removing rbac. Locally i have a kustomize chart that fixes the issue, allowing me to keep rbac and reuse an existing service account while I wait for a pr to be created (todo) and merged upstream.

Before Kustomizing the chart for my needs, in order to allow what I'd like to do, I will add datadog's `serviceAccountAnnotation` on the datadog helm chart (for both clusterAgent and agents) to allow it to create service account and annotate it with a single IAM role. This means I would set `create_kubernetes_service_account = false` to avoid the error below.

However, the service account that it creates is called `datadog` and `datadog-cluster-agent` and the IAM role created by this module cannot use wildcards to match on all `datadog*` without triggering an error. This is why I need to add `datadog*` which triggers the below error.

## Actual behaviour

This error is returned

```hcl
│ Error: metadata.0.name a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
│
│   with module.eks.module.datadog.kubernetes_service_account_v1.irsa[0],
│   on .terraform/modules/eks.datadog/modules/irsa/main.tf line 35, in resource "kubernetes_service_account_v1" "irsa":
│   35:     name        = var.kubernetes_service_account
```

### Terminal Output Screenshot(s)

N/A

## Additional context

- Previous PR https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/244 that added the following

    https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/2ad6bfac663d799aea5dd4e1db9d1eff29ed74c9/modules/irsa/main.tf#L45

**Comment by csantanapr** [comment]
Hi @nitrocode said you want the helm chart create the service account with annotation 
> I want the datadog chart to reuse my service account for both the cluster-agent and the dd agent

you can avoid the error by skipping the creation of the service account in irsa since your already doing it in helm, specify false for this parameter 

create_kubernetes_service_account = false

**Comment by csantanapr** [comment]
I think you will hit another problem with the role name even skipping create sa, the role name will end up with “-*”
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/irsa/main.tf#L52

**Comment by nitrocode** [comment]
Yes this is true. However, I'm trying to get the upstream datadog helm chart to use the service account that I created in terraform. It doesn't support it yet but i can use kustomize to modify the chart locally before an upstream pr is created (todo) and merged to fix the chart.

This was an issue I saw with service agent wildcards && service account creation. It seems like a bug in this module since at one time, see linked pr, it did support wildcards im iam role service accounts without throwing an error.

**Comment by bryantbiggs** [comment]
thank you for the issue - as we move forward with the project, we will not be continuing to support this addon within the project. if you wish to use Datadog you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
