### ISSUE TITLE
Add example for ArgoCD multi-cluster as hub-spoke

### ISSUE THREAD

**Issue by csantanapr** [aws-ia/terraform-aws-eks-blueprints#1424]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Add an example that shows how to configure ArgoCD in multi-cluster setup, having single instance of ArgoCD in a central/hub cluster and spoke clusters with no ArgoCD Instance, addons on the spoke cluster are deployed from central ArgoCD Instance.

#### Describe the solution you would like

A simple example that contains:
- Configure ArgoCD with IRSA 
- Auto-register the spoke clusters into ArgoCD
- template for spoke cluster, can be use to create multiple spoke cluster with same configuration

**Comment by malikdraz** [comment]
There is surely need for multi-cluster management with single ArgoCD instance example (GitOps way of add-ons) across the clusters. This will be interesting example, and POV to see how it will be deployed.
