### ISSUE TITLE
Example of AWS CodeCommit as a repository for ArgoCD workloads 

### ISSUE THREAD

**Issue by ybezsonov** [aws-ia/terraform-aws-eks-blueprints#1430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Add an example that shows how to configure ArgoCD to use AWS Codecommit as a source repository for ArgoCD workloads. 
AWS Codecommit can trigger ArgoCD sync by calling ArgoCD webhook. It can start deployment of changes to EKS cluster immediately after push to AWS Codecommit repository and remove the need of pulling repository each X minutes.

#### Describe the solution you would like

A simple example that contains:

- Create AWS Codecommit repository
- Copy sample workloads repository from Github and push to AWS Codecommit
- Create AWS Codecommit credentials and configure ArgoCD to use them via Secret to access AWS Codecommit repository
- Create AWS Codecommit trigger to execute AWS Lambda function to call ArgoCD webhook

**Comment by ybezsonov** [comment]
Hi @askulkarni2 Could you please assign this issue to me? I have a draft implementation already and can deliver a solution.

**Comment by bryantbiggs** [comment]
in light of the recent announcement around [CodeCommit](https://aws.amazon.com/blogs/devops/how-to-migrate-your-aws-codecommit-repository-to-another-git-provider/) we are going to close this feature request
