### ISSUE TITLE
Why examples changed and now using terraform-aws-modules/eks/aws instead of eks blueprints module

### ISSUE THREAD

**Issue by Tstrul-work** [aws-ia/terraform-aws-eks-blueprints#1444]
- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I was looking at the latest examples and saw you do not use the blueprints module to install EKS cluster and you are using terraform-aws-modules/eks/aws. 

Is there a reason for it? I had some issues with the addons and wanted to make sure vpc cni installs before nodes provisioning  and saw it in the examples, but it's with a different module.

How hard is the migration? I see there are some parameters that missing from this. module like map_users.

Thank you!

#### Provide a link to the example/module related to the question
[ PR Link](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1428)

** I see its related to v5 upgrade but it is not official yet right?

**Comment by askulkarni2** [comment]
@Tstrul-work we are incrementally making updates to the repo for the v5 changes. We will publish a migration guide as we get closer.

**Comment by bryantbiggs** [comment]
please track #1421 for changes related to the project, thank you!
