### ISSUE TITLE
[QUESTION] Add node labels on bottlerocket nodes

### ISSUE THREAD

**Issue by cptalex** [aws-ia/terraform-aws-eks-blueprints#1446]
Hello all!

- [ X ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here
We need to add node labels to a self managed bottlerocket self managed group, 
currently the only way is to use **post_userdata** variable

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/launch-templates/templates/userdata-bottlerocket.tpl

- Is this the correct way? 
-  As this is a common use case maybe worth a dedicated variable?

Thanks for the support in advance!

**Comment by askulkarni2** [comment]
@cptalex a more detailed example [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e265e23cbc622041fc153193f490cfe948f/examples/eks_managed_node_group/main.tf#L160) but yes that is the correct way to assign node labels today. As you may know, you can wrap this in your own terraform module and create variables for it.
