### ISSUE TITLE
Dependecy  issue between addons and eks cluster causes terraform destroy fail

### ISSUE THREAD

**Issue by mk2134226** [aws-ia/terraform-aws-eks-blueprints#1449]
I have this  addons module

module "eks_blueprints_kubernetes_addons" {
  depends_on = [module.eks_blueprints]

You guys told  that we dont use depends on as it causes issues of some resources to create and recreate

But problem is if i dont use that line then During terraform destroy the eks cluster get destroyed first and addons does not start deleting. Ideally addons should be deleted before eks cluster module

**Comment by FernandoMiguel** [comment]
using `-target`
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/getting-started.md#destroy

**Comment by bryantbiggs** [comment]
as Fernando stated, the intended approach is to use a targetted destroy
