### ISSUE TITLE
vpc_security_group_ids parameter is ignored

### ISSUE THREAD

**Issue by meakbiyik** [aws-ia/terraform-aws-eks-blueprints#1452]
## Description

- [x] ✋ I have searched the open/closed issues and my issue is not listed.
- [x]  reinitialized terraform directory 

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.3.7
on windows_amd64
- Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.53.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

```hcl

resource "aws_security_group" "ingress_sg" {
  name_prefix = "ingress"
  description = "inbound rules"
  vpc_id      = module.vpc.vpc_id
  ingress {
    protocol    = "tcp"
    from_port   = 8000
    to_port     = 8000
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}

module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.22.0"

  cluster_name    = local.cluster_name
  cluster_version = "1.24"

  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets
  cluster_endpoint_public_access = true
  managed_node_groups = {
    node_groups = {
      node_group_name = "node_group"
      ami_type = "AL2_ARM_64"
      capacity_type = "ON_DEMAND"

      instance_types = [
        "c6g.xlarge"
      ]

      min_size     = 1
      max_size     = 10
      desired_size = 1

      subnet_ids      = module.vpc.public_subnets
      vpc_security_group_ids = [
        "${aws_security_group.ingress_sg.id}"
      ]
    }
  }
}
```

Adding or removing the segment 
```
      vpc_security_group_ids = [
        "${aws_security_group.ingress_sg.id}"
      ]
```
does not trigger any change in the plan, it reports "No changes. Your infrastructure matches the configuration."

## Expected behaviour

External security group is applied to the managed node group.

## Actual behaviour

Security group is successfully created, but is not applied.

**Comment by meakbiyik** [comment]
I believe this is related to #328, but I am still keeping it open because this seems like a somewhat trivial addition to `managed_ng` resource.

**Comment by bryantbiggs** [comment]
Thank you but please see #1421 - we will be removing support for creation of cluster resources soon
