### ISSUE TITLE
AccessDeniedException when trying to set Cloudwatch log group retention from aws-for-fluentbit

### ISSUE THREAD

**Issue by tanvp112** [aws-ia/terraform-aws-eks-blueprints#1454]
## Description

When using aws-for-fluentbit addon there's error in the log:

`AccessDeniedException: User: arn:aws:sts::<redacted>:assumed-role/<redacted>-aws-for-fluent-bit-sa-irsa/1677224270028524181 is not authorized to perform: logs:PutRetentionPolicy on resource: arn:aws:logs:<redacted>:<redacted>:log-group:/aws/eks/<cluster>/host:log-stream: because no identity-based policy allows the logs:PutRetentionPolicy action\n\tstatus code: 400, request id: b232c74f-a569-4aa4-bb49-aba1c5d74d7e"`

The action "logs:PutRetentionPolicy" is required at: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/aws-for-fluentbit/data.tf#L18

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

4.24.0

## Reproduction Code [Required]

enable_aws_for_fluentbit                 = true
aws_for_fluentbit_cw_log_group_retention = 10  # <-- will not work.

## Expected behaviour

aws-for-fluentbit should be able to set retention period for the cloudwatch log group.

## Actual behaviour

aws-for-fluentbit is not able to set retention period for the cloudwatch log group.

**Comment by askulkarni2** [comment]
Fixed in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/9
