### ISSUE TITLE
[FEATURE] Karpenter blueprint does not include SQS/EventRules for handling Node Termination

### ISSUE THREAD

**Issue by hawkesn** [aws-ia/terraform-aws-eks-blueprints#1464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
Since Karpenter v0.19.1, Karpenter has been able to handle [Node Termination ](https://github.com/aws/karpenter/pull/2546) via a SQS queue and EventRules.
Currently, this extra infrastructure has been documented in the Cloudformation template, but not as a part of the Terraform EKS Blueprint. 

Cloudformation template for reference:
https://karpenter.sh/"${KARPENTER_VERSION}"/getting-started/getting-started-with-eksctl/cloudformation.yaml
https://karpenter.sh/v0.25.0/getting-started/getting-started-with-eksctl/cloudformation.yaml

#### Describe the solution you would like
An update to the Terraform EKS Blueprint for Karpenter that includes the pieces for the SQS Queue and EventRules

#### Describe alternatives you have considered

N/A

**Comment by bryantbiggs** [comment]
this was added in #1458
