### ISSUE TITLE
How to add ENV variables to VPC cni addon,

### ISSUE THREAD

**Issue by mk2134226** [aws-ia/terraform-aws-eks-blueprints#1468]
I want to add these variables to aws vpc cni addon

AWS_VPC_K8S_CNI_EXTERNALSNAT=true
DISABLE_TCP_EARLY_DEMUX=true
POD_SECURITY_GROUP_ENFORCING_MODE=standard

I cant find any way to do it

**Comment by bryantbiggs** [comment]
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/351b763e673227fd88b0b670d769ce4b5674c9a0/examples/ipv4-prefix-delegation/main.tf#L57-L71
