### ISSUE TITLE
Karpenter event_rules clash

### ISSUE THREAD

**Issue by FernandoMiguel** [aws-ia/terraform-aws-eks-blueprints#1471]
This new code has a static event_rules name.
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/351b763e673227fd88b0b670d769ce4b5674c9a0/modules/kubernetes-addons/karpenter/locals.tf#L59
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/351b763e/modules/kubernetes-addons/karpenter/main.tf#L52

so when more than one cluster is created, they will share the event_rule 

if you look into the eks module, they use `name_prefix` which avoids this issue
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/c7565e26/modules/karpenter/main.tf#L270

**Comment by waiyanmin95** [comment]
We're also facing that kind of issue 
+1 Upvote

**Comment by dtherhtun** [comment]
the same issue happens

**Comment by bryantbiggs** [comment]
closing with https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/11 which will be the new home of addons - we are freezing all addon changes here and will provide an upgrade/migration guide soon
