### ISSUE TITLE
Make EMR on EKS module CI/CD ready

### ISSUE THREAD

**Issue by frank-bee** [aws-ia/terraform-aws-eks-blueprints#1485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Describe the solution you would like

Do not do this, it is not suitable for a CD pipeline (where you typically only want explicit changes ;done in a PR or so)
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/emr-on-eks/main.tf#L122

#### Describe alternatives you have considered

 find another solution to trigger this explicitly maybe?

**Comment by bryantbiggs** [comment]
thanks for reporting - this module is slated to be removed in v5 and there are alternate routes for creating EMR virtual clusters on EKS instead. Here is the latest implementation https://github.com/bryantbiggs/terraform-aws-emr/tree/master/modules/virtual-cluster and an example that demonstrates how to use it https://github.com/bryantbiggs/terraform-aws-emr/tree/master/examples/virtual-cluster

**Comment by frank-bee** [comment]
That makes sense! Thanks for the quick feedback!
