### ISSUE TITLE
IAM role attachment not working when using terraform-aws-module v18.29.1

### ISSUE THREAD

**Issue by IgorKurylo** [aws-ia/terraform-aws-eks-blueprints#1499]
Hi guys, just trying to spin out the cluster in eks with the blueprint module and I get a error

I make some investigation and looked the for_each on should get the argument a map instead of toset. 
i go to the https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v19.0.0/main.tf#L309
and the module fix the issue. but you dont update the version of this module.
 
Any suggestion?

## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v4.17.0

- Terraform version: 1.2

- Provider version(s): 4.58.0

## Reproduction Code [Required]

``Error: Invalid for_each argument
10:54:58  │ 
10:54:58  │   on .terraform/modules/eks.eks_cluster.aws_eks/main.tf line 290, in resource "aws_iam_role_policy_attachment" "this":
10:54:58  │  290:   for_each = local.create_iam_role ? toset(compact(distinct(concat([
10:54:58  │  291:     "${local.policy_arn_prefix}/AmazonEKSClusterPolicy",
10:54:58  │  292:     "${local.policy_arn_prefix}/AmazonEKSVPCResourceController",
10:54:58  │  293:   ], var.iam_role_additional_policies)))) : toset([])``

remove all .terraform folder and caching. 
run terraform init again
run terraform plan

**Comment by DUBANGARCIA** [comment]
I have been dealing with this error, and I still can't find the reason why I get this error, except for the fact that I create an ec2 instance to build my docker images that I am going to use in the cluster. At the moment what I have had to do is to build my infrastructure in parts with: terraform apply -target module, so for each module, if you have divided the infrastructure like this

**Comment by cole-ratner** [comment]
@bryantbiggs Hi there so we at Sovrn are seeing this issue as well, and would appreciate some attention to this issue. 

Some context, tf state got corrupted and needed to be removed, we manually deleted some resources, and then removed those items manually deleted items from tf state and then pushed an update to our remote tf state store. 

Upon attempting to recreate the once state-corrupted resources, this exact error comes up. 

for your convenience ive uploaded an excerpt of the log file from the job where this error was raised: 
[gha-log.txt](https://github.com/aws-ia/terraform-aws-eks-blueprints/files/11154255/gha-log.txt)

The error message:

`Plan: 34 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/eks_blueprints_smrtb.aws_eks/main.tf line 290, in resource "aws_iam_role_policy_attachment" "this":
│  290:   for_each = local.create_iam_role ? toset(compact(distinct(concat([
│  291:     "${local.policy_arn_prefix}/AmazonEKSClusterPolicy",
│  292:     "${local.policy_arn_prefix}/AmazonEKSVPCResourceController",
│  293:   ], var.iam_role_additional_policies)))) : toset([])
│     ├────────────────
│     │ local.create_iam_role is true
│     │ local.policy_arn_prefix is a string, known only after apply
│     │ var.iam_role_additional_policies is empty list of string
│ 
│ The "for_each" set includes values derived from resource attributes that
│ cannot be determined until apply, and so Terraform cannot determine the
│ full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to use a map
│ value where the keys are defined statically in your configuration and where
│ only the values contain apply-time results.
│ 
│ Alternatively, you could use the -target planning option to first apply
│ only the resources that the for_each value depends on, and then apply a
│ second time to fully converge.
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.`

**Comment by bryantbiggs** [comment]
In terms of the issue reported, please see more details here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.29.1/docs/faq.md#i-received-an-error-error-invalid-for_each-argument-

Updating to use v19 of the EKS module in this project would be a breaking change. Therefore, in the v5 changes that are happening we are removing the cluster creating from this project and instead encouraging users to lever the EKS module directly which allows them to upgrade to the version of their choosing. You can see more about the v5 changes here https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1421

Closing this for now since the aren't any actions to be taken in the current project

**Comment by cole-ratner** [comment]
@bryantbiggs not sure i understand how we should solve this issue in the mean time, we are blocked in cluster creation, is there any advice for the current module version? (pre-v5?)

**Comment by bryantbiggs** [comment]
yes, see the link provided above https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.29.1/docs/faq.md?rgh-link-date=2023-04-06T17%3A39%3A32Z#i-received-an-error-error-invalid-for_each-argument-

**Comment by cole-ratner** [comment]
@bryantbiggs thank you! we will review this link
