### ISSUE TITLE
eks-managed-nodegroup-w-multiple-volumes examples is wrong

### ISSUE THREAD

**Issue by bla-ckbox** [aws-ia/terraform-aws-eks-blueprints#1502]
## Description

Example of [EKS managed nodegroup with decated volumes](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/dbd9ca385b0f8055e9aab1a54f76e0e74159fbe4/examples/stateful#eks-managed-nodegroup-w-multiple-volumes) for _containerd_ is not working.
`/var/lib/containerd` is not mounted on decated volumes, but on /.

- [X]  I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: v4.25.0

- Terraform version:

Terraform v1.3.7 on linux_amd64

- Provider version(s):

> + provider registry.terraform.io/gavinbunney/kubectl v1.14.0
> + provider registry.terraform.io/hashicorp/aws v4.50.0
> + provider registry.terraform.io/hashicorp/cloudinit v2.3.2
> + provider registry.terraform.io/hashicorp/dns v3.2.4
> + provider registry.terraform.io/hashicorp/helm v2.8.0
> + provider registry.terraform.io/hashicorp/kubernetes v2.16.1
> + provider registry.terraform.io/hashicorp/null v3.2.1
> + provider registry.terraform.io/hashicorp/random v3.4.3
> + provider registry.terraform.io/hashicorp/time v0.9.1
> + provider registry.terraform.io/hashicorp/tls v4.0.4
> + provider registry.terraform.io/terraform-aws-modules/http v2.4.1

- Module(s) version(s):

> - terraform-aws-modules/eks/aws ~> 19.9

## Reproduction Code [Required]

See examples https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/dbd9ca385b0f8055e9aab1a54f76e0e74159fbe4/examples/stateful/

See documentation https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/dbd9ca385b0f8055e9aab1a54f76e0e74159fbe4/examples/stateful#deploy

## Expected behaviour

See https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/dbd9ca385b0f8055e9aab1a54f76e0e74159fbe4/examples/stateful#eks-managed-nodegroup-w-multiple-volumes

`/var/lib/containerd` must be mounted on `/dev/nvme1n1`

## Actual behaviour

`/var/lib/containerd` is mounted on `/`

## Additional context

problem is on `pre_bootstrap_user_data` script:
`SECOND_VOL=$(lsblk -o NAME,TYPE -d | awk '/disk/ {print $1}' | sed -n '2 p')` does not retrieve the name of the correct disk because the result of the lsblk command is not sorted.

I use this solution to get the right Filesystem:

```
        VOLUME_ID=$(aws ec2 describe-volumes \
            --region ${local.region} \
            --filters \
                Name=attachment.instance-id,Values=$${EC2_INSTANCE_ID} \
                Name=attachment.device,Values=${local.second_volume_name} \
            --query Volumes[].Attachments[].VolumeId \
            --output text | sed 's/-//')
        SECOND_VOL=$(lsblk -o NAME,SERIAL -d |awk -v id="$${VOLUME_ID}" '$2 ~ id {print $1}')

```

**Comment by bryantbiggs** [comment]
thank you for the issue - we will keep an eye on this change coming to the EKS optimized AMI https://github.com/awslabs/amazon-eks-ami/pull/1171
