### ISSUE TITLE
How to migrate from blueprint module to eks/aws?

### ISSUE THREAD

**Issue by nascimento** [aws-ia/terraform-aws-eks-blueprints#1515]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

How to migrate from module "terraform-aws-eks-blueprints" to "terraform-aws-modules/eks/aws" without recreate cluster?

As usage recent examples.

**Comment by askulkarni2** [comment]
Hi @nascimento, we will be publishing a migration guide when we make the switch. In the meantime, please track updates to our [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to see how the code would change.

**Comment by nascimento** [comment]
Thanks @askulkarni2 

Maybe it could be help others...
Here it was less traumatic adding the new aws_eks module and renewing the previous one.
With the new name and migrating some resources to not recreate the cluster, I did as below... but recreating nodes.

```
terraform state pull > backup_state.json
terraform state mv module.eks_blueprints.module.aws_eks   module.aws_eks
terraform state rm module.aws_eks.module.kms.data.aws_caller_identity.current
terraform state rm module.aws_eks.module.kms.data.aws_partition.current
terraform state mv module.eks_blueprints.module.kms[0]    module.aws_eks.module.kms
terraform state rm module.eks_blueprints.data.http.eks_cluster_readiness
terraform state rm module.eks_blueprints.kubernetes_config_map.aws_auth[0]

terraform plan
terraform apply
```

It was migrated because I wanted to use vpc-cni with before_compute options .. and some other things.
