### ISSUE TITLE
I believe this resource does not exist anymore

### ISSUE THREAD

**Issue by Sherm4nLC** [aws-ia/terraform-aws-eks-blueprints#1529]
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/12e43950ab56eaba44307e14739d4860edd1511f/examples/fargate-serverless/README.md?plain=1#L11

**Comment by bryantbiggs** [comment]
It does [exist today](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/app-2048), it was just moved up to an addon so it can be re-used by others. So its just the relative path is incorrect currently
