### ISSUE TITLE
How can we configure a private Github ssh key via Terraform?

### ISSUE THREAD

**Issue by laurentenhoor** [aws-ia/terraform-aws-eks-blueprints#1531]
What is the Terraform way of setting this Credentials Template URL (see blue arrow).

<img width="1023" alt="Screenshot 2023-04-03 at 15 06 37" src="https://user-images.githubusercontent.com/32955832/229518878-5b0a0210-4014-480d-ad7c-e19cbd51188e.png">

**Comment by askulkarni2** [comment]
Hi @laurentenhoor, this is documented at [here](https://aws-ia.github.io/terraform-aws-eks-blueprints/main/add-ons/argocd/#private-repositories) as far as the argocd add-on is concerned.

**Comment by bryantbiggs** [comment]
closing with the guidance provided above

**Comment by akzov** [comment]
404

**Comment by allamand** [comment]
@akzov check in this pattern: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/blue-green-upgrade/modules/eks_cluster/main.tf#L529-564
