### ISSUE TITLE
Failed to create eks cluster in AWS China due to the lack of support of the "cluster_iam_role_dns_suffix" parameter

### ISSUE THREAD

**Issue by Monster-Zhu** [aws-ia/terraform-aws-eks-blueprints#1551]
## Description

When deploying eks cluster in AWS China, it reports the following error:
```
│ Error: creating IAM Role (bootstrap-cluster-role): MalformedPolicyDocument: Invalid principal in policy: "SERVICE":"eks.amazonaws.com.cn"
│       status code: 400, request id: XXX
│ 
│   with module.eks.module.eks_blueprints.module.aws_eks.aws_iam_role.this[0],
│   on .terraform/modules/eks.eks_blueprints.aws_eks/main.tf line 250, in resource "aws_iam_role" "this":
│  250: resource "aws_iam_role" "this" {
```

It's a known issue fixed in the terraform-aws-eks module by exposing a new parameter "cluster_iam_role_dns_suffix": 

- https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1905

However the parameter is not exposed by terraform-aws-eks-blueprints.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v4.28.0

## Reproduction Code [Required]

```
module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.28.0"

  cluster_name                    = var.cluster_name
  cluster_version                 = "1.25"
  cluster_endpoint_public_access  = var.cluster_endpoint_public_access
  cluster_endpoint_private_access = true

  cloudwatch_log_group_retention_in_days = 30

  # cluster_iam_role_dns_suffix = "amazonaws.com"

  vpc_id             = var.vpc_id
  private_subnet_ids = var.subnet_ids
}
```

1. tf apply

## Expected behaviour

Successfully create the eks cluster in AWS China account.

## Actual behaviour

Failed to create the eks cluster.

**Comment by bryantbiggs** [comment]
this project is switching to use the mentioned EKS module in v5 - the recommendation would be to switch to use that module for cluster creation today
