### ISSUE TITLE
IAM Role and Policy Conflict when deploying in multiple regions with same cluster name

### ISSUE THREAD

**Issue by mttwise** [aws-ia/terraform-aws-eks-blueprints#1552]
## Description

When deploying an EKS Cluster with the same name to 2 different regions, the add-on IRSA roles and policy names conflict between the clusters.

It would be good to either postfix the roles/policies with region_id or use the terraform Role/Policy name prefix instead of 'name' field.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 4.28.0

- Terraform version: 1.3.9

- Provider version(s): hashicorp/aws: 4.55.0

## Reproduction Code [Required]

```hcl

module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.28.0//modules/kubernetes-addons"

  eks_cluster_id       = module.eks.cluster_name
  eks_cluster_endpoint = module.eks.cluster_endpoint
  eks_oidc_provider    = module.eks.oidc_provider
  eks_cluster_version  = module.eks.cluster_version

  enable_aws_load_balancer_controller           = true

  aws_load_balancer_controller_helm_config = {
    repository_username = data.aws_ecrpublic_authorization_token.token.user_name
    repository_password = data.aws_ecrpublic_authorization_token.token.password 
 }
}

```

## Expected behaviour

Unique IAM roles/policies are created

## Actual behaviour

The following output occurs:
```
╷
│ Error: creating IAM Policy osdu-lb-irsa: EntityAlreadyExists: A policy called osdu-lb-irsa already exists. Duplicate names are not allowed.
│   status code: 409, request id: 23b72462-fecf-4d8d-b9c7-bdc6a8fd251e
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_load_balancer_controller[0].aws_iam_policy.aws_load_balancer_controller,
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/aws-load-balancer-controller/main.tf line 10, in resource "aws_iam_policy" "aws_load_balancer_controller":
│   10: resource "aws_iam_policy" "aws_load_balancer_controller" {
│ 
╵
╷
│ Error: creating IAM Policy osdu-aws-nth-irsa: EntityAlreadyExists: A policy called osdu-aws-nth-irsa already exists. Duplicate names are not allowed.
│   status code: 409, request id: 0cb9d926-f014-4329-a099-3f54f4a87929
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_node_termination_handler[0].aws_iam_policy.aws_node_termination_handler_irsa,
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/aws-node-termination-handler/main.tf line 60, in resource "aws_iam_policy" "aws_node_termination_handler_irsa":
│   60: resource "aws_iam_policy" "aws_node_termination_handler_irsa" {
│ 
```

### Terminal Output Screenshot(s)

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/24458226/231882888-e7252006-cb39-451c-aab0-b63e321b7cdb.png">

**Comment by bryantbiggs** [comment]
thank you for the issue - this has been resolved here in the new addons project https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/95
