### ISSUE TITLE
Documentation Bug in Direction for v5 of EKS Blueprints

### ISSUE THREAD

**Issue by aniketwalse** [aws-ia/terraform-aws-eks-blueprints#1560]
## Description

Getting 404 while navigating to [terraform-aws-eks-kubernetes-addon](https://github.com/aws-ia/terraform-aws-kubernetes-addon). Which is specified [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/docs/v5-direction/DIRECTION_v5.md#notable-changes) at point no 4.
What is the right url for this ?

**Comment by askulkarni2** [comment]
Thanks for reporting this. We've not made this repo public yet. It will be available soon.
