### ISSUE TITLE
Create gp3 storage class when enabling ebs csi driver

### ISSUE THREAD

**Issue by idjemaoune** [aws-ia/terraform-aws-eks-blueprints#1562]
We want to add the ability to create new storage class on the Kubernetes EKS cluster to meet specific storage needs for our applications.

When activating the ebs csi driver, which is necessary to use gp3, we can create a new storage class without making it a default class. So we can keep gp2 and gp3 for workloads that need optimized storage.

**Comment by bryantbiggs** [comment]
see comment here https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1564#issuecomment-1522328148
