### ISSUE TITLE
Support tagging flag for ek primary security group

### ISSUE THREAD

**Issue by Pacobart** [aws-ia/terraform-aws-eks-blueprints#1563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Currently, the eks primary security group has a boolean value to create tags and is defaulted to true. In our environment, the security group gets a "kuberentes.io/cluster/<myclustername>" tag and it causes issues with the aws-load-balancer-controller as multiple security groups have this tag. We'd like the ability to disable putting tags on the primary security group. The variable exists in the terraform-aws-eks module.

I propose we add `create_cluster_primary_security_group_tags` variable to the blueprint repository.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.29.1/main.tf#L65

**Comment by tanvp112** [comment]
You can remove the cluster tag: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1986#issuecomment-1147709576

**Comment by Pacobart** [comment]
> You can remove the cluster tag: [terraform-aws-modules/terraform-aws-eks#1986 (comment)](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1986#issuecomment-1147709576)

This doesn't work. It results in a "tag requires a value" error. I've also tried setting the tag to anything other than "owned" and still have issues with the multiple security group error.
