### ISSUE TITLE
Self Managed Nodes are not getting upgraded

### ISSUE THREAD

**Issue by gauravchaudhary999** [aws-ia/terraform-aws-eks-blueprints#1566]
## Description

When I upgrade the EKS version from 1.22 to 1.23

Then Self-Managed should be upgraded to 1.23

Actual: Self Managed nodes remain on eks 1.22 

This is because aws_autoscaling_group in self-managed node template is using launch templates that do not receive a new name when they are updated; they receive a new version instead which does not force the autoscaling group to launch new instances.

**Comment by bryantbiggs** [comment]
please provide a full reproduction so that we can properly triage and provide guidance

**Comment by bryantbiggs** [comment]
Closing for now - please see the https://github.com/terraform-aws-modules/terraform-aws-eks project which as of v19.x defaults to automatically rolling out launch template changes
