### ISSUE TITLE
How to make Blueprint create nodes with custom Security Groups?

### ISSUE THREAD

**Issue by fernandomullerjr** [aws-ia/terraform-aws-eks-blueprints#1568]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have 1 EKS cluster that I created using Blueprint v4.21.0.
I want to expose some ports of my nodes, but I want these ports already exposed while creating the cluster via Terraform.
How can I make Terraform create the node-groups of the EKS cluster that is created via Blueprint, with custom Security Groups?
I tried in several ways, but I couldn't make an adjustment where the EC2 that are part of the managed node group use custom Security Groups with additional ip permission rules.

#### Provide a link to the example/module related to the question

Link to my project:
https://github.com/fernandomullerjr/eks-via-terraform-github-actions/tree/main/09-eks-blueprint

I tried some parameter options in main.tf:

```
create_cluster_security_group
cluster_security_group_additional_rules

create_node_security_group
node_security_group_additional_rules

cluster_additional_security_group_ids
```

But they didn't work

I tried to do something like this, using the "additional_security_group_ids" for the "managed_node_groups", but it had no effect:

```
[...omitted...]
   managed_node_groups = {
     T3A_NODE2 = {
       node_group_name = "test2"
       instance_types = ["t3a.medium"]
       subnet_ids = module.vpc.public_subnets
       scaling_config = {
         additional_security_group_ids = [aws_security_group.sg.id]
       }

     }
   }
```

What can be done in this case?

**Comment by bryantbiggs** [comment]
please provide a full reproduction so that we can properly triage and provide guidance

**Comment by bryantbiggs** [comment]
Please see the `terraform-aws-eks` module which provides examples that demonstrate how to achieve this functionality https://github.com/terraform-aws-modules/terraform-aws-eks/blob/f741db1b2c7c4ef0409d7c2e4f588bbc639cbaf2/examples/complete/main.tf#L78-L117
