### ISSUE TITLE
How are CRDs handled?

### ISSUE THREAD

**Issue by d-m** [aws-ia/terraform-aws-eks-blueprints#1569]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Does the kubernetes-addons module handle addon custom resource definitions, and if so, how does it manage upgrades? For example, if an upstream project upgrades their CRD, how is that handled here?

If it's not, does anyone have a good pattern of how they're managing this?

#### Provide a link to the example/module related to the question

I.E. how does [kyverno](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/kyverno) manage CRD updates?

**Comment by bryantbiggs** [comment]
addons rely on the helm chart of the underlying addon - so in short, the addon should have its own mechanism for managing CRD upgrades. Most appear to be going the way of packaging their CRD in its own helm chart and then making that a dependency of the controller chart

**Comment by bryantbiggs** [comment]
closing with above guidance - please let me know if there are any additional questions left unanswered
