### ISSUE TITLE
Add support for Gateway API Controller and required security group to Blueprints

### ISSUE THREAD

**Issue by sheetaljoshi** [aws-ia/terraform-aws-eks-blueprints#1575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Describe the solution you would like

Amazon VPC has recently launched Amazon VPC Lattice to support application networking across VPCs, Accounts, and compute platforms. Amazon VPC Lattice is a fully managed service built directly into the AWS network infrastructure and supports service discovery, obserbvability, and traffic management. 

At AWS, we implement Gateway API to integrate with Amazon VPC Lattice. AWS Gateway API controller is an open-source project and fully supported by Amazon. When AWS Gateway API controller is installed in your cluster, the controller watches for the creation of Gateway API resources such as Gateway and Routes and provisions corresponding Amazon VPC Lattice objects. 

We would like Blueprints team to add support for deploying Gateway API Controllers, related IAM permissions, and security group required by Lattice. 

#### Describe alternatives you have considered

Currently for customers it is a multi-step process and customers use helm chart to install Gateway API controller.

**Comment by bryantbiggs** [comment]
duplicate of https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/94 - we are tracking addons in the linked (new) repository and this repository demonstrates usage/architectural patterns
