### ISSUE TITLE
Getting started documentation example missing

### ISSUE THREAD

**Issue by MarcAnProv** [aws-ia/terraform-aws-eks-blueprints#1576]
## Description

The directory `examples/eks-cluster-with-new-vpc/` as mentioned in the "Getting started" section in the documentation is missing. The documentation tells you to cd into that directory, but it's non existent. I believe it was deleted by commit `243ae23284c132753957508de3f724c0af73ebf0`. 

I see that it is part of this PR #1428, but could you please point me to an example for beginners?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by paravatha** [comment]
So, what's the new basic example for beginners under here?
https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples
