### ISSUE TITLE
Can I add an ArgoCD application via chart and not via git repo?

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [aws-ia/terraform-aws-eks-blueprints#1583]
I'm looking through these parameters:
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/argocd/main.tf#L28

There does not seem to be an option to pull directly from a Helm repo. It's only git repo with Helm chart.
I need something like `chart = "elasticsearch"` instead of `path` and it does not seem possible with the current templates. The below example will not work in ArgoCD with the error `rpc error: code = Unknown desc = repository not found`:

```
      elastic-stack = {
        path               = "elasticsearch"
        repo_url            = "https://helm.elastic.co"
        values              = {}
        type                = "helm"
        target_revision = "7.17.3"
      }
```

Here is a part of the default example of an ArgoCD application where you use `path` for git repos and `chart` for Helm repos:

```
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: guestbook  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

    # helm specific config
    chart: chart-name  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
```

**Comment by bryantbiggs** [comment]
closing this issue for now - please see https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114 where we are collecting feedback on how to improve the integration between Terraform and GitOps providers
