### ISSUE TITLE
[ENHANCEMENT] Kubernetes version 1.26 support

### ISSUE THREAD

**Issue by armujahid** [aws-ia/terraform-aws-eks-blueprints#1592]
Support for Support for version [1.26](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-26/)

**Comment by armujahid** [comment]
Related: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1456

**Comment by injectedfusion** [comment]
Looking forward to this one!

**Comment by deepakjeena** [comment]
I have upgrade my eks to 1.27 , and it is successfully upgraded with addons.
