### ISSUE TITLE
Enable GuardDuty EKS runtime monitoring?

### ISSUE THREAD

**Issue by leonidkhelemes** [aws-ia/terraform-aws-eks-blueprints#1596]
How can I enable [GuardDuty EKS runtime monitoring](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-eks-runtime-monitoring.html), if I'm using aws-ia/terraform-aws-eks-blueprints?

According to the documentation in need to pass

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "17.4.0"

  # ...

  vpc_subnets         = module.vpc.private_subnets
  tags                = local.common_tags
  oidc_provider       = module.eks_oidc_provider.this_oidc_provider_url
  cluster_name        = var.cluster_name
  subnets_map_public  = local.subnets_map_public
  subnets_map_private = local.subnets_map_private

  # ...

  vpc_config = {
    # ...

    # Enable GuardDuty EKS runtime monitoring
    guardduty = {
      detector_id = data.aws_guardduty_detector.example.id
    }
  }
}
```

But I'm not sure how to do it from eks blueprints module. How to pass `vpc_config`?
I already have aws_guardduty_detector created with k8s audit logs enabled.

**Comment by askulkarni2** [comment]
Hi @leonidkhelemes, see [this](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/90a70ba07eebdd2af91047798c0887361cfe31d8/tests/complete/main.tf#L129) for example.
