### ISSUE TITLE
How can I add kubernetes add-on prometheus without creation of new iam role

### ISSUE THREAD

**Issue by chebroluharika** [aws-ia/terraform-aws-eks-blueprints#1598]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have used helm-addon module to provision prometheus add-on for EKS cluster, but its saying "the argument vpc-id is required, but no definition found". But I don't see any vpc_id getting used inside prometheus module terraform code.

#### Provide a link to the example/module related to the question

[](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/prometheus/main.tf#L22)

#### Additional context

**main.tf**
`# Prometheus addon
module "prometheus" {
  count       = var.enable_prometheus ? 1 : 0
  source      = "../modules/prometheus"
  enable_amazon_prometheus = false
  addon_context     = local.addon_context
}`

**inside modules/prometheus**

`locals {
  name             = "prometheus"
  namespace_name   = "prometheus"
  create_namespace = false

  # `namespace_name` is just the string representation of the namespace name
  # `namespace` is the name of the resultant namespace to use - created or not
  namespace = local.create_namespace ? kubernetes_namespace_v1.prometheus[0].metadata[0].name : local.namespace_name

  workspace_url          = ""
  ingest_service_account = "amp-ingest"
  ingest_iam_role_arn    = var.enable_amazon_prometheus ? module.irsa_amp_ingest[0].irsa_iam_role_arn : ""

  amp_gitops_config = var.enable_amazon_prometheus ? {
    roleArn            = local.ingest_iam_role_arn
    ampWorkspaceUrl    = local.workspace_url
    serviceAccountName = local.ingest_service_account
  } : {}
}

module "helm_addon" {
  source = "../helm-addon"

  manage_via_gitops = true

  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/Chart.yaml
  helm_config = merge(
    {
      name        = local.name
      chart       = local.name
      version     = "15.17.0"
      repository  = "https://prometheus-community.github.io/helm-charts"
      namespace   = local.namespace_name
      description = "Prometheus helm Chart deployment configuration"
      values = [templatefile("${path.module}/values.yaml", {
        operating_system = "linux"
      })]
    }
  )

  set_values = var.enable_amazon_prometheus ? [
    {
      name  = "serviceAccounts.server.name"
      value = local.ingest_service_account
    },
    {
      name  = "serviceAccounts.server.create"
      value = false
    },
    {
      name  = "serviceAccounts.server.annotations.eks\\.amazonaws\\.com/role-arn"
      value = local.ingest_iam_role_arn
    },
    {
      name  = "server.remoteWrite[0].url"
      value = local.workspace_url
    },
    {
      name  = "server.remoteWrite[0].sigv4.region"
      value = var.addon_context.aws_region_name
    }
  ] : []

  addon_context = var.addon_context
}

resource "kubernetes_namespace_v1" "prometheus" {
  count = local.create_namespace ? 1 : 0

  metadata {
    name = local.namespace_name
  }
}`

**Comment by bryantbiggs** [comment]
please see https://github.com/aws-ia/terraform-aws-eks-blueprints-addons where addons will be managed going forward

Ref: #1421
