### ISSUE TITLE
Passing HELM values file overrwrite  some settings from addon

### ISSUE THREAD

**Issue by mk2134226** [aws-ia/terraform-aws-eks-blueprints#1609]
I was passing helm values for karpeneter addons via file and that override your settings fromt his file

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/karpenter/locals.tf#L25

You should merge the values rather than override like settings variable  if i pass settings var with single field then it override it and remove critical components clike clusterName etc

<img width="952" alt="image" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/64355236/e517bc03-bfde-458f-a047-5720933797f1">

**Comment by bryantbiggs** [comment]
we will be tracking future changes to the GitOps integration here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114
