### ISSUE TITLE
Ability to configure volume size for xvdb in case of BottlerocketOS AMI

### ISSUE THREAD

**Issue by dbcelm** [aws-ia/terraform-aws-eks-blueprints#1610]
## Description

Currently "disk_size" is configured to be passed just through launch template. This limits the use case where someone would want disk size to be controlled directly from "aws_eks_node_group" resource block. This is limiting max usable disk available to BottlerocketOS based nodes as it creates two volumes with "xvda" and "xvdb" mounts, and "xvdb" mount is what decides how much ephemeral storage will be made available to node, and current implementation only let us change volume size for "xvda". 

## Versions

- Module version [Required]: v4.31.0

- Terraform version: v1.3.5
- Provider version(s): v4.67.0

## Reproduction Code [Required]

1. Create a BottlerocketOS based node group and give disk size as any value above 20gb
2. Once Node Group is created each EC2 node will show 2 volumes attached, one with mount point "xvda" which will also we Root Volume and will have same size as mentioned in point 1,
3. Second volume "xvdb" will be of size 20gb (I used GPU based nodes so this is the size I got, might vary) and this will also reflect as size for your available ephemeral storage,
4. This limits the maximum image size of pods one can have on these nodes and node constantly go under disk pressure on spinning heavy images

## Additional context

Try creating Node Group manually and mention disk size there and don't provide disk size in launch template and now "xvdb" will have desired provided size and also pods come into running state just fine.

**Comment by invalidred** [comment]
I am facing disk pressure issue on blueprints `4.24.0` and I noticed `xvdb` which I assume is used by bottlerocket is limited to 20GB. Did you manage to increase this limit? If yes, how did you do it? Is there a way to make containerD use a different volume instead?

**Comment by FernandoMiguel** [comment]
@invalidred should be as easy as
```hcl
    block_device_mappings = {
      data_volume = {
        device_name = var.ng_platform == "bottlerocket" ? "/dev/xvdb" : "/dev/xvda"
        ebs = {
          volume_size           = 100
          volume_type           = "gp3" # The volume type. Can be standard, gp2, gp3, io1, io2, sc1 or st1 (Default: gp3).
          delete_on_termination = true
        }
      }
    }
```

**Comment by invalidred** [comment]
Thank you for the prompt response @FernandoMiguel. I am unfamiliar with the configuration you have listed. I am using the `github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.24.0` and that contains block device mapping which as in array.

```
module "eks_cluster" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.24.0"

  // some cluster info...
  // some vpc info ...

  managed_node_groups = {
    private_node = {

      node_group_name        = "private-node"
      create_launch_template = true
      launch_template_os     = "bottlerocket"
      public_ip              = false

      desired_size    = 1
      max_size        = 2
      min_size        = 1
      max_unavailable = 1

      ami_type      = "BOTTLEROCKET_ARM_64"
      capacity_type = "ON_DEMAND"
      instance_types = ["m6g.xlarge"] 

     block_device_mappings = [{
      device_name           = "/dev/xvda"
      volume_type           = "gp3"
      volume_size           = 100
      delete_on_termination = true
      encrypted             = true
      kms_key_id            = ""
      iops                  = 3000
      throughput            = 125
    }]
```

When I create the above cluster... the following created.

<img width="1045" alt="Screenshot 2023-06-07 at 8 50 46 AM" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/5270458/df4513d9-eaf6-4c5e-bba0-0751eeb1db18">


The issue I'm facing is... I don't see the 100GB volume ever used. What am I doing wrong?

**Comment by FernandoMiguel** [comment]
Try adding a block for xvdb with the size you want.
You only have one for xvda and that is only for the root volume, not the data volume.

**Comment by FernandoMiguel** [comment]
@invalidred you only need 2GBs for the root volume (4GB is using GPU)
