### ISSUE TITLE
Whats the process for people who want to stay on v4 ?

### ISSUE THREAD

**Issue by mk2134226** [aws-ia/terraform-aws-eks-blueprints#1623]
We are currently in the process of migrating our workloads to V4, and we don't have enough resources to upgrade to V5. My primary concern is whether the process of upgrading the cluster, for instance from 1.27 to 1.28, will continue to be compatible with your latest release. If not, what additional changes would we need to implement?

You can't just leave people in the lurch. There should be some documentation outlining what steps need to be taken. For third-party add-ons, we can modify the configuration with Helm, but our main concern lies with AWS native add-ons and cluster upgrades.

**Comment by bryantbiggs** [comment]
Hi @mk2134226 - great question. In short, nothing is required - you should always pin your modules to avoid any unintended changes and you can continue to use that version for as long as you wish or until you are ready to make changes to follow the new direction in v5. As I've stated in a similar question [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1592#issuecomment-1545868336), there really isn't anything required to support later versions of EKS. There may be some configuration changes required based on the addons if they have changes required to support later versions, but this configuration is already exposed to users today for them to configure as they see fit.

Lastly, we are not leaving anyone in the dark. When we make the changes in the project, there will be documentation provided. Most of this should be captured under issue https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1421

Please let me know if there are any additional questions I can help answer

**Comment by bryantbiggs** [comment]
FYI - if you wish to stay on v4 you will need to pin your version to v4.32.1 - you can read more about why this version [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1630#issuecomment-1577525242)
