### ISSUE TITLE
Blueprint for VPC Lattice

### ISSUE THREAD

**Issue by askulkarni2** [aws-ia/terraform-aws-eks-blueprints#1638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I would like to see an example of how I can provision VPC Lattice and use the API gateway controller to connect services across EKS clusters and possibly with Lambda/ECS based services.

#### Describe the solution you would like

A terraform pattern that provisions an architecture similar to the one described [here](https://aws.amazon.com/blogs/containers/introducing-aws-gateway-api-controller-for-amazon-vpc-lattice-an-implementation-of-kubernetes-gateway-api/).

#### Describe alternatives you have considered

Manual setup as described in the blog.

#### Additional context

Related: https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/94

**Comment by neelaruban** [comment]
@askulkarni2  I would be happy to work on this one ?

**Comment by Tim-AWS** [comment]
@neelaruban are you still interested in working on this?

**Comment by neelaruban** [comment]
@Tim-AWS  yes

**Comment by allamand** [comment]
@neelaruban I've got also something working here, can we sync on what you plan to deliver also ?

**Comment by neelaruban** [comment]
@allamand sure

**Comment by allamand** [comment]
Nice i'll look at it.
