### ISSUE TITLE
Question: Error setting create var to false

### ISSUE THREAD

**Issue by SteveL1** [aws-ia/terraform-aws-eks-blueprints#1643]
After successfully creating a cluster i am trying to destroy it by setting the create variable to false.  But when I do I get the error

```
│   on _providers.tf line 16, in provider "helm":
│   16:     cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
│     ├────────────────
│     │ while calling base64decode(str)
│     │ module.eks.cluster_certificate_authority_data is null
│ 
│ Invalid value for "str" parameter: argument must not be null.
```

Does anyone know any way around this?

**Comment by jsidney** [comment]
hi @SteveL1  - did you manage to find a way around this? cause I am having the same problem. 
i just want to destroy the cluster and I cant because of the providers being dependent on it.

**Comment by SteveL1** [comment]
@jsidney I seem to remember that I found the problem was something really quite silly, but I can't remember what I'm afraid.

If it was an actual issue i would have closed this off with a helpful comment, i'm not sure why I didn't to that this time.

Sorry i can't be of more help

**Comment by jsidney** [comment]
no problem man! im also sure im just missing something silly too :)
