### ISSUE TITLE
Failed to upgrade beyond v4.28.0 when using self-managed node group with mixed instance policy and SPOT instances 

### ISSUE THREAD

**Issue by pablomfc** [aws-ia/terraform-aws-eks-blueprints#1650]
## Description

After this change in release v4.29.0:
fix: Fix spot instance issue in self managed node group template by @gauravchaudhary999 in https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1540

I was not able to upgrade to the latest versions

## Versions

- Module version [v4.32.1]

- Terraform version:
terraform -version 
Terraform v1.5.0 on linux_amd64

- Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.3.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

Code for nodegroup:

module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.32.1"
  ....

  self_managed_node_groups = {
    # Self Managed Node group with Launch templates using AMI TYPE and SPOT instances of 2 vCPUs and 8 Gib Memory
    spot_4vcpu_32mem_a = {
      node_group_name = "smng-spot-4vcpu-32mem-a"
      capacity_type   = "spot"
      instance_types  = ["r4.xlarge", "r5.xlarge", "r6i.xlarge", "r6a.xlarge"]
      max_size        = 5
      #desired_size    = 1
      min_size        = 1
      launch_template_os = "amazonlinux2eks"
      eni_delete        = true
      create_iam_role = false
      iam_role_arn  = aws_iam_role.managed_ng.arn
      iam_instance_profile_name = aws_iam_instance_profile.managed_ng.name

      # Node Group network configuration
      subnet_type = "private" # public or private - Default uses the private subnets used in control plane if you don't pass the "subnet_ids"
      subnet_ids  = [local.subnet_a]        # Defaults to private subnet-ids used by EKS Control plane. Define your private/public subnets list with comma separated subnet_ids  = ['subnet1','subnet2','subnet3']

      k8s_taints = [{ key = "spotInstance", value = "true", effect = "NO_SCHEDULE" }]
      additional_tags = {

      }

      create_launch_template      = true 
      enable_metadata_options     = true

    }

...
}

- terraform plan

module.eks_blueprints.module.aws_eks_self_managed_node_groups["spot_4vcpu_32mem_a"].module.launch_template_self_managed_ng.aws_launch_template.this["self-managed-node-group"] will be updated in-place
  ~ resource "aws_launch_template" "this" {
      ~ default_version         = 4 -> (known after apply)
        id                      = "lt-0e29ddeac47a55b4d"
       image_id           = ""ami-0f7abd12e02335c8d"
      ~ latest_version          = 4 -> (known after apply)
        name                    = "smng-spot-4vcpu-32mem-a-cluster-dev-eks"
        tags                    = {
            "Blueprint"                                                      = "lifewallet-dev-eks"
            "GithubRepo"                                                     = "github.com/aws-ia/terraform-aws-eks-blueprints"
            "Name"                                                           = "smng-spot-4vcpu-32mem-a-cluster-dev-eks"
            "aws-node-termination-handler/managed"                           = "true"
            "k8s.io/cluster-autoscaler/enabled"                              = "TRUE"
            "k8s.io/cluster-autoscaler/lifewallet-dev-eks"                   = "owned"
            "k8s.io/cluster-autoscaler/node-template/label/eks/capacityType" = "spot"
            "k8s.io/cluster-autoscaler/node-template/label/eks/nodegroup"    = "smng-spot-4vcpu-32mem-a"
            "k8s.io/cluster-autoscaler/node-template/label/nodegroup"        = "generic"
            "kubernetes.io/cluster/lifewallet-dev-eks"                       = "owned"
            "managed-by"                                                     = "terraform-aws-eks-blueprints"
        }
        # (11 unchanged attributes hidden)

      + instance_market_options {
          + market_type = "spot"
        }

        # (7 unchanged blocks hidden)
    }

## Expected behaviour

upgrade module version

## Actual behaviour

terraform apply fail with errors

### Terminal Output Screenshot(s)

╷
│ Error: updating Auto Scaling Group (cluster-dev-eks-smng-spot-4vcpu-32mem-a): InvalidQueryParameter: Incompatible launch template: You cannot use a launch template that is set to request Spot Instances (InstanceMarketOptions) when you configure an Auto Scaling group with a mixed instances policy. Add a different launch template to the group and try again.
│ 	status code: 400, request id: a0747aba-68f2-481c-bb2c-e804d19d15f7
│ 
│   with module.eks_blueprints.module.aws_eks_self_managed_node_groups["spot_4vcpu_32mem_a"].aws_autoscaling_group.self_managed_ng,
│   on .terraform/modules/eks_blueprints/modules/aws-eks-self-managed-node-groups/main.tf line 1, in resource "aws_autoscaling_group" "self_managed_ng":
│    1: resource "aws_autoscaling_group" "self_managed_ng" {
│

**Comment by bryantbiggs** [comment]
could you please format the code and output provided
