### ISSUE TITLE
How to create ArgoCD application of type "GIT" instead of "HELM"

### ISSUE THREAD

**Issue by shazib-summar** [aws-ia/terraform-aws-eks-blueprints#1651]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here
How can I create an ArgoCD application that syncs with a private GitHub repo containing yaml manifests?

I am completely new to both ArgoCD and Terraform, so the examples provided in this repo were very helpful. However, I'm confused as to how I can create a "git" application instead of a helm one. That is, my GitHub repo contains raw yaml manifests and not helm charts. 

Following is my `eks_blueprints_addons` module

```
module "eks_blueprints_addons" {
  # Users should pin the version to the latest available release
  # tflint-ignore: terraform_module_pinned_source
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.32.1"

  eks_cluster_id        = data.aws_eks_cluster.cluster.id
  eks_cluster_endpoint  = data.aws_eks_cluster.cluster.endpoint
  eks_cluster_version   = data.aws_eks_cluster.cluster.version
  eks_oidc_provider     = data.aws_eks_cluster.cluster.identity[0].oidc[0].issuer
  eks_oidc_provider_arn = data.aws_eks_cluster.cluster.identity[0].oidc[0].issuer

  enable_argocd = true
  # This example shows how to set default ArgoCD Admin Password using SecretsManager with Helm Chart set_sensitive values.
  argocd_helm_config = {
    set_sensitive = [
      {
        name  = "configs.secret.argocdServerAdminPassword"
        value = bcrypt_hash.argo.id
      }
    ]
  }

  argocd_manage_add_ons = true # Indicates that ArgoCD is responsible for managing/deploying add-ons
  argocd_applications = {
    manifests = {
      path               = "path/to/manifests/folder"
      repo_url           = "redacted"
      ssh_key_secret_name = "ssh_key_secret_name_here" # needed for private repos
      directory_recurse  = true
      target_revision    = "dev-branch"
      type = "git"
    }
  }

}
```
Notice that I have set `type` to `"git"` in the argocd_applications block. This however causes the entire application to be ignored (`tf plan` says there are no changes). If I remove the line or set it to `"helm"` explicitly the application is created but its not what I want (an application of git type), consequently, ArgoCD complains that there is no `Chart.yaml` in the specified path (there are deployments/replicasets etc.)

#### Provide a link to the example/module related to the question

ArgoCD example: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/argocd

#### Additional context

See the following screenshot to understand what I mean by a git type application.
<img width="559" alt="image" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/27294025/180e6e41-f714-4048-ba40-de97bb8df88e">

I can create the application from the ArgoCD UI but not from terraform. Following is my terraform version not sure if anything else is needed here.

```
➜ tf version
Terraform v1.5.0
on darwin_arm64
```

**Comment by askulkarni2** [comment]
Hi @shazib-summar, thank you for the question. The existing implementation in v4 supports application type = `helm` or `kustomize`. We do not have support for directory of manifests at this time. We are in the process of revamping our gitops approach, see [this](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114) issue for more information. We will take this feedback into consideration in the new design.
