### ISSUE TITLE
Getting error when trying to install calico Addon

### ISSUE THREAD

**Issue by OoJiaShyang** [aws-ia/terraform-aws-eks-blueprints#1653]
#### Please describe your question here

Just some context, I have tried to install calico similarly to the eks-blueprint, but my cluster is a private one with no access to the internet, so I have to go to artifacthub - https://artifacthub.io/packages/helm/projectcalico/tigera-operator/3.25.0?modal=install
to download the charts instead, upload them to ECR and reference them in my helm values.yaml file to deploy them.

![calico pods](https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/22861795/7eb80880-67f4-4926-83e0-14082528369d)
The error I'm getting is "Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown"
![calico error msg](https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/22861795/d3f3fb8d-bd6e-4fc6-a7ae-77df8161e0e9)

I have a bastion host which I can SSM into and use kubectl to describe and log the pods, and I can SSM into the node as well for debugging purposes but I can't find anything notable. Do tell if there's any logs you want me to retrieve or look at.

### Here's the code snippets 
```go
module "calico_helm_addon" {
    source  = "prod-tfe.web.rbsgrp.net/CTO/eks-helm/aws"
    version = "1.0.3"
    helm_config = merge(
      {
        name             = "calico"
        chart            = "${path.module}/charts"
        version          = "v3.25.1"
        namespace        = "tigera-operator"
        create_namespace = true
        values           = []
        description      = "Calico"
      },
      var.calico_helm_config
  )
}
```

Here I basically use the helm release resource for the calico helm charts. On path.module/charts, its basically the tar out contents of the tigera-operator chart I got from artifact hub - https://artifacthub.io/packages/helm/projectcalico/tigera-operator/3.25.1

```go
module "calico" {
  source      = "./modules/calico"
  count       = var.enable_calico ? 1 : 0
  calico_helm_config = var.calico_helm_config
}
```

And then I turn it into a module which I can call from my workspaces

```go
module "eks_controls" {  
     depends_on = [module.eks]
     source          = "./calico_module"

     enable_calico = true
     calico_helm_config = {
       values = [templatefile("${path.module}//calico_values.yaml", {})]
     }

     standard_tags      = var.standard_tags
     cluster_name       = var.cluster_name
     kubernetes_version = "1.24"
}
```

#### Basically, I changed nothing in the downloaded tigera charts except in the calico_values.yaml file which is shown below here

```go
# you can find more installation references here - https://docs.tigera.io/calico/3.25/reference/installation/api
installation:
  enabled: true
  kubernetesProvider: "EKS"
  registry: 254208046539.dkr.ecr.eu-west-1.amazonaws.com
  # nonPrivileged: Enabled

# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: tigera/operator
  version: v1.29.3
  registry: 254208046539.dkr.ecr.eu-west-1.amazonaws.com
calicoctl:
  image: calico/ctl
  tag: v3.25.1
  registry: 254208046539.dkr.ecr.eu-west-1.amazonaws.com
```

I have to use my own ECR as my instances don't have internet access, so I downloaded all the images beforehand via a proxy and upload them to ECR.

#### Additional Context
Do tell if there's more information that you need and any and all insights are appreciated !

Thanks

**Comment by askulkarni2** [comment]
@OoJiaShyang please provide formatted code inline in the issue as security policies prevent us from downloading arbitrary zip archives. TIA.

**Comment by OoJiaShyang** [comment]
Thanks, I've updated the ticket to display the relevant code areas, do tell if anymore information is needed

**Comment by OoJiaShyang** [comment]
Found a version misconfiguration in the code, relaunched and got a new error, will work through that first, will close this off and re-raise a new one if issue persists.
