### ISSUE TITLE
correct way to install addons? cilium for exmaple

### ISSUE THREAD

**Issue by NahumLitvin** [aws-ia/terraform-aws-eks-blueprints#1656]
I"m trying to deploy cilium in my cluster

I wanted to Deploy Cilium using Gitops with a custom`values.yaml`

```hcl
enable_cilium = true
```

Deploy Cilium with custom `values.yaml`

```hcl
  # Optional Map value; pass cilium-values.yaml from consumer module
   cilium_helm_config = {
    name       = "cilium"                                               # (Required) Release name.
    repository = "https://helm.cilium.io/"                              # (Optional) Repository URL where to locate the requested chart.
    chart      = "cilium"                                               # (Required) Chart name to be installed.
    version    = "1.12.1"                                               # (Optional) Specify the exact chart version to install. If this is not specified, it defaults to the version set within default_helm_config: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/cilium/locals.tf
    values = [templatefile("${path.module}/cilium-values.yaml", {})]
  }
```

but at #1594  by @ [bryantbiggs](https://github.com/bryantbiggs)

the method in the official example was changed to deploying the chart directly to the cluster. with no argocd option?

what is the correct way to deploy?

I see that https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/tree/main
is missing cilium but also misses a way to deploy with argocd

edit: I now found https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114

does this mean argocd is no longer supported for managing plugins? is using terraform is the recommended approach?

**Comment by askulkarni2** [comment]
>does this mean argocd is no longer supported for managing plugins? is using terraform is the recommended approach?

Definitely not the case. On the contrary we think gitops is the right way to manage kubernetes resources. Based on customer feedback and our own experience with it, we have determined that our previous implementation of gitops for argocd in particular is limited in scope and does not provide an elegant, scalable approach. We are revamping this in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114 and hope to improve upon our previous design in the next iteration. Please provide any feedback you may have on that issue.

Also going forward as far as add-ons are concerned we will be limiting our support to a certain core set of add-ons. This is documented here https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/helm-release/.
