### ISSUE TITLE
ADOT Documentation not working

### ISSUE THREAD

**Issue by vazkarvishal** [aws-ia/terraform-aws-eks-blueprints#1658]
## Description
The ADOT documentation on the [website](https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/) is not working. Is this website maintained?

## Reproduction Code [Required]

Visit the link: [AWS Distro for OpenTelemetry](https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/aws-open-telemetry.md), it does not work and just returns icons.

## Expected behaviour

Clear documentation on how to use the add-on

## Actual behaviour

Broken page

### Terminal Output Screenshot(s)

<img width="1489" alt="image" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/13076513/fbdb21ab-e1bd-47e0-8986-f02f4c3c402c">

**Comment by askulkarni2** [comment]
The latest documentation is at https://aws-ia.github.io/terraform-aws-eks-blueprints/main/. If you want to see v5 documentation its at https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.32.1/. EKS Observability related documentation is at https://aws-observability.github.io/terraform-aws-observability-accelerator/.

**Comment by vazkarvishal** [comment]
> The latest documentation is at https://aws-ia.github.io/terraform-aws-eks-blueprints/main/. If you want to see v5 documentation its at https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.32.1/. EKS Observability related documentation is at https://aws-observability.github.io/terraform-aws-observability-accelerator/.

Can we retire/302 redirect from the [old website](https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/) then? It is quite misleading.
