### ISSUE TITLE
Update Argocd server add-on to support IPv6

### ISSUE THREAD

**Issue by sheetaljoshi** [aws-ia/terraform-aws-eks-blueprints#1671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Argocd server service deploys as Single stack on IPv6 server. Update the add-on to consider cluster IP family. When deploying on EKS IPv6 cluster, the add-on must add dual-stack annotation to the service spec.

**Comment by askulkarni2** [comment]
The add-ons module deploys a vanilla argocd helm chart and allows users to configure argocd however they see fit. But this would be a good example to show in the IPv6 cluster example.
