### ISSUE TITLE
Error - Experiment "module_variable_optional_attrs" is no longer available when upgrading to v4.32.1

### ISSUE THREAD

**Issue by kepuri** [aws-ia/terraform-aws-eks-blueprints#1682]
While currently updating the version of eks blueprints from v4.15 to latest version of v4.32.1, I am receiving the terraform error attached. If I downgrade to a TF version of 1.27, I receive three errors for unsupported arguments on "enable_classiclink" and "enable_classiclink_dns_support" in resource "aws_vpc" aswell as "enable_classiclink"  in resource "aws_default_vpc". 

Current TF Version: 1.3.4
Current Blueprint Version: 4.15
Desired Blueprint Version: 4.32.1

The link to the example being used: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/multi-tenancy-with-teams
[run-hh5bshYFKntXofyv-plan-log.txt](https://github.com/aws-ia/terraform-aws-eks-blueprints/files/12006142/run-hh5bshYFKntXofyv-plan-log.txt)
[run-pBj8HmiHWjKbvPsr-plan-log.txt](https://github.com/aws-ia/terraform-aws-eks-blueprints/files/12006154/run-pBj8HmiHWjKbvPsr-plan-log.txt)

**Comment by bryantbiggs** [comment]
The errors you are reporting are not related to EKS blueprints but to modules. Could you share the configuration you are using? 

For example:
>"enable_classiclink" and "enable_classiclink_dns_support" in resource "aws_vpc" aswell as "enable_classiclink" in resource "aws_default_vpc"

These errors are emitted when using v3.x of the VPC module. But the example you linked, it uses v5.0 of the VPC module which does not produce these errors https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/164bb84372b92a46862e2123af6252454f094d68/examples/multi-tenancy-with-teams/main.tf#L183

**Comment by kepuri** [comment]
Thanks Bryant, here is my main.tf file which has the link the modules with-in GitHub
[main.tf.zip](https://github.com/aws-ia/terraform-aws-eks-blueprints/files/12007505/main.tf.zip)

**Comment by bryantbiggs** [comment]
would you mind posting it in a gist or pastebin, not quite safe downloading and unpacking zip files

**Comment by bryantbiggs** [comment]
you can also post it directly in a comment here as well

**Comment by kepuri** [comment]
Hi Bryant, here is the main.tf which has the link to GitHub modules


provider "aws" {
  region = local.region
}

provider "kubernetes" {
  host                   = module.eks_blueprints.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_blueprints.eks_cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.this.token
}

provider "helm" {
  kubernetes {
    host                   = module.eks_blueprints.eks_cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks_blueprints.eks_cluster_certificate_authority_data)
    token                  = data.aws_eks_cluster_auth.this.token
  }
}

data "aws_eks_cluster_auth" "this" {
  name = module.eks_blueprints.eks_cluster_id
}

data "aws_availability_zones" "available" {}

locals {
  name   = var.cluster_name
  region = var.region_name

  vpc_cidr =   var.cidr_name
  azs      = slice(data.aws_availability_zones.available.names, 0, 3)
  aws-eks-administrators-wso = "arn:aws:iam::xxxxxxxx:role/xxxxxxxxxxxxxxxxxxxxxxxxx"

  tags = {
    Blueprint  = local.name
    Project    = "xxxxxxxx"
    Environment = "Stage"
    datadog = "monitored"    
  }
}

#---------------------------------------------------------------
# EKS Blueprints
#---------------------------------------------------------------

module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.32.1"

  cluster_name    = local.name
  cluster_version = var.cluster_version

  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets

  managed_node_groups = {
    mg_5 = {
      node_group_name = "managed-ondemand"
      instance_types  = ["m5.xlarge"]
      subnet_ids      = module.vpc.private_subnets

      desired_size = 5
      max_size     = 10
      min_size     = 3
    }
  }
  
  platform_teams = {
    admin-team-eksstg-app = {
      users = [
        "arn:aws:iam::xxxxxxxxrole/xxxxxxxxx"
      ]
    }
    dev-team-eksstg-app = {
      users = [
        "arn:aws:iam::xxxxxxxx:role/xxxxxxx"
      ]
    }
    readonly-team-eksstg-app = {
      users = [
        "arn:aws:iam::xxxxxxxx:role/xxxxxxxxxxxxxxxxxxxxxxxxxxx"
      ]
    }
  }

  tags = local.tags
}



module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.6.2"


  eks_cluster_id       = module.eks_blueprints.eks_cluster_id
  eks_cluster_endpoint = module.eks_blueprints.eks_cluster_endpoint
  eks_oidc_provider    = module.eks_blueprints.oidc_provider
  eks_cluster_version  = module.eks_blueprints.eks_cluster_version

  enable_amazon_eks_aws_ebs_csi_driver = true
  amazon_eks_aws_ebs_csi_driver_config = {
    resolve_conflicts = "OVERWRITE"
  }
}

#---------------------------------------------------------------
# Supporting Resources
#---------------------------------------------------------------

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0"

  name = local.name
  cidr = local.vpc_cidr

  azs             = local.azs
  public_subnets  = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k)]
  private_subnets = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 10)]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  # Manage so we can name
  manage_default_network_acl    = true
  default_network_acl_tags      = { Name = "${local.name}-default" }
  manage_default_route_table    = true
  default_route_table_tags      = { Name = "${local.name}-default" }
  manage_default_security_group = true
  default_security_group_tags   = { Name = "${local.name}-default" }

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/elb"              = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.name}" = "shared"
    "kubernetes.io/role/internal-elb"     = 1
  }

  tags = local.tags
}

**Comment by bryantbiggs** [comment]
You will want to update this:

```diff

module "eks_blueprints_kubernetes_addons" {
-  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.6.2"
+  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.32.1"
...
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
-  version = "~> 3.0"
+  version = "~> 5.0"
 ... 
}
```

**Comment by bryantbiggs** [comment]
after you make those changes then do:
```sh
terraform init -upgrade=true
terraform plan
```

And evaluate the plan output before attempting to apply

**Comment by kepuri** [comment]
Thanks Bryant, since I am using terraform cloud, as soon as I committed, It applied the plan which is successful and currently being applied now. Also I noticed the following, is this normal to change the session duration back to default value

     id                    = "eksstg-app-admin-team-eksstg-app-access"
      ~ max_session_duration  = 43200 -> 3600
        name                  = "eksstg-app-admin-team-eksstg-app-access"

**Comment by bryantbiggs** [comment]
which resource is that for?

**Comment by kepuri** [comment]
Thanks Bryant the cluster upgrade went fine but since the CSI driver was manually installed through UI, I had to comment out from the terraform script as it was failing eventhough the OVERWRITE was specified in the code.

**Comment by bryantbiggs** [comment]
good to hear. closing this out for now, but please feel free to reach out with any additional questions

**Comment by kepuri** [comment]
module.eks_blueprints_kubernetes_addons.module.aws_ebs_csi_driver[0].aws_eks_addon.aws_ebs_csi_driver[0]: Creation complete after 55s [id=eks-ops:aws-ebs-csi-driver]
╷
│ Warning: Argument is deprecated
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_ebs_csi_driver[0].aws_eks_addon.aws_ebs_csi_driver[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/aws-ebs-csi-driver/main.tf line 21, in resource "aws_eks_addon" "aws_ebs_csi_driver":
│   21:   resolve_conflicts        = try(var.addon_config.resolve_conflicts, "OVERWRITE")
│ 
│ The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial
│ resource creation. Use "resolve_conflicts_on_create" and/or
│ "resolve_conflicts_on_update" instead

**Comment by kepuri** [comment]
this is the error I am getting for the CSI driver

**Comment by bryantbiggs** [comment]
That is just a warning stating that the `resolve_conflicts` is deprecated and will be removed in v6.0 of the AWS Terraform provider

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2635
