### ISSUE TITLE
Broken link of the full example to deploy the EKS Cluster with Karpenter

### ISSUE THREAD

**Issue by hongbo-miao** [aws-ia/terraform-aws-eks-blueprints#1689]
At page https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.32.0/add-ons/karpenter/

The URL of full example to deploy the EKS Cluster with Karpenter inside: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/karpenter/locals.tf is broken.

![image](https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/3375461/9e33c27c-8fae-4350-a9a4-91c142cabe6a)

It would be great to fix, thanks! ☺️

**Comment by Hongbo-Miao** [comment]
Activate

**Comment by bryantbiggs** [comment]
this is a prior version of docs that won't receive updates - here is the link to the example https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/karpenter

**Comment by hongbo-miao** [comment]
I see, thanks @bryantbiggs ! ☺️
