### ISSUE TITLE
Karpenter example is not working as expected

### ISSUE THREAD

**Issue by subashprabanantham** [aws-ia/terraform-aws-eks-blueprints#1702]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here
I tried to run the Karpenter provisioning example from https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/karpenter

The terraform scripts ran successfully and I could see the Karpenter pods executed through Fargate as well. But when I try to scale the example deployment, the pods are still in "Pending" state. 

Is it something related to AWS user with which I am executing the commands or something else ?

#### Additional context

I execute the command using admin user, existing policy is as follows,
[AdministratorAccess]
[AmazonEKSClusterPolicy]

**Comment by bryantbiggs** [comment]
Can you please share a reproduction

**Comment by subashprabanantham** [comment]
Hi @bryantbiggs,

I cloned the repo and executed `terraform apply` within examples/karpenter folder.

Once I execute the command, the terraform successfully provisioned EKS cluster names `karpenter` in us-west-2. 

When I checked the `eks-node-viewer`, I am able to see fargate managed nodes are created for `kube-system` and `karpenter` namespace as expected.

<img width="1004" alt="Screenshot 2023-07-29 at 18 30 15" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/7386167/be0d8dd2-5ec5-40fd-adba-ab4faa83d893">

Deployments:
<img width="460" alt="Screenshot 2023-07-29 at 18 31 08" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/7386167/a45e50bf-6dbd-49ae-a411-e4c06f3acf3f">

Pods:
<img width="545" alt="Screenshot 2023-07-29 at 18 30 56" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/7386167/80b73170-5f4f-4074-ab7e-df2ca5c815c9">

I could also see, `inflate` deployment is created with 0 pods as expected.

Now, I tried scaling the instance as below:

```
kubectl scale deployment/inflate --replicas=2

deployment.apps/inflate scaled
```

But now when I look at the pods, the state shows as `pending`. 

<img width="555" alt="Screenshot 2023-07-29 at 18 42 14" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/7386167/c157c363-3479-4a1c-9144-873c2cf639e7">

Node viewer:

<img width="1007" alt="Screenshot 2023-07-29 at 18 45 20" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/7386167/3133c909-de4a-40ad-a8e4-f3cd377a19cd">



-----

So was trying to understand how this works ?
- Does the deployment works only if deployed under `karpenter` namespace or any Fargate managed namespace ?

**Comment by subashprabanantham** [comment]
I tried to quickly check on the question, 

> Does the deployment works only if deployed under karpenter namespace or any Fargate managed namespace ?

I deployed the karpenter example deployment under `karpenter` namespace. It worked fine.
<img width="1006" alt="Screenshot 2023-07-29 at 18 51 14" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/7386167/91dd8b7a-8158-4d8e-85c2-3d41c42ffded">

<img width="536" alt="Screenshot 2023-07-29 at 18 51 07" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/7386167/789d4b3b-d0dd-494f-8ca4-cdcdd437fd33">


If so then, is it correct to say that in this setup (Fargate enabled) - every add-ons and workloads should be managed by `Fargate` to use `Karpenter` ?

or using mix of Fargate (for controllers) and eks managed nodes (for workloads) is feasible ?

**Comment by bryantbiggs** [comment]
I'm not sure I quite follow - you can run workloads on Fargate or with Karpenter; it all just depends on the configuration, the supported features, and the desired end result. I'm going to close this for now but please feel free to open a new issue with a reproduction if still encountering issues
