### ISSUE TITLE
[4.32.1] terraform init fails with subdir "modules/irsa" not found

### ISSUE THREAD

**Issue by barlevalon** [aws-ia/terraform-aws-eks-blueprints#1707]
## Description

It seems the [latest removal of modules](https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/a1de62c0496c6149d67b817ead6519823948d645) broke 4.32.1.
As far as I can tell, `helm-addon` depends on `modules/irsa` from `main`.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 4.32.1

- Terraform v1.5.4
on darwin_arm64
  + provider registry.terraform.io/gavinbunney/kubectl v1.14.0
  + provider registry.terraform.io/hashicorp/aws v4.67.0
  + provider registry.terraform.io/hashicorp/cloudinit v2.3.2
  + provider registry.terraform.io/hashicorp/helm v2.9.0
  + provider registry.terraform.io/hashicorp/kubernetes v2.20.0
  + provider registry.terraform.io/hashicorp/local v2.4.0
  + provider registry.terraform.io/hashicorp/null v3.2.1
  + provider registry.terraform.io/hashicorp/random v3.5.1
  + provider registry.terraform.io/hashicorp/time v0.9.1
  + provider registry.terraform.io/hashicorp/tls v4.0.4
  + provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

Using the addons module like this:
```hcl
module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.32.1"
  # ...
}
```

`terraform init`

## Actual behaviour
```
│ Error: Failed to expand subdir globs
│ 
│ subdir "modules/irsa" not found
```

**Comment by miwita** [comment]
github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.27.0

Some issue here, Failed to dowload

**Comment by barlevalon** [comment]
My bad. Turns out I was referencing the module source in another place in the code without a ref param. 🤦
