### ISSUE TITLE
Is there any reason why the eks-cluster-with-new-vpc example was removed in v4.25.0?

### ISSUE THREAD

**Issue by cer** [aws-ia/terraform-aws-eks-blueprints#1709]
IMHO It was a really simple example of a non-fargate cluster. Just wondering?

**Comment by bryantbiggs** [comment]
the primary reason was that all of our examples provide configurations for creating both a cluster and a VPC so it was redundant. 

Is there a particular pattern or solution that you are looking for?

**Comment by cer** [comment]
I'm putting together some training materials about how to deploy microservices on EKS.
`eksctl create cluster` is the simplest approach.
But I'd prefer to use an IaC/Terraform-based setup.
I want to point students at a simple, minimal example of a non-Fargate EKS cluster that they can build upon.

**Comment by bryantbiggs** [comment]
the terraform equivalent would be something like:

```hcl
module "eks_al2" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.15"

  cluster_name    = "example"
  cluster_version = "1.27"

  # EKS Addons
  cluster_addons = {
    coredns    = {}
    kube-proxy = {}
    vpc-cni    = {}
  }

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  eks_managed_node_groups = {
    al2 = {
      instance_types = ["m6i.large"]

      min_size     = 1
      max_size     = 5
      desired_size = 2
    }
  }
}
```

**Comment by cer** [comment]
Sure. But sadly, the examples do an excellent job of hiding the potential simplicity. 😀
