### ISSUE TITLE
How to update modules/kubernetes-addons/<addon-name>/ content

### ISSUE THREAD

**Issue by manuelbcd** [aws-ia/terraform-aws-eks-blueprints#1713]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Hi, I updated [Sysdig addon](https://github.com/sysdiglabs/terraform-eksblueprints-sysdig-addon) with some new features and artifact versions, also changed it to point to source = "aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons/helm-addon?ref=v4.32.1"... but the addon is installing the older content **as if I never updated it**. 

The reason is that the terraform-aws-eks-blueprints [release](https://github.com/aws-ia/terraform-aws-eks-blueprints/releases/tag/v4.32.1) contains and old version of Sysdig addon... and since the /modules/ folder was removed from your repo, I'm unable to update it. 

To be more clear, I need to update "modules/kubernetes-addons" folders from the release. How can I update those files to unblock our blueprints?

thanks

FYI @bryantbiggs

**Comment by bryantbiggs** [comment]
Could you share a reproduction that demonstrates the issue?

**Comment by manuelbcd** [comment]
sure, it is quite easy to reproduce (and it is making me having a hard time until I understood the root problem)

1. Pull sysdig-addon project https://github.com/sysdiglabs/terraform-eksblueprints-sysdig-addon
    (please note that locals.tf points to version **"1.17.0"** of sysdig helm chart
2. Go to any of the bluerpints i.e. bluerpints/getting-started  and test it `terraform init` `terraform apply --auto-approve`
3. After 15-20 mins you will have an EKS cluster provisioned, but the installation corresponds to sysdig helm **"1.5.71"** which is older.

The reason is simple. Sysdig-addons point to "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons/helm-addon?ref=v4.32.1" and can get those modules from the [releases 4.32.1](https://github.com/aws-ia/terraform-aws-eks-blueprints/releases/tag/v4.32.1) which is there but not in your repository (as "modules/" folder was removed)...  Long story short: terraform-aws-eks-blueprints is forcing to use an older version of the addon

Please open terraform-aws-eks-blueprints release 4.32.1 and unzip it, go to modules/kubernetes-addons/sysdig and you will notice that this script is older that ours from our original repo

Does it make sense to you?

**Comment by bryantbiggs** [comment]
you don't need to update anything here - you just need to remove the use of v4 EKS blueprints from your module https://github.com/sysdiglabs/terraform-eksblueprints-sysdig-addon/pull/57

**Comment by manuelbcd** [comment]
thanks for your support @bryantbiggs, I appreciate your PR

I have tested your version and it is also provisioning a cluster with older agents (old helm chart) ignoring the one defined in the blueprint. Any idea on where it is taking this version if it does not come from this repo?

**Comment by bryantbiggs** [comment]
since this is a standard helm release, I would say its down to the chart and its values. Have you tried doing a simple `helm install ...` and checking the versions?

**Comment by manuelbcd** [comment]
Yes, this standard helm is doing the same... it is installing a very old version of Sysdig helm chart. 

To your question, yes I tried to uninstall the blueprint helm chart, install it manually... and it works like a charm, showing latest versions. I tested it also using an AWS instance terminal to make sure there is not any chance to being affected by any caching mechanism

Do you understand why I'm almost sure that here is any kind of external dependency? And the only location where I saw an older version mentioned is in your zip release under /modules/kubernetes-addons/sysdig

**Comment by bryantbiggs** [comment]
Cloning the project with the recent changes and running `terraform init` show there are no traces of EKS Blueprints in the project 

```json
{
  "Modules": [
    {
      "Key": "eks.fargate_profile",
      "Source": "./modules/fargate-profile",
      "Dir": ".terraform/modules/eks/modules/fargate-profile"
    },
    {
      "Key": "eks.self_managed_node_group.user_data",
      "Source": "../_user_data",
      "Dir": ".terraform/modules/eks/modules/_user_data"
    },
    {
      "Key": "sysdig_addon",
      "Source": "../..",
      "Dir": "../.."
    },
    {
      "Key": "",
      "Source": "",
      "Dir": "."
    },
    {
      "Key": "eks",
      "Source": "registry.terraform.io/terraform-aws-modules/eks/aws",
      "Version": "19.15.4",
      "Dir": ".terraform/modules/eks"
    },
    {
      "Key": "eks.eks_managed_node_group.user_data",
      "Source": "../_user_data",
      "Dir": ".terraform/modules/eks/modules/_user_data"
    },
    {
      "Key": "vpc",
      "Source": "registry.terraform.io/terraform-aws-modules/vpc/aws",
      "Version": "5.1.1",
      "Dir": ".terraform/modules/vpc"
    },
    {
      "Key": "eks.eks_managed_node_group",
      "Source": "./modules/eks-managed-node-group",
      "Dir": ".terraform/modules/eks/modules/eks-managed-node-group"
    },
    {
      "Key": "eks.kms",
      "Source": "registry.terraform.io/terraform-aws-modules/kms/aws",
      "Version": "1.1.0",
      "Dir": ".terraform/modules/eks.kms"
    },
    {
      "Key": "eks.self_managed_node_group",
      "Source": "./modules/self-managed-node-group",
      "Dir": ".terraform/modules/eks/modules/self-managed-node-group"
    }
  ]
}
```

So there is no dependency on EKS Blueprints in its current form

**Comment by manuelbcd** [comment]
ok, let me try it again with high verbosity, I will analyze logs carefully and get back to you
do you mind keeping the issue open for a while?
