### ISSUE TITLE
Error: subdir "modules/kubernetes-addons/helm-addon" not found

### ISSUE THREAD

**Issue by koosungmo** [aws-ia/terraform-aws-eks-blueprints#1715]
I use v4.28.0.
I ran terraform init today.
It gave an error.

Please help me

Message: Error: subdir "modules/kubernetes-addons/helm-addon" not found

**Comment by bryantbiggs** [comment]
you need to use version 4.32.1 to stay on v4.x

**Comment by nitrocode** [comment]
@bryantbiggs could this issue be pinned and could this message be documented in the README.md ? A lot of people currently use the blue prints for the helm addons and people may not be ready to migrate just yet so this error may catch people off guard

**Comment by Laxman-SM** [comment]
@nitrocode , I face the same issue and updated helm provider version and issue resolve for me.

 helm = {
      version = ">= 2.10.1"
      source  = "hashicorp/helm"
    }
