### ISSUE TITLE
Config-driven definion for the EKS blueprint Terraform

### ISSUE THREAD

**Issue by haofeif** [aws-ia/terraform-aws-eks-blueprints#1716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

The current way of deploying EKS cluster via bluerpint has to have the terraform knowledge. From specifying the subnets of the eks, specifying the node group size and instance type, and fargate profile. 

However, for some of the users, particularly in a self-service fashion, all of these could be configuration like YAML or JSON. The users/application team who request for an EKS cluster only need to know what information to put in as a configuration, instead of knowing the details of the terraform code.

Therefore, we recommend providing examples/features that is config-driven via YAML/JSON to specify the configuration details of the EKS cluster without the need to know Terraform.

#### Describe the solution you would like

We would like to provide a way for the users input config as YAML/JSON to define the deployment instead of terraform code.

#### Describe alternatives you have considered
N/A

**Comment by bryantbiggs** [comment]
I don't know that this is appropriate for this project. This is EKS Blueprints for *Terraform, and there is EKS Blueprints for CDK - it sounds like you are talking about using something like a Kubernetes operator that understands YAML/JSON and can interpret what resources need to be created (i.e. - ACK, Crossplane, CAPI, etc.)

**Comment by nickgityu** [comment]
@bryantbiggs Basically, we are asking for a wrapper that can take user inputs of the cluster configuration as a json or yaml file. The user only needs to specify the wanted features (cluster config, addons, team, etc.) in the configuration file then an entire cluster can be created matching the user's specification in the configuration file. Of course behind the scene, the wrapper was feeding the configuration in the json/yaml file to the EKS Blueprint. This way, the user does not need to understand Terraform or CDK to be able to create EKS clusters. Part of a sample configuration file could be
{  
"eks_compute": {
    "nodegroups": {
      "managed": {
        "awsmanagednodegroup": {
          "desired_size": 3,
          "instance_types": ["m5.large"],
          "max_size": 6,
          "min_size": 3,
          "node_group_name": "aws-managed-ondemand",
          "subnet_ids": [
            "subnet-xxx",
            "subnet-xxx",
            "subnet-xxx"
          ]
        }
      },
      "self_managed": {}
    },
    "fargate_profiles": {}
  }
}

**Comment by bryantbiggs** [comment]
Since HCL started out life as a superset of JSON, if I remove the module declaration and source, isn't that what we have today?

```hcl
{
  cluster_name                   = local.name
  cluster_version                = "1.27"
  cluster_endpoint_public_access = true

  cluster_addons = {
    coredns    = {}
    kube-proxy = {}
    vpc-cni    = {}
  }

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  eks_managed_node_groups = {
    default = {
      instance_types = ["m5.large"]

      min_size     = 1
      max_size     = 5
      desired_size = 2
    }
  }

  tags = local.tags
}
```

**Comment by haofeif** [comment]
@bryantbiggs the current way is good. But think about the scenario, where you have a platform team managing the EKS platform and the module for every part of the EKS including cluster config, add on config, and some organization policies. And the platform team is hosting a configuration repo or a folder to store all tenants' configurations.  These configurations will be open for tenants' raising PR if they request a new cluster. And in the repo or folder there will be 50 to 100 tenants coming from different part of the organization. With the correct configurations, there will be CI/CD pipeline pre-setup to deploy the infrastructure for all these tenants without they setting up themselves.  Some of them may not know about any syntax of terraform. In that case, a YAML/JSON config file will be self explanatory, and also easy to manage. 



On the other side, the configuration may consist way more information that the example listed. It may include organization /application-team related tagging, multiple clusters/multiple addons, and multiple node group/fargate profile. The configuration itself could be 70-100 lines along. In that case a terraform-led code might be introducing higher operating risks.

**Comment by askulkarni2** [comment]
@haofeif I see your point but I do not see this being much different than what you can do with .tfvars file today. Platform teams can build the blueprint and dev teams can provide the .tfvars file. They do not need to know terraform just know what the inputs are (and what they mean).
