### ISSUE TITLE
Add Rabbit mq cluster operator as an add-on

### ISSUE THREAD

**Issue by neelaruban** [aws-ia/terraform-aws-eks-blueprints#1717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
The ability to install the rabbit mq cluster operator just by enabling it via the eks blueprint add-ons parameters. 

#### Describe the solution you would like
The solution should be able to opt in to install the rabbit mq cluster operator via eks blueprint add-on parameters. The solution should be able to create the IRSA with the required IAM policies for the operator to fulfil its functions.

**Comment by neelaruban** [comment]
Team, I believe I could start working on this feature request. Could you please assign the task to me?

**Comment by bryantbiggs** [comment]
What is the motivation for this?

**Comment by bryantbiggs** [comment]
Users should be able to deploy this operator today using the `helm_releases` argument https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/bd1df9c3ff3feab4c8ec5f704fb1acdab01b483f/tests/complete/main.tf#L189-L219

For now, I am going to close this issue - thank you!

**Comment by neelaruban** [comment]
@bryantbiggs  thanks for pointing this out , i didn't this way existed .
