### ISSUE TITLE
Would love examples in CDKTF!

### ISSUE THREAD

**Issue by corkupine** [aws-ia/terraform-aws-eks-blueprints#1724]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Examples take some massaging to use CDKTF

#### Describe the solution you would like

Would love to see examples in both HCL and CDKTF 

#### Describe alternatives you have considered

Pushing through dealing with the conversion of maps, lists, etc. 

#### Additional context

We're now standardizing on CDKTF, so having examples would help. I'll try to open a PR if I have time and the maintainers think it would be valuable.

**Comment by bryantbiggs** [comment]
thank you for the issue - however, this is not something that we are seeing demand for at this time. We can leave this issue open for now to see if there is additional feedback from the community
