### ISSUE TITLE
Windows Managed Node Group Support

### ISSUE THREAD

**Issue by McNinja** [aws-ia/terraform-aws-eks-blueprints#1729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
When passing a supported windows ami_type (listed below) the ability to provision windows managed node group via this terraform module.

```
WINDOWS_CORE_2019_x86_64
WINDOWS_FULL_2019_x86_64
WINDOWS_CORE_2022_x86_64
WINDOWS_FULL_2022_x86_64
```

Currently when using the `aws-ia/terraform-aws-eks-blueprints` the node group fails to create due to bad user data. It is currently passing linux user data and the node group will have the following error: 

```
code: Ec2LaunchTemplateInvalidConfiguration
message: User data was not a valid PowerShell format and could not be processed.
```

#### Describe the solution you would like

Something similar to how cloudposse has this implemented, using the amy_type to determine windows or linux workflow 

https://github.com/cloudposse/terraform-aws-eks-node-group/pull/139/files

#### Describe alternatives you have considered

Looking at writing some logic into our terraform code to use the cloudposse module when a windows ami_type is passed. As we use the `aws-ia/terraform-aws-eks-blueprints` else where for all of our other AWS EKS code.

**Comment by bryantbiggs** [comment]
this is supported today, you just have to use the default EKS launch template https://github.com/clowdhaus/eks-reference-architecture/blob/main/windows/eks.tf

**Comment by bryantbiggs** [comment]
closing since this is supported today
