### ISSUE TITLE
Error: creating Secrets Manager Secret: name is already scheduled for deletion

### ISSUE THREAD

**Issue by 9474757** [aws-ia/terraform-aws-eks-blueprints#1733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Fix problem "Error: creating Secrets Manager Secret: because a secret with this name is already scheduled for deletion"

#### Describe the solution you would like

I got error from examples.
Error: creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.
<img width="1180" alt="Снимок экрана 2023-08-16 в 14 02 30" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/28390805/0d27f6a4-e793-4282-a8f9-35b36433b00f">

#### Describe alternatives you have considered
How about use this code for resource "aws_secretsmanager_secret" "arogcd"? 

resource "random_password" "arogcd_secret_id" {
  length  = 6
  special = false
}

resource "aws_secretsmanager_secret" "arogcd" {
  name = "${local.name}-argocd-${random_password.arogcd_secret_id.result}"
}

**Comment by bryantbiggs** [comment]
this is normal behavior for secrets manager. you can forcefully remove it using `aws secretsmanager delete-secret --secret-id <SECRET> --force-delete-without-recovery`
