### ISSUE TITLE
"resolve_conflicts" Argument is deprecated in sub modules

### ISSUE THREAD

**Issue by 9474757** [aws-ia/terraform-aws-eks-blueprints#1736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

"resolve_conflicts" Argument is deprecated 

#### Describe the solution you would like

"resolve_conflicts" Argument is deprecated, please to replace in all modules the option to >>
"resolve_conflicts_on_create" and/or "resolve_conflicts_on_update"

#### Describe alternatives you have considered

"resolve_conflicts" Argument is deprecated, please to replace in all modules the option to >>
"resolve_conflicts_on_create" and/or "resolve_conflicts_on_update"

#### Additional context

<img width="1256" alt="Снимок экрана 2023-08-18 в 00 53 50" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/28390805/3f82e06d-2442-4c7d-9e8b-d93fe86b5fb5">

**Comment by bryantbiggs** [comment]
thank you - its deprecated but its still valid functionality until the Terraform AWS provider v6.0 is released. at the next breaking change, these warnings will be resolved
