### ISSUE TITLE
The argument "name" is required, but no definition was found.

### ISSUE THREAD

**Issue by Bushra178** [aws-ia/terraform-aws-eks-blueprints#1743]
- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

 I am trying to create EKS module with terraform. I am getting cluster info with data attribute but i am getting the following error

Error: Missing required argument
│
│ with data.aws_eks_cluster.myapp-cluster,
│ on eks-cluster.tf line 9, in data “aws_eks_cluster” “myapp-cluster”:
│ 9: name = module.eks.cluster_id
│
│ The argument “name” is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│ with data.aws_eks_cluster_auth.myapp-cluster,
│ on eks-cluster.tf line 13, in data “aws_eks_cluster_auth” “myapp-cluster”:
│ 13: name = module.eks.cluster_id
│
│ The argument “name” is required, but no definition was found.

**I am using the following configuration**

provider "kubernetes" {
    #load_config_file = "false"
    host = data.aws_eks_cluster.myapp-cluster.endpoint
    token = data.aws_eks_cluster_auth.myapp-cluster.token
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.myapp-cluster.certificate_authority.0.data)
}

data "aws_eks_cluster" "myapp-cluster"{
    name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "myapp-cluster" {
    name = module.eks.cluster_id
}   

output "cc-name" {
    value = module.eks.cluster_id
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.16.0"

  cluster_name = "myapp-eks-cluster"
  cluster_version = "1.27"
  
  subnet_ids = module.myapp-vpc.private_subnets
  vpc_id = module.myapp-vpc.vpc_id

  tags = {
    environment = "development"
    application = "myapp"
  }

  eks_managed_node_groups = [
    {
        instance_type = "t2.small"
        name = "worker-group-1"
        asg_desired_capacity = 2
    },
    {
        instance_type = "t2.medium"
        name = "worker-group-2"
        asg_desired_capacity = 1
    },
  ]
}

**Comment by bryantbiggs** [comment]
anywhere you use `module.eks.cluster_id`, it should be `module.eks.cluster_name`
