### ISSUE TITLE
Add example for Amazon VPC CNI Network Policy feature

### ISSUE THREAD

**Issue by valentinwidmer** [aws-ia/terraform-aws-eks-blueprints#1747]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Amazon announced native Network Policy support through Amazon VPC CNI (https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-vpc-cni-kubernetes-networkpolicy-enforcement/). Adding an example how to use Network Policies with Amazon VPC CNI helps user to get started.

#### Describe the solution you would like

Add TF code (inside examples folder) how to use Network Policies with Amazon VPC CNI

#### Describe alternatives you have considered

N/A

**Comment by csantanapr** [comment]
Thank you for working on this @valentinwidmer 👍

**Comment by alanwu4321** [comment]
are there examples or PRs? If not I could help contribute

**Comment by valentinwidmer** [comment]
https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1781

**Comment by valentinwidmer** [comment]
> are there examples or PRs? If not I could help contribute
> 
> my own setting
> 
> ```yaml
>     vpc-cni = {
>       configuration_values = jsonencode({
>         enableNetworkPolicy = "true",
>         init = {
>           env = {
>             DISABLE_TCP_EARLY_DEMUX = "true"
>           }
>         }
>         env = {
>           ENABLE_POD_ENI                    = "true",
>           POD_SECURITY_GROUP_ENFORCING_MODE = "standard",
>           AWS_VPC_K8S_CNI_EXTERNALSNAT      = "true"
>       } })
>     }
> ```

Hi @alanwu4321 . Thanks a lot for your contribution. I've already raise a PR https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1781
