### ISSUE TITLE
What is the default aws load balancer controller?

### ISSUE THREAD

**Issue by tekno45** [aws-ia/terraform-aws-eks-blueprints#1752]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I am trying to run argocd from an internal loadbalancer but my annotations don't seem to be being respected coming from argocd-values.yml

Im not sure what is configureing the AWS load balancers by default.

I dont have aws loadbalancer controller turned on, or crossplane. 

With all defaults what controller for external load balancers is installed?
and How do i configure it for internal load balancer? Specifically for argocd

#### Additional context

The aws load balancer controller is off by deafult.
https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/addons/aws-load-balancer-controller/

So its unclear what is interacting with AWS for the load balancer of services.

**Comment by askulkarni2** [comment]
Hi @tekno45, this is documented in the ArgoCD [documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode). You will need to enable the aws-load-balancer-controller addon. Follow the annotations documented [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/) to configure them as you see fit.

**Comment by tekno45** [comment]
But by default it is creating a load balancer. What load balancer controller is there already?
