### ISSUE TITLE
Deprecated argument for resolve_conflicts attribute

### ISSUE THREAD

**Issue by jebbens** [aws-ia/terraform-aws-eks-blueprints#1779]
## Description

When deploying a stack from this repo as part of the AWS Observability Accelerator for Terraform, I get the following message from Terraform: 

Warning: Argument is deprecated
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_coredns[0].aws_eks_addon.coredns[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/aws-coredns/main.tf line 18, in resource "aws_eks_addon" "coredns":
│   18:   resolve_conflicts        = try(var.addon_config.resolve_conflicts, "OVERWRITE")
│ 
│ The "resolve_conflicts" attribute can't be set to "PRESERVE" on initial resource creation. Use "resolve_conflicts_on_create" and/or "resolve_conflicts_on_update" instead
│ 
│ (and 3 more similar warnings elsewhere)

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

v1.5.6
- Provider version(s):

├── provider[registry.terraform.io/hashicorp/aws] >= 5.0.0
├── provider[registry.terraform.io/hashicorp/kubernetes] >= 2.20.0
├── provider[registry.terraform.io/gavinbunney/kubectl] >= 1.14.0
├── provider[registry.terraform.io/hashicorp/helm] >= 2.10.0

## Reproduction Code [Required]

  cd ~/repos/github/terraform-aws-observability-accelerator/examples/eks-cluster-with-vpc
  export TF_VAR_aws_region=us-west-2
  export TF_VAR_cluster_name=demo
  terraform init
  terraform apply

git clone https://github.com/aws-observability/terraform-aws-observability-accelerator.git

## Expected behaviour

Stack deploys with no warning messages

## Actual behaviour

Stack deploys with warning message

## Additional context

See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2635 for similar issue

**Comment by bryantbiggs** [comment]
This is expected - it is a warning coming from the Terraform provider that a deprecated argument is in use

**Comment by bryantbiggs** [comment]
we will track this in the EKS module under https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2635
