### ISSUE TITLE
False alerts in "terraform plan" output

### ISSUE THREAD

**Issue by oferca** [aws-ia/terraform-aws-eks-blueprints#1784]
## Description

While no policy is actually being modified, "terraform plan" output is cluttered with false and unnecessary change alerts such as:

``` 
#module.eks.module.eks_blueprints.module.aws_eks_managed_node_groups["ng-1"].aws_iam_role.managed_ng[0] will be updated in-place
  ~ resource "aws_iam_role" "managed_ng" {
      ~ assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRole"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "ec2.amazonaws.com"
                        }
                      - Sid       = "EKSWorkerAssumeRole"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        id                    = "123"
        name                  = "ng name"
        tags                  = {
            "Blueprint"  = "staging"
            "GithubRepo" = "github.com/aws-ia/terraform-aws-eks-blueprints"
        }
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

This is probably because data source "data.aws_iam_policy_document.managed_ng_assume_role_policy" is evaluated every plan and a new hash is placed.

Proposed change ( tested and works ) :
https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1783/files

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
4.32.1
- Terraform version:
Terraform v1.5.7
on darwin_arm64
- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
## Reproduction Code [Required]

Any "terraform plan" as eks blueprints creates multiple managed nodegroups

## Expected behaviour
Nothing reported in "terraform plan" log
## Actual behaviour
"terraform plan" output is cluttered with alerts: 

```module.eks_blueprints.module.aws_eks_managed_node_groups["nodegroup-1"].aws_iam_role.managed_ng[0] will be updated in-place...
module.eks_blueprints.module.aws_eks_managed_node_groups["nodegroup-2"].aws_iam_role.managed_ng[0] will be updated in-place...
module.eks_blueprints.module.aws_eks_managed_node_groups["nodegroup-3"].aws_iam_role.managed_ng[0] will be updated in-place...```

**Comment by askulkarni2** [comment]
We are not planning on making any further changes on the v4. Recommend you switch to v5 and use the [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) for all the cluster creation needs.
