### ISSUE TITLE
Karpenter pattern: failed to call webhook

### ISSUE THREAD

**Issue by mjlbach** [aws-ia/terraform-aws-eks-blueprints#1786]
## Description

Applying the [karpenter pattern](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/karpenter) results in the following error:

```
kubectl_manifest.karpenter_provisioner: Creation complete after 0s [id=/apis/karpenter.sh/v1alpha5/provisioners/default]
╷
│ Error: default failed to run apply: error when creating "/tmp/886475097kubectl_manifest.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:8443/?timeout=10s": no endpoints available for service "karpenter"
│
│   with kubectl_manifest.karpenter_node_template,
│   on main.tf line 227, in resource "kubectl_manifest" "karpenter_node_template":
│  227: resource "kubectl_manifest" "karpenter_node_template" {
│
╵
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
```
Terraform v1.6.0 on linux_amd64
```
- Provider version(s):
```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.20.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

* Clone the [karpenter pattern](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/karpenter)

* Clone the [karpenter pattern](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/karpenter)
* `terraform init`
* `terraform apply`
* 
## Expected behaviour

Karpenter is succesfully set up

## Actual behaviour

Karpenter is not set up.

## Additional context

Seems related to https://github.com/aws/karpenter/issues/4660

**Comment by pete911** [comment]
@mjlbach looks like security group for nodes does not allow controller plane security group on port 8443. You could check flow logs (if you have them enabled) and use log insights query:
```
fields @timestamp, instanceId, interfaceId, srcAddr, srcPort, dstAddr, dstPort
| filter (action="REJECT")
| sort @timestamp desc
| limit 50
```
check where the port 8443 is rejected, search by srcAddr in network interfaces (EC2 -> network interfaces). If this is the case, pls post control plane outbound rules and node inbound rules. I will try to check where it is misconfigured.

**Comment by mjlbach** [comment]
Hi @pete911! Thanks for suggestions. I don't see anything in flow logs for the two VPCs created by the template. Where would I check the control plane outbound rules or enable flow logs? Is that a modification I would have to make to the terraform template?

**Comment by pete911** [comment]
Hi @mjlbach, I just run the pattern (I kept everything default) and it completed successfully. I didn't realise that this pattern uses fargate, there is no need to play with security groups.
Could you try to run terraform destroy and then apply?

**Comment by mjlbach** [comment]
Hi Peter,

Yes, I just destroyed and reapplied. I ran into the same issue. For some reason, it worked the first time I tried in a new region (us-west-2) but not after I terraform destroy && terraform apply it.

Karpenter seems to be up but the terraform template still has the issue in my original post.

 ~/Repositories/dream/infra/github-ci  main ?4     ⎈ github-ci ***@***.***

❯ kubectl get po -A -l app.kubernetes.io/name=karpenter ( http://app.kubernetes.io/name=karpenter )

NAMESPACE   NAME                         READY   STATUS    RESTARTS   AGE

karpenter   karpenter-XXXXXXX-mxm9k   1/1     Running   0          11m

karpenter   karpenter-XXXXXXX-qdtkk   1/1     Running   0          11m

 ~/Repositories/dream/infra/github-ci  main ?4     ⎈ github-ci ***@***.***

❯ kubectl get ep -A -l app.kubernetes.io/name=karpenter ( http://app.kubernetes.io/name=karpenter )

NAMESPACE   NAME        ENDPOINTS                                                        AGE

karpenter   karpenter 10.0.XX.XXX:8000 ( http://10.0.xx.xxx:8000/ ) ,10.0.XX.XXXX:8000,10.0.XXXXX:8443 + 1 more...   11m

Sent via Superhuman ( ***@***.*** )
