### ISSUE TITLE
The NLB created by `istio-ingress` service does not have cross-zone loadbalancing enabled as desired

### ISSUE THREAD

**Issue by vchintal** [aws-ia/terraform-aws-eks-blueprints#1793]
## Description

In the `istio` pattern, the service for the `istio-ingress` (Helm Chart) is provided desired annotation on this [line](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/istio/main.tf#L170) which enables the cross-zone load balancing on the NLB created as a result. However, the processing of such AWS specific annotations is contingent upon the AWS Loadbalancer Controller being deployed and ready prior to any service of Loadbalancer type deployed in the cluster. 

The way the Terraform code is structured in `main.tf` the order of creation of AWS Loadbalancer Controller and the `istio-ingress` Helm chart deployment is not deterministic. And because of that
1. The AWS Loadbalancer Controller is deployed after the `istio-ingress` service deployment and
2. The annotations provided on the `istio-ingress` service is not picked up, processed and hence the cross-zone loadbalancing is not enabled as desired.

## Reproduction Code [Required]

1. Follow the deployment steps in the `istio` pattern and if possible capture the deployment order of AWS Loadbalancer Controller and `istio-ingress` Helm chart
2. Go to the EC2 Console → Load Balancers →  Choose the one created by `istio-ingress` service → click on Attributes tab  and verify if the cross-zone loadbalancing is enabled

## Expected behaviour

Cross-zone loadbalancing is **enabled**

## Actual behaviour

Cross-zone loadbalancing is **disabled**

### Terminal Output Screenshot(s)

<img width="2489" alt="image" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/4762573/1627d829-9808-4eee-9ea9-d62747751a44">

<img width="2559" alt="image" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/4762573/fa3c2fca-beac-48e1-b920-38ebaed583d9">

**Comment by vchintal** [comment]
+ @bryantbiggs

**Comment by bryantbiggs** [comment]
since we have multi-language blueprints, how would we solve this for alternative deployment methods? Meaning - if I use a GitOps controller, how do I resolve this issue?

**Comment by vchintal** [comment]
I do not have a personal recommendation or suggestion here but I would like to ask how other patterns are dealing with a similar requirement?

Setting this specific usecase aside, it not uncommon for an operator/controller (with CRDs) and a dependent application (with CRs) to be both packaged as Helm charts. How will we handle cases when they both need to deployed in a specific order?

I reached out to my ex-Red Hat colleague Christian Hernandez who is the author of this post https://codefresh.io/blog/argo-cd-application-dependencies/ and he says _"App of Apps pattern is something most people do"_ and he offered me sequence of steps:

1. [App of Apps + Sync waves](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/)
2. [Sync waves ](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-do-i-configure-waves)within each app
3. enable [retries](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L202-L207) for each app (because the first time trying to apply something will probably fail)
4. I do [SkipDryRunOnMissingResource=true](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types) annotation anytime I'm doing anything that needs a CRD. This annotation (along with the retries) will make Argo CD keep trying to apply the manifests until it's successful
