### ISSUE TITLE
Deploy documentation incorrect for `privatelink-access` pattern

### ISSUE THREAD

**Issue by vchintal** [aws-ia/terraform-aws-eks-blueprints#1797]
## Description

The [Deploy](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/privatelink-access#deploy) steps for `privatelink-access` pattern is:
* incorrect
* not the right set of steps 
* and if/when used fails with errors

## Reproduction Code [Required]

Follow the suggest steps in the link provided to Deploy the pattern

## Expected behavior

The sequence of terraform steps complete successfully with no errors.

## Actual behavior

The sequence of terraform steps fail with errors.

### Terminal Output Screenshot(s)

<img width="2560" alt="image" src="https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/4762573/f305e980-dd8c-4ba7-a081-c455c83cbc99">

## Additional context

As per the [orginial set of instructions](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/145e6e2bbccfbac5474ca0e6f027e6c7e83a150a/examples/privatelink-access/README.md) per author(s)  the instructions for deploy were:

```sh 
terraform init
terraform apply -target=module.eventbridge -target=module.nlb
terraform apply 
```
> [!Note] 
> The above mentioned original instructions still work

These instructions were lost in the effort to consolidate Deploy/Destroy instructions across all patterns to a single page of common instructions.

**Comment by bryantbiggs** [comment]
resolved in #1806
