### ISSUE TITLE
[PrivateLink Access] Tracking issue to update this pattern when cluster access with EKS API is released

### ISSUE THREAD

**Issue by aaroniscode** [aws-ia/terraform-aws-eks-blueprints#1816]
## Description

The [PrivateLink Access pattern](https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/privatelink-access/) initially creates the EKS cluster with a public endpoint. This is done to allow Terraform to add an IAM role to the `aws-auth` ConfigMap. The cluster endpoint is then manually set to private.

This issue is a reminder to update the pattern when the [Cluster Access roadmap feature](https://github.com/aws/containers-roadmap/issues/185) is released.  At this point in time, it's labeled as "Coming Soon"

The updated pattern will initially set the cluster endpoint as private and use new EKS API capabilities to add the IAM role acces to the Kubernetes cluster.

**Comment by aaroniscode** [comment]
[IAM Cluster Access Management](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-eks-controls-iam-cluster-access-management/) has been released.

Will work on updating the blueprint shortly. cc: @vchintal @praseedasathaye

**Comment by bryantbiggs** [comment]
we'll be able to update once https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2858 lands

**Comment by vchintal** [comment]
Working on it this week.
