### ISSUE TITLE
Add FluxCD GitOps patterns

### ISSUE THREAD

**Issue by csantanapr** [aws-ia/terraform-aws-eks-blueprints#1829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Provide users with patterns that show how to use fluxcd with EKS to manage addons. 

#### Describe the solution you would like

We currently have a few patterns with argocd, showing a getting started and multi-cluster patterns. We would like to offer similar patterns for fluxcd
- https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/gitops-getting-started-argocd/
- https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/gitops-multi-cluster-hub-spoke-argocd/
- 

#### Describe alternatives you have considered

N/A

**Comment by ebcarty** [comment]
Any chance this has been done or can be revived?
