### ISSUE TITLE
external-secrets pattern with error Status: SecretSyncedError

### ISSUE THREAD

**Issue by estanqueiroa** [aws-ia/terraform-aws-eks-blueprints#1833]
I have deployed external-secrets patterns successfully AS IS and I´m getting this status error "SecretSyncedError" during validation steps, please let me know if that´s expected behavior.

kubectl get externalsecrets -n external-secrets

NAME                                                            AGE    STATUS                  CAPABILITIES   READYclustersecretstore.external-secrets.io/cluster-secretstore-sm   5d2h   InvalidProviderConfig                  False
NAME                                              STORE                    REFRESH INTERVAL   STATUS              READY
externalsecret.external-secrets.io/eks-mvp-0-ps   secretstore-ps           1h                 SecretSyncedError   False
externalsecret.external-secrets.io/eks-mvp-0-sm   cluster-secretstore-sm   1h                 SecretSyncedError   False

NAME                                             AGE    STATUS                  CAPABILITIES   READY
secretstore.external-secrets.io/secretstore-ps   5d2h   InvalidProviderConfig                  False 

Everything looks good here:

kubectl get secrets -n external-secrets
NAME                                     TYPE                 DATA   AGE
external-secrets-webhook                 Opaque               4      5d2h
sh.helm.release.v1.external-secrets.v1   helm.sh/release.v1   1      5d2h

![error](https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/50240388/8ee7288c-de93-4532-86aa-d0f94b286d05)

**Comment by estanqueiroa** [comment]
any updates? thank you

**Comment by iancharles** [comment]
I am also seeing this error. Are there any updates?
