### ISSUE TITLE
The cluster's authentication mode must be set to one of [API, API_AND_CONFIG_MAP] to perform this operation.

### ISSUE THREAD

**Issue by dantot** [aws-ia/terraform-aws-eks-blueprints#1877]
I encountered an issue where the authentication_mode parameter is missing in version 18.29.1 of the terraform-aws-modules/eks/aws module, which is required for the aws_eks_access_entry module. Consequently, this results in the following error:

Error: creating EKS Access Entry (cluster:arn:aws:iam::339712812380:role/Karpenter-cluster-20240207214924404600000005): operation error EKS: CreateAccessEntry, https response error StatusCode: 400, RequestID: 4fa53b84-263c-40f9-97b1-ea8871cc8652, InvalidRequestException: The cluster's authentication mode must be set to one of [API, API_AND_CONFIG_MAP] to perform this operation.

I removed the local .terraform directory (only applicable if state is stored remotely): rm -rf .terraform/
I re-initialized the project root to pull down modules: terraform init
i re-attempted the terraform plan or terraform apply commands to check if the issue persists.

Terraform v1.6.6
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.35.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.25.2
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

```
module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.32.1"

  cluster_name    = "${var.project}-cluster"
  cluster_version = "1.29"
  enable_irsa     = true

  map_roles = [
    {
      rolearn  = module.karpenter.iam_role_arn
      username = "system:node:{{EC2PrivateDNSName}}"
      groups = [
        "system:bootstrappers",
        "system:nodes",
      ]
    },
  ]

  vpc_id = module.vpc.vpc_id

  private_subnet_ids = module.vpc.private_subnets

  managed_node_groups = {
    role = {
      capacity_type   = "SPOT"
      node_group_name = "general"
      instance_types  = ["t3a.medium"]
      desired_size    = "1"
      max_size        = "3"
      min_size        = "1"
    }
  }
}
```

```
module "karpenter" {
  source  = "terraform-aws-modules/eks/aws//modules/karpenter"
  version = "20.2.0"

  cluster_name           = module.eks_blueprints.eks_cluster_id
  irsa_oidc_provider_arn = module.eks_blueprints.eks_oidc_provider_arn
  enable_irsa            = true
}

```
Expected behavior
I expected the authentication_mode parameter to be available with a default value in the terraform-aws-modules/eks/aws module, allowing the aws_eks_access_entry module to function properly without encountering the authentication mode error.

Actual behavior
The authentication_mode parameter is missing from version 18.29.1 of the terraform-aws-modules/eks/aws module, causing the aws_eks_access_entry module to fail with the authentication mode error described above.

![Screenshot_2024-02-08_00-11-01](https://github.com/aws-ia/terraform-aws-eks-blueprints/assets/6368442/e6a23e40-0136-4a0c-8dde-91846c123b77)

Additional context
I believe adding the authentication_mode parameter with a default value in the terraform-aws-eks-blueprint variables would resolve this issue. And or upgrade terraform-aws-modules/eks/aws 18.29.1 version.

```
variable "authentication_mode" {
  description = "The authentication mode for the cluster. Valid values are `CONFIG_MAP`, `API` or `API_AND_CONFIG_MAP`"
  type        = string
  default     = "API_AND_CONFIG_MAP"
}
```

**Comment by bryantbiggs** [comment]
I'm not sure how to answer this one - in short, `authentication_mode` is not supported in v18, or even v19, of the EKS module - it was only recently added in v20 of the EKS module. 

this is not going to be supported in the outdated v4.x of EKS Blueprints module since that version is no longer active
