### ISSUE TITLE
karpenter-mng - tolerations: is not defined in the schema and the schema does not allow additional properties

### ISSUE THREAD

**Issue by iocron** [aws-ia/terraform-aws-eks-blueprints#1963]
## Description
Using the pattern "karpenter-mng" (`terraform init... terraform apply -target="module.eks" -auto-approve`) results in: tolerations: is not defined in the schema and the schema does not allow additional properties

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Terraform version:
Terraform v1.8.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.53.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.13.2
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

Can be found at: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/karpenter-mng

I just followed the official getting-started steps: https://aws-ia.github.io/terraform-aws-eks-blueprints/getting-started/

```
terraform init # works
terraform apply -target="module.vpc" -auto-approve # works
terraform apply -target="module.eks" -auto-approve # FAILS with ERROR message provided!
```

```
Error: creating EKS Add-On (ex-karpenter-mng:coredns): operation error EKS: CreateAddon, https response error StatusCode: 400, RequestID: 193a2e4b-b99b-43e3-b025-a8003e08882b, InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.tolerations: is not defined in the schema and the schema does not allow additional properties]
│
│   with module.eks.aws_eks_addon.this["coredns"],
│   on .terraform/modules/eks/main.tf line 498, in resource "aws_eks_addon" "this":
│  498: resource "aws_eks_addon" "this" {
```

## Expected behavior
module.eks should work as described from the docs.

## Actual behavior
The tolerations schema error happened.

**Comment by bryantbiggs** [comment]
Are you deploying the pattern as is or are you modifying the values?

**Comment by iocron** [comment]
Which values exactly? I've only modified 2 vars (regarding my git log): 
cluster_version = "1.24" # eks.tf
region = "eu-west-1" # main.tf

I think I've also tried the original values before, and it failed, but I can't remember for certain.
