### ISSUE TITLE
Fix cluster-autoscaler irsa policy conditional keys

### ISSUE THREAD

**Issue by samuelsalon** [aws-ia/terraform-aws-eks-blueprints#1990]
## Description

Cluster Autoscaler logs fail and cannot describe the node group as the policy conditional key is incorrectly defined. As I checked the AWS documentation for resource types defined by EKS I found out that the conditional key used with the `nodegroup` resource is not specified right. As a result, we are getting fail logs from the cluster-autoscaler pod which can be seen below in the terminal output. When I changed the condition manually, the pod did not log fail anymore.

AWS documentation: [Resource types defined by Amazon Elastic Kubernetes Service](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.32.1/modules/kubernetes-addons/cluster-autoscaler/data.tf#L61)
Cluster Autoscaler Policy Conditional Key: [modules/kubernetes-addons/cluster-autoscaler/data.tf#L61](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.32.1/modules/kubernetes-addons/cluster-autoscaler/data.tf#L61)

Actual condition variable:
`"autoscaling:ResourceTag/k8s.io/cluster-autoscaler/${var.addon_context.eks_cluster_id}"`

Expected condition variable:
`"aws:ResourceTag/k8s.io/cluster-autoscaler/${var.addon_context.eks_cluster_id}"`

## Versions

- Module version: 
  - `v4.32.1`
- Provider version(s):
  - `hashicorp/aws = 5.52.0`

### Terminal Output 
```
k logs -n kube-system cluster-autoscaler-aws-cluster-autoscaler-5dff469fc4-7fml2 | grep -i '<node-group-name>' | grep -i failed | tail -2

E0801 11:57:24.955907       1 managed_nodegroup_cache.go:136] Failed to query the managed nodegroup <node-group-name> for the cluster <cluster-name> while looking for labels/taints/tags: AccessDeniedException: User: arn:aws:sts::<account-id>:assumed-role/<cluster-name>-cluster-autoscaler-sa-irsa/<irsa-id> is not authorized to perform: eks:DescribeNodegroup on resource: arn:aws:eks:eu-central-1:<account-id>:nodegroup/<cluster-name>/<node-group-name>/<node-group-id>
E0801 11:57:24.955965       1 aws_manager.go:308] Failed to get labels from EKS DescribeNodegroup API for nodegroup <node-group-name> in cluster <cluster-name> because AccessDeniedException: User: arn:aws:sts::<account-id>:assumed-role/<cluster-name>-cluster-autoscaler-sa-irsa/<irsa-id> is not authorized to perform: eks:DescribeNodegroup on resource: arn:aws:eks:eu-central-1:<account-id>:nodegroup/<cluster-name>/<node-group-name>/<node-group-id>.
```

Can somebody explain or help with this?

**Comment by bryantbiggs** [comment]
I believe this is fixed on the current module - this repository no longer hosts any modules
