### ISSUE TITLE
blue green upgrade pattern - Where is my workload?  Finished the "Create the Green cluster" Section but No Results are Returned

### ISSUE THREAD

**Issue by Tony-Lutz** [aws-ia/terraform-aws-eks-blueprints#2023]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

blue green upgrade pattern - Where is my workload?  Finished the "Create the Green cluster" Section but No Results are Returned

#### Provide a link to the example/module related to the question

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/blue-green-upgrade#how-this-work

#### Additional context

```bash
kubectl get deployment -n team-burnham -l app=burnham

**Comment by allamand** [comment]
Hi @Tony-Lutz 

Once you have created on cluster, you can connect to it and check for the workload with thoses commands :

1. Connect to the cluster
```
eval `terraform output -raw configure_kubectl` # to connect to the cluster
```

2. Check for the workload
```
$ kubectl get deployment -n team-burnham -l app=burnham
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
burnham   3/3     3            3           9d
nginx     1/1     1            1           9d
```

3. Test the application with curl
```
URL=$(echo -n "https://" ; kubectl get ing -n team-burnham burnham-ingress -o json | jq ".spec.rules[0].host" -r)
curl -s $URL | grep CLUSTER_NAME | awk -F "<span>|</span>" '{print $4}'
```

the response should be the name of the cluster:

Example:
```
eks-blueprint-blue
```

Do you have issues with this ?
