### ISSUE TITLE
Support for EKS 1.31 in Rancher

### ISSUE THREAD

**Issue by SaurabhGuptaAsu** [aws-ia/terraform-aws-eks-blueprints#2043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Support for EKS 1.31 in Rancher . Currently not able to add monitoring in EKS 1.31 cluster which is added in Rancher. 

#### Describe the solution you would like

Add monitoring for EKS 1.31 in Rancher.

**Comment by bryantbiggs** [comment]
Could you elaborate a bit more - we don't provide any Rancher resources within this project
