### ISSUE TITLE
[FEATURE] Example showing disk + Amazon EKS encryption

### ISSUE THREAD

**Issue by ruzickap** [aws-ia/terraform-aws-eks-blueprints#232]
#### Describe the solution you'd like
Would be possible to enhance (or add) one example to show disk + EKS encryption using KMS? 

It should be quite easy for Amazon EKS encryption using `cluster_kms_key_arn` variable, but example for worker node disk encryption is probably not trivial, because it may require creation of launch template.

Anyway - any example for Amazon EKS + worker node disk encryption would be welcome...

**Comment by askulkarni2** [comment]
Thanks @ruzickap for raising this issue. @ricardosouzamorais any updates on the PR?

**Comment by askulkarni2** [comment]
Depends on https://github.com/aws/containers-roadmap/issues/185
