### ISSUE TITLE
[ebs-csi & argocd] Support Graviton instance

### ISSUE THREAD

**Issue by grid-dev** [aws-ia/terraform-aws-eks-blueprints#243]
I want to use the repo together with AWS Graviton instances. Sadly, not all pods are running as expected.

#### Problem

I tried version 3.2.2 together with
* terraform 1.1.4
* instance type t4g.medium
* ami AL2_ARM_64

Sadly, the "ebs-csi-node" and "ebs-csi-controller" will never start up. The same applies to argo-cd.

#### Target

I would love to have a cluster running with Graviton instances as without including EBS-CSI and ArgoCD.

My assumption is that the helm release uses an outdated version, or a version pinned to X86 and needs to be architecture agnostic.

[This compatibility site](https://github.com/aws/aws-graviton-getting-started/blob/main/containers.md) states that CSI should support ARM, for [ArgoCD there](https://github.com/aws/aws-graviton-getting-started/blob/main/containers-workarounds.md) is still an open issue, and you have to compile from source for now.

**Comment by vara-bonthu** [comment]
I have just validated and found that EBS CSI add-on is failing to deploy on ARM instances. This module is using the EKS Managed add-ons for EBS CSI driver with a version `v1.4.0-eksbuild.preview`. 

I could see this issue has been fixed as per this https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/604. This fix may be available in later versions(v1.5.1) of EBS CSI driver. 

You can try deploying the latest version of add-on using helm charts without using the managed add-on to verify the issue.

**Comment by vara-bonthu** [comment]
Hi @grid-dev Created an issue in EKS Roadmap. Please feel free to add more details to this 
https://github.com/aws/containers-roadmap/issues/1655

**Comment by grid-dev** [comment]
@vara-bonthu sorry but so far had no time to test your recommended solution – as I am currently using none ARM instances as a workaround and am consumed by the cluster config itself. The roadmap item looks complete for me -thanks for the initiative!

**Comment by vara-bonthu** [comment]
Let's keep this issue open until the root cause is resolved

**Comment by grid-dev** [comment]
I tried but did not get it deployed. "ImagePullBackOff" for version 1.5.1.

**Comment by bryantbiggs** [comment]
hi @grid-dev - could you try again when you get a chance and let us know if this is working for you? The EBS CSI driver just recently went GA and it looks like the upstream issues related to ARM support are resolved now. Thanks!
