### ISSUE TITLE
[FEATURE] Windows support of OpenTelemetry addon

### ISSUE THREAD

**Issue by schwichti** [aws-ia/terraform-aws-eks-blueprints#245]
#### Is your feature request related to a problem? Please describe
I want to collect performance metrics for Windows nodes in EKS cluster. However, the [aws-opentelemetry-eks addon](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/modules/kubernetes-addons/aws-opentelemetry-eks) currently supports only linux nodes. In general, it seems to be feasible to collect metrics from windows nodes: https://aws-otel.github.io/docs/setup/build-collector-on-windows

#### Describe the solution you'd like
Collect performance metrics from windows nodes.

#### Describe alternatives you've considered
Install OpenTelemetry Collector manually on windows nodes: https://aws-otel.github.io/docs/setup/build-collector-on-windows

**Comment by vara-bonthu** [comment]
Thanks @schwichti We are currently working on improving the Open Telemetry Add-on overall. I will add the Windows feature to the roadmap.

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use OTEL for Windows you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment or the EKS addon for ADOT
