### ISSUE TITLE
[FEATURE] Add kms support in launch template of eks managed node groups - `kms_key_id`

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-eks-blueprints#373]
#### Is your feature request related to a problem? Please describe
I need encrypt EBS in eks managed node groups.

#### Describe the solution you'd like
Add argument `kms_key_id` in launch template and flag  `encrypted` as `true` in `ebs block`.

**Comment by vara-bonthu** [comment]
Thanks for raising @evairmarinho . We are currently working on Managed node group to leverage launch templates module. Your request will be covered in that feature

**Comment by ruzickap** [comment]
This seems to be similar to #232

**Comment by evairmarinho** [comment]
@ruzickap, its not a example. But we can gather all the needs in one issue just to make it easier. If we centralize, then this issue can be closed.

**Comment by vara-bonthu** [comment]
Could you please try this PR @evairmarinho and let me know for any issues?

KMS Key ID can be provided through block_device_mappings with the new PR. See the PR docs more details

```hcl
      mng_lt = {
        # Node Group configuration
        node_group_name        = "mng-lt"
        create_launch_template = true  
        ...

        block_device_mappings = [
          {
            device_name = "/dev/xvda"
            volume_type = "gp3"
            volume_size = 100
          },
          {
            device_name           = "/dev/xvdf" # mount point to /local1 (it could be local2, depending upon the disks are attached during boot)
            volume_type           = "gp3" # The volume type. Can be standard, gp2, gp3, io1, io2, sc1 or st1 (Default: gp3).
            volume_size           = "100"
            delete_on_termination = true
            encrypted             = true
            kms_key_id            = "" # Custom KMS Key can be used to encrypt the disk
            iops                  = 3000
            throughput            = 125
          }
        ]
 ...
}
```

**Comment by ruzickap** [comment]
It would be handy to include the example code for using KMS in https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/456 showing the way how to create + use KMS (like the old attempt here: #247)
Setting up the KMS, IAM policy + EKS integration may not be easy...

**Comment by evairmarinho** [comment]
@ruzickap and @vara-bonthu
Can I close the issue? Seeing the PR, what I asked for is already being added.

**Comment by evairmarinho** [comment]
Thanks!
