### ISSUE TITLE
[FEATURE] Add Velero as an add on to the accelerator. 

### ISSUE THREAD

**Issue by greengangsta** [aws-ia/terraform-aws-eks-blueprints#382]
#### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is. 

Having a tool to backup and restore your Kubernetes cluster resources and persistent volumes.

#### Describe the solution you'd like
Adding valero as an add on to the accelerator. 

#### Additional context

Velero is a tool to backup and restore your Kubernetes cluster resources and persistent volumes. Velero lets you :

1. Take backups of your cluster and restore in case of loss.
2. Migrate cluster resources to other clusters.
3. Replicate your production cluster to development and testing clusters.

**Comment by askulkarni2** [comment]
@greengangsta this will be a great addon to have. Please feel free to submit a PR for the addon along with a complete example documenting the use case.
