### ISSUE TITLE
Run coreDNS on Fargate

### ISSUE THREAD

**Issue by tanvp112** [aws-ia/terraform-aws-eks-blueprints#394]
#### Is your feature request related to a problem? Please describe

Currently, to run coreDNS on Fargate after the EKS cluster is created, a manual call to patch the coredns deployment is needed to remove an annotation (eks.amazonaws.com~1compute-type).

#### Describe the solution you'd like

Is it possible to configure/change coreDNS deployment _not_ to have the annotation at the [default_addon_config](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/d110446deca55bfa3ae662a1216dacffb6ac0a22/modules/kubernetes-addons/aws-coredns/locals.tf#L3)?

#### Describe alternatives you've considered

Use `null_resource` with `local-exec` provisioner to make manual `kubectl patch` until this [issue](https://github.com/hashicorp/terraform-provider-kubernetes/issues/723) is resolved.

#### Additional context

Relevant to Fargate only cluster creation and maintenance.

**Comment by redeux** [comment]
Does the new `kubernetes_annotations` resource solve this use case for you?

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/annotations

**Comment by bryantbiggs** [comment]
@redeux I don't think so. I'm trying this out now and I can modify the deployments annotations for CoreDNS, but what I need to modify are is the deployments `spec.template.metadata.annotations`. 

This is the kubectl command equivalent that I don't know how to convert into something the kubernetes annotations resource would understand:

```bash
kubectl patch deployment coredns \
    -n kube-system \
    --type json \
    -p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
```

**Comment by bryantbiggs** [comment]
Closed in #558

**Comment by niroz89** [comment]
This new release https://aws.amazon.com/about-aws/whats-new/2022/12/eks-add-ons-supports-advanced-configuration/ can be used to modify coredns for fargate profile ?

**Comment by bryantbiggs** [comment]
> This new release https://aws.amazon.com/about-aws/whats-new/2022/12/eks-add-ons-supports-advanced-configuration/ can be used to modify coredns for fargate profile ?

Correct

**Comment by christianlafleur** [comment]
@bryantbiggs did you found a way to remove annotation using addon advanced configuration ? metadata seem not to be part of the schema.

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/273c48a631c0ab45ffac1d1a77c7752e8541b1f2/examples/fargate_profile/main.tf#L36-L40

**Comment by christianlafleur** [comment]
> https://github.com/terraform-aws-modules/terraform-aws-eks/blob/273c48a631c0ab45ffac1d1a77c7752e8541b1f2/examples/fargate_profile/main.tf#L36-L40

thanks for the info !
