### ISSUE TITLE
[QUESTION] Call module kubernetes-addons source 

### ISSUE THREAD

**Issue by joaoferreira1985** [aws-ia/terraform-aws-eks-blueprints#399]
#### Please describe your question here
I would like to use this module but I'm wondering what is the public official  module without blueprints? 
The source of the module should point to github? 

~~~ 
module "eks-blueprints-kubernetes-addons" {
 source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons"
}
~~~ 

#### More

- [X] Yes, I have checked the repo for existing issues before raising this question

**Comment by askulkarni2** [comment]
Hi @joaoferreira1985, thank you for the question. That's exactly right. I recommend pinning the source to a release tag such as shown below.

`source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.0.1"`

**Comment by joaopcferreira** [comment]
Thanks

**Comment by askulkarni2** [comment]
I will close this issue for now. Please don't hesitate to reach out if you have any more questions/issues. Thanks!
