### ISSUE TITLE
[Bug]: Failed to query available provider packages

### ISSUE THREAD

**Issue by ZeroDeth** [aws-ia/terraform-aws-eks-blueprints#417]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

latest

### What is your environment, configuration and the example used?

Terraform version = 1.1.8

### What did you do and What did you see instead?

The latest merge through that error and working fine with previous commit `854974d80304d736fce537699f86b8657c5fde98`

```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints >= 2.0.0, >= 2.23.0, >= 2.53.0,  >= 3.0.0, ~> 3.0, >= 3.2.0, >= 3.15.0, >= 3.34.0, >= 3.37.0, >= 3.63.0, >= 3.66.0, >= 3.72.0, >= 4.5.0
```

I don't know what the issue is exactly but after testing several times in another machine something is wrong with the latest 3 merges today. Thanks

**Comment by vara-bonthu** [comment]
Hi @ZeroDeth 

I have just tried running Terraform init and plan with Terraform Version 1.1.8 on the main branch and it works fine for me.

You may need to provide full example and the command you tried along with the logs. Have you done any further changes to the example you tried?

**Comment by vara-bonthu** [comment]
Hi @ZeroDeth 

I have just tried running Terraform init and plan with Terraform Version 1.1.8 on the main branch and it works fine for me.

You may need to provide full example and the command you tried along with the logs. Have you done any further changes to the example you tried?

**Comment by ZeroDeth** [comment]
Hi @vara-bonthu 

Working now after downgrade `terraform-aws-s3-bucket` https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/149

Apologies and Thank you!
