### ISSUE TITLE
[Bug]: OIDC_ISSUER_URL does not return full URL

### ISSUE THREAD

**Issue by danvau7** [aws-ia/terraform-aws-eks-blueprints#420]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

v4.0.2

### What is your environment, configuration and the example used?

N/A

### What did you do and What did you see instead?

Receive the full OIDC URL but without the http prefix. This throws off what other resources are expecting, such as the resource "oidc" and its parameter "issuer_url".

### Additional Information

```shell
This can be simply fixed in the current version by using the workaround: `join("", ["https://", module.eks.eks_oidc_issuer_url])`.
```

**Comment by bryantbiggs** [comment]
@danvau7 are you able to use the `oidc_provider` which does not include the `https://` prefix

**Comment by bryantbiggs** [comment]
closing for now but please feel free to let me know if this needs to be opened - the existing `oidc_provider` should suffice for this request
