### ISSUE TITLE
[TEST] - Add Terratest Suite

### ISSUE THREAD

**Issue by kcoleman731** [aws-ia/terraform-aws-eks-blueprints#429]
This story covers the following
Status

- [x] Terratest code is ready to plan and apply the E2E test (EKS Cluster with new vpc example)
- [x] Validate deployed VPC and EKS Cluster name and Managed node groups
- [x] Validate deployed Add-ons 
- [ ] Makefile for executing the Terratest E2E test
- [x] Github workflow for Terratest E2E test

Note: 
- Terratest E2E test which replaces existing E2E test with Github Workflow

**Comment by bryantbiggs** [comment]
I think we can close this now, correct @vara-bonthu , @kcoleman731 ?
