### ISSUE TITLE
[DOCS] - Cluster Upgrade Guide

### ISSUE THREAD

**Issue by kcoleman731** [aws-ia/terraform-aws-eks-blueprints#430]
Add documentation which details how to upgrade EKS clusters using EKS Blueprints.

**Comment by AditModi** [comment]
Hi @kcoleman731 ,
can you briefly describe the things you would like to implement here. I would like to contribute here.
I see some documentation briefly describing the cluster upgrade scenario [here](https://aws-ia.github.io/terraform-aws-eks-blueprints/advanced/cluster-upgrades/).

**Comment by bryantbiggs** [comment]
the first body of work has been captured here https://github.com/aws-ia/terraform-aws-eks-blueprints/milestone/2 

closing out this issue in favor of the linked milestone
