### ISSUE TITLE
[ADDON] - AppMesh

### ISSUE THREAD

**Issue by kcoleman731** [aws-ia/terraform-aws-eks-blueprints#437]
Add support for AppMesh as an add-on.

https://github.com/aws/eks-charts#app-mesh

**Comment by bryantbiggs** [comment]
IRSA role support for both controller and sidecar proxy https://github.com/terraform-aws-modules/terraform-aws-iam/pull/231 recently added

**Comment by askulkarni2** [comment]
We need to resume/take over the work for #539

**Comment by florentio** [comment]
Excited to see this addons available. We decide to adopt appmesh as service mesh solution and looking forward to have it on the addons list.

**Comment by bryantbiggs** [comment]
closed in #539
