### ISSUE TITLE
[Bug]: The time out in `data.http.eks_cluster_readiness` is too short under some circumstances

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#449]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

34921232356fb69b5a41094246d488c37c596d97

### What is your environment, configuration and the example used?

Terraform v1.1.7

### What did you do and What did you see instead?

There are times that spinning up an EKS cluster results in this:

```
│ Error: Error making request: Get "https://C567CC227DA5BE40A1E0154ADE3395EE.gr7.us-east-1.eks.amazonaws.com/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│ 
│   with module.eks_blueprints.data.http.eks_cluster_readiness[0],
│   on .terraform/modules/eks_blueprints/data.tf line 12, in data "http" "eks_cluster_readiness":
│   12: data "http" "eks_cluster_readiness" {
```

Simply re-run the `plan` and `apply` resolves the issue.

This strongly suggests that, at least in some circumstances, the timeout is simply too low. I'd recommend simply doubling it (10 minutes) for good measure, given nothing about spinning up an EKS cluster is particularly fast.

### Additional Information

I believe that I have mostly noticed this when destroying the cluster and then spinning it back up in close succession. Maybe under these circumstances, it takes a little longer for things to stabilize?

**Comment by evairmarinho** [comment]
I think it would be more practical if `timeout` value were a variable with a default value defined.

**Comment by spkane** [comment]
Sure, putting it into a variable AND increasing the default would be a good fix. The primary point was that the timeout is currently too low for certain normal situations, so at a minimum, it needs to be increased, as this time this takes is outside the user's control and is happening behind the scenes.

**Comment by Zvikan** [comment]
Thank you for reporting this, for short term, we can set the timeout value as variable with default increased to 10 minutes.
Long term, I hope we won't need this (`data.http.eks_cluster_readiness`) at all and the EKS endpoint would show `ACTIVE` only when it's really active. 

Related PR: https://github.com/aws/containers-roadmap/issues/654
