### ISSUE TITLE
[DOCS] - Multi-Region Cluster Example

### ISSUE THREAD

**Issue by a-patel** [aws-ia/terraform-aws-eks-blueprints#451]
Add documentation that details how to create EKS clusters in multiple regions using EKS Blueprints.

**Comment by a-patel** [comment]
Any update on this?

**Comment by a-patel** [comment]
Any update on this?

**Comment by askulkarni2** [comment]
@a-patel not sure I understand the request. What specifically are you looking for in this example? What's stopping you from creating multiple clusters across different regions today by configuring the providers?

**Comment by a-patel** [comment]
Example documentation to create the clusters in multiple regions (2-3).
@askulkarni2
