### ISSUE TITLE
[ADDON] - Grafana Agent

### ISSUE THREAD

**Issue by a-patel** [aws-ia/terraform-aws-eks-blueprints#453]
Add support for Grafana (and managed Grafana services like Amazon Managed Grafana and Azure Managed Grafana) as an add-on.

**Comment by askulkarni2** [comment]
AMG being outside the EKS cluster does not fit well as an add-on. We do have example of how to provision a Prometheus, AMP, AMG stack [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/observability/amp-amg-opensearch). But for those who want to deploy Grafana on EKS, I guess we could create an add-on for that.

**Comment by askulkarni2** [comment]
Re-purposing this ticket to add support for [Grafana Agent](https://grafana.com/docs/agent/latest/)

**Comment by bryantbiggs** [comment]
This is already supported https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/grafana
