### ISSUE TITLE
[ADDON] - Grafana Loki

### ISSUE THREAD

**Issue by a-patel** [aws-ia/terraform-aws-eks-blueprints#454]
Add support for Grafana Loki as an add-on.

**Comment by evairmarinho** [comment]
Can you help me this this related issue in `terraform-provider-aws` ?

https://github.com/hashicorp/terraform-provider-aws/issues/20394

**Comment by sharepointoscar** [comment]
I can take on this custom `add-on`~ @Zvikan

**Comment by season1946** [comment]
@sharepointoscar  any update on Grafana Loki?

**Comment by Hokwang** [comment]
@sharepointoscar Hi, please comment on this issue if you have any progress.

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Grafana Loki you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
