### ISSUE TITLE
[FEATURE]  `aws-for-fluentbit` - Make it possible to pass in additional ARNs that should have `kms:*` in the key policy.

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#460]
#### Is your feature request related to a problem? Please describe

Managing KMS keys is tricky and various missteps can cause Keys to become unmanageable. All KMS key policies should at a minimum make it easy to pass in a list of ARNs that have full KMS access.

Even better, would be some flexibility to add a list of ARNs to each section.

Something that basically works like this recent PR into the core part of the repo.
https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/414

#### Describe the solution you'd like
There is a `cluster_kms_key_additional_admin_arns`, so maybe add something like an `addon_fleuntbit_kms_key_additional_admin_arns` variable to accomplish the same task.

It might even make sense to support a `global_kms_key_additional_admin_arns` that when set would be added to all key policies.

#### Describe alternatives you've considered
Nothing. I just want more control over the key policy, in case of emergency, etc.

**Comment by bryantbiggs** [comment]
This should be resolved in v5 when the addon is updated to use the https://github.com/terraform-aws-modules/terraform-aws-kms module

**Comment by bryantbiggs** [comment]
closed in #857
