### ISSUE TITLE
unable to execute TLS connection towards oidc.eks

### ISSUE THREAD

**Issue by estebane-frb** [aws-ia/terraform-aws-eks-blueprints#462]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

v4.0.2

### What is your environment, configuration and the example used?

Terraform version: 1.1.9
Example Used: eks-cluster-with-new-vpc (from Getting started section in https://aws-ia.github.io/terraform-aws-eks-blueprints/getting-started/)

Additional notes:
1) I am trying to deploy this in GovCloud (us-gov-west-1) so I am using that as the region.

### What did you do and What did you see instead?

Followed the exact steps in the Getting Started tutorial [here](https://aws-ia.github.io/terraform-aws-eks-blueprints/getting-started/) but instead of doing a git clone I downloaded the v4.0.2 zip artifact to make sure I'm using an official release instead of the main branch.

Terraform init and plan ran fine. Error occurred when running "terraform apply -target="module.eks_blueprints""

I get this error:
![image](https://user-images.githubusercontent.com/88841823/164773475-260c995d-257f-49be-9760-76575d89ddb1.png)

When I went to look into the .terraform/modules/eks_blueprints.aws_eks/main.tf of this external module, I noticed that 

resource "aws_eks_cluster" "this" does not have an OIDC identity block! So when the data "tls_certificate" "this" resource tries to pull:

```
data "tls_certificate" "this" {
  count = local.create && var.enable_irsa ? 1 : 0

  url = aws_eks_cluster.this[0].identity[0].oidc[0].issuer
}
```

It can't find anything to pull and gives me the error in the screenshot.

### Additional Information

```shell
Fix should be to add an identity block to the EKS cluster resource.
```

**Comment by naris-silpakit** [comment]
I'm going to close this issue due to inactivity. Please re-open this if the issue comes up again!
