### ISSUE TITLE
[Bug]: Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)

### ISSUE THREAD

**Issue by ZeroDeth** [aws-ia/terraform-aws-eks-blueprints#466]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

latest

### What is your environment, configuration and the example used?

Running any of examples and enable metrics-server

####  when I tried to run the metric server:
`kubectl top nodes`
`kubectl top podes`

error:
`Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)`

#### When I tried to enable `hostNetwork: ture`

`kubectl edit deployments.apps -n kube-system metrics-server`

error: 
`error: path "metrics-server" not found`

**Comment by ZeroDeth** [comment]
ArgoCD HPA error from  `main & 4.0.3`

```
failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API
```

**Comment by ZeroDeth** [comment]
Useful info: https://keda.sh/docs/2.6/troubleshooting/

### Why is Kubernetes unable to get metrics from KEDA?
If while setting up KEDA, you get an error: `(v1beta1.external.metrics.k8s.io) status FailedDiscoveryCheck with a message: no response from https://ip:443: Get https://ip:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

### Why is KEDA API metrics server failing when Istio is installed?
While setting up KEDA, you get an error: `(v1beta1.external.metrics.k8s.io) status FailedDiscoveryCheck` and you have [Istio](https://istio.io/) installed as service mesh in your cluster.

This can lead to side effects like not being able to delete namespaces in your cluster. You will see an error like:

`NamespaceDeletionDiscoveryFailure - Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

**Comment by bryantbiggs** [comment]
hi @ZeroDeth - metrics-server requires some additional network access. Can you try adding the following to your configuration and confirm if this resolves your issue?

```hcl
node_security_group_additional_rules = {
    ingress_cluster_metrics_server_tcp = {
      description                   = "Cluster API to metrics server 8443 ingress port"
      protocol                      = "tcp"
      from_port                     = 8443
      to_port                       = 8443
      type                          = "ingress"
      source_cluster_security_group = true
    }
    ingress_self_kubelet_tcp = {
      description = "Node to node metrics server 10250 ingress port"
      protocol    = "tcp"
      from_port   = 10250
      to_port     = 10250
      type        = "ingress"
      self        = true
    }
    egress_self_kubelet_tcp = {
      description = "Node to node metrics server 10250 egress port"
      protocol    = "tcp"
      from_port   = 10250
      to_port     = 10250
      type        = "egress"
      self        =  true 
    }
  }
```

**Comment by ZeroDeth** [comment]
> hi @ZeroDeth - metrics-server requires some additional network access. Can you try adding the following to your configuration and confirm if this resolves your issue?
> 
> ```terraform
> node_security_group_additional_rules = {
>     ingress_cluster_metrics_server_tcp = {
>       description                   = "Cluster API to metrics server 8443 ingress port"
>       protocol                      = "tcp"
>       from_port                     = 8443
>       to_port                       = 8443
>       type                          = "ingress"
>       source_cluster_security_group = true
>     }
>     ingress_self_kubelet_tcp = {
>       description = "Node to node metrics server 10250 ingress port"
>       protocol    = "tcp"
>       from_port   = 10250
>       to_port     = 10250
>       type        = "ingress"
>       self        = true
>     }
>     egress_self_kubelet_tcp = {
>       description = "Node to node metrics server 10250 egress port"
>       protocol    = "tcp"
>       from_port   = 10250
>       to_port     = 10250
>       type        = "egress"
>       self        =  true 
>     }
>   }
> ```

Issue fixed by adding SGs. Thanks, @bryantbiggs
