### ISSUE TITLE
[Bug]: Disk provisioning logic fails for managed node groups

### ISSUE THREAD

**Issue by cvlc** [aws-ia/terraform-aws-eks-blueprints#468]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

v4.0.3 and main

### What is your environment, configuration and the example used?

Using the example from https://github.com/ondat/terraform-eksblueprints-ondat-addon/blob/main/blueprints/getting-started/main.tf, removing the ref pins to f22c58.

### What did you do and What did you see instead?

A `terraform apply` resulted in a timeout as the nodes never joined the cluster. Further investigation of the EKS managed node group nodes revealed that cloud-init failed due to:

```shell
+ IDX=1
++ awk '/disk/ {print $1}'
++ lsblk -o NAME,TYPE -dsn
+ DEVICES='nvme1n1
└─nvme0n1
nvme2n1
nvme3n1'
+ for DEV in $DEVICES
+ mkfs.xfs /dev/nvme1n1
meta-data=/dev/nvme1n1           isize=512    agcount=16, agsize=1638400 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1
data     =                       bsize=4096   blocks=26214400, imaxpct=25
         =                       sunit=1      swidth=1 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=12800, version=2
         =                       sectsz=512   sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
+ mkdir -p /local1
+ echo /dev/nvme1n1 /local1 xfs defaults,noatime 1 2
+ IDX=2
+ for DEV in $DEVICES
+ mkfs.xfs /dev/└─nvme0n1
Error accessing specified device /dev/└─nvme0n1: No such file or directory
Usage: mkfs.xfs
[snip]
```

The loop seems to have become confused as our disks are pre-provisioned and pre-partitioned by the `ebs-bootstrap` component so they already have a partition ready and are populated with data when the code in https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/f22c583290b2321a2bb169f11b57e7bc9d83ccfa#diff-de4948d167bbfc9b217e569f535730d007e98ee2702514233db204160a5e893dR18 runs.

### Additional Information

```shell
This would be a serious issue if somebody attached disks with state as it could lead to lost data - the mkfs.xfs is done regardless of the existing content of the disks. It's not clear how to opt out of this logic.
```

**Comment by askulkarni2** [comment]
@vara-bonthu looks like we need to add a check to see if partitions already exist?

**Comment by vara-bonthu** [comment]
NVMe disk partition and mounting is requested by few users for managed node groups hence we added. This is already an existing feature for Self Managed Linux and Windows node groups.

@cvlc Could you please try running your example by removing the `for` block from the below user data and confirm if that works ok?

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/093574f79a50413b961376d9ec0310bda6b514b9/modules/aws-eks-managed-node-groups/templates/userdata-amazonlinux2eks.tpl#L18

I will see if i can add a check to see if the disk is already mounted to avoid the issue. Or i will introduce a parameter to enable or disable this for loop from Managed Node groups

**Comment by cvlc** [comment]
Hey @vara-bonthu - I can confirm that it works just fine when removing lines 14-27 in the file you linked!

**Comment by vara-bonthu** [comment]
I am working on a PR which i will push soon
