### ISSUE TITLE
[FEATURE] Support custom networking 

### ISSUE THREAD

**Issue by sheetaljoshi** [aws-ia/terraform-aws-eks-blueprints#474]
#### Is your feature request related to a problem? Please describe
There are a limited number of IP addresses available in a subnet. This might limit the number of pods that can be created in the cluster. Using different subnets for pods allows you to increase the number of available IP addresses. This feature is called as Custom networking in EKS. Custom networking configuration seems to be a complicated setup for customers and most of the our customers run into IP issues.

#### Describe the solution you'd like
As customers chose to adopt EKS blueprints, support for custom networking will become requirement. Please refer https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html for implementation details.

#### Additional context
Sample TF implementation to consider 
https://tf-eks-workshop.workshop.aws/500_eks-terraform-workshop/570_advanced-networking/secondary_cidr/configure-cni.html

**Comment by sheetaljoshi** [comment]
We might hit the same issues as mentioned on below link, so careful attention must be paid. 

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/870

**Comment by Tstrul-work** [comment]
Hey,
Is there some kind of workaround/example for using eks blueprints module with different subnet for pods?

**Comment by migalsp** [comment]
Hi, please, add additional parameter for different pod's subnets.  It could be something like this
```tf
pods_subnet_ids = ["subnet-000000001",  "subnet-000000002"]

**Comment by qtruong77** [comment]
Please assign this item to me.

**Comment by satveerkhurpa** [comment]
I have a customer requesting this feature and is a blocker for them to use EKS.
