### ISSUE TITLE
[FEATURE] externalize cluster_iam_role 

### ISSUE THREAD

**Issue by kumarpmd** [aws-ia/terraform-aws-eks-blueprints#475]
#### Is your feature request related to a problem? Please describe
terraform-aws-eks module is currently used to provision cluster with pre-created iam_roles.
aws-ia/terraform-aws-eks-blueprints seems to always create cluster_iam_role, with name derived from tags.  
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/locals.tf#L154
can we have the module use pre-created cluster-iam-role and use create_iam_role similar to terraform-aws-eks?
  https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/main.tf#L42-L43

#### Describe the solution you'd like
expose variables - create_iam_role and cluster_iam_role_name 
pass create_iam_role to submodule to trigger cluster_iam resources 
use var.cluster_iam_role_name when create_iam_role is enabled

#### Describe alternatives you've considered
Our Security requires IAM roles to be pre-created.  An alternate option is for us to continue using terraform-aws-eks modules. 

#### Additional context
Let me know if you want me to update the code and submit

**Comment by bryantbiggs** [comment]
hi @kumarpmd - you should be able to achieve this today with:

```hcl
  create_iam_role = false
  iam_role_arn    = "<your_existing_iam_role_arn>"
```

These values are passed directly to the `terraform-aws-eks` module https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/main.tf#L28-L29

**Comment by bryantbiggs** [comment]
Closing out with the provided guidance above - please let us know if you have any additional questions
