### ISSUE TITLE
[ADDON] Linkerd (SMI)

### ISSUE THREAD

**Issue by joebowbeer** [aws-ia/terraform-aws-eks-blueprints#478]
Add support for Linkerd as an add-on for mTLS and traffic shaping.

#### Additional context

Eventually this should be possible via generic support for Service Mesh Interface (SMI) implementations, but I'm not sure about the timing.

* https://github.com/servicemeshinterface/smi-spec
* https://smi-spec.io/

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Linkerd you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
