### ISSUE TITLE
[FEATURE] Provide examples to launch clusters with EC2 Spot Instances

### ISSUE THREAD

**Issue by christianhxc** [aws-ia/terraform-aws-eks-blueprints#483]
#### Is your feature request related to a problem? Please describe
There are no explicit examples on how to create clusters using EC2 Spot Instances.

#### Describe the solution you'd like
A set of examples with Spot instances when using managed node groups, self-managed node groups, and Karpenter.

#### Describe alternatives you've considered
N/A

#### Additional context
I'm working on creating the set of examples, a PR is on the way

**Comment by askulkarni2** [comment]
Hi @christianhxc, these would be great!

**Comment by vara-bonthu** [comment]
@christianhxc Did you checkout the examples here https://aws-ia.github.io/terraform-aws-eks-blueprints/node-groups/?  This has examples for creating SPOT node groups. 

Are you looking for more details? Please describe so that we can extend this doc.

**Comment by christianhxc** [comment]
@vara-bonthu I did, but as I mentioned this PR https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/484, to use Spot effectively you need to do more than just adding a capacity type, and it varies if using managed node-groups or self-managed node groups. I didn't want to submit too many changes at once but the docs you're referencing need to be changed too (i.e. if using managed node groups, you don't need to specify the capacity type as it's done automatically).

**Comment by vara-bonthu** [comment]
Thanks @christianhxc!  It sounds like you added some missing features to our node groups. 
I didn't go through your PR yet.  I will get back to you after reviewing the PR.

**Comment by christianhxc** [comment]
awesome, thanks @vara-bonthu

**Comment by bryantbiggs** [comment]
Closed in #484 - thanks @christianhxc !
