### ISSUE TITLE
[QUESTION] Cannot Delete KMS after Creation with Terraform

### ISSUE THREAD

**Issue by vrodriguezcl** [aws-ia/terraform-aws-eks-blueprints#485]
#### Please describe your question here:

Recently I was playing with this project, and after the cluster creation, everything was Ok. But, in the time to destroy the created infrastructure using Terraform, one resource specifically cannot be deleted. And I tried many times to delete it an I cannot, I got this error when I tried to delete it from the AWS Web Console, and using **awscli** I cannot get any output.

AccessDeniedException - User: arn:aws:iam::111111111111:user/kube-administrator is not authorized to perform: kms:DisableKey on resource: arn:aws:kms:us-east-1:111111111111:key/be374906-a2d3-21ad-8ef5-25b2cb8048a0 because no resource-based policy allows the kms:DisableKey action

To continue testing this project, I added the **kms module** in my **main.tf** but, changing the values of the alias name (**alias/custom-name**), it cannot be shown in the **tf plan**.

If I need to use kms module is required referencing the URL from GitHub as the same way as the addons example show us?.

Please, help me of how to delete this **KMS** or give me the steps to use a custom KMS name.

I'm using **Terraform Cloud** and **1.1.9** as Terraform Binary version.

Just to know, how can I add a default alias/custom-name to my KMS to avoid that terraform validates that this currently one exists and create a new one?. Or, exists any walkthrough to avoid the kms creation ?. Something like: **aws_kms_enabled = true/false** and put this parameter in my **main.tf** file ?. This module is a must for the eks cluster creation ?. Or we can skip this ?

#### Additional context:
            "Sid": "Allow access for Key Administrators",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "**_AROAYWHCTDYSNS3AU5YK4_**",
                    "arn:aws:iam::111111111111:user/kube-administrator"
                ]

#### More:

- [X] Yes, I have checked the repo for existing issues before raising this question

**Comment by spkane** [comment]
You have to look at the key policy. By default only two roles are allowed to delete the KMS aliases or keys (have `kms:*`). KMS keys are very sensitive and highly protected.

If you delete those roles by hand, etc. it is possible to make a KMS key unmanageable, in which case you will need help from AWS support.

https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html

This is why there is now a new variable that lets you add additional ARNs that you would like to have full access to the KMS key created in this module.

`cluster_kms_key_additional_admin_arns = ["arn:aws:iam::000000000000:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_Administrators_0000000000000000"]
`

**Comment by vrodriguezcl** [comment]
> You have to look at the key policy. By default only two roles are allowed to delete the KMS aliases or keys (have `kms:*`). KMS keys are very sensitive and highly protected.
> 
> If you delete those roles by hand, etc. it is possible to make a KMS key unmanageable, in which case you will need help from AWS support.
> 
> https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html
> 
> This is why there is now a new variable that lets you add additional ARNs that you would like to have full access to the KMS key created in this module.
> 
> `cluster_kms_key_additional_admin_arns = ["arn:aws:iam::000000000000:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_Administrators_0000000000000000"] `

I did not delete any policy manually. I have used earlier terraform destroy and after that it come this issue. And after that, I cannot use terraform apply. :( :(

**Comment by spkane** [comment]
It is deleting `roles` by hand that usually causes this issue. Strickly using terraform should do the right thing, however, if you take a look at the KMS key policy (in the console) and you don't see any valid roles listed in there with `kms:*` access, then you will have to create an AWS support ticket and jump through a week or so of hoops to get it fixed.

The safeguard for this in the future is to use the `cluster_kms_key_additional_admin_arns` variable mentioned above and pass in a user or role that you have in the account, which will always be around and accessible.

**Comment by vrodriguezcl** [comment]
> It is deleting `roles` by hand that usually causes this issue. Strickly using terraform should do the right thing, however, if you take a look at the KMS key policy (in the console) and you don't see any valid roles listed in there with `kms:*` access, then you will have to create an AWS support ticket and jump through a week or so of hoops to get it fixed.
> 
> The safeguard for this in the future is to use the `cluster_kms_key_additional_admin_arns` variable mentioned above and pass in a user or role that you have in the account, which will always be around and accessible.

Oks, thanks for your quick response. Sorry, but, can you please show me how can I do this ?.

Also, this KMS module is really needed for EKS cluster creation ?

**Comment by spkane** [comment]
KMS is required for this approach, but the upstream EKS module does not require KMS (it is a good idea, however). https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest

We can't really show you how to do this. Only AWS support can help you fix this. Contact them and they can walk you through getting access to the key, if you have no more valid roles attached to the key policy.
