### ISSUE TITLE
[Addon] Istio

### ISSUE THREAD

**Issue by gobrial** [aws-ia/terraform-aws-eks-blueprints#488]
Add support for Istio as an add-on for mTLS, telemetry, traffic management and Blue green deployment.

https://istio.io/latest/docs/

**Comment by joebowbeer** [comment]
Dup of #452 ?

**Comment by bryantbiggs** [comment]
Istio is already offered via the Tetrate for Istio addon - see https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/452#issuecomment-1105334175
