### ISSUE TITLE
[BLUEPRINT]Replace `gitlab-ci-cd` with an example that shows self-hosted GitLab on EKS

### ISSUE THREAD

**Issue by bryantbiggs** [aws-ia/terraform-aws-eks-blueprints#493]
#### Describe the solution you'd like
- Replace https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ci-cd/gitlab-ci-cd with an example that shows how to run self-hosted GitLab runners on EKS
	- Both EKS managed node groups and Fargate profiles since there are distinct differences in either route

The current example is not useful from a blueprint perspective - it currently appears to show how to use Terraform with GitLab as the backend which is more of a Terraform/GitLab concern than EKS/Blueprint concern. Instead, it would be more useful for users to see how they can use EKS Blueprints to run self-hosted GitLab runners on EKS using either an EC2 based route (EKS Managed node groups) or serverless route (Fargate profiles)

**Comment by bobdoah** [comment]
@bryantbiggs @askulkarni2  I've made PR which I'm hoping at least partially resolves this issue. I thought I'd raise it before I get stuck into a Fargate example. I don't have a lot of familiarity with Fargate. I also wanted to check that this is the kind of thing you were thinking.

**Comment by smaruy30** [comment]
@bryantbiggs @askulkarni2 
Hi, maintainers. I would appreciate it if you could check the PR from @bobdoah and proceed with the gitlab ci addon.

**Comment by bryantbiggs** [comment]
closing this one for now due to lack of demand
