### ISSUE TITLE
[FEATURE] Add some easy to see cautionary notes and helpful hints around KMS usage in the README & examples

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#494]
#### Is your feature request related to a problem? Please describe

After helping out with this https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/485 and having had a similar issue early on here https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/414

It might be good to make sure that people using this module are aware of the basics of KMS and how they can protect themselves from unmanageable keys. It really is a pain when this happens, especially when you aren't really familiar with KMS and all of a sudden find yourself with a terraform stack that can't be easily destroyed and replaced.

#### Describe the solution you'd like

Add some very easy-to-discover documentation in the README and default examples for new users with a few warnings, and explanations of best practices, and bad outcomes.

**Comment by bryantbiggs** [comment]
Thank you for creating this - I agree, theres a bit of work to do around KMS; possibly even externalizing it and instead showing example usage from an `example/` rather than create within the root module.

**Comment by vrodriguezcl** [comment]
Will we see an any boolean option if we want to use kms or not ? I mean, something like: enable_kms = true/false in our tf file ?. @bryantbiggs

**Comment by bryantbiggs** [comment]
This will be resolved in the upcoming v5 release

**Comment by bryantbiggs** [comment]
closed in #857
