### ISSUE TITLE
IAM Role issue

### ISSUE THREAD

**Issue by skuriyadi** [aws-ia/terraform-aws-eks-blueprints#496]
Hi,

I am getting below error when using latest version of your module, please advise.

 Error: Invalid for_each argument
│ 
│   on .terraform/modules/eks-cluster.aws_eks/main.tf line 250, in resource "aws_iam_role_policy_attachment" "this":
│  250:   for_each = local.create_iam_role ? toset(compact(distinct(concat([
│  251:     "${local.policy_arn_prefix}/AmazonEKSClusterPolicy",
│  252:     "${local.policy_arn_prefix}/AmazonEKSVPCResourceController",
│  253:   ], var.iam_role_additional_policies)))) : toset([])
│     ├────────────────
│     │ local.create_iam_role is true
│     │ local.policy_arn_prefix is a string, known only after apply
│     │ var.iam_role_additional_policies is empty list of string
│ 
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the for_each depends on.

**Comment by askulkarni2** [comment]
Hi @skuriyadi this error is documented [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#i-received-an-error-error-invalid-for_each-argument-). As documented there, this is an issue in [Terraform Core](https://github.com/hashicorp/terraform/issues/4149).

If you remove the `depends_on` in your module definition like suggested this error should go away. On the flip side, you may have to do multiple passes over your terraform `apply` and `destroy`.

**Comment by grid-dev** [comment]
@askulkarni2 As this code is coming from the module, what are you usually doing to circumvent it here? As removing the dependency seems not really a solution.

**Comment by skuriyadi** [comment]
@askulkarni2 , I will continue using the older version for now, I guess the solution which is provided will beat the purpose of creating a complete automated infra setup.
Thank you,
Shiva

**Comment by bryantbiggs** [comment]
@skuriyadi can you share you current configuration?

**Comment by skuriyadi** [comment]
Hi @bryantbiggs  I am using your module to create a EKS cluster with managed nodegroup and your addon module.
Sorry, I wont be able to share the configuration.

Thank you!

**Comment by grid-dev** [comment]
A bit unsatisfying, but thanks for your responses

**Comment by bryantbiggs** [comment]
there has been some recent movement on this issue so hopefully improvements in Terraform core are coming soon https://github.com/hashicorp/terraform/issues/30937

**Comment by skuriyadi** [comment]
HI @bryantbiggs , 
Please let me know if here any update on this?

**Comment by bryantbiggs** [comment]
Hi @skuriyadi - you can track the progress in the linked issue above https://github.com/hashicorp/terraform/issues/30937

**Comment by domeales-paloit** [comment]
I also had this issue. It turned up when I added a `depends_on` argument on the module resource using this module.

I worked out that if remove the `depends_on` and use an implicit dependency by using the outputs of the upstream resource in the `tags` of this module.

It worked for me. Bit of a hack, but I moved forward at least.

**Comment by bryantbiggs** [comment]
Please see https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1319

This has been resolved in v19 of the `terraform-aws-eks` module
