### ISSUE TITLE
[FEATURE] Support additional add-on application repos in ArgoCD

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#513]
#### Is your feature request related to a problem? Please describe
At the moment you can not create a second addon repo that can utilize the `enable_${addon_name}` switch the same way as the standard one identified with the `add_on_application  = true` argument. Using this on two argcd_applications does not work, and you can't pass in your custom helm values.

It appears like the primary reason that this doesn't work is that the list of addons is hard-coded in the argocd addon module and this block can not be passed in directly from what I have gathered:

```hcl
  set {
    name = "source.helm.values"
    value = yamlencode(merge(
      { repo_url = each.value.repo_url },
      each.value.values,
      local.global_application_values,
      each.value.add_on_application ? var.addon_config : {}
    ))
  }
```

#### Describe the solution you'd like

It would be nice to make it possible for an organization to easily mix-in it's own add-ons with the add-ons provided upstream without needing to fork the repo.

#### Describe alternatives you've considered
Not making them add-ons that can be enabled/disabled and just using ArgoCD in the normal fashion.

**Comment by bryantbiggs** [comment]
thank you for the issue! At this time we are re-evaluating the integration between Terraform and GitOps operators like ArgoCD. We have removed the integration from the current project and will be tracking all feedback input in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/114 while developing the next iteration of this integration
