### ISSUE TITLE
[Bug]: External DNS cannot find other account domain

### ISSUE THREAD

**Issue by loicvolle** [aws-ia/terraform-aws-eks-blueprints#516]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.0.4

### What is your environment, configuration and the example used?

Terraform 1.0.9
EKS 1.22
IAM configuration for shared service account hosting the domain done with another provider

```hcl
  enable_external_dns        = true
  eks_cluster_domain         = var.route53_external_zone_id
  external_dns_irsa_policies = [module.external_dns_irsa_role.iam_role_arn]
  external_dns_helm_config = {
    version = "1.9.0"
  }
```

### What did you do and What did you see instead?

```sh
 Error: no matching Route53Zone found
│ 
│   with module.eks_blueprints_kubernetes_addons.module.external_dns[0].data.aws_route53_zone.selected,
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/external-dns/data.tf line 1, in data "aws_route53_zone" "selected":
│    1: data "aws_route53_zone" "selected" {
│ 
```

I was expecting to get a parameter to override it or an assume policy

### Additional Information

External provider :

```hcl
resource "aws_iam_openid_connect_provider" "eks_provider" {
  provider = aws.ssvc
  url      = "https://${module.eks_blueprints.eks_oidc_issuer_url}"

  client_id_list = ["sts.amazonaws.com"]

  thumbprint_list = []
}

module "external_dns_irsa_role" {
  providers                     = { aws = aws.ssvc }
  source                        = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version                       = "4.24.0"
  role_name                     = "${var.APPLI}-${var.ENV}-external-dns"
  attach_external_dns_policy    = true
  external_dns_hosted_zone_arns = ["arn:aws:route53:::hostedzone/${var.route53_external_zone_id}"]

  oidc_providers = {
    ex = {
      provider_arn               = aws_iam_openid_connect_provider.eks_provider.arn
      namespace_service_accounts = ["kube-system:external-dns"]
    }
  }
}
```

**Comment by fbreckle** [comment]
is the zone you want to use as cluster zone private?

**Comment by loicvolle** [comment]
yes that zone is private

**Comment by bryantbiggs** [comment]
your example is close but we'll have to make some changes to support this - in this repo we'll have to allow disabling the IRSA role we create here and allow users to pass in the externally created IRSA role from the external account 

Ref: https://aws.amazon.com/blogs/containers/cross-account-iam-roles-for-kubernetes-service-accounts/

**Comment by fbreckle** [comment]
We just put "private = true" in https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/external-dns/data.tf
