### ISSUE TITLE
[Bug]: CNI does not accept a version

### ISSUE THREAD

**Issue by srhoton** [aws-ia/terraform-aws-eks-blueprints#519]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.0.4

### What is your environment, configuration and the example used?

$ terraform --version
Terraform v1.1.9
on darwin_amd64

Setting up the CNI addon with the exact syntax in the docs (https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/managed-add-ons/), i.e.: 

`  amazon_eks_vpc_cni_config = {
    addon_name               = "vpc-cni"
    addon_version            = "v1.10.1-eksbuild.1"
    service_account          = "aws-node"
    resolve_conflicts        = "OVERWRITE"
    namespace                = "kube-system"
    additional_iam_policies  = []
    service_account_role_arn = ""
    tags                     = {}
  }`

### What did you do and What did you see instead?

This appears to error out asking for a semantic version on a plan: 

`
│ Error: invalid value for addon_version (must follow semantic version format)
│ 
│   with module.kubernetes_addons.module.aws_vpc_cni[0].aws_eks_addon.vpc_cni,
│   on .terraform/modules/kubernetes_addons/modules/kubernetes-addons/aws-vpc-cni/main.tf line 4, in resource "aws_eks_addon" "vpc_cni":
│    4:   addon_version            = local.addon_config["addon_version"]
│ 
`

Even providing an actual semantic version here (i.e. "1.10.1") results in the same error. Other add-ons (coredns, kube-proxy) follow the documentations format for the version.

**Comment by bryantbiggs** [comment]
Hi @srhoton - is there a specific version you are looking to use? Could you try the following and see if this resolves your issue:

```hcl
data "aws_eks_addon_version" "this" {
  addon_name         = "vpc-cni"
  kubernetes_version = "1.21" # Set this to your current cluster version
  most_recent        = true # flip to `false` to use default version for cluster version
}

module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.0.4"

  eks_cluster_id               = module.eks_blueprints.eks_cluster_id
  eks_worker_security_group_id = module.eks_blueprints.worker_node_security_group_id
  auto_scaling_group_names     = module.eks_blueprints.self_managed_node_group_autoscaling_groups

  enable_amazon_eks_vpc_cni = true
  amazon_eks_vpc_cni_config = {
    addon_name               = "vpc-cni"
    addon_version            = data.aws_eks_addon_version.this.version
  }
  ... 
}
```

**Comment by srhoton** [comment]
Hi! That got it. Just for my knowledge, should we always be deploying the aws add-ons with a data block like that, or is this specific to the CNI? Thanks!

**Comment by bryantbiggs** [comment]
Hey @srhoton - awesome, glad that worked. 

> should we always be deploying the aws add-ons with a data block like that, or is this specific to the CNI?

No; this has highlighted an issue we need to resolve regarding how we handle default addon versions prescribed. I have something in progress to solve this and it should be fixed soon, but for now the data source should offer you a workaround to get unblocked. Thank you again for reporting and verifying!
