### ISSUE TITLE
[ADDON]Will be good to have SMB CSI driver add-on on this blueprint

### ISSUE THREAD

**Issue by ARivoliRam** [aws-ia/terraform-aws-eks-blueprints#522]
Will be good to have SMB CSI driver add-on on this blueprint

**Comment by bryantbiggs** [comment]
Thanks @ARivoliRam - would you mind sharing your use case? What workloads are you running on K8s that requires the SMB driver? Thank you!

**Comment by ARivoliRam** [comment]
our workload connects to file share which is running in datacenter. our pod need connects to the smb file share.
