### ISSUE TITLE
[FEATURE] Remove dependency on terraform-aws-eks

### ISSUE THREAD

**Issue by stevehipwell** [aws-ia/terraform-aws-eks-blueprints#538]
#### Is your feature request related to a problem? Please describe
The use of the [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) module is problematic for a couple of reasons both technical and cultural.

Firstly wrapping a complex Terraform module in another complex module makes the resultant code exponentially harder to understand, made even worse by needing to jump between two repos to follow the code paths. As the terraform-aws-eks module has a number of architectural issues that you need to work around you end up having to put almost as much work in to fixing these as it would have taken to write the code from scratch but you don't get a clean implementation. All of this means that anyone starting here as a beginner is going to find it harder to increase their knowledge by reading the code than it should be.

Secondly, and more importantly, ever since just before v18 of terraform-aws-eks was released the module is no longer operating as a "community" and the maintainers have not behaved in a way that is conducive to it being one. I don't want to air dirty laundry in public, and until I discovered that AWS was using the module I was happy to just stop contributing, but now that AWS has made this module feel "official" I feel that I need to bring this up. The way that the v18 release was made, the functionality it removed, the closing of all issues and PRs and the way users who questioned this were spoken to was very much not OK and not how a community should operate. After this happened I made an attempt to work with the module and the maintainers a few times but each time it was made clear that the project was theirs and that only their opinions mattered. I don't think that this behaviour is something that an organisation like AWS should condone let alone promote?

#### Describe the solution you'd like
I'd like the terraform-aws-eks module dependency to be removed and the implementation to be written directly in this module.

#### Describe alternatives you've considered
n/a

#### Additional context
I'd be interested in if you started using terraform-aws-eks before or after the v18 release?

**Comment by stevehipwell** [comment]
CC @kcoleman731

**Comment by spotaws** [comment]
I just want to better understand the concern here. Is the issue you have with terraform-aws-eks technical, political/social, or both?

**Comment by stevehipwell** [comment]
@spotaws both, but I probably wouldn't have taken the time to open an issue on a project that I only have a passing academic interest in if it was only technical.

**Comment by kcoleman731** [comment]
Hi @stevehipwell - thank you taking the time write this issue and share your concern. At this time, we don't have plans to remove the dependency on the [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) module.
