### ISSUE TITLE
[EXAMPLES] - Update source path

### ISSUE THREAD

**Issue by kcoleman731** [aws-ia/terraform-aws-eks-blueprints#542]
In each example, we currently use relative paths for module sources. Example [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/main.tf#L75). 

Tasks

- [ ]  **Update Source Urls** - we should switch to using git urls (and eventually terraform registry urls) and specific version tags, so that it is easier for customers to bring code into their own terraform project. 
- [ ] **Update CI** - we want to ensure that our CI still runs against source on each branch, so we will need to replace module source in CI to reference relative paths.  
- [ ] **Add Release Automation** - to ensure that source paths are updated to use the latest version on new releases.

**Comment by askulkarni2** [comment]
Working on it.
