### ISSUE TITLE
[FEATURE] Blueprint for serverless Fargate cluster

### ISSUE THREAD

**Issue by bryantbiggs** [aws-ia/terraform-aws-eks-blueprints#549]
#### Is your feature request related to a problem? Please describe
- A blueprint that demonstrates how to create a serverless based EKS cluster using Fargate profiles. This solution will rely on showing users how they need to manage patching CoreDNS to avoid having to run an EC2 based node for essential addons

#### Describe the solution you'd like
- Blueprint of EKS cluster with Fargate profiles for data plane

#### Describe alternatives you've considered
- None

**Comment by FernandoMiguel** [comment]
We use this
```
resource "null_resource" "patch_coredns" {
  count = var.fargate_create ? 1 : 0

  triggers = {
    cmd_patch = <<-EOT
      ## TODO : replace with token
      aws eks --region "${var.aws_region}" update-kubeconfig --name "${data.aws_eks_cluster.this.id}"
      kubectl patch deployment coredns \
        -n kube-system \
        --type json \
        -p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
      kubectl rollout restart -n kube-system deployment coredns
    EOT
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = self.triggers.cmd_patch
  }

  depends_on = [
    module.fargate_profiles,
  ]
}
```
after that, we instal coredns addon
