### ISSUE TITLE
[FEATURE] introduction of nullable argument in variables

### ISSUE THREAD

**Issue by FernandoMiguel** [aws-ia/terraform-aws-eks-blueprints#567]
#### Is your feature request related to a problem? Please describe
For many practitioners using external modules, they end up having to copy the module `variables.tf` and their default values.
This can be cumbersome, and if upstream changes the default values, hard for downstream to keep up. 

#### Describe the solution you'd like
Terraform 1.1 introduced the concept of nullable
https://www.terraform.io/language/values/variables#disallowing-null-input-values
This means that for the variables in the module with already set default values, the downstream root module wont have to set a default, and can just have a `null`, and the apply run will work as expect

#### Additional context
If this is accepted, I am willing to provide a PR updating https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/variables.tf with the argument `nullable=false` in all places a default is set.

There is only one pesky problem, that this requires terraform v1.1 as min, which would mean this module would jump from 1.0 to 1.1
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/versions.tf#L2

**Comment by FernandoMiguel** [comment]
is there any interest in this ?

**Comment by bryantbiggs** [comment]
hey @FernandoMiguel - could you share the value proposition of this addition?

**Comment by FernandoMiguel** [comment]
@bryantbiggs This means that for the variables in the module with already set default values, the downstream root module wont have to set a default, and can just have a null, and the apply run will work as expect.
Do you feel this adds value, and reduce overhead for practitioners?

**Comment by FernandoMiguel** [comment]
the root module is what the practitioners write on their own side.
I was going to show with the examples from this module, https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/variables.tf
but that one is pretty empty.

Most modules I see, folks copy the external module variables.tf to their own root module, so they can tweak all and any options they want.
and by doing that, they will also have to copy the default values, even if they dont want to change them.

with `nullable = false` added to this module `variables.tf`, practitioners would not need to do that.

**Comment by bryantbiggs** [comment]
why would users who are utilizing the module copy the `variables.tf`? If you don't copy the `variables.tf` then you achieve the same outcome that you are seeking - the defaults provided by the module will be used unless you opt in to providing a different value for the exposed variables - correct?

**Comment by bryantbiggs** [comment]
Thanks for surfacing this @FernandoMiguel but I think at this point we will not bring this into the project. We can always re-visit in the future if there are strong use cases for supporting this. Thank you again!

**Comment by FernandoMiguel** [comment]
hi @bryantbiggs 
here's an example
prior to https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/634 being merged, those chart versions defaulted to very old versions.
our karpenter module using blueprints, uses a variable to allow to set the version
```hcl
module "eks_blueprints_kubernetes_addons_karpenter" {
  source = "git::ssh://git@github.com/aws-ia/terraform-aws-eks-blueprints.git//modules/kubernetes-addons?ref=v4.0.10"

  eks_cluster_id   = var.eks_cluster_id
  enable_karpenter = true
  karpenter_helm_config = {
    cleanup_on_fail = true
    force_update    = true
    replace         = true
    version         = var.karpenter_helm_config_version
  }

}

variable "karpenter_helm_config_version" {
  type     = string
  default  = "0.11.1"
  nullable = false
}
```

but if blueprints track newer versions often, all we need to do is to track blueprints releases instead of the charts.
that means we can set our var default to `null` and if there is `nullable` enabled in blueprints and this value is used instead https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/karpenter/locals.tf#L20
if nullable is not available, we either have to not have any code since it would override (even with null) the blueprints default, or we would have to track it in two places (chart and blueprints version).

Hope this help understand the benefits of this little unknown but super useful feature.
