### ISSUE TITLE
Error: context deadline exceeded: when destroying 'eks-cluster-with-new-vpc"

### ISSUE THREAD

**Issue by markl11** [aws-ia/terraform-aws-eks-blueprints#573]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-new-vpc

### What is your environment, configuration and the example used?

I just deployed the Terraform as instructed here:

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-new-vpc

### What did you do and What did you see instead?

I just did 'terraform apply' which works fine, but when I try to destroy it I get the following error:

Error: context deadline exceeded

**Comment by bryantbiggs** [comment]
The examples provided include all the resources to bring up the example cluster and its resources. Normally, things like VPC and cluster would be in separate statefiles. The recommendation to avoid this issue is to destroy using targets such as:
```bash
terraform destroy -target module.eks_blueprints_kuberenetes_addons
terraform destroy -target module.eks_blueprints
terraform destroy
```

**Comment by kcoleman731** [comment]
@markl11 the approach is outlined in our [Getting Started guide](https://aws-ia.github.io/terraform-aws-eks-blueprints/getting-started/#cleanup). We are in the process of updating READMEs for each our our examples to reflect this approach as well.

**Comment by SemperRuminare** [comment]
@kcoleman731 It looks like your example in the getting started guide has typos that say "terraform apply -target="module.eks_blueprints"" instead of terraform destroy for the last two commands.
