### ISSUE TITLE
[FEATURE] Cilium as a replacement of Amazon VPC CNI

### ISSUE THREAD

**Issue by ruzickap** [aws-ia/terraform-aws-eks-blueprints#581]
#### Is your feature request related to a problem? Please describe
Is it possible to add the functionality to install Cilium into Amazon EKS instead of Amazon VPC CNI? 

Details: https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-default/

#### Describe the solution you'd like
I would like to use Cilium as a default CNI instead of "Amazon VPC CNI".

**Comment by bryantbiggs** [comment]
I believe between the following, this is already covered:
- #436
- #439
- #523

**Comment by ruzickap** [comment]
Maybe...

The addons mentioned above are about installing Cilium / Calico on top of existing Amazon VPC CNI.

This issue is about installing Cilium as replacement of "Amazon VPC CNI".

But let me mentioned it in the Issues to clarify...

**Comment by taliesins** [comment]
I am giving it my best go with replacing AWS CNI with Cilium. This might prove helpful: https://github.com/taliesins/terraform-provider-cleaneks. Strips out all the mandatory AWS installed stuff in your cluster and returns the ip address used for CoreDNS (the dns ip configured on all the managed nodes, so you want your new DNS server to be on this ip)

I have been able to bootstrap the cluster to install ArgoCD (Cilium, CoreDNS and ArgoCD) using helm release and marking all attributes as ignore change and then using ArgoCD to install Cilium, CoreDNS and ArgoCD over itself using app of apps style.

The main issue I am running into now is that master nodes don't seem to have access to Cilium overlay network, so the webhook for cert-manager is not working as expected. The issue: https://medium.com/@denisstortisilva/kubernetes-eks-calico-and-custom-admission-webhooks-a2956b49bd0d
