### ISSUE TITLE
[QUESTION] Is it possible a direct usage of the helm-addon from the Terraform code?

### ISSUE THREAD

**Issue by it-praktyk** [aws-ia/terraform-aws-eks-blueprints#590]
I've created a separate add-on for that helm (with all required a boilerplate code) but I'm curious if is it possible to do in more direct way.

I try to install a third-party helm chart using directly the helm-addon add-on.

Does the helm-addon is intended to use in this way as well?

If it's possible, please provide an example.

Thank you in advance.

**Comment by askulkarni2** [comment]
Documented in #614

**Comment by it-praktyk** [comment]
Thank you for your answer and updated documentation.
