### ISSUE TITLE
[Bug]: examples/eks-cluster-with-new-vpc doesn't create a fargate profile 

### ISSUE THREAD

**Issue by cer** [aws-ia/terraform-aws-eks-blueprints#608]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

latest

### What is your environment, configuration and the example used?

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/README.md?plain=1#L7

### What did you do and What did you see instead?

Claims to create a fargate profile: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/README.md?plain=1#L7

But only creates a managed node group

**Comment by vara-bonthu** [comment]
Thanks @cer . Its a documentation issue. This [example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/main.tf) only creates one managed node group. Please feel to raise PR for doc fix.

If you are looking for fargate examples then you can refer to https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/node-groups/fargate-profiles
