### ISSUE TITLE
[QUESTION] Existing EKS support?

### ISSUE THREAD

**Issue by tomerleib** [aws-ia/terraform-aws-eks-blueprints#624]
#### Please describe your question here

Is it possible to use the blueprints here for existing environments, or at least some of the submodules?
#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by FernandoMiguel** [comment]
yep. we do that. we have our own cluster module and our own addons, and add things from blueprints that are useful for us, without the need for us to write adicional code

**Comment by askulkarni2** [comment]
@tomerleib as @FernandoMiguel its certainly possible. Out of curiousity, what (sub)modules are you interested in using?

**Comment by askulkarni2** [comment]
@tomerleib see this [example](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/upstream-with-k8s-addons) we recently added to demonstrate how you can use kubernetes-addons module with the upstream terraform-aws-eks module. Hope this answers your question. If not please, feel free to reopen.
