### ISSUE TITLE
[QUESTION] <How to create managed_node_groups on an existing EKS cluster >

### ISSUE THREAD

**Issue by yaoluoye** [aws-ia/terraform-aws-eks-blueprints#632]
I had an EKS cluster and want to create some managed_node_groups on it, how to do that?

**Comment by yaoluoye** [comment]
I tried many times today and finally did it. The problem is the file `eks_blueprints/modules/aws-eks-managed-node-group/main.tf` has issue, the variable `cluster_name = var.context.eks_cluster_id` got empty string, I gave it a static string and succeed.

**Comment by FernandoMiguel** [comment]
that is fixed in main.
4.0.9 is broken
