### ISSUE TITLE
[QUESTION] Experimental feature "module_variable_optional_attrs" generates a warning

### ISSUE THREAD

**Issue by muram** [aws-ia/terraform-aws-eks-blueprints#635]
#### Please describe your question here
There are currently three modules with experiments enabled (see link below) which generates a warning on every `terraform plan` or `terraform apply`. 

1. What's the intention behind this feature?
2. Is this a hard requirement or a workaround?
3. Would this cause any future breaking changes may appear even in minor and patch releases?

#### Provide a link to the example related to the question
https://github.com/aws-ia/terraform-aws-eks-blueprints/search?q=experiments

#### Additional context

```
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on .terraform/modules/eks_blueprints_kubernetes_addons.ondat/locals.tf line 2, in terraform:
│    2:   experiments = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│
│ (and 75 more similar warnings elsewhere)
╵
```

Related open issue with TF: https://github.com/hashicorp/terraform/issues/30965

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by bryantbiggs** [comment]
apologies @muram - this is a warning generated by Terraform core thats simply an "info" to users that optional attributes (experiments) are enabled. This should be resolved soon for users that are able to utilize Terraform v1.3 once its released https://github.com/hashicorp/terraform/releases/tag/v1.3.0-alpha20220608

**Comment by pachico** [comment]
with Terraform 1.3 it actually fails.
@bryantbiggs , do you perhaps mean that there's a new branch being cooked that will make it work with Terraform 1.3?

**Comment by bryantbiggs** [comment]
yes, this was meant to be resolved with v5 that has not shipped yet https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/659
