### ISSUE TITLE
[Bug]: Huge number of new nodes created while upgrading cluster

### ISSUE THREAD

**Issue by szkbury** [aws-ia/terraform-aws-eks-blueprints#637]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.0.9

### What is your environment, configuration and the example used?

I have a test cluster created by blueprint **v4.0.9** with 2 node groups and 1 node per each group = two nodes - m5.large instances.
The cluster is fresh - created today, version is 1.21, **13 pods** (just the addons installed by blueprint: 
amazon_eks_kube_proxy
amazon_eks_coredns
aws_load_balancer_controller
metrics_server
aws_cloudwatch_metrics
amazon_eks_aws_ebs_csi_driver
)

I am testing upgrade from 1.21 to 1.22 changing cluster_version to 1.22 and calling terraform apply.

While upgrading the node groups I observed a huge number of newly created nodes - starting from 2 old I reached **2 old + 10 new nodes !!!** 

then 2 old nodes were terminated, then number of new nodes was decreased down to 2 new nodes...

Whole node groups upgrade took 28 minutes

### What did you do and What did you see instead?

Standard AWS EKS upgrade used to create **the same number of new nodes as old nodes** assuming the same instance type

Here I'm afraid what would happen if I have 10, 100, 1000 nodes

**Comment by bryantbiggs** [comment]
hi @szkbury - have you seen this documentation on updating EKS managed node groups https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html ?

**Comment by bryantbiggs** [comment]
hey @szkbury I'm going to close this issue out since its not related to the project here - please see the doc linked above to understand the rolling upgrade process and how to control the number of nodes provisioned during the process
