### ISSUE TITLE
CoreDNS addon takes at least 15minutes to complete

### ISSUE THREAD

**Issue by tanvp112** [aws-ia/terraform-aws-eks-blueprints#642]
#### Please describe your question here

When provision new cluster using the module, the coredns addon always take 15 minutes to complete, despite that the coredns pods are already running with healthy state. Similar behavior is seen for ebs-csi addon. But kube-proxy and vpc-cni are working fine (soon as the pods passed readiness check, terraform returned these 2 addons are ready).

Is there additional settings required to make coredns and ebs-csi addons complete as soon as it is ready?

#### Provide link to the example related to the question

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/19d88272b5108e73ed1159ccc5f256f949189f28/examples/complete-kubernetes-addons/main.tf#L173

#### Additional context

N/A.

#### More

- [ ] Yes, I have checked the repo for existing issues before raising this question

Yes, no existing issue found.

**Comment by FernandoMiguel** [comment]
did your cluster have nodes available?
is it ec2 or fargate?

**Comment by bryantbiggs** [comment]
hi @tanvp112 - unfortunately there isn't anything else that can be done at this time, this is the nature of what is typically experienced with these two addons when deploying a new cluster. Please let us know if there are any other questions though
