### ISSUE TITLE
[FEATURE] what if one application team use two namespace?

### ISSUE THREAD

**Issue by Hokwang** [aws-ia/terraform-aws-eks-blueprints#647]
#### Please describe your question here
Hi,

I have few questions.

Q1. In my case, there are one app dev team and one platform team,
app dev team use two namespace,
How can I do?

I think you need to make one more depth like,
```
application_teams = {
  "team1" = {
    "namespace1" = {
      "label"
      "quota"
    }
    "namespace2" = {
      "label"
      "quota"
    }
  }
}
```
so that you can 
- create one cluster_role for `team1`
- use `team1` to cluster_role_binding's Group name.
- create one irsa for `team`
- in this case, create only cluster role, not role, and create role bindings for each namespaces.

Q2. when I want to add more rules in role,
for example, there's no "pods/log" so I want to add this.
But now, your `aws-eks-teams` module does not support this.

Q3. there's no `managed_policy_arns` in `aws_iam_role.team_sa_irsa`
so I can't attach policy easily.

[Y] Yes, I have checked the repo for existing issues before raising this question

**Comment by Hokwang** [comment]
@Zvikan Could you review this FR?
How to update teams module?

**Comment by bryantbiggs** [comment]
this is referenced in the re-design issue #842 so closing out to clear things up
