### ISSUE TITLE
[QUESTION] aws_node_termination_handler and karpenter

### ISSUE THREAD

**Issue by FernandoMiguel** [aws-ia/terraform-aws-eks-blueprints#661]
#### Please describe your question here
How does aws_node_termination_handler addon and karpenter work?
I see in the code at https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/793504a213662333a8e2e561e23fef2f650d82ff/modules/kubernetes-addons/main.tf#L122 
that if ASG **or** karpenter are enabled , this addon can be made enabled.
but while ASG do use , well...., ASG, karpenter nodes are individual instances.

Does it require us to manually tag those instances by adding this tag?
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/793504a213662333a8e2e561e23fef2f650d82ff/modules/kubernetes-addons/aws-node-termination-handler/main.tf#L24-L27

#### Provide link to the example related to the question
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/793504a213662333a8e2e561e23fef2f650d82ff/modules/kubernetes-addons/main.tf#L122

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by mleklund** [comment]
I modified the NTH to match the resiliency section [this blog entry](https://aws.amazon.com/blogs/containers/using-amazon-ec2-spot-instances-with-karpenter/)
