### ISSUE TITLE
[QUESTION] Custom namespace for argocd application?

### ISSUE THREAD

**Issue by jorfermo** [aws-ia/terraform-aws-eks-blueprints#663]
#### Please describe your question here
Is there any way to set a custom namespace per each argocd application? It seems to me it's "hardcoded" to the argocd deployment namespace, but I wanted to make sure I'm not missing something.

#### Provide link to the example related to the question
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/c459a963d92f11b41f4c9fc5f40c7a279fe01be1/modules/kubernetes-addons/argocd/main.tf#L25

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by spkane** [comment]
```hcl
 argocd_helm_config = {
  namespace = "different"
}
```

Similar to this and some of the other addon examples:
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/complete-kubernetes-addons/main.tf#L195

**Comment by jorfermo** [comment]
Yes, but that would set the same namespace for argocd and every application installed through it, right? My question was if it's possible to define the namespace for every application installed through argocd.

**Comment by bryantbiggs** [comment]
resolved in #595
