### ISSUE TITLE
[QUESTION] set tag at EC2 level

### ISSUE THREAD

**Issue by hugueslepesant** [aws-ia/terraform-aws-eks-blueprints#676]
#### Please describe your question here
I would like to use terraform-aws-eks-blueprints to deploy some EKS cluster in AWS.
And I need to put some specific tags at EC2 level, and somewhere else.

How can I do that ?

#### Additional context
The specific tag is "map-migrated", as my customer has integrated the AWS MAP program.
So I need to tag AWS resources with the tag "map-migrated".
All the resources can't be tagged with this tag.
See [MAP-Included-Services-List](https://s3-us-west-2.amazonaws.com/map-2.0-customer-documentation/included-services/MAP-Included-Services-List.pdf) for more details.

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by hugueslepesant** [comment]
An alternative is to create a aws_autoscaling_group_tag, as : 

```
data "aws_autoscaling_groups" "eks_node_group" {
  filter {
    name   = "tag:eks:cluster-name"
    values = [local.cluster_name]
  }
}

resource "aws_autoscaling_group_tag" "mg_t3" {

  for_each = toset(data.aws_autoscaling_groups.eks_node_group.names)

  autoscaling_group_name = each.value

  tag {
    key = "map-migrated"
    value = local.server_id
    propagate_at_launch = true
  }
}
```

**Comment by FernandoMiguel** [comment]
this will only impact newer launched instances. 
existing/initial VMs won't have these additional tags, which might prevent selectors from working.
