### ISSUE TITLE
[Bug]: Nginx_ingress not able to install

### ISSUE THREAD

**Issue by s9r-5** [aws-ia/terraform-aws-eks-blueprints#682]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.0.9

### What is your environment, configuration and the example used?

module "eks_kubernetes_addons" {
  source         = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons"
  
  eks_cluster_id = module.eks_addon.eks_cluster_id

  # EKS Managed Add-ons
  enable_amazon_eks_coredns    = true
  enable_amazon_eks_kube_proxy = true
# Ingress 
  enable_ingress_nginx = true
  ingress_nginx_helm_config = {
    version = "4.1.4"
    values  = [templatefile("${path.module}/helm_values/nginx_values.yaml", {})]
  }
  # K8s Add-ons
  enable_aws_load_balancer_controller = true
  enable_metrics_server               = true
  enable_cluster_autoscaler           = true
  enable_aws_efs_csi_driver           = false
 # Prometheus and Amazon Managed Prometheus integration
  enable_prometheus                    = true
  enable_amazon_prometheus             = false
  amazon_prometheus_workspace_endpoint = module.prometheus.workspace_prometheus_endpoint

  # Fluentbit integration
  enable_aws_for_fluentbit = true
  aws_for_fluentbit_helm_config = {
    name                                      = "aws-for-fluent-bit"
    chart                                     = "aws-for-fluent-bit"
    repository                                = "https://aws.github.io/eks-charts"
    version                                   = "0.1.0"
    namespace                                 = "logging"
    aws_for_fluent_bit_cw_log_group           = "/${module.eks_addon.eks_cluster_id}/worker-fluentbit-logs" # Optional
    aws_for_fluentbit_cwlog_retention_in_days = 90
    create_namespace                          = true
    values = [templatefile("${path.module}/helm_values/fluentbit-values.yaml", {
      region                          = var.region_name
      aws_for_fluent_bit_cw_log_group = "/${module.eks_addon.eks_cluster_id}/worker-fluentbit-logs"
    })]
    set = [
      {
        name  = "nodeSelector.kubernetes\\.io/os"
        value = "linux"
      }
    ]
  }

### What did you do and What did you see instead?

I tried searching in issue and google but no luck. 

### Additional Information

```shell
Other charts are working properly.

Error: release ingress-nginx failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
with module.**********.module.ingress_nginx[0].module.helm_addon.helm_release.addon[0]
on .terraform/modules/********/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
resource "helm_release" "addon" {
```

**Comment by s9r-5** [comment]
I tried to look into it . Deployment is not able to create load balancer with external ip .

ingress-nginx-controller             LoadBalancer   172.00.00.00   <pending>     80:30222/TCP,443:32457/TCP   4m35s

**Comment by Zvikan** [comment]
hey @s9r-5 , while working on https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/683 i'll look into this.

**Comment by Zvikan** [comment]
Unable to reproduce the issue with latest main SHA, going to try again with 4.0.9, I couldn't see any related changes to lb controller/nginx that may affect this from >4.0.9 .

**Comment by Zvikan** [comment]
Unable to reproduce with 4.0.9.
@s9r-5 , can you please try the following:
- re-create the addons module, you can do so by running:
```
terraform destroy -target="module.eks_blueprints_kubernetes_addons" -auto-approve
```
Then:
```
terraform apply -target="module.eks_blueprints_kubernetes_addons" -auto-approve
```

If the timeout still occurs, check the helm release status (`helm ls -A -a` and you can also check the overall events).
If problem still persists, let us know.

**Comment by s9r-5** [comment]
Yes , Now it's working. Thanks
