### ISSUE TITLE
[FEATURE] - Simplify usage of kubernetes-addons and IRSA modules

### ISSUE THREAD

**Issue by askulkarni2** [aws-ia/terraform-aws-eks-blueprints#697]

**Comment by askulkarni2** [comment]
@bryantbiggs I am not sure I get it. Are you suggesting removing the kubernetes-addons module?

**Comment by bryantbiggs** [comment]
no, just removing [this](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/locals.tf#L35-L47)

so in an addon sub-module, we can use the data sources for account ID or partition if the sub-module needs it, etc. I think once you strip all that stuff away, the context object is just [this](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/karpenter/main.tf#L107-L110) which we can just pass as variables. For users who use the addons today, there is no change (no-op). But for users who want to use the `helm` module, the `irsa` module, or the addon sub-module directly, they only need to provide a few details and not re-create the whole context object

**Comment by askulkarni2** [comment]
Gotcha. @vara-bonthu @Zvikan correct me if I am wrong, but didn't we have data sources before and ended up removing them because `plan` was taking too long?

**Comment by Zvikan** [comment]
Mostly correct for the IRSA module, the 2nd decision was around DRY practice, see https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/298 for the original motivation.

**Comment by vara-bonthu** [comment]
Add-on context keeps the code clean and also helps to reduce the amount of API calls made of data sources for each add-on. We did this based on the recommendation from Hashicorp devs and we also noticed the improved plan time by call data resources only once at add-ons root module and passing the values a variables to all the add-ons.
