### ISSUE TITLE
[Bug]: `eks_blueprints.module.aws_eks.aws_security_group.node` not being deleted properly due to orphaned ENI(s)

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#699]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

* a421b980c5c7c665ff5c42a805dbe07ecf232d5b

### What is your environment, configuration and the example used?

* terraform 1.2.3

```hcl
module "eks_blueprints" {
  # aws-ia/terraform-aws-eks-blueprints
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=a421b980c5c7c665ff5c42a805dbe07ecf232d5b"

  tags                 = local.tags
  cluster_name = local.cluster_name

  # KMS
  cluster_kms_key_additional_admin_arns = local.cluster_kms_key_additional_admin_arns

  # Auth
  map_roles               = local.map_roles
  application_teams = var.application_teams
  platform_teams     = var.platform_teams

  # EKS Cluster VPC and Subnets
  vpc_id                      = var.vpc_id
  private_subnet_ids = var.private_subnet_ids

  # EKS CONTROL PLANE VARIABLES
  cluster_version                               = var.cluster_version
  cluster_endpoint_private_access = false
  cluster_endpoint_public_access  = true

  # EKS MANAGED NODE GROUPS
  managed_node_groups = local.managed_node_groups

  # Change these according to your security requirements if needed
  node_security_group_additional_rules = local.node_security_group_additional_rules
}
```

### What did you do and What did you see instead?

* After a successful apply:

```sh
$ terraform destroy
...
module.eks_cluster.module.eks_blueprints.module.aws_eks.aws_security_group.node[0]: Still destroying... [id=sg-045d4f0919f27419e, 15m0s elapsed]

│ Error: Error deleting security group: DependencyViolation: resource sg-045d4f0919f27419e has a dependent object
│ 	status code: 400, request id: 7190c7d2-5a08-4415-a9d1-9c56585c08a1
```

<img width="1369" alt="CleanShot 2022-06-27 at 16 31 20@2x" src="https://user-images.githubusercontent.com/129629/176053816-ab2540fe-cf16-4e13-b683-537f26ce0f01.png">

They appear to have been attached to some of the instances from the managed node group, but there is not an ENI for each node that was in the cluster.

At this point, I have tested this twice and ended up with one or two leftover ENIs, which I had to clean up by hand to get the security group to delete.

### Additional Information

The core issue may actually be an issue in the upstream `aws-eks` module.

* https://github.com/terraform-aws-modules/terraform-aws-eks

**Comment by Zvikan** [comment]
This may be related to a known issue - please see https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/KNOWN_ISSUES.md#timeouts-on-destroy

**Comment by askulkarni2** [comment]
Also see https://github.com/aws/amazon-vpc-cni-k8s/issues/1447

**Comment by bryantbiggs** [comment]
closing out issue - please track https://github.com/aws/amazon-vpc-cni-k8s/issues/1447 for updates
