### ISSUE TITLE
[FEATURE] Make it possible to disable namespace creation for ArgoCD

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#704]
#### Is your feature request related to a problem? Please describe

For ArgoCD, I want to make sure the very first refresh, right after the argocd_applications are installed works, but to do this I need to have a few k8s secrets (_with this label: "argocd.argoproj.io/secret-type" : "repository"_) in place so that Argo can read our private Github repos, and to do this, I really need to create the namespace BEFORE the `kubernetes-addons` module is run, to ensure that the secrets exist in the namespace the very first-time ArgoCD tries to connect to the repos.

#### Describe the solution you'd like

It would be great to have something like `argocd_create_namespace = true` as a default that can be overridden. The default behavior is the same as today.

`argocd_create_namespace = false` would skip the namespace creation here:
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/argocd/main.tf#L11-L15

and assume that the namespace already exists.

**Comment by spkane** [comment]
I may be able to take a stab at this in the near future if folks think that it makes sense.

**Comment by spkane** [comment]
@bryantbiggs What are the odds that #595 could include ArgoCD as well, and might get merged in this week? I am nearing the end of my current project and am just hoping to get this one last fix in before I move on to other things.

I am wondering if it would make sense to keep this separate and simply focus on making the ArgoCD namespace optional in this issue.

cc/ @vara-bonthu

**Comment by spkane** [comment]
@bryantbiggs I think that would get the job done. I just need to be able to tell the module not to create the `argocd` namespace, so that I can pre-create it and then drop a secret and config map into it, before the module runs and installs ArgoCD.

I noticed that you were checking to make sure that the namespace wasn't defined as `kube-system`. It might be better to just let it fail naturally if the namespace already exists, since there are other namespaces, like `default`, and some of the others that start with `kube-` which will also result in a failure, if people supply that as the namespace name, and don't disable the namespace creation.

**Comment by bryantbiggs** [comment]
@spkane we merged #595 and will be cutting a release tomorrow - let us know if theres anything additional needed here or feel free to close out the issue, thank you!

**Comment by spkane** [comment]
Thank you @bryantbiggs. This got me what I needed.
