### ISSUE TITLE
How can I ignore changes to kubernetes_config_map.aws_auth[0]?

### ISSUE THREAD

**Issue by tanvp112** [aws-ia/terraform-aws-eks-blueprints#719]
#### Please describe your question here

Similar issue has been found [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1535) but the solution doesn't apply here because aws-auth is always be [created](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/aws-auth-configmap.tf) in `terraform-aws-eks-blueprint`.

#### Provide link to the example related to the question

Applicable to any `terraform-aws-eks-blueprint` cluster with managed node group.

#### Additional context

When performing `terraform apply` (eg. updating addon), the aws-auth will be **reset**:

```
 # module.kubernetes.module.eks.kubernetes_config_map.aws_auth[0] will be updated in-place
  ~ resource "kubernetes_config_map" "aws_auth" {
      ~ data        = {
          ~ "mapRoles"    = <<-EOT
              - - groups:
              -   - system:bootstrappers
              -   - system:nodes
              -   rolearn: arn:aws:iam::<redacted>
              -   username: system:node:{{EC2PrivateDNSName}}
              + - "groups":
              +   - "system:bootstrappers"
              +   - "system:nodes"
              +   "rolearn": "arn:aws:iam::<redacted>:role/<redacted>"
              +   "username": "system:node:{{EC2PrivateDNSName}}"
            EOT
          ~ "mapUsers"    = <<-EOT                 # <---- user added by cluster admin will be removed!
              - - groups:
              -   - system:masters
              -   userarn: arn:aws:iam::<redacted>  # <---- user added by cluster admin will be removed!
              -   username: <redacted>
              - - groups:
              -   - system:masters
              -   userarn: arn:aws:iam::<redacted>  # <---- user added by cluster admin will be removed!
              -   username: <redacted>
              + []    # <---- will be reset!
            EOT
            # (1 unchanged element hidden)
        }
        id          = "kube-system/aws-auth"
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

```

#### More

- [X ] Yes, I have checked the repo for existing issues before raising this question

**Comment by FernandoMiguel** [comment]
the way we have around this is to pass all roles to a module to handle the `aws_auth`, avoiding any of our code to add more roles out of it.
it's really sad there isn't a way to patch it, and the resource only allows to write the all thing.

**Comment by bryantbiggs** [comment]
as @FernandoMiguel stated - these should be added through the `map_users` variable so that Terraform knows of the values and won't try to remove

**Comment by tanvp112** [comment]
Thanks, I have tested this approach;  terraform will still delete the existing entries and (only) re-create the entries declared in the module. It would be great if `terraform-aws-eks-blueprint` can have similar behavior like `manage_aws_auth_configmap`.
