### ISSUE TITLE
[QUESTION] Flag argocd_admin_password_secret_name not working. Am I doing something wrong?

### ISSUE THREAD

**Issue by vale21** [aws-ia/terraform-aws-eks-blueprints#728]
#### Please describe your question here
Hello,

I am trying to set up a custom admin password for ArgoCD. Here is a snippet of what I do:

```
resource "aws_secretsmanager_secret" "argo_pwd" {
  name = "argo-admin-pwd"
}

resource "aws_secretsmanager_secret_version" "argo_pwd_value" {
  secret_id = aws_secretsmanager_secret.argo_pwd.id
  secret_string = jsonencode({
    password = bcrypt("${var.argocd_admin_password}")
  })
}
```

If I provide the name of the resource to the addon module, like

`argocd_admin_password_secret_name  = "argo-admin-pwd"`

I get the following error:

```
│ Error: template: argo-cd/templates/argocd-configs/argocd-secret.yaml:38:72: executing "argo-cd/templates/argocd-configs/argocd-secret.yaml" at <b64enc>: wrong type for value; expected string; got []interface {}
│
│   with module.eks-cluster.module.eks_blueprints_kubernetes_addons.module.argocd[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks-cluster.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│
╵
ERRO[0490] 1 error occurred:
        * exit status 1
```

I don't understand what I am doing wrong. Note that if I override the admin password as a helm value, it works:

```
configs:
  secret:
    argocdServerAdminPassword: "${jsondecode(<...>}"
```

Am I doing something wrong here?

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by vara-bonthu** [comment]
Thanks for raising this issue @vale21 

I have handled this admin password without forcing the Secrets using secrets manager in other PR #746 

I will update ArgoCD example as well with similar approach once the above PR is merged.

You should be able to pass the ArgoCD admin password as

```hcl
enable_argocd = true

argocd_helm_config = {
  set_sensitive = [
    {
      name  = "configs.secret.argocdServerAdminPassword"
      value = data.aws_secretsmanager_secret_version.admin_password_version.secret_string
    }
  ]
}

```
