### ISSUE TITLE
[FEATURE] Create FAQ Readme/Doc

### ISSUE THREAD

**Issue by Zvikan** [aws-ia/terraform-aws-eks-blueprints#739]
As we scale, naturally there will be repeated asked questions, therefore we should have FAQ readme/doc that we can users can use.

Some FAQs on top of my mind to consider:
- Why we suggest using multiple applies with `-target` instead of using depends_on ?
- Why we are using `exec` for k8s provider in the examples?
- While trying to delete the cluster/addons, namespaces get stuck in terminating state and I have to manually delete them, what should I do?

Feel free to comment which more questions that you think should be considered as part of the FAQ doc.

**Comment by cavvaws** [comment]
The minimum required version of software (like awscli) should also be listed

**Comment by bryantbiggs** [comment]
Closed in #769
