### ISSUE TITLE
Replace self-managed node group module

### ISSUE THREAD

**Issue by bryantbiggs** [aws-ia/terraform-aws-eks-blueprints#750]
#### Is your feature request related to a problem? Please describe
- Replace the local implementation of self-managed managed node group with the implementation provided by the `terraform-aws-eks` module https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/self-managed-node-group

#### Describe the solution you'd like
- The local self-managed node group is replaced with https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/modules/self-managed-node-group 

#### Additional context
- Changes that users need to make when upgrading from v4.x to v5.x need to be added to the upgrade guide

**Comment by bkalcho** [comment]
Is it possible in the current implementation of `self_managed_node_groups` to define `desired_size`? I haven't seen it, just `min_size` and `max_size`.

**Comment by bryantbiggs** [comment]
> Is it possible in the current implementation of `self_managed_node_groups` to define `desired_size`? I haven't seen it, just `min_size` and `max_size`.

No - `desired_size` is usually not set or ignored due to the use of autoscaling of the node group. Users are strongly recommended to utilize an autoscaling mechanism such as cluster-autoscaler or karpenter

**Comment by bryantbiggs** [comment]
Closed in #876
