### ISSUE TITLE
Remove warnings from Terraform output

### ISSUE THREAD

**Issue by bryantbiggs** [aws-ia/terraform-aws-eks-blueprints#754]
#### Is your feature request related to a problem? Please describe
- Remove the use of `optional()` attributes that was a Terraform experiment that has been marked for removal in v1.3 
- Resolve any other warnings shown through Terraform output 

#### Describe the solution you'd like
- The end goal will be to make the applied output as clean as possible for users, however we will have to evaluate on a case by case basis for addons

#### Additional context
- Changes that users need to make when upgrading from v4.x to v5.x need to be added to the upgrade guide

**Comment by bkalcho** [comment]
Just for the record. Additional warning:

    Warning: Redundant ignore_changes element
    │ 
    │   on .terraform/modules/eks.aws_eks/main.tf line 298, in resource "aws_eks_addon" "this":
    │  298: resource "aws_eks_addon" "this" {

**Comment by bryantbiggs** [comment]
Thank you @bkalcho - this has been resolved in the upstream module https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2114 and will be remediated here when we bump the version we are using in this project
