### ISSUE TITLE
[ADDON] - Grafana Tempo

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-eks-blueprints#772]
Add support for Grafana Tempo as an add-on.

Ref: https://github.com/grafana/helm-charts/tree/main/charts/tempo

Other implementations:
https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed
https://github.com/grafana/helm-charts/tree/main/charts/tempo-vulture

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Grafana Tempo you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
