### ISSUE TITLE
[ADDON] - kube2iam - IRSA Alternative

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-eks-blueprints#773]
Add support for kube2iam as an add-on.

https://github.com/jtblin/kube2iam

**Comment by ayeks** [comment]
I don't think its wise to add kube2iam to the blueprint because it has only one maintainer and is not updated very often ([yearly releases since 2020](https://github.com/jtblin/kube2iam/tags), [helm chart points to an old version](https://github.com/jtblin/kube2iam/pull/338)).

**Comment by bryantbiggs** [comment]
What would be the motivation for using kube2iam over IAM roles for service accounts?

**Comment by evairmarinho** [comment]
The idea would not be to replace the IRSA. But rather stay as an alternative. I've been using kube2iam for over a year now, and that's what I have experience granting permission to pods on AWS. I don't think I'm the only one who uses this tool. If at least the installation of the addon was in the project it would already help. Regarding the pods, it will be necessary to use the annotations in addons such as cluster-autoscaler.

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use kube2iam you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
