### ISSUE TITLE
Improve discoverability and usability of examples/blueprints

### ISSUE THREAD

**Issue by bryantbiggs** [aws-ia/terraform-aws-eks-blueprints#782]
#### Is your feature request related to a problem? Please describe
- Not a problem, but it could be improved to increase its usefulness

#### Describe the solution you'd like
- Re-evaluate the structure and naming scheme used for examples to improve discoverability. How can we help users who come to the project get to the solution they are looking for quickly and easily? Some questions I have:
  - Should it be a flat structure or a nested structure? Flat is easier for a single pane of glass to quickly scan/search for a solution similar to https://github.com/aws-samples/serverless-patterns but the naming (as usual) will be challenging. Nested makes things appear cleaner under select topics, but then the question always arises of "should this go under topic A or topic B?" Plus topics generally don't align with how clusters are actually provisioned - a cluster would typically have parts of implementations from each topic in one cluster (topics being something like `gitops`, `secrets`, `ingress`, `scalability`, etc.)
  - Should we add to the addons README links to the examples/blueprints that utilize the addon? If someone comes to the project wanting to know how to get Karpenter provisioned, where do they  naturally start from? If its the addon, then having links to various implementations helps them via only 2 hops (1st hop is Karpenter addon - 2nd hop is the implementation that was listed/linked) instead of hunting and searching
  - What is our strategy for examples/blueprints? Right now its a mix of - show how this new addon can be used in a new example (one off example thats really addon specific, not great for a blueprint or reference architecture), or an example is created to show how to achieve a specific outcome (recent ones being `fargate-serverless`, `ipv4-prefix-delegation`, and `vpc-cni-custom-networking`) which is slightly better. However, I think there are larger themes which are not being exposed - instead of `ipv4-prefix-delegation` and `vpc-cni-custom-networking`, what about `jumbo-cluster`, `ip-constrained-environement`, etc., where its not just a single implementation detail but more of a holistic view of all the various components that should be considered along with an example implementation and some information on `why`. The `fully-private-eks-cluster` is a great example of a missed opportunity - simply disabling the cluster public endpoint does not holistically represent a "fully private cluster". We should educate users on how GitOps improves the security posture of a private cluster through the pull model as opposed to the push model, we should show how to enforce network policies by the addition of Calico or Cillium, how to enforce what actions are allowed via Kyverno or OPA Gatekeeper, etc. We call it `fully-private` but I believe its more along the theme of - how should we think about secure clusters, what aspects should be considered, how do the different personas interact with the cluster (devops, admins, developers, auditors, etc.)
  
Some "themes" that I think we could better align the examples around (probably more than what I have listed):
- Data oriented workloads - we have this pretty well covered under `analytics` and can continue to expand on those
- Scalability - not just HPA/VPA/cluster-autoscaler/karpenter but how do you design a cluster to scale and grow for the future, networking is a big part of this (subnet considerations, IPv4 vs IPv6, CNIs and their configurations, etc.) as well as providing guidance on things such as CoreDNS autoscaling, being mindful of addons that are very chatty with the API server, multi-region, multi-cluster, etc.
- DevEx - Clusters with the lowest operational overhead (serverless), guidance on how teams can best interact with the clusters for a "frictionless" experience, how admins can manage multi-tenant clusters/environments, etc. This is also the realm of PaaS with tools like CrossPlane, Backstage, etc., where the end users aren't really aware of the underlying cluster. There are two primary perspectives to keep in mind - the admin persona, and the end user/consumer persona. 
- Security - There are those who will require very stringent controls (public sector, financial, health care, etc.), and there are those that just want to know what security measures they should be aware of, what to consider, and how to implement. mTLS, secret management, access controls, guardrails, auditing, etc.
- Stateful - Most know that stateless clusters are preferred but stateful workloads still exist; how best to manage, which CSI driver should I be using and why, disaster recovery, etc.

Things that are not "themes" but are utilized in all of the situations above and tend to show up in examples. (The conversation is usually "should I use x, y, or z; why?"):
- Ingress controllers
- Observability, monitoring, logging tools
- CNIs
- CSIs
- HPA/VPA/cluster-autoscaler/karpenter

#### Describe alternatives you've considered
- Just thoughts (shared above) so far

#### Additional context
- What are your thoughts? Leave comments below

**Comment by FernandoMiguel** [comment]
one suggestion I would like to contribute, in the examples, use either terraform registry or github url instead of relative path, since many folks won't be using the checked-out module, and finding the right way to write that source, can be complicated for anyone who has not done it before.

**Comment by Zvikan** [comment]
> one suggestion I would like to contribute, in the examples, use either terraform registry or github url instead of relative path, since many folks won't be using the checked-out module, and finding the right way to write that source, can be complicated for anyone who has not done it before.

Working on it @ https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/542

**Comment by bryantbiggs** [comment]
Well ... that's sad
