### ISSUE TITLE
[EXAMPLE]: ArgoCD example missing proper README

### ISSUE THREAD

**Issue by Zvikan** [aws-ia/terraform-aws-eks-blueprints#791]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.5.0

### What is your environment, configuration and the example used?

N/A

### What did you do and What did you see instead?

Currently, the ArgoCD example missing detailed README like the other examples.

**Comment by bryantbiggs** [comment]
closed in #792
