### ISSUE TITLE
Unexpected upstream (v18.26.5) breaking change

### ISSUE THREAD

**Issue by tanvp112** [aws-ia/terraform-aws-eks-blueprints#795]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

v4.5.0

### What is your environment, configuration and the example used?

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/upstream-with-k8s-addons

### What did you do and What did you see instead?

`terraform init` follow by `terraform plan`

```
 Error: Invalid index
│
│   on .terraform/modules/eks/main.tf line 211, in resource "aws_iam_openid_connect_provider" "oidc_provider":
│  211:   thumbprint_list = concat([data.tls_certificate.this[0].certificates[0].sha1_fingerprint], var.custom_oidc_thumbprints)
│     ├────────────────
│     │ data.tls_certificate.this[0].certificates is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```

### Additional Information

```shell
The data object is trying to get certificate from non-existence EKS (not yet create).
```

**Comment by FernandoMiguel** [comment]
I just saw that and was in the process of debug.
thanks for opening the ticket

**Comment by FernandoMiguel** [comment]
FYI this is in another module, not blueprints
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/640a994/main.tf#L211

**Comment by FernandoMiguel** [comment]
here's a bug report there https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2173

**Comment by FernandoMiguel** [comment]
temp fix https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2170#issuecomment-1191922960

**Comment by bryantbiggs** [comment]
https://github.com/hashicorp/terraform-provider-tls/issues/244
