### ISSUE TITLE
[QUESTION] Is it supposed not to use "node_security_group_id" input which already exsisted?

### ISSUE THREAD

**Issue by Leddy92** [aws-ia/terraform-aws-eks-blueprints#809]
#### Please describe your question here
<html>
<body>

create_node_security_group | Determines whether to create a security group for the node groups or use the existing node_security_group_id | bool | true | no
-- | -- | -- | -- | --

I saw the **node_security_group_id** input in README but I couldn't find it in the module aws_eks part in main.tf
Cause I already have several self managed security groups for managing cluster and nodegroup, I wanna reuse them.

### main.tf
```
module "aws_eks" {
...
# Worker Node Security Group
node_security_group_id               = var.node_security_group_id
```

### variable.tf
```
....
#-------------------------------
# Worker Additional Variables
#-------------------------------
variable "node_security_group_id" {
  description = "Security group to be used if creation of node security group is turned off"
  type        = string
  default     = ""
}
```

So, what if I add these blocks for using already-exsisting security groups, anything possibly goes wrong with thes points?

#### Amazon EKS Blueprints Release version
4.6.0

#### Version info I used

Terraform v1.1.6 on linux_amd64

Thank you for reading and sorry for my humble question.

</body>
</html>

**Comment by utk231** [comment]
Facing the same issue. Existing Node security group variable  `node_security_group_id` doesn't seem to be used while creating the node group launch template. The launch template skips the security group attachment and default security group of that VPC gets attached to self managed worker nodes.

`create_node_security_group = false
node_security_group_id    = "<Existing Security group ID>`


Amazon EKS Blueprints Release version

4.11.0

Version info I used

Terraform v1.2.9
on linux_amd64

**Comment by bryantbiggs** [comment]
the node security group created by the module is only used when a custom launch template is used. when the default launch template is used, the EKS managed node group service attaches the cluster primary security group to nodes
