### ISSUE TITLE
[FEATURE] Add-ons to provide IAM role arn and name as outputs and IAM roles have easy to find prefix

### ISSUE THREAD

**Issue by andrewhibbert** [aws-ia/terraform-aws-eks-blueprints#816]
#### Is your feature request related to a problem? Please describe
Would be good if each add on provides the details for the IRSA IAM role as outputs as it is difficult to find the roles as they are `terraform-<uid>`, perhaps a prefix would be good also so it is searchable in the UI

#### Describe the solution you'd like
As above

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by bryantbiggs** [comment]
This is available today https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/irsa/outputs.tf

**Comment by andrewhibbert** [comment]
It also needs to be in the outputs for the other modules though doesn't it - https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/outputs.tf

**Comment by bryantbiggs** [comment]
apologies - this was not clear in the ticket with the lack of detail provided. I will open a PR now

**Comment by bryantbiggs** [comment]
> There were several problems reported too:

Where were these reported?

**Comment by bryantbiggs** [comment]
you have roles named `terraform-*` today?

**Comment by florentio** [comment]
Hello @andrewhibbert this PR https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/908 is supposed to let consumers override the role name of IRSA though via the addons once it is merged.

**Comment by bryantbiggs** [comment]
closed in #1136
