### ISSUE TITLE
[Blueprint] - Multi-cluster monitoring, logging using AMP, AMG, Opensearch

### ISSUE THREAD

**Issue by askulkarni2** [aws-ia/terraform-aws-eks-blueprints#823]
Basically implement [this](https://aws.amazon.com/blogs/mt/build-an-observability-solution-using-managed-aws-services-and-the-opentelemetry-standard/) pattern via a blueprint. TGW can possibly replace the VPC peering as it offers more flexibility.

![image](https://user-images.githubusercontent.com/4845260/184235348-25c68901-7878-46ce-9d54-8d3aa73a9180.png)

**Comment by raviaappala** [comment]
Thanks for opening this case, We are looing for multi-cluster monitoring with centarlized logging using AMP, AMG, OpenSearch.

**Comment by normalfaults** [comment]
@alex-rawman working on a new approach.

**Comment by maiconrocha** [comment]
FYI: https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples/eks-cross-account-with-central-amp

**Comment by bryantbiggs** [comment]
closing - see linked reference above
