### ISSUE TITLE
[QUESTION] That`s possible create EKS Node Groups in existing cluster?

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-eks-blueprints#828]
#### Please describe your question here
That`s possible create EKS Node Groups in existing cluster?

If not, I know that in the next major release the node group module implementation will be replaced by the `terraform-aws-eks` module. For the maintainers, what do you think about giving this option to the user? Does this feature make sense, or in these situations is it better for one to directly call the node group sub-module of `terraform-aws-eks`?

#### Provide link to the example related to the question
https://github.com/terraform-aws-modules/terraform-aws-eks

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by bryantbiggs** [comment]
Would you mind clarifying what the request is please?

**Comment by evairmarinho** [comment]
Can terraform-aws-eks-blueprints create node groups without creating the EKS cluster? That is, creating node groups on an existing EKS cluster.

**Comment by bryantbiggs** [comment]
*can users create node groups for an existing EKS cluster - yes; you can use the sub-modules under this project provided you satisfy the variables required

**Comment by evairmarinho** [comment]
Ok, thanks for attention @bryantbiggs !
