### ISSUE TITLE
[QUESTION] Is it possible to create a single managed node group iam role to be used across all node groups

### ISSUE THREAD

**Issue by dhf22** [aws-ia/terraform-aws-eks-blueprints#831]
I would like to use this module to create a single worker node iam role to be used across all managed node groups. It is currently creating an iam role per managed node group. I know that you are able to pass an externally created iam role to the node group objects to use instead of creating it via this module, but just wondering if it's possible to create a single iam role to be used across all managed node groups.

**Comment by bryantbiggs** [comment]
You can achieve the same outcome by providing an externally created IAM role and passing it into the module

**Comment by dhf22** [comment]
sure, just wanted to confirm it would be external to the module. thanks!
