### ISSUE TITLE
IRSA: Commit 832 breaks IRSA config

### ISSUE THREAD

**Issue by srhoton** [aws-ia/terraform-aws-eks-blueprints#837]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

latest (not running a tagged version)

### What is your environment, configuration and the example used?

Currently using Blueprints for AWS Add-ons with IRSA roles, running against main branch. This morning we started to see weird irsa trust relationships come up in the plans of our clusters: 

` module.kubernetes_addons[0].module.aws_vpc_cni[0].module.irsa_addon[0].aws_iam_role.irsa[0] will be updated in-place
  ~ resource "aws_iam_role" "irsa" {
      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Condition = {
                          ~ StringLike = {
                              - "oidc.eks.us-east-1.amazonaws.com/id/5CF99D8C9D9BAFF88489CB4583BB9782:aud"     = "sts.amazonaws.com" -> null
                              - "oidc.eks.us-east-1.amazonaws.com/id/5CF99D8C9D9BAFF88489CB4583BB9782:sub"     = "system:serviceaccount:kube-system:aws-node" -> null
                              + "oidc.eks.us-east-1.amazonaws.com/id/5CF99D8C9D9BAFF88489CB4583BB9782:sub:aud" = "sts.amazonaws.com"
                              + "oidc.eks.us-east-1.amazonaws.com/id/5CF99D8C9D9BAFF88489CB4583BB9782:sub:sub" = "system:serviceaccount:kube-system:aws-node"
                            }
                        }
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        id                    = "staging-dp-services-use1-1-aws-node-irsa"
        name                  = "staging-dp-services-use1-1-aws-node-irsa"
        tags                  = {}
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }`

### What did you do and What did you see instead?

We did not apply these plans

### Additional Information

```shell
It looks like commit 832 (https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/fb2346f71822bde1f0922e1a4282326f7f14302d) changed lines 40/41 on main/modules/irsa/main.tf, which may be causing this misconfiguration. Just wanted to give everyone a heads up in case it's not just us.
```

**Comment by Zvikan** [comment]
Thank you for reporting this, raised it with the team and https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/839 created, fix inc.

**Comment by srhoton** [comment]
Great - thank you for the fast turn around!
