### ISSUE TITLE
[FEATURE] `teams` next design iteration

### ISSUE THREAD

**Issue by bryantbiggs** [aws-ia/terraform-aws-eks-blueprints#842]
#### Is your feature request related to a problem? Please describe
- This issue will be used to collect feedback and share direction on the next iteration of the `teams` module and its functionality. 

#### Proposed Changes
- Support `n` number of namespaces per team
- Support `n` number of teams - currently `application_team` and `platform_team` 
	- We can provide a default with the current two teams, but allow users to also specify additional teams
- Support for using as standalone module
- Support for [limit ranges](https://kubernetes.io/docs/concepts/policy/limit-range/)

#### Additional context
- #433 
- #647
- #691
- #975
- #1354

**Comment by mikeinton** [comment]
Interested in this feature but could you also consider adding the following scenario as well?  It would be beneficial for an environment where namespace access is not locked into being managed by a single team.

- Support namespaces that can be accessed/controlled by multiple teams

**Comment by csantanapr** [comment]
Have consider in addition of quotas for the namespace, also support limitranges? 
Bad idea or good idea?

**Comment by mikeinton** [comment]
> Have consider in addition of quotas for the namespace, also support limitranges? Bad idea or good idea?

Agree that we would also make use of limitranges if they were available here as well.

**Comment by Hokwang** [comment]
@bryantbiggs 
I am looking forward to completing this feature.

**Comment by bryantbiggs** [comment]
here is a look at proposed changes for the next iteration of the `teams` module https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/refactor/v5-part-deux/modules/kubernetes-team

**Comment by jasondewitt** [comment]
is there any update on the status of this refactor? My team is working on building our internal k8s platform and we want to use these blueprints as the basis of the project. We have the EKS cluster up and running, but are wondering what is the current recommendation for setting up teams and users? Should we continue with the older `aws-eks-teams` module and migrate once v5 is released? Or should we stand up our teams with the new `kubernetes_team` module on this branch?

**Comment by bryantbiggs** [comment]
this is now available here https://github.com/aws-ia/terraform-aws-eks-blueprints-teams - we will continue to support the current implementation here and will provide an upgrade/migration guide before removing it from the project
