### ISSUE TITLE
[BUG] Spark Operator IRSA Set up

### ISSUE THREAD

**Issue by gsinghk81** [aws-ia/terraform-aws-eks-blueprints#850]
## Description
I am Following this [instruction](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/analytics/spark-k8s-operator) to install the EKS cluster and Spark operator. Also it contains Spark job examples.

The issue with the Spark Operator blueprint is that it misses the IRSA setup, so [S3 connection](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/bba0a11bd29a4c16ef79ba14f732626b831a30df/examples/analytics/spark-k8s-operator/k8s-schedular/pyspark-s3.yaml#L16) is based on your EKS cluster’s IAM role setup not the IAM role for the Spark service account.

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by bryantbiggs** [comment]
closed in #853
