### ISSUE TITLE
Each terraform apply create a new Managed Group, that fails to finish properly

### ISSUE THREAD

**Issue by huats** [aws-ia/terraform-aws-eks-blueprints#862]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ X ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 4.6.1

- Terraform version:

Terraform v1.2.7
on linux_amd64

- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.24.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

```
module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.6.1"

  cluster_name       = var.commons.project_name
  cluster_version    = "1.22"                             # EKS Cluster Version
  vpc_id             = var.commons.vpc.vpc.id             # Enter VPC ID
  private_subnet_ids = var.commons.vpc.private_subnet_ids # Enter Private Subnet IDs

  managed_node_groups = {
    ng1 = {
      node_group_name = "ng1"
      instance_types  = ["t3.small"]
      subnet_ids      = []  # Mandatory Public or Private Subnet IDs
      disk_size       = 100 # disk_size will be ignored when using Launch Templates

      public_ip = false

      desired_size = 2
      max_size     = 2
      min_size     = 1

      create_launch_template = true
      pre_userdata           = <<-EOT
            sed -i '/^CONTAINER_RUNTIME=/a CONTAINER_RUNTIME="containerd"' /etc/eks/bootstrap.sh
         EOT

      remote_access                   = true
      cluster_endpoint_public_access  = false
      cluster_endpoint_private_access = true

      update_config   = [{
          max_unavailable_percentage = 30
      }]
    }
  }
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    },
    egress_all = {
      description = "Node all egress"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "egress"
      self        = true
    }
  }

  tags = {
    created_by = "Terraform"
  }
}

module "eks-ssp-kubernetes-addons" {
  source         = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.6.1"
  eks_cluster_id = module.eks_blueprints.eks_cluster_id

  # EKS Addons
  enable_amazon_eks_vpc_cni            = true
  enable_amazon_eks_coredns            = true
  enable_amazon_eks_kube_proxy         = true
  enable_amazon_eks_aws_ebs_csi_driver = true

  #K8s Add-ons
  enable_aws_load_balancer_controller = true
  enable_metrics_server               = true
  enable_cluster_autoscaler           = true

  depends_on = [module.eks_blueprints.managed_node_groups]
  tags = {
    created_by = "Terraform"
  }
}

provider "kubernetes" {
  experiments {
    manifest_resource = true
  }
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster_auth.token

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", module.eks_blueprints.eks_cluster_id]
  }
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    token                  = data.aws_eks_cluster_auth.cluster_auth.token
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  }
}

data "aws_eks_cluster" "cluster" {
  name = module.eks_blueprints.eks_cluster_id
}

data "aws_eks_cluster_auth" "cluster_auth" {
  name = module.eks_blueprints.eks_cluster_id
}

data "aws_caller_identity" "current" {}
```

terraform apply

## Expected behavior

The launch of terraform apply should stick to 1 single managed node_group

## Actual behavior

Each time terraform apply is used a new managed nodegroup is created, the newly created nodes being unable to join the cluster. Terraform apply fails after a timeout of 23 min 30 sec

### Terminal Output Screenshot(s)
![2022-08-16_18-00](https://user-images.githubusercontent.com/3296287/184993010-826a71f0-e49f-4410-9cbc-b881a6dbfe29.png)

**Comment by bryantbiggs** [comment]
hi @huats - any reason the subnet IDs are an empty array? have you tried providing subnets IDs and does that produce a different outcome?

**Comment by huats** [comment]
I have put the subnet IDs empty since it was noted like this in https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/node-groups.md for the minimum for managed group.
(I could add a note in the doc if you want to be clearer that it is needed to have something)

I have tested with my subnets, but I face the same issue.
I have been able to create without issue, but if I relaunch it right after, I got many stuffs
including

`  # module.eks.module.eks_blueprints.module.aws_eks_managed_node_groups["ng1"].aws_eks_node_group.managed_ng must be replaced`

and in that case it starts by creating a new node group that never success, and ends with a timeout after 23min 30sec

**Comment by bryantbiggs** [comment]
could you share the plan output to see whats forcing the replacement

**Comment by huats** [comment]
Sure.
As you can notice, it detects that some elements changed outside of Terraform which is not the case. I have simply relaunch terraform apply twice in a row...

[tf-plan.txt](https://github.com/aws-ia/terraform-aws-eks-blueprints/files/9364999/tf-plan.txt)

**Comment by bryantbiggs** [comment]
thank you - when creating a custom launch template, `remote_access` is not a viable argument. If you comment out `remote_access` your issue should go away. let me know if this helps

**Comment by huats** [comment]
Indeed you nailed it....
I haven't found anything like that in the documentation. Would you like that I do a PR for that ?

**Comment by askulkarni2** [comment]
Hi @huats this is actually documented [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html).

**Comment by huats** [comment]
> Hi @huats this is actually documented [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html).

I have to say that it is not obvious (at least for me) looking at the page that you mentionned that we cannot have both... That is why I think instead of relying on an external page, it would be better to have a little note in the documentation like I have put in my proposed PR.
@bryantbiggs @askulkarni2 if disagree you can simply withdraw the PR https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/879 or accept it :)
Anyway thanks for your really really precious help

**Comment by huats** [comment]
Fixed by https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/862#issuecomment-1219431632
