### ISSUE TITLE
Karpenter provisioners 

### ISSUE THREAD

**Issue by andrewhibbert** [aws-ia/terraform-aws-eks-blueprints#866]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Be able to create karpenter provisioners via terraform and store config in code.

#### Describe the solution you would like

Able to create karpenter provisioners as part of the cluster build out process in a repeatable manner through terraform.

#### Additional context

PR #864 is a draft of this

**Comment by bryantbiggs** [comment]
Karpenter provisioners are captured as code, typically using YAML - what is the value proposition for replicating this in HCL, what problems or challenges does it solve?

**Comment by andrewhibbert** [comment]
* Have code for provisioners alongside cluster creation and karpenter install
* Provide a guided way to create provisioners + AWSNodeTemplates, with distinction when there are changes - e.g. there is a lot of yaml not needed when using launch templates
* Standardise tags for selecting subnets, security groups etc
* Able to pass in values from other terraform resources - e.g. the EKS cluster ID, Launch template name, AMI ID etc

**Comment by bryantbiggs** [comment]
But isn't all of that possible today using the current YAML approach? If we take this on, we are now responsible for schema evolution and changes as Karpenter evolves 

Said differently - YAML is the common denominator in the world of Kubernetes. Why is the Karpenter provisioner different in that it would benefit from being controlled through HCL instead of the standard YAML approach? Should other YAML resources be converted into their HCL equivalent, and why?

**Comment by andrewhibbert** [comment]
You could say the same things you are saying now about writing helm charts or any other kind of thing which is meant to improve on just managing things with yaml. I was pretty surprised when I started using Karpenter that you couldn't just manage these through the helm chart which may be better with the schema changes etc. Then you could just change the addon. Either way I think if you are managing multiple launch templates (which is likely) you would want some kind of wrapper

**Comment by andrewhibbert** [comment]
In fact a pull request to add this to the helm chart was closed - https://github.com/aws/karpenter/pull/1956. Suggestion to have a secondary helm chart was also not accepted - https://github.com/aws/karpenter/pull/1956#issuecomment-1163713299

**Comment by FernandoMiguel** [comment]
we do this with `data "kubectl_path_documents"` and `resource "kubectl_manifest"`
we use terraform to pass vars and render the manifests, like
```hcl
  vars = {
    azs                    = jsonencode(var.aws_availability_zones)
    capacity-type          = jsonencode(var.capacity-type)
    instance-type          = jsonencode(var.instance-type)
    arch                   = jsonencode(var.arch)
    tags                   = jsonencode(local.tags)
```

this feeds yamls like the examples in https://github.com/aws/karpenter/blob/main/examples/provisioner/bottlerocket.yaml

**Comment by bryantbiggs** [comment]
I think the tl;dr here is that I don't see this as something that is providing additional value in the project, if anything its taking on additional burden just for a translation of language (YAML vs HCL). However, I highly encourage you to take this on and create a Terraform module for yourself if this helps simplify things on your end

**Comment by bryantbiggs** [comment]
thank you for opening this - however, we won't be proceeding with support for this approach. users can continue to use the YAML manifests for creating provisioners. thank you
