### ISSUE TITLE
External-dns should use zoneIdFilters when multiple DNS domains are passed through

### ISSUE THREAD

**Issue by andrewhibbert** [aws-ia/terraform-aws-eks-blueprints#873]
## Description

You can pass through ARNS for zones which is configuring the IAM role to allow to change specific zones in route53 but you will receive errors in the log if you have zones which are not meant to be managed by external-dns in the EKS cluster. In addition to increased logging this can also cause external-dns to get stuck trying to add records for a particular domain when it does not have permissions

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

v4.7.0

- Terraform version:
1.0.9

- Provider version(s):

## Reproduction Code [Required]

Have multiple route53 zones some managed by EKS, some not

## Expected behavior

No AWS IAM permissions errors in the logs and able to create all records

## Actual behavior

AWS IAM permissions errors in the logs and unable to create all records, unless restrict to the domains

## Additional Information

Previous change #838 switches to ARNs, this is okay for IAM but you need the domain name for the filters, so it may be better to do a data lookup on the domain names, to get the ARNs for the IAM role

**Comment by bryantbiggs** [comment]
this is all possible from the implementation side - trying to do data lookups within the module dynamically is a challenging thing, instead users are now able to do the lookup on their end and pass in via set values

**Comment by andrewhibbert** [comment]
`zoneIdFilters` in the helm chart is a list so I don't think you can use the set stuff as that looks like just for maps. So currently would need to override the whole values until #863. I don't think it is that hard to do data lookups, example code for IAM policy:

```
data "aws_route53_zone" "selected" {
  for_each     = var.domains
  name         = each.value.name
  private_zone = each.value.private_zone
}

data "aws_iam_policy_document" "external_dns_iam_policy_document" {
  statement {
    effect    = "Allow"
    resources = [
      for domain in aws_route53_zone.selected : domain.arn
    ]
    actions = [
      "route53:ChangeResourceRecordSets",
    ]
  }

  statement {
    effect    = "Allow"
    resources = ["*"]
    actions = [
      "route53:ListHostedZones",
      "route53:ListResourceRecordSets"
    ]
  }
}
```

Then in the templated yaml file something like:

```
zoneIdFilters:
%{ for domain in domains ~}
- ${domain}
%{ endfor ~}
```

**Comment by bryantbiggs** [comment]
this should work I believe:

```hcl
	...
	set_values = [
		  {
			  name = "zoneIdFilters[0]"
			  value = "xxx"
		  }, {
			  name = "zoneIdFilters[1]"
			  value = "yyy"
		  }
	]
```

or even:

```hcl
	...
	set_values = [
		  {
			  name = "zoneIdFilters"
			  value = "[xxx,yyy,zzz]"
		  }
	]
```
