### ISSUE TITLE
Are there any plans to add instance_refresh to self managed node groups?

### ISSUE THREAD

**Issue by olibenni** [aws-ia/terraform-aws-eks-blueprints#874]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here
Changing stuff like the launch template currently requires a manual instance refresh.
Is it reasonable to add:
``` hcl
  instance_refresh {
    strategy = "Rolling"
  }
```

to the aws_autoscaling_group?

**Comment by askulkarni2** [comment]
Handled in #876
