### ISSUE TITLE
[ADDON] ACK AddOn

### ISSUE THREAD

**Issue by chunlea** [aws-ia/terraform-aws-eks-blueprints#877]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

If we could integrate other [aws-controllers](https://github.com/aws-controllers-k8s), for example [RDS](https://github.com/aws-controllers-k8s/rds-controller), it will help us to set up more quickly.

#### Describe the solution you would like

One config toggle to enable other aws-controllers

#### Describe alternatives you have considered

Using helm provider to add them manually.

**Comment by bryantbiggs** [comment]
Hi @chunlea - could you elaborate a bit on why controllers would be useful, especially in the context of provisioning infrastructure resources using Terraform?

**Comment by askulkarni2** [comment]
I would imagine this is similar to the crossplane use-case to setup a bootstrap/management cluster?

**Comment by chunlea** [comment]
Hi, @bryantbiggs. I am exploring kubernetes preview development. And I think k8s should manage provisioning supported environment. In that case, the developer could apply resources like database/Redis via k8s, and I can easily clean that resource later. 

BTW, using terraform should also work for this use case.

**Comment by thegippygeek** [comment]
Hey Folks, I have Forked and updated a bit of work by the DNXLabs crew on their terraform-aws-eks-ack module.
https://github.com/thegippygeek/terraform-aws-eks-ack - This may be what you are looking for @chunlea.

**Comment by domeales-paloit** [comment]
There is definitely a valid use case for this. In a project I worked on recently we were looking at installing ACK in the cluster to bring the management of application resources closer to the developers and to allow them to configure specific infrastructure like AWS API Gateway. As I see it ACK is just another management tool like some of the other addons in this project.

**Comment by bryantbiggs** [comment]
hi all - we've released a new module specifically for ACK addons and will be adding examples that use this module in the future https://github.com/aws-ia/terraform-aws-eks-ack-addons
