### ISSUE TITLE
Creating more than one Kubernetes namespaces and service accounts with IRSA module

### ISSUE THREAD

**Issue by jadhavnitind** [aws-ia/terraform-aws-eks-blueprints#884]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
As of now IRSA supports adding one Kubernetes namespace and one service account with below section.
````
module "iam_role_service_account" {
  source                      = "../../terraform_modules/irsa"
  eks_cluster_id              = module.eks.cluster_id
  eks_oidc_provider_arn       = module.eks.oidc_provider_arn
  kubernetes_namespace        = "development"
  create_kubernetes_namespace = true
  kubernetes_service_account  = "connections-serviceaccount"
  irsa_iam_policies           = [aws_iam_policy.this.arn]

  depends_on = [module.eks]
}
````
If we wanted to create few more service accounts in same namespace then we have to add same section multiple times.

#### Describe the solution you would like
If we have Kubernetes service accounts and namespaces in list(string) which will allow us to add one or more service account in single namespace and multiple namespaces.
```
module "iam_role_service_account" {
    source                        = "../../terraform_modules/irsa"
    eks_cluster_id                = module.eks.cluster_id
    eks_oidc_provider_arn         = module.eks.oidc_provider_arn
    kubernetes_namespace          = [
      "test",
      "dev",
      "etc..."
    ]
    kubernetes_service_account     = [
       "connections-serviceaccount",
       "web-serviceaccount",
       "some-serviceaccount",
       "etc...."
    ]
    irsa_iam_policies               = [aws_iam_policy.this.arn]
  
    depends_on = [module.eks]
  }
```
Here it doesn't need to duplicate the code and it look clean.

**Comment by bryantbiggs** [comment]
Could you elaborate a bit on the motivation or desired outcome you are trying to achieve? The current module is setup per a "recommended practice" approach where the access is scoped to 1 role - 1 service_account:namespace. What you are proposing looks like a single role that has quite broad permissions across several service accounts and namespaces which is generally not ideal from a security perspective

**Comment by jadhavnitind** [comment]
Yes, I am with you on the best practices. I am trying to make it simple so anybody can come and just add few lines and it will work as expected.
This is specifically I am look for AWS Secret manager, so so pods can be mount secrets and they can be consumed by pods.
If I am going to have minimum 5 environments on single Kubernetes cluster and each environment has more than 10 application components which needs 10 service accounts for single namespace to get access to AWS secret manager. In total 50+ Service accounts and 5 namespaces.
Also when duplicating the code it has flag to create namespace that needs to be false in other 9 service account creation.
`create_kubernetes_namespace = true`
If we do something similar to original post to get AWS secret manger secrets access that would be helpful.

Also I would appreciate hearing your opinion on this or right approach to deal with such a situations.
