### ISSUE TITLE
Secondary CIDR outing with Pod IP.

### ISSUE THREAD

**Issue by nascimento** [aws-ia/terraform-aws-eks-blueprints#890]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Using `vpc-cni-custom-networking` example PODs from secondary CIDR is no outbound with NodeIP. Why ?
Docs referenced saying that outbound will work with NodeIp... :(

#### Provide a link to the example/module related to the question

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking

#### Additional context

As the example I created 10.0 and 10.99 subnet.
I create a pod and everything is working and running as 10.99.x.x

I created an EC2 instance on a peering VPC and all requests receiving there is 10.99.x.x from pods.

Thanks

**Comment by tanvp112** [comment]
>I create a pod and everything is working and running as 10.99.x.x
>I created an EC2 instance on a peering VPC and all requests receiving there is 10.99.x.x from pods.

Since the pods run in private subnet in 10.99.x.x range; what's the issue that the receiving end sees 10.99.x.x as the source? Note that traffic do not go out via the NodePort.

**Comment by FernandoMiguel** [comment]
for pods on extended subnets, they will go out to the subnet with that same IP CIDR.
resources in the same VPC will need to allow traffic from that CIDR in their SGs.
the other option is to have a NAT GW and route in the routing table to make all traffic go over it (expensive)

**Comment by askulkarni2** [comment]
When custom networking is enabled, the VPC CNI creates secondary ENIs in the subnet defined under ENIConfig. The primary ENI is not used by custom networking.

What outcome are you looking to achieve?
