### ISSUE TITLE
[FEATURE]Access to `helm_release` in addon outputs

### ISSUE THREAD

**Issue by niallthomson** [aws-ia/terraform-aws-eks-blueprints#892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

We're using EKS Blueprints to build EKS clusters for workshop users in a new set of content. A challenge that we have is that Blueprints is hiding a lot of the hard work that goes in to installing components like Cluster Autoscaler, AWS Load Balancer Controller etc. and we'd like to consider a way that we can give users an idea of what helm mechanics are going on under the covers.

An idea that we're thinking about is auto-generated snippets of content the user can optionally view to give insight in to how each component was installed. This would require metadata from the Helm release such as the chart name, repository name, version and the set of values provided when it was deployed (not the full set including computed values).

We have a lot of emphasis on maintainability for this content, so we really want to avoid having to hand-write or maintain content like this which can be generated.

This is a prototype:

![Screen Shot 2022-08-23 at 7 41 59 AM](https://user-images.githubusercontent.com/808369/186556550-d9fd6f55-83fc-4c78-a38b-b4f00afb414d.png)

#### Describe the solution you would like

One option is to generate this content using the outputs of the `helm_release` from each addon, which includes the combined values from `values.yaml` and `set` inputs that shows a concise set of configuration we're using for each addon. I've prototyped this approach with an addon we maintain for ourselves and it does work.

#### Describe alternatives you have considered

Also considered pulling this information directly via the helm CLI from a running EKS cluster, which should be able to provide similar information.

**Comment by tanvp112** [comment]
Try helm_release [metadata.values](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#values)

**Comment by FernandoMiguel** [comment]
long ago I added outputs to the helm addons
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/helm-addon/outputs.tf

never got around to add outputs to each of the addons themselves.
feel free to open a PR.

**Comment by niallthomson** [comment]
@FernandoMiguel thats the exact output I used in my prototype since it was our own module since I could easily hack on it and what spurred on this question 👍 

I'm not excited by the prospect of adding this to ALL the addons, I have a handful that are relevant right now. Would you consider this an "all or nothing" type endeavor?

**Comment by FernandoMiguel** [comment]
> @FernandoMiguel thats the exact output I used in my prototype since it was our own module since I could easily hack on it and what spurred on this question 👍 
> 
> I'm not excited by the prospect of adding this to ALL the addons, I have a handful that are relevant right now. Would you consider this an "all or nothing" type endeavor?

I have no power of decision here.
Like you, I'm a community member, contributing to help others and upstreaming our own changes!

**Comment by askulkarni2** [comment]
@niallthomson it has to be all or nothing for consistency. We are thinking about some refactor for the `kubernetes-addon` module, we might be able to do this as a part of that which would make it easier to implement.

**Comment by FernandoMiguel** [comment]
> @niallthomson it has to be all or nothing for consistency. We are thinking about some refactor for the `kubernetes-addon` module, we might be able to do this as a part of that refactor which would make it easier to implement.

can we have some visibility over that discussion or design process @askulkarni2  ?
thanks

**Comment by bryantbiggs** [comment]
once #1032  is complete, we will start planning to migrate over to that resource for addons which exposes all of the output attributes provided by the `helm_release` resource plus it will expose all of the IAM role outputs for the associated IRSA role (if one is created)
