### ISSUE TITLE
Manual eks managed node group scale out

### ISSUE THREAD

**Issue by lupindeterd** [aws-ia/terraform-aws-eks-blueprints#893]
- [ ✔️  ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I want to increase the capacity of my cluster on an eks managed node group. I added this settings( desired_size and max_size == 6 from current which 3) but it didn't change the capacity nor change the ASG. Am I missing something?

``` managed_node_groups = {
      mg_ng = {
         node_group_name = "managed-ondemand"
          instance_types  = var.instance_type
          subnet_ids      = var.private_subnets
          desired_size    = var.desired_size
          max_size        = var.max_size
    }
  }
```

**Comment by bryantbiggs** [comment]
`desired_size` is ignored after its initially set. this is intentional so that terraform no longer controls this setting because of the popular use of cluster scaling mechanisms like cluster-autoscaler and karpenter

**Comment by lupindeterd** [comment]
@bryantbiggs  so  can I increase the capacity of an existing node group without cluster-autoscaler or kapenter? Is that possible? I used to do that with the plain `aws eks` module.

**Comment by bryantbiggs** [comment]
you can through other means (awscli, console, etc.), but not currently through this project. Terraform does not allow us to variabilize the `ignore_changes` configuration unfortunately

**Comment by lupindeterd** [comment]
thanks @bryantbiggs., If I increase the ASG size using cli would Terraform revert that?

**Comment by bryantbiggs** [comment]
Nope - it's ignored after initial launch

**Comment by lupindeterd** [comment]
Thanks. I'll proceed to close this with comment.

**Comment by FernandoMiguel** [comment]
@lupindeterd we have been VERY happy by spinning up two ASG nodes and then having karpenter deal with the remaining capacity

**Comment by lupindeterd** [comment]
@FernandoMiguel  I'll do the same approach. cheers
