### ISSUE TITLE
Kubecost chart failing to download

### ISSUE THREAD

**Issue by espuuks** [aws-ia/terraform-aws-eks-blueprints#913]
When running the example "eks-cluster-with-new-vpc" and deploying the add-ons with "terraform apply -target="module.eks_blueprints_kubernetes_addons"" I am experiencing an error during the kubecost chart download:

Error: could not download chart: failed to download "oci://public.ecr.aws/kubecost/cost-analyzer/cost-analyzer" at version "1.96.0"

with module.eks_blueprints_kubernetes_addons.module.kubecost[0].module.helm_addon.helm_release.addon[0],
  on ../../modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
  1: resource "helm_release" "addon" {

The download link looks strange, with "cost-analyzer" duplicated. How can I fix this?

**Comment by florentio** [comment]
Hello @espuuks this issue should be fixed once we merge this https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/915

**Comment by alejandraRamos** [comment]
> Hi still facing the same error with `v4.11.0`. Thanks

What terminal problem did you have? I'm having the same error  @ZeroDeth
