### ISSUE TITLE
Examples and docs keep EKS and add-ons in the same TF state

### ISSUE THREAD

**Issue by vprus** [aws-ia/terraform-aws-eks-blueprints#914]
## Description

All the examples, such as https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-new-vpc right now have the following pattern:
- TF resource to create VPC
- TF resource teo create EKS cluster, using "aws" provider
- TF resource to create add-ons, using "kubernetes" and "helm" providers

Configuration of the "kubernetes" provider appears to interpolate the output of the eks module. 

However, Terraform [docs](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) say this:

> When using interpolation to pass credentials to the Kubernetes provider from other resources, these resources SHOULD NOT be created in the same Terraform module where Kubernetes provider resources are also used. This will lead to intermittent and unpredictable errors which are hard to debug and diagnose.

and their [examples](https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/_examples/eks) indeed use kubernetes provider in a separate folder and instruct to apply it separately.

I would propose to clearly document that these are just example, and propose the approach from TF docs for production use.

For context, I actually run into a problem where "kubernetes" provider initialization was throwing confusing errors.

**Comment by Zvikan** [comment]
Thank you for reporting this issue.
Can you please share what errors you are seeing? Also, a reproducible code snippet will be helpful so we can review and test.
Thanks.

**Comment by vprus** [comment]
Unfortunately, exactly as terraform docs warn, the error was intermittent. It was triggered on this fragment of code 
```
provider "kubernetes" {
  host                   = module.eks_blueprints.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_blueprints.eks_cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.this.token
}
```
That said, basically, "eks_blueprints does not exist, run plan", and it was emitted when running "terraform plan". I don't have a reproducible code snippet, since the error went away after I deleted the cluster and tried again.

**Comment by bryantbiggs** [comment]
@vprus please see https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/FAQ.md#provider-authentication

**Comment by vprus** [comment]
@bryantbiggs: thanks, that does discuss the matter indeed. I wonder, if maybe the README.md for the examples can explicitly say that a single TF state is used for convenience? The section in FAQ titles "provider authentication" is not the first part of docs anybody would read.

**Comment by bryantbiggs** [comment]
There is always room for improvement, definitely. However, this is the crux of documentation - if users do not read the docs or find the information in the docs in the place they expect, it then leads to repeated changes of moving things around based on different personas and expectations. We can look at making some tweaks but at the end of the day - this project shows blueprints for EKS clusters and not guidance for Terraform project structures or state management. It is very common within the Terraform community to use this `examples/` style setup in a single directory, but users should be aware of Terraform design practices and its not the concern of the examples to instruct them on those.

**Comment by vprus** [comment]
That's totally up to you; there are obviously trade-offs. I have the answers I needed, thanks.

**Comment by robertlagrant** [comment]
> However, this is the crux of documentation - if users do not read the docs or find the information in the docs in the place they expect, it then leads to repeated changes of moving things around based on different personas and expectations.

One common pattern is to have the information laid out in a sensible structure, and then a Troubleshooting/FAQs section that pulls out common questions from people for whom the layout doesn't work so well.

**Comment by bryantbiggs** [comment]
> > However, this is the crux of documentation - if users do not read the docs or find the information in the docs in the place they expect, it then leads to repeated changes of moving things around based on different personas and expectations.
> 
> 
> 
> One common pattern is to have the information laid out in a sensible structure, and then a Troubleshooting/FAQs section that pulls out common questions from people for whom the layout doesn't work so well.

What is, objectively, a "sensible structure"?
