### ISSUE TITLE
can we use emr-on-eks and aws-eks-teams together?

### ISSUE THREAD

**Issue by srikaanthpenugonda** [aws-ia/terraform-aws-eks-blueprints#918]
I m trying to use emr-on-eks and aws-eks-teams together.

emr-on-eks creates it own namespace so that we can deploy spark jobs in it andi tried to use aws-eks-teams for gaining access to the ns created by emr-on-eks but realized that aws-eks-teams creates it own namespace and gets the app team to access to a new namespace.
Tried to do this but application teams user didnt get access to emr_on_eks ns

```
enable_emr_on_eks = true

platform_teams = {
  cluster-admins = {
    users = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/customrole-admin"
    ]
  }
}

  application_teams = {
    # First Team
    paml-team = {
      # Belows are examples of IAM users and roles
      users = [
        "arn:aws:iam::*:user/k8s-users"
      ]
    }
  } 
```

**Comment by askulkarni2** [comment]
@srikaanthpenugonda please see the exampl for emr-on-eks with teams [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/analytics/emr-on-eks/main.tf#L205).

**Comment by srikaanthpenugonda** [comment]
@askulkarni2  I wasnt referring to having multiple teams with multiple emr namespaces.

[here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/analytics/emr-on-eks/main.tf#L205).

If you run this example end-to-end it will create two namespaces emr-data-team-a & emr-data-team-b and can be accessed by cluster owner.

now if we want to enable cluster access to other roles/user as cluster admin or application owner as described here https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/aws-eks-teams its not enabling access to the emr namespaces created above

This code https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/4b47ef0518d60a8620818c6a56d119752962dcb3/modules/aws-eks-teams/main.tf#L4 is creating separate namespace for each app team
