### ISSUE TITLE
 EMR on EKS Terraform Blueprint not working with EMR Studio

### ISSUE THREAD

**Issue by thehamzam** [aws-ia/terraform-aws-eks-blueprints#925]
Issue: Unable to see kernels in EMR Studio notebook when attaching the workspace to the EKS cluster created by terraform blueprint here - https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/analytics/emr-on-eks

EMR Studio setup requires a load balancer. We determined that the load balancer hosts were unhealthy and after diving deeper, saw that the security group for the nodes did not have the ELB’s security group as part of the inbound rules. After adding this rule in (and likewise giving the ELB's security group the outbound rule to the node’s security group), we fixed the issue and we are now able to see the kernels in EMR Studio.

I have attached a screenshot of a node's info page which shows its security group (this same security group is used across all nodes in the cluster). 
Also, I have attached screenshots with details + description of the load bala
![Screen Shot 2022-08-29 at 6 41 40 PM](https://user-images.githubusercontent.com/22417244/188178180-67610420-c9b9-4dff-8821-d6f38593156f.png)
![Screen Shot 2022-08-29 at 6 42 21 PM](https://user-images.githubusercontent.com/22417244/188178184-7c320216-1182-49ca-9845-243c57baf762.png)
![Screen Shot 2022-08-29 at 6 43 04 PM](https://user-images.githubusercontent.com/22417244/188178188-72d47dcb-6347-4cab-8687-5128f5175d49.png)
ncer security group, and the node's security group (both of which were modified as mentioned in the paragraph above).

It seems like this issue might have come up from the terraform template I was using; previously, using AWS documentation (not Terraform) did not result in such an issue. As other customers may also have similar use case (i.e. using EMR Studio with EMR EKS), we wanted to bring this up. 

Since this would be a manual fix for every virtual cluster + endpoint combination created for EMR studio, our request is that the EMR on EKS template can be looked at for this use case!

POTENTIAL SOLUTION: make the node security group to be same as cluster security group since the cluster sg seems to have the right sg attached for the LB.

Thanks,
Hamza

**Comment by thehamzam** [comment]
setting create_launch_template = false
fixes at least this issue. found info here https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1542

but from security perspective , the cluster security group is quite open ... allows all traffic on ingress
so perhaps creating our own launch template that will still allow the load balancer security group to work as expected is the better solution ?

**Comment by bryantbiggs** [comment]
hi @thehamzam - this example has moved to https://github.com/awslabs/data-on-eks - please try out that latest example to see if it resolves your issue
