### ISSUE TITLE
Please add 

### ISSUE THREAD

**Issue by jochemvankessel** [aws-ia/terraform-aws-eks-blueprints#932]
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/f9a7ebdae3454f7997590268166ad519df9f6617/modules/kubernetes-addons/kube-prometheus-stack/main.tf#L2

Please add the manage_via_gitops here as well

and also in variables.tf ofcourse:
variable "manage_via_gitops" {
  description = "Determines if the add-on should be managed via GitOps."
  type        = bool
  default     = false
}

I would be very greatful if we can create a patch sooooon 😇

**Comment by bryantbiggs** [comment]
Hi @jochemvankessel - please use the issue/feature templates provided.

**Comment by bryantbiggs** [comment]
closing for now - please utilize the templates provided and populate with the requested information
