### ISSUE TITLE
AWS Load Balancer Controller cannot register target

### ISSUE THREAD

**Issue by duclm2609** [aws-ia/terraform-aws-eks-blueprints#938]
I'm using GitOps approach to install EKS addon AWS Load Balancer Controller and Nginx Ingress controller. When the Nginx ingress controller is deployed, the load balancer is automatically created by AWS load balancer controller, but the load balancer cannot register target (Nginx ingress controller pods). If I register target manually, it just works fine.

I found out the root cause is the tag on the security group that attached to the worker node. My worker node is AWS managed node group and all node is attached by 2 security groups: primary cluster security group and node group security group. These 2 security groups both have this tag:

kubernetes.io/cluster/${cluster_id} = owned

Delete this tag on cluster security group and the AWS load balancer can now register the target automatically again. Just one question, is this expected behaviour or bug in Terraform code? 

I'm using version: 4.8.1.
Thank you.

**Comment by FernandoMiguel** [comment]
FYI only a single node SG can have that tag or the AWS LBC will fail to update with its SG Rule.

**Comment by FernandoMiguel** [comment]
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/#:~:text=multiple%20security%20groups%20on%20an%20ENI
![image](https://user-images.githubusercontent.com/168366/189093718-f85d52b1-022d-489e-aabf-b9de2c89bc75.png)

**Comment by duclm2609** [comment]
> FYI only a single node SG can have that tag or the AWS LBC will fail to update with its SG Rule.

Thank your for your reply. I know about that. The problem I want to mention here is that the newly created EKS from this Blueprint Terraform source code should also handling this case as well and the Load Balancer addon should work out of the box, rather than I have to manually fix the problem above.

**Comment by duclm2609** [comment]
I will try to re-create the cluster to see if this problem still exist using the latest release v4.9.0.

**Comment by duclm2609** [comment]
Sorry for late response. I still got the same error when trying to create new EKS cluster from scratch using v4.10.0.

> `expect exactly one securityGroup tagged with kubernetes.io/cluster/prod-infra-cluster for eni eni-0f240b4ba320cc7a9`

Here is configuration I used to provision the EKS cluster:
```tf
module "control_plane_access_sg" {
  providers = {
    aws = aws.shared-services
  }
  source  = "terraform-aws-modules/security-group/aws"
  version = "~> 4.0"

  name        = "eks-control-plane-additional-sg"
  description = "EKS Infra cluster control plane access"
  vpc_id      = local.shared_services_vpc_id

  ingress_cidr_blocks = var.control_plane_allowed_cidr_blocks
  ingress_rules       = ["https-443-tcp"]

  tags = {
      Name = "eks-control-plane-additional-sg"
    }
}

module "eks_infra_cluster" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.10.0"

  providers = {
    aws = aws.shared-services
  }

  cluster_name = var.cluster_name

  # EKS Cluster VPC and subnets
  vpc_id             = local.shared_services_vpc_id
  private_subnet_ids = local.shared_services_vpc_common_subnets

  # EKS CONTROL PLANE VARIABLES
  # Fully private cluster
  cluster_version                       = var.cluster_version
  cluster_endpoint_public_access        = false
  cluster_endpoint_private_access       = true
  cluster_additional_security_group_ids = [module.control_plane_access_sg.security_group_id]

  #Add karpenter.sh/discovery tag so that we can use this as securityGroupSelector in karpenter provisioner
  node_security_group_tags = {
    "karpenter.sh/discovery/${var.cluster_name}" = var.cluster_name
  }

  node_security_group_additional_rules = {
    # Extend node-to-node security group rules. Recommended and required for the Add-ons
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    # Recommended outbound traffic for Node groups
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
    # Allows Control Plane Nodes to talk to Worker nodes on Karpenter ports.
    # This can be extended further to specific port based on the requirement for others Add-on e.g., metrics-server 4443, spark-operator 8080, etc.
    # Change this according to your security requirements if needed
    ingress_nodes_karpenter_port = {
      description                   = "Cluster API to Nodegroup for Karpenter"
      protocol                      = "tcp"
      from_port                     = 8443
      to_port                       = 8443
      type                          = "ingress"
      source_cluster_security_group = true
    }
    # Allow traffic from pod to access worker node host network. For example: collecting node metrics
    ingress_from_pods = {
      description = "Ingress traffic from pod"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      cidr_blocks = local.shared_services_vpc_eks_pod_subnet_cidrs
    }
    # Allow traffic from internal network
    allow_shared_services_vpc = {
      description = "Ingress traffic from internal Shared Services VPC CIDRs"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      cidr_blocks = [local.shared_services_cidr]
    }
  }

  # EKS MANAGED NODE GROUPS
  # AWS recommendation:
  #   We recommend to have a MNG to place your critical workloads and add-ons
  #   Then rely on Karpenter to scale your workloads
  #   You can also make uses on nodeSelector and Taints/tolerations to spread workloads on MNG or Karpenter provisioners
  managed_node_groups = {
    base_m5 = {
      node_group_name        = "eks-base-m5"
      ami_type               = "AL2_x86_64"
      custom_ami_id          = data.aws_ami.amazonlinux2eks.id
      instance_types         = ["m5.xlarge", "m5a.xlarge"]
      # Launch template configuration
      create_launch_template = true
      launch_template_os     = "amazonlinux2eks"
      enable_monitoring      = true
      # https://docs.aws.amazon.com/eks/latest/userguide/choosing-instance-type.html#determine-max-pods
      pre_userdata           = <<-EOT
        MAX_PODS=$(/etc/eks/max-pods-calculator.sh \
        --instance-type-from-imds \
        --cni-version ${trimprefix(data.aws_eks_addon_version.latest["vpc-cni"].version, "v")} \
        --cni-prefix-delegation-enabled \
        --cni-custom-networking-enabled \
        )
      EOT
      # bootstrap_extra_args used only when you pass custom_ami_id. Allows you to change the Container Runtime for Nodes
      bootstrap_extra_args   = "--container-runtime containerd --use-max-pods false"
      # https://docs.aws.amazon.com/eks/latest/userguide/choosing-instance-type.html#determine-max-pods
      kubelet_extra_args     = "--max-pods=110"
      # Node Group scaling configuration
      desired_size           = 3
      min_size               = 3
      max_size               = 10
      # Node Group network configuration
      subnet_type            = "private"
      subnet_ids             = local.shared_services_vpc_common_subnets
    }
  }
}
```
The cluster security group and node security group both have the tag `kubernetes.io/cluster/${cluster_id} = owned`, which is the cause of aforementioned error.

**Comment by FernandoMiguel** [comment]
Apply it only to the node SG. Or apply a diff one, like shared.

**Comment by duclm2609** [comment]
Sorry I don't get it. What do you mean by applying it only to the node SG?

**Comment by FernandoMiguel** [comment]
The tag you need so aws LBC can find it as an annotation.

**Comment by duclm2609** [comment]
Maybe you misunderstand the problem. What I want to explain here is that, the Blueprint Terraform project provision EKS cluster with 2 security groups which both have the tag `kubernetes.io/cluster/${cluster_id} = owned`. While the AWS load balancer controller expects only 1 security group with this tag, it failed to register its target. 
My question is why this project tag both cluster security group and node security with the above tag, which cause the problem of AWS Load balancer controller?

**Comment by FernandoMiguel** [comment]
AWS LBC is particularly picky , while other tools don't suffer from that limitation.
You either submit a PR to this project improving the code base, or manage the SGs yourself, outside of this module, of disable AWS LBC auto discovery and instead provide the SG IDs directly.

**Comment by FernandoMiguel** [comment]
We end up going with #2
```hcl
resource "aws_security_group" "ec2_nodes" {
  provider = aws.without_default_tags

  name_prefix = "${local.cluster_name}-SG-nodes-"
  description = "EKS created Security Group applied to any managed workloads."
  vpc_id      = data.aws_vpc.vpc_id.id

  tags = merge(
    {
      "Name"                                        = "${local.cluster_name}-SG-nodes-"
      "NodeSG"                                      = "true"
      "kubernetes.io/cluster/${local.cluster_name}" = "owned"
    },
    local.tags,
  )

  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#i-received-an-error-expect-exactly-one-securitygroup-tagged-with-kubernetesioclustername-
