### ISSUE TITLE
[FEATURE] Add ability to set the destination namespace of applications managed by ArgoCD

### ISSUE THREAD

**Issue by mhazegh** [aws-ia/terraform-aws-eks-blueprints#947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I need to be able to configure the destination namespace of an application that is managed by ArgoCD.

For example, let's say I want to deploy ArgoCD itself to the namespace "argocd". This is currently possible by setting the namespace in the argocd_helm_config - so far so good.

Next, I want to configure an application managed by ArgoCD which deploys to the default namespace.

This part is missing because the namespace of an argocd_application is hard coded as:

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/c459a963d92f11b41f4c9fc5f40c7a279fe01be1/modules/kubernetes-addons/argocd/main.tf#L25

This results in the k8s resources created by my application existing in the "argocd" namespace.

#### Describe the solution you would like
I would like to be able to set the destination namespace when defining argocd applications:

```
argocd_applications = {
    my-project = {
      path                  = "chart"
      repo_url              = "https://github.com/<some-repo>.git"
      destination_namespace = "default" // Resources created by this application will exist in the default namespace.
    }
  }
```

**Comment by askulkarni2** [comment]
Hi @mhazegh, I agree that this is a limitation. Beyond the obvious rationale of having that flexibility, is there a specific reason you want to be able to configure the namespace for an argocd application. As you probably know this is not the namespace for the workloads that are deployed by argocd but just for argocd application instead. I am interested in knowing if having that flexibility satisfies some kind of an operational concern.

**Comment by mhazegh** [comment]
@askulkarni2, thanks for the response!

In my case, all of my application's resources were getting deployed to the argocd namespace.

The reason way was kind of hidden in the ArgoCD docs - here's the documented behavior of application.destination.namespace:

> The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace

I hadn't explicitly set the namespace of the resources I was deploying, so they all ended up in the argocd namespace. The fix for this is to explicitly namespace my resources (which I should have been doing anyways 🙂).

Allowing users to override the application.destination.namespace would act as a catch-all to ensure non-namespaced resources end up in a particular namespace, but the real solution is to properly namespace resources in the first place. I think this issue can be closed.
