### ISSUE TITLE
How can I wait with the add-ons install until eks_managed_node_groups is ready ?

### ISSUE THREAD

**Issue by VladoPortos** [aws-ia/terraform-aws-eks-blueprints#948]
- [x ] ✋ I have searched the open/closed issues and my issue is not listed.
How can I make the module:
`  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.8.1"`
wait for or depends_on until all worker nodes are up and ready from `eks_managed_node_groups` VPC module because I have one or two modules always failing and making the Terraform stuck with worker node still tainted not ready, but when I check it, it deployed 2 out of 2 pods... and aws still see it as degraded. When I manually redeploy the coredns or csi plugin, it finishes ok ( while the pending Terraform crashes )

I have tried:
`depends_on = [module.eks.cluster_id, module.eks.managed_node_group]`

But that did not help.

**Comment by Zvikan** [comment]
@VladoPortos Utilizing TF `-target` to target the specific modules should do the trick in this case, depends_on has its own challenges.
Example running example with multiple applies (recommended if using same state):
```
terraform apply -target=module.vpc
terraform apply -target=module.eks_blueprints
terraform apply -target=module.eks_blueprints_kubernetes_addons
terraform apply 
```
(same goes for tf destroy, just the other way around.)


if you still want to use `depends_on`, I believe it should be `depends_on = [module.eks_blueprints.managed_node_groups]`  (you were missing a `s` at the end there)

**Comment by VladoPortos** [comment]
It was the missing `s`, I feel dumb 👍
