### ISSUE TITLE
The Getting Started example has a hard-coded region - should be a variable?

### ISSUE THREAD

**Issue by robertlagrant** [aws-ia/terraform-aws-eks-blueprints#953]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

When running the Getting Started example, it's not obvious how to change the region that it uses. In a corporate environment this can be locked down by policy, and the error message isn't clear.

#### Describe the solution you would like

Break out the hard-coded region into a variable. Can default to the current region. Update Getting Started doc to include the option.

#### Describe alternatives you have considered

No other alternatives to speak of.

#### Additional context

None.

**Comment by bryantbiggs** [comment]
see comment https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/954#issuecomment-1272330068
