### ISSUE TITLE
ipv4-prefix-delegation with bottlerocket

### ISSUE THREAD

**Issue by pescador691** [aws-ia/terraform-aws-eks-blueprints#961]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Enable Prefix Delegation with Bottlerocket AMI

I am trying to deploy a managed node group with eks blueprints in aws and need to increase the pod capacity of the nodegroup.

I am using the [ ipv4-prefix-delegation example](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ipv4-prefix-delegation).

However, when I change the `launch_template_os = "bottlerocket"` and  `ami_type = "BOTTLEROCKET_x86_64"`, it doesn't increase the capacity of the nodes.

The snippet of code that was changed using the example as a guideline is the following:

```
infra_nodegroup_green = {
      node_group_name = "infra_nodegroup_greens-test"
      launch_template_os     = "bottlerocket"
      create_launch_template = true
      ami_type             = "BOTTLEROCKET_x86_64"
      min_size        = 1
      max_size        = 1
      desired_size    = 1
      instance_types       = ["m5.xlarge"]
      pre_userdata = <<-EOT
        MAX_PODS=$(/etc/eks/max-pods-calculator.sh --instance-type-from-imds --cni-version ${trimprefix(data.aws_eks_addon_version.latest["vpc-cni"].version, "v")} --cni-prefix-delegation-enabled)
      EOT
      kubelet_extra_args   = "--max-pods=$${MAX_PODS}"
      bootstrap_extra_args = "--use-max-pods false"
    }
```

What variables could be missing that need to be set up before creating the nodegroups?

**Comment by FernandoMiguel** [comment]
if you are setting max size 1, there's not much for it to increase, right?
but ideally you want to use something like karpenter.sh to handle the cluster nodes

**Comment by pescador691** [comment]
@FernandoMiguel the max size is just the number of the nodes managed by the node group and to deploy the module faster.

The problem here is that an instance m5.xlarge, can have around 58pods. 

When increasing the pod capacity per node, it should calculate the `MAX_PODS` and set the extra argument to allow the node to have 110 pods. This should take effect to every node in the managed nodegroup

**Comment by bryantbiggs** [comment]
the user data for bottlerocket is in TOML format but here you have used the shell format

**Comment by bryantbiggs** [comment]
> are you sure a m5.xlarge can run more than 58? the docs state [aws/karpenter@`main`/website/content/en/v0.12.1/AWS/instance-types.md#m5xlarge](https://github.com/aws/karpenter/blob/main/website/content/en/v0.12.1/AWS/instance-types.md#m5xlarge) 58!

yes it can - I'm not sure what karpenter has to do with this question but you can calculate for yourself using https://github.com/awslabs/amazon-eks-ami/blob/master/files/max-pods-calculator.sh

```
> ./max-pods-calculator.sh --instance-type m5.xlarge --cni-version 1.11.0 --cni-prefix-delegation-enabled

110
```

**Comment by FernandoMiguel** [comment]
here is a node started by karpenter
![image](https://user-images.githubusercontent.com/168366/190434454-fc48af3d-1ff1-4a26-ace2-40d5eac41291.png)
and one started by MNG
![image](https://user-images.githubusercontent.com/168366/190434580-82061991-6b05-4498-b151-fff499843524.png)
the MNG is managed by
```
  source  = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  version = "~> 18.29"
```

**Comment by bryantbiggs** [comment]
@FernandoMiguel I'm not following what you are trying to highlight. this issue is regarding prefix delegation with bottlerocket - nothing to do with karpenter

**Comment by pescador691** [comment]
> the user data for bottlerocket is in TOML format but here you have used the shell format

@bryantbiggs that should be the problem. I wasn't aware of that. 

Don't know how to convert that shell commands to TOML Guess I just got one more thing in the bucket list to learn! =D

I think the issue can be closed. If the command in TOML format doesn't work, I'll reopen the issue.

Many thanks!
