### ISSUE TITLE
custom cluster name and custom tag names

### ISSUE THREAD

**Issue by Chakki1301** [aws-ia/terraform-aws-eks-blueprints#964]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

How do I provide the name of the cluster which I prefer and additional tags while creating the EKS cluster using this EKS blueprint

#### Provide a link to the example/module related to the question

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc

#### Additional context

I encounter errors while I update the main.tf locals section in examples/eks-cluster-with-new-vpc. I do see the tag PR issue was completed but I couldn't find the information on how do I pass the variables for name of the EKS cluster and additional tags.

**Comment by askulkarni2** [comment]
As the [variables.tf](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/variables.tf) file indicates you can provide the `cluster_name` as `-var cluster_name=<name`.

For `tags` you can update the [local.tags](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/54e81c84331e1e4d4a9445afe7ac548a361318b3/examples/eks-cluster-with-new-vpc/main.tf#L34) map and provide your own instead.

**Comment by Chakki1301** [comment]
Got it. Yes, variable I could pass while tf apply. I provided the name in the local section in main.tf. Seems for the tag and the name, I should have given in double quotes. That's what I missed. Thanks for the prompt response.
