### ISSUE TITLE
Windows support not working: Pod stuck at ContainerCreating status

### ISSUE THREAD

**Issue by duclm2609** [aws-ia/terraform-aws-eks-blueprints#965]
Hello guys,
I'm using this project to provision my EKS cluster with custom networking enable. It worked great so far for Linux container.
Today I try to deploy Windows container but the conatiner stuck at ContainerCreating status with the following error:

`failed to set up sandbox container "dd764292de39cc9db144f11e5e95b8572b597872ff71f966042706a2f14e22e6" network for pod "sample-windows-54dfc4d87d-76tzv": networkPlugin cni failed to set up pod "sample-windows-54dfc4d87d-76tzv_sandbox" network: failed to parse Kubernetes args: pod does not have label vpc.amazonaws.com/PrivateIPv4Address`

I have enable Windows support and deploy a self-managed node group using the following configuration:

```tf
  enable_windows_support   = true
  self_managed_node_groups = {
    general_windows = {
      node_group_name    = "general-windows"
      launch_template_os = "windows"
      instance_type      = "m5.xlarge"
      subnet_ids         = local.private_subnets
      min_size           = 2
      kubelet_extra_args = join(" ", [
        "--node-labels=node.example.com/os=windows",
        "--register-with-taints node.example.com/os=windows:NoSchedule"
      ])
    }
```
I can see that the pod is assigned to the right node. Also since I'm using latest version of this repo, I understand that Windows support should be done in control plane as AWS doc.

I have no idea how to resolve this problem. Any sugguestion? Thank you in advance.

**Comment by askulkarni2** [comment]
cc @awsitcloudpro 

Hi @duclm2609, I am not a windows expert but this error seems to be documented [here](https://aws.amazon.com/premiumsupport/knowledge-center/eks-failed-create-pod-sandbox/). Can you please follow the steps to debug and report what you see?

**Comment by duclm2609** [comment]
I already read this before writing here. At first, I think I need to install the VPC resource controller and the admission webhook. But it turns out that the EKS version I'm using is 1.22 and according to AWS, the VPC resource controller and VPC admission webhook is no longer needed, as quote below:

> If you enabled Windows support on a cluster that is earlier than a Kubernetes or platform version listed in the [Prerequisites](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#windows-support-prerequisites), then you must first [remove the vpc-resource-controller and vpc-admission-webhook from your data plane](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#remove-windows-support-data-plane). They're deprecated and no longer needed.

I carefully read the Terraform plan output and see that this module create all neccessary resources to enable Windows support. That's why I have no idea why this problem come up and how to resolve it.
The amazon-vpc-cni configmap seems correct:
```yaml
apiVersion: v1
data:
  enable-windows-ipam: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-15T07:28:59Z"
  name: amazon-vpc-cni
  namespace: kube-system
  resourceVersion: "61369283"
  uid: 9eae324d-d5bc-4b38-9a31-e77079dead1b
```

**Comment by duclm2609** [comment]
Sorry for taking your time. I try to re-enable windows support (by toggle `enable_windows_support` false then true) to re-install and everything is working now.
