### ISSUE TITLE
[FEATURE] Allow ArgoCD application auto-sync to be disabled

### ISSUE THREAD

**Issue by mhazegh** [aws-ia/terraform-aws-eks-blueprints#969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
It would be nice to have the ability to disable the auto-sync policy when creating an ArgoCD application.

This would allow for deployment processes which still require a human-in-the-loop.

In our case, we need to be able to prepare everything for deployment (build and tag images, update manifests), then perform the actual deployment at a later time. Unfortunately this process is outside of my control.

#### Describe the solution you would like

When defining an ArgoCD application, I would like to be able to set an 'auto_sync' variable to false.
```
argocd_applications = {
  my-project = {
    path               = "chart"
    repo_url           = "https://github.com/aws-samples/eks-blueprints-add-ons.git"
    auto_sync          = false
  }
}
```

When this variable is false, the resulting Application.spec.syncPolicy should not have an 'automated' property.

#### Describe alternatives you have considered
Being able to override all values of Application.spec.syncPolicy would be a more robust solution, but may be overkill.

**Comment by bryantbiggs** [comment]
this is controlled here https://github.com/aws-samples/eks-blueprints-add-ons
