### ISSUE TITLE
[QUESTION] Can `var.auto_scaling_group_names` be used for managed node groups too?

### ISSUE THREAD

**Issue by domeales-paloit** [aws-ia/terraform-aws-eks-blueprints#980]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have an EKS cluster with a managed node group (created by a different TF module) with `capacity_type = "SPOT"` and I want to use the [AWS Node Termination Handler](https://aws-ia.github.io/terraform-aws-eks-blueprints/main/add-ons/aws-node-termination-handler/#aws-node-termination-handler) to handle spot instance lifecycle events.

The documentation for the `var.auto_scaling_group_names` in the `kubernetes-addons` module is: "List of self-managed node groups autoscaling group names"

Can the AWS Node Termination Handler add-on also be used for managed node groups?

#### Provide a link to the example/module related to the question

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons
https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons#input_auto_scaling_group_names

#### Additional context

-

**Comment by bryantbiggs** [comment]
Absolutely - apologies that the description is not 100% correct but its really any autoscaling groups that the node termination handler should be aware of https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/adfbef65cfd3a011b6551d740833573794a9e26b/modules/kubernetes-addons/main.tf#L151

**Comment by domeales-paloit** [comment]
Thanks, much appreciated.
