### ISSUE TITLE
Launch Templates 'locals.tf' use of 'experiments' is no longer supported in Terraform 1.3.0+

### ISSUE THREAD

**Issue by ed-barberis** [aws-ia/terraform-aws-eks-blueprints#982]
## Description

The AWS EKS Blueprints use of **experiments** in the Launch Templates [locals.tf](https://raw.githubusercontent.com/aws-ia/terraform-aws-eks-blueprints/main/modules/launch-templates/locals.tf) file is no longer supported in Terraform 1.3.0+.

In particular, the "built-in ```defaults``` function, previously used to meet the use-case of replacing null values with default values, has been removed." This code will need to "remove the experiment opt-in and adopt the new syntax for declaring default values in order to migrate your existing module to the stablized version of this feature."

Please see the EXPERIMENTS section of the Terraform 1.3.0 release notes [here](https://github.com/hashicorp/terraform/releases/tag/v1.3.0).

## Versions

- Module version 4.10.0 and earlier:
- Terraform version: 1.3.0+
- Provider version(s): AWS Provider 4.31

## Reproduction Code [Required]

Current 4.10.0 release.

```
terraform init
```

## Expected behaviour

Successful init.

## Actual behaviour

The ```terraform init``` command fails.

### Terminal Output Screenshot(s)

```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Experiment has concluded
│
│   on .terraform/modules/eks_blueprints/modules/launch-templates/locals.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment differs from the experimental form and is
│ available in the Terraform language from Terraform v1.3.0 onwards.
```

## Additional context

The ```launch_template_config``` template code needs refactoring.

**Comment by martip07** [comment]
Have the same problem as well but in my case is with the addons:

>`╷
│ Error: Experiment has concluded
│ 
│   on .terraform/modules/eks_cluster.eks_blueprints_kubernetes_addons.ondat/locals.tf line 2, in terraform:
│    2:   experiments = [module_variable_optional_attrs]
│ 
│ Experiment "module_variable_optional_attrs" is no longer available. The
│ final feature corresponding to this experiment differs from the
│ experimental form and is available in the Terraform language from Terraform
│ v1.3.0 onwards.
╵`

**Comment by bryantbiggs** [comment]
yes, we were aiming to have this resolved in [v5](https://github.com/aws-ia/terraform-aws-eks-blueprints/milestone/1)

For now, I will pin the version to avoid this issue for folks
