### ISSUE TITLE
Update to be compatible with terraform 1.3.0+

### ISSUE THREAD

**Issue by nedhanks** [aws-ia/terraform-aws-eks-blueprints#988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Current scripts use an experimental feature that was depreciated in 1.3.0. 

Terraform 1.3.0 

`
> terraform init
Initializing modules...
...
╷
│ Error: Unsupported Terraform Core version
│
│   on ../../modules/kubernetes-addons/versions.tf line 2, in terraform:
│    2:   required_version = ">= 1.0.0, < 1.3.0"
│
│ Module module.eks_blueprints_kubernetes_addons (from ../../modules/kubernetes-addons) does not support Terraform version 1.3.0. To proceed,
│ either choose another supported Terraform version or update this version constraint. Version constraints are normally set for good reason, so
│ updating the constraint may lead to other errors or unexpected behavior.
╵
`

Terraform 1.2.9

`
> terraform init
...
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on .terraform/modules/eks_blueprints_kubernetes_addons.ondat/locals.tf line 2, in terraform:
│    2:   experiments = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│
│ (and 63 more similar warnings elsewhere)
╵
`

#### Describe the solution you would like

Update so scripts will work with latest version of terraform.

#### Describe alternatives you have considered

It is possible to run terraform v1.2.9.

**Comment by mbenson** [comment]
In the interest of completeness, per https://www.hashicorp.com/blog/terraform-1-3-improves-extensibility-and-maintainability-of-terraform-modules it appears that optional attributes have "graduated" as a supported feature, so are still available but no longer experimental.

**Comment by bryantbiggs** [comment]
yes, but the `defaults()` function from the experiment was removed and the syntax has changed which means breaking changes are required https://github.com/hashicorp/terraform/blob/v1.3/CHANGELOG.md

**Comment by mbenson** [comment]
(working on a possible patch)

**Comment by dshamanthreddy** [comment]
@bryantbiggs  will the possible fix available with TF 1.3.0 ?

**Comment by bryantbiggs** [comment]
I'm not sure I follow - the fix should relax the version window back to `">= 1.0.0"` once the `defaults()` and experiment configs are removed from the project. This would support any version of Terraform 1.0+

**Comment by mbenson** [comment]
That is one way to go, but the feature was finalized (with minor changes) for 1.3.0. If you didn't want to use the feature, why opt into the experiment at all?

The link above to https://github.com/ondat/terraform-eksblueprints-ondat-addon/issues/11 leads back to my branch of *this* repo. However, if you did choose to rework this repo's modules not to use the optional object key feature at all, that would:

* expand the set of valid Terraform versions compatible with the module/s as \[would be] released
* eliminate the circular dependency described in the linked issue

**Comment by bryantbiggs** [comment]
> That is one way to go, but the feature was finalized (with minor changes) for 1.3.0. If you didn't want to use the feature, why opt into the experiment at all?

The addition of the experiments to this project was before my time so I can't comment there. The issue with this is not around using or not using, its about the one way directionality. If we ignore the `defaults()` portion which was removed post-experiment, Terraform does not expose the means to conditionally set configuration based on version used. We couldn't do something like - use the experiment flag for versions < 1.3, or not for versions >= 1.3 

That said, I am looking to see if we can re-work the code to remove the experiment and replicate the functionality without introducing any breaking changes and open back up support for >= 1.0 - stay tuned
