### ISSUE TITLE
Newrelic Add-on

### ISSUE THREAD

**Issue by viktoraws** [aws-ia/terraform-aws-eks-blueprints#998]
Hello
Is there any plan or active development to add Newrelic add-on to EKS Bluepirnts kubernetes-addons list?
Here is more info:
https://github.com/newrelic-experimental/newrelic-eks-blueprints-addon

**Comment by askulkarni2** [comment]
We will defer to Marketplace support once #1260 is implemented.

**Comment by bryantbiggs** [comment]
Thank you for the issue @viktoraws - as you have pointed out, there already exists a module to provision the New Relic addon or you can use the `aws_eks_addon` resource for deploying EKS addons or 3rd party addons from the AWS Marketplace
